### ISSUE TITLE
Combination minkowski() and difference() produces incorrect results and/or renders weirdly.

### ISSUE THREAD

**Issue by Feuermurmel** [openscad/openscad#1027]
I'm trying to implement the _erosion_ operation from morphology [0]. In theory, it should be possible using the `minkowski()` operator which implements the _dilation_ operation and erosion is equivalent to erosion of the complement of a set of points. I planned to implement the complement by subtracting an object from a large enough cube.

But I'm having a really hard time getting any results using both the current sable version (2014.03) or the current snaptshot for OS X (2014.11.17). This is a near-minimal version of the code that reproduces the problem:

	// For fast and scale-independent results.
	$fn = 8;
	
	// Object we want to apply the erode operation to.
	module object() {
		union() {
			cylinder(r = 1, h = 5);
			
			rotate(90, [1, 0, 0]) {
				cylinder(r = 1, h = 5);
			}
		}
	}
	
	// The complement of the result of the dilation. This should yield an eroded version of the object.
	difference() {
		cube(15, center = true);
		
		// Dilate to the complement.
		minkowski() {
			// The complement of the object.
			difference() {
				cube(20, center = true);
				object();
			}
			
			// The kernel.
			sphere(d = .5, center = true);
		}
	}

What I'd expect is to get two intersecting cylinders, like if `object()` was rendered directly, just slightly smaller. 2014.03 renders it like this in the preview:

![screen shot 2014-11-22 at 01 51 58](https://cloud.githubusercontent.com/assets/50332/5152101/34864a18-71ea-11e4-87b9-3a75124da254.png)

It's about the right shape but rendered strangely. Rendering it yields this:

![screen shot 2014-11-22 at 01 55 07](https://cloud.githubusercontent.com/assets/50332/5152141/178cbde2-71eb-11e4-97cb-170bab183236.png)

Some faces are missing. 2014.11.17 shows a big cube in bot the preview and rendered view while the cube is only partially shown in the preview, e.g.:

![screen shot 2014-11-22 at 01 58 03](https://cloud.githubusercontent.com/assets/50332/5152139/0c40f570-71eb-11e4-8b86-47421f1a86df.png)

[0]: http://en.wikipedia.org/wiki/Erosion_%28morphology%29

**Comment by kintel** [comment]
To clarify; the reason why this fails:
* In preview mode, we convert and cache geometry from CGAL into an OpenSCAD PolySet (a polygon mesh).
* In render mode, we need to pass CGAL Nef polyhedrons into the union operator. Even though we cached both a Nef polyhedron and a PolySet of the minkowski result, we prefer the PolySet as it's usually faster.
* However, in this case, the PolySet fails to convert back to a Nef polyhedron. The reason for this is that CGAL is very picky about normal vectors. Some polygons are too small to have a valid normal and CGAL bails, leaving an exception, and thus an empty object.

Suggestion for a fix:
Whenever we know that we'll need a Nef polyhedron, we should set a flag in the traversal prefix state to signal to nodes lower in the hierarchy that they should prefer Nef polyhedrons when retrieving objects from the cache. We just need a good mechanism for managing and passing such a flag.

Alternatively, make the conversion from PolySet to Nef polyhedrons more robust. This will also fix a bunch of STL import issues (but is likely more work than the first idea).
