### ISSUE TITLE
Critical Scintilla editor issues

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1068]
These are critical issues for the 2014 QX milestone. See #915 for less critical issues.

- [x] EOL incorrect for Windows, See [Forum](http://forum.openscad.org/Newline-changed-in-scad-files-between-2014-11-09-and-2014-12-04-td10451.html).
- [x] Also note lack of EOL on last line (?) -> not an issue
- [x] Tune the color schemes (e.g. not red highlight)
- [x] Fix TAB behavior -> Waiting for confirmation/discussion

**Comment by MichaelAtOz** [comment]
>  make the window size bigger so the scroll bar is not showing (but still sizable - scroll bar will appear again)

It is a pain to have to resize.

**Comment by MichaelAtOz** [comment]
See [forum](http://forum.openscad.org/Indentation-getting-uppity-td10855.html)

**Comment by MichaelAtOz** [comment]
I can live with it but it looks strange, not highlighting the whitespace
![whitespace highlight](https://cloud.githubusercontent.com/assets/1972961/5601456/698d74e0-9353-11e4-8851-8b874b5091a4.JPG)

**Comment by t-paul** [comment]
It seems setting the WhitespaceBackground is broken in QScintilla. I think we can just drop that. The only important one is the foreground color for whitespaces.
