### ISSUE TITLE
RAM and OS version in Library Info is wrong in Windows 8.1

### ISSUE THREAD

**Issue by Scalpel78** [openscad/openscad#1076]
In the Library Info I have this line:
System information: Windows **8 (v6.2)** 8 CPUs **3.91 GB RAM**

Correct info should be: Windows **8.1 (v6.3)** 8 CPUs **16GB RAM**

The Windows version number error is most likely because the GetVersionEx has been changed in Windows 8.1 - see http://msdn.microsoft.com/en-us/library/windows/desktop/dn481241(v=vs.85).aspx

For the RAM I'm unsure of the cause. If I run the following code in a separate Visual Studio C++ project I get 15.9087. The code is very similar to that OpenSCAD uses in PlatformUtil-win.cc, but without the PlatformUtils::toMemorySizeString call.

	MEMORYSTATUSEX memoryinfo;
	memoryinfo.dwLength = sizeof(memoryinfo);
	if (GlobalMemoryStatusEx(&memoryinfo) != 0) {
		cout << "RAM:" << (float)memoryinfo.ullTotalPhys / (1024 * 1024 * 1024) << endl;
	}

The 3.91 GB OpenSCAD reports could be a 32-bit upper limit, but the application isn't running in 32-bit mode. It's running as a regular 64-bit app.

**Comment by Scalpel78** [comment]
I can confirm that the RAM size is correct now.

Windows version is still reported as standard Windows 8 (v6.2).

**Comment by t-paul** [comment]
Looks like the VersionHelper.h is not available on MinGW, but I found http://hg.m1xa.com/findversion which uses the same underlying API to detect versions up to 8.1 and it's MIT licensed.
This reports now ```Windows 7 SP1 (v6.1.1.0) 2 CPUs 3.00 GB RAM``` on my VM which matches the ```HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion``` info.

@Scalpel78 I've pushed the change to https://github.com/openscad/openscad/tree/win-version-detect - can you test this on your Win8.1 system?

**Comment by Scalpel78** [comment]
Thanks - I didn't get the development environment up and running on my machine, so either we'll have to wait until I get it working (might take a long time), or I can test this if the change is merged into the master branch and a new fileset is made.

**Comment by kintel** [comment]
Snapshots will come soon :)
Did you try the new MSYS2-based setup? It worked like a charm on my VM, and I'm not familiar with Windows dev at all: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Microsoft_Windows

**Comment by t-paul** [comment]
Snapshots 2015.01.10 are online. Note that those are including both the ```gui-updates``` (#1150) and the ```win-version-detect``` changes which are not yet merged...

**Comment by Scalpel78** [comment]
I got some errors last time I tried the Msys2 setup. I'll clear it out, and try again today.

@t-paul The version info now says:

System information: Windows 8.1 (v6.3.0.0) 8 CPUs 7.89 GB RAM

So it looks good :)
