### ISSUE TITLE
Sticky mouse/weird zooming behaviour on OSX

### ISSUE THREAD

**Issue by QuackingPlums** [openscad/openscad#1085]
1. Grab-rotate causes unintentional zooming (and viewport translation) if mouse cursor is allowed to move into titlebar area above the preview window whilst the model is being rotated.
2. Mouse button is 'sticky' after cursor returns to main pane if button state is different from when it entered the titlebar area.

I made a video to illustrate this in the original community discussion thread: http://forum.openscad.org/Has-the-preview-window-orbit-functionality-changed-2014-11-05-OSX-10-9-5-tp10133.html

Direct link to video is also here: https://dl.dropboxusercontent.com/u/9774553/OpenSCAD%20preview%20bug.mp4

First found in 2014.11.05
Last confirmed in 2014.12.07
##

**Comment by kintel** [comment]
Haven't seen this reported for a while. Assuming it's fixed.
