### ISSUE TITLE
Hard crash on rendering

### ISSUE THREAD

**Issue by oysteinkrog** [openscad/openscad#1089]
I have a closed-source design I am working on and get a hard crash (c++ runtime exception).
I might try to create a repro, but until then I get the following info from gdb:

ERROR: boost::filesystem::canonical: No such file or directory: "C:\Users\Øystein\Documents"
CGAL error: assertion violation!
Expression : orientation(v1,v2,vz) != COPLANAR
File       : /data/OpenSCAD/libraries-mingw64-master/mxe-w64/usr/x86_64-w64-mingw32.static/include/CGAL/convex_hull_3.h
Line       : 350
Explanation:
Refer to the bug-reporting instructions at http://www.cgal.org/bug_report.html
[Thread 10444.0x1250 exited with code 3]
[Thread 10444.0x11b0 exited with code 3]
[Thread 10444.0x2dbc exited with code 3]
[Thread 10444.0x2c14 exited with code 3]
[Inferior 1 (process 10444) exited with code 03]
(gdb) bt
No stack.
(gdb)

OpenSCAD Version: 2014.12.20
System information: Windows 8 (v6.2) 4 CPUs 15.98 GB RAM
Compiler, build date: GCC "4.9.2" 64bit, Dec 20 2014
Boost version: 1_57
Eigen version: 3.2.2
CGAL version, kernels: 4.5, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.3.2
Qt version: 5.4.0
QScintilla version: 2.8.4
MingW build: MingW64
GLib version: 2.42.1
Application Path: C:/Program Files/OpenSCAD
Documents Path: C:\Users\Øystein\Documents
Resource Path: C:/Program Files/OpenSCAD
User Library Path: 
User Config Path: C:\Users\Øystein\AppData\Local/OpenSCAD
Backup Path: 
OPENSCADPATH: 
OpenSCAD library path:

C:/Program Files/OpenSCAD\libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.11.0
OpenGL Version: 4.4.0
GL Renderer: GeForce GTX 570/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Using QGLWidget

GL Extensions:
GL_AMD_multi_draw_indirect
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_texture
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_blend_equation_advanced
GL_KHR_debug
GL_KTX_buffer_region
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NV_ES1_1_compatibility
GL_NV_ES3_1_compatibility
GL_NV_bindless_multi_draw_indirect
GL_NV_bindless_multi_draw_indirect_count
GL_NV_blend_equation_advanced
GL_NV_blend_square
GL_NV_compute_program5
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_draw_texture
GL_NV_explicit_multisample
GL_NV_fence
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_gpu_program4
GL_NV_gpu_program4_1
GL_NV_gpu_program5
GL_NV_gpu_program5_mem_extended
GL_NV_gpu_program_fp64
GL_NV_gpu_shader5
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_shader_atomic_counters
GL_NV_shader_atomic_float
GL_NV_shader_buffer_load
GL_NV_shader_storage_buffer_object
GL_NV_shader_thread_group
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_expand_normal
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_attrib_integer_64bit
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum
GL_WIN_swap_hint
WGL_EXT_swap_control

**Comment by oysteinkrog** [comment]
I compiled a debug version of openscad (using msys2), and tried to get stack using gdb, but gdb does not break when the C++ runtime exception popup appears (and I can't write any gdb commands).
When I close the popup the openscad process is also closed, which means I also can't use any gdb commands.
How do I make gdb break?
I wanted to enclose stack info etc.

**Comment by oysteinkrog** [comment]
Ah, I had to use "catch catch" and "catch throw" in gdb.
```
Catchpoint 2 (exception thrown), 0x00000000005298b0 in __cxa_throw ()
(gdb) bt
#0  0x00000000005298b0 in __cxa_throw ()
#1  0x000000000071c4f9 in make_certain (this=<optimized out>)
    at C:/msys64/mingw64/include/CGAL/Uncertain.h:125
#2  operator bool (this=<optimized out>)
    at C:/msys64/mingw64/include/CGAL/Uncertain.h:133
#3  has_on_positive_side (p=..., this=<optimized out>)
    at C:/msys64/mingw64/include/CGAL/Plane_3.h:206
#4  CGAL::internal::Convex_hull_3::Is_on_positive_side_of_plane_3<CGAL::Convex_hull_traits_3<CGAL::Epick>, CGAL::Boolean_tag<true> >::operator() (
    this=this@entry=0x238010, s=...)
    at C:/msys64/mingw64/include/CGAL/convex_hull_3.h:233
#5  0x0000000000660a77 in CGAL::internal::Convex_hull_3::non_coplanar_quickhull_3<CGAL::Triangulation_data_structure_2<CGAL::Triangulation_vertex_base_with_info_2<int, CGAL::GT3_for_CH3<CGAL::Convex_hull_traits_3<CGAL::Epick> >, CGAL::Triangulation_vertex_base_2<CGAL::GT3_for_CH3<CGAL::Convex_hull_traits_3<CGAL::Epick> >, CGAL::Triangulation_ds_vertex_base_2<void> > >, CGAL::Convex_hull_face_base_2<int, CGAL::Convex_hull_traits_3<CGAL::Epick>, CGAL::Triangulation_face_base_2<CGAL::Convex_hull_traits_3<CGAL::Epick>, CGAL::Triangulation_ds_face_base_2<void> > > >, CGAL::Convex_hull_traits_3<CGAL::Epick> > (
    points=std::list = {...}, tds=..., traits=...)
    at C:/msys64/mingw64/include/CGAL/convex_hull_3.h:617
#6  0x0000000000661ce3 in CGAL::internal::Convex_hull_3::ch_quickhull_polyhedron_3<std::_List_iterator<CGAL::Point_3<CGAL::Epick> >, CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Convex_hull_traits_3<CGAL::Epick> > (points=std::list = {...},
    point1_it=point1_it@entry=..., point2_it=point2_it@entry=...,
    point3_it=point3_it@entry=..., P=..., traits=...)
    at C:/msys64/mingw64/include/CGAL/convex_hull_3.h:771
#7  0x000000000057d17a in CGAL::convex_hull_3<std::_Rb_tree_const_iterator<CGAL::Point_3<CGAL::Epick> >, CGAL::Polyhedron_3<CGAL::Epick, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::allocator<int> >, CGAL::Convex_hull_traits_3<CGAL::Epick> > (first=..., beyond=..., beyond@entry=..., polyhedron=...,
    traits=...) at C:/msys64/mingw64/include/CGAL/convex_hull_3.h:947
#8  0x00000000004ff248 in convex_hull_3<std::_Rb_tree_const_iterator<CGAL::Point_3<CGAL::Epick> >, CGAL::Polyhedron_3<CGAL::Epick> > (polyhedron=...,
    beyond=..., first=...)
    at C:/msys64/mingw64/include/CGAL/convex_hull_3.h:959
#9  CGALUtils::applyHull (children=std::list, result=...)
    at src/cgalutils.cc:144
#10 0x00000000004738ed in GeometryEvaluator::applyToChildren3D (
    this=this@entry=0x239af0, node=..., op=op@entry=OPENSCAD_HULL)
    at src/GeometryEvaluator.cc:115
#11 0x0000000000474d71 in GeometryEvaluator::applyToChildren (
    this=this@entry=0x239af0, node=..., op=op@entry=OPENSCAD_HULL)
    at src/GeometryEvaluator.cc:98
#12 0x0000000000476828 in GeometryEvaluator::visit (this=0x239af0, state=...,
    node=...) at src/GeometryEvaluator.cc:1000
#13 0x00000000006c6f44 in CgaladvNode::accept (this=<optimized out>,
    state=..., visitor=...) at src/cgaladvnode.h:24
#14 0x00000000004728c2 in Traverser::traverse (this=0x238dd0, node=...,
    state=...) at src/traverser.cc:41
#15 0x0000000000472a23 in Traverser::execute (this=0x302bbd60,
    this@entry=0x238dd0) at src/traverser.cc:11
#16 0x0000000000472ff3 in GeometryEvaluator::evaluateGeometry (this=0x239af0,
    node=..., allownef=allownef@entry=false) at src/GeometryEvaluator.cc:58
#17 0x00000000004b2fbc in CSGTermEvaluator::visit (this=0x239bc0, state=...,
    node=...) at src/CSGTermEvaluator.cc:208
#18 0x00000000006c6f44 in CgaladvNode::accept (this=<optimized out>,
    state=..., visitor=...) at src/cgaladvnode.h:24
#19 0x00000000004728c2 in Traverser::traverse (this=this@entry=0x2397a0,
    node=..., state=...) at src/traverser.cc:41
#20 0x0000000000472901 in Traverser::traverse (this=this@entry=0x2397a0,
    node=..., state=...) at src/traverser.cc:30
#21 0x0000000000472901 in Traverser::traverse (this=this@entry=0x2397a0,
    node=..., state=...) at src/traverser.cc:30
#22 0x0000000000472901 in Traverser::traverse (this=this@entry=0x2397a0,
    node=..., state=...) at src/traverser.cc:30
#23 0x0000000000472901 in Traverser::traverse (this=0x2397a0, node=...,
    state=...) at src/traverser.cc:30
#24 0x0000000000472a23 in Traverser::execute (this=0x302bbd60,
    this@entry=0x2397a0) at src/traverser.cc:11
#25 0x00000000004b19cc in CSGTermEvaluator::evaluateCSGTerm (
    this=this@entry=0x239bc0, node=...,
    highlights=std::vector of length 0, capacity 0,
    background=std::vector of length 0, capacity 0)
    at src/CSGTermEvaluator.cc:36
#26 0x00000000004d6df2 in MainWindow::compileCSG (this=this@entry=0x2d89db00,
    procevents=procevents@entry=true) at src/mainwin.cc:1063
#27 0x00000000004d7fd0 in MainWindow::csgReloadRender (this=0x2d89db00)
    at src/mainwin.cc:1667
#28 0x000000000051eeab in MainWindow::qt_static_metacall (_o=<optimized out>,
    _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at objects/moc_MainWindow.cpp:484
#29 0x000000000d72af8e in QMetaMethod::invoke (this=0x23a700, object=
    0x2d89db00, connectionType=Qt::DirectConnection, returnValue=...,
    val0=..., val1=..., val2=..., val3=..., val4=..., val5=..., val6=...,
    val7=..., val8=..., val9=...) at kernel/qmetaobject.cpp:2183
#30 0x000000000d72a36a in QMetaObject::invokeMethod (obj=0x2d89db00,
    member=0x7b7a98 <lodepng_default_compress_settings+33656> "csgReloadRender", type=Qt::AutoConnection, ret=..., val0=..., val1=..., val2=..., val3=...,
    val4=..., val5=..., val6=..., val7=..., val8=..., val9=...)
    at kernel/qmetaobject.cpp:1478
#31 0x00000000004d6b9a in invokeMethod (val9=..., val8=..., val7=...,
    val6=..., val5=..., val4=..., val3=..., val2=..., val1=..., val0=...,
    member=0x1 <Address 0x1 out of bounds>, obj=0x2d89db00)
    at C:/msys64/mingw64/include/QtCore/qobjectdefs.h:407
#32 MainWindow::compileDone (this=this@entry=0x2d89db00,
    didchange=didchange@entry=true) at src/mainwin.cc:962
#33 0x00000000004e47b4 in MainWindow::compile (this=0x2d89db00,
    reload=<optimized out>, forcedone=<optimized out>) at src/mainwin.cc:935
#34 0x00000000004e4894 in MainWindow::waitAfterReload (this=0x2d89db00)
    at src/mainwin.cc:945
#35 0x000000000051f16c in MainWindow::qt_static_metacall (_o=<optimized out>,
    _c=<optimized out>, _id=<optimized out>, _a=<optimized out>)
    at objects/moc_MainWindow.cpp:537
#36 0x000000000d7545c0 in QMetaObject::activate (sender=0x2e4cab70,
    signalOffset=3, local_signal_index=0, argv=0x0) at kernel/qobject.cpp:3716
#37 0x000000000d753d7a in QMetaObject::activate (sender=0x2e4cab70,
    m=0xd9e1c20 <QTimer::staticMetaObject>, local_signal_index=0, argv=0x0)
    at kernel/qobject.cpp:3582
#38 0x000000000d7b6072 in QTimer::timeout (this=0x2e4cab70)
    at .moc/debug/moc_qtimer.cpp:192
#39 0x000000000d758749 in QTimer::timerEvent (this=0x2e4cab70, e=0x23b700)
    at kernel/qtimer.cpp:247
#40 0x000000000d74dbf6 in QObject::event (this=0x2e4cab70, e=0x23b700)
    at kernel/qobject.cpp:1226
#41 0x000000001b6a0d90 in QApplicationPrivate::notify_helper (this=0x303f90,
    receiver=0x2e4cab70, e=0x23b700) at kernel/qapplication.cpp:3722
#42 0x000000001b69e4c8 in QApplication::notify (this=0x23f070,
    receiver=0x2e4cab70, e=0x23b700) at kernel/qapplication.cpp:3164
#43 0x000000000d7221f4 in QCoreApplication::notifyInternal (this=0x23f070,
    receiver=0x2e4cab70, event=0x23b700) at kernel/qcoreapplication.cpp:932
#44 0x000000000d7e224b in QCoreApplication::sendEvent (receiver=0x2e4cab70,
    event=0x23b700)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:228
#45 0x000000000d77d2ab in QEventDispatcherWin32Private::sendTimerEvent (
    this=0x314f50, timerId=16) at kernel/qeventdispatcher_win.cpp:615
#46 0x000000000d77c774 in qt_internal_proc (hwnd=0x110eca, message=275,
    wp=16, lp=0) at kernel/qeventdispatcher_win.cpp:417
#47 0x00007ffb04e2250d in USER32!DispatchMessageW ()
   from C:\Windows\system32\user32.dll
#48 0x0000000000110eca in ?? ()
#49 0x0000000000000113 in ?? ()
#50 0x0000000000000010 in ?? ()
#51 0x0000000000000000 in ?? ()
```

**Comment by kintel** [comment]
Looks like a bug in CGAL. I wrote a minimal CGAL program which also crashes:
```
#include <CGAL/Exact_predicates_inexact_constructions_kernel.h>
#include <CGAL/convex_hull_3.h>

typedef CGAL::Epick K;

int main()
{
  std::vector<K::Point_3> points;
  points.push_back(K::Point_3(-71.199011502334841, 14.664467308583257, 32.003440443428268));
  points.push_back(K::Point_3(-71.199011502334841, 26.092309142341527, 28.509598571991564));
  points.push_back(K::Point_3(-71.199011502334841, 37.520150976099799, 25.01575670055486));
  points.push_back(K::Point_3(-71.199011502334841, 0, 0));

  CGAL::Polyhedron_3<K> r;
  CGAL::convex_hull_3(points.begin(), points.end(), r);

  return 0;
}
```

**Comment by kintel** [comment]
The issue seems to be that CGAL first selects three vertices which are not collinear (i.e. defines a valid plane in space), and later asserts that these three vertices are indeed non collinear. ..but they use two different ways for testing for collinearity which gives different results for the three first vertices in the program above.

**Comment by kintel** [comment]
See http://cgal-discuss.949826.n4.nabble.com/Epick-convex-hull-3-assertion-td4660264.html

**Comment by kintel** [comment]
@oysteinkrog Could you give the latest master a spin? I fixed some things which should make all this a bit robust, partially including the other issues you reported.

**Comment by oysteinkrog** [comment]
I can confirm that latest master fixes this, thank you:)
