### ISSUE TITLE
Crash on highly concave minkowski

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1097]
Reported by @Scalpel78:
The following design causes a hard crash.

The crash happens in Nef_nary_union_3::add_polyhedron(): https://github.com/openscad/openscad/blob/master/src/cgalutils.cc#L658
..when trying to union the minkowski'ed convex decomposition (56 objects).

PS! Running this in a debugger causes a crash in most cases, but it's not 100% deterministic.

```
depth=20; 
height=43; 
width=60; 
outerhole=20; 
innerhole=10; 

minkowski() { 
    difference() { 
        cube([depth, width, height], center=true); 
        translate([0,0,height/10]) rotate([0,90, 0]) cylinder(d=outerhole, h=depth*2, center=true); 
        translate([0, -width/2+(width/8.1), height/2.75]) cube([depth+1, width/4, height/3], center=true); 
        translate([0, width/2-(width/8.1), height/2.75]) cube([depth+1, width/4, height/3], center=true); 
        for (x = [-4,12]) 
            for (y = [-22,22]) 
                rotate([0,90,0]) translate([x,y,0]) cylinder(d=5.5, h=depth+1, center=true); 
        translate([0,-width/2+8,0]) cylinder(d=6.6, h=height+1, center=true); 
        mirror([0,1,0]) translate([0,-width/2+8,0]) cylinder(d=6.6, h=height+1, center=true); 
    } 
    sphere(2); 
}
```

**Comment by kintel** [comment]
I've been fixing some corner cases and, in the latest master, this problem has apparently been reduced down to being a duplicate of #1105. Let's keep it open until it's sorted though.

**Comment by kintel** [comment]
Fixed by #1156

**Comment by spicetraders** [comment]
Hello
First I am new to Openscad and its use, just months of use in hand.
So I keep user manual and support docs open all the time.
So far every thing is going along good till I tried to use minkowski on a cylinder cap I was developing.
I could enter in the lines, do a save as for the .scad file but when I went to render it cause the screen to go into the good old spinning color wheel and stay. (OSX 10.11.5)  I had to resort to force quit command to stop it all.  
One selecting the file I had save to open the Openscad launched and locked up immediately.

In searching for why this was doing this has brought me to this previously reported issue (only one I could seem to find) but I see it is closed and resolved.  So am I missing something in my usage of minkowski some rule on do not use this this way?  Or is there still a issue?  

CAP_CORNERS_ROUNDED (locks up)
$fn=20;  //added for corners
minkowski() {  //added for corners
difference(){   /orig
translate ([0,0,0])  cylinder (r=1*10.6, h=17.5, $fa=1, $fs=1);   //orig
    translate ([0,0,3])  cylinder (r=1*8.35, h=17.5, $fa=1, $fs=1);  //orig 
       translate([0,0,-1])  cylinder (r=1*6.46, h=17.5, $fa=1, $fs=1); //orig
}   /orig
    sphere(1);  //added for corners
}   //added for corners

**Comment by t-paul** [comment]
This renders in 38 seconds for me. What OpenSCAD version are you using? The preview (F5) is not run in background, so that might cause the application to get unresponsive for that time (as there's no real way to preview `minkowski()`, it is always fully calculated).

**Comment by spicetraders** [comment]
I had not even click preview, just render.
Openscad 2015.03-3

**Comment by spicetraders** [comment]
Well now I am really lost as I cut and pasted the post lines into a new file and they render.
Only difference between those and the orig file is the //comments and deleting two blank lines, at least as far as I can see. 
Just tried the original file again and locks, but pasting in the above renders.
Even worse taking the original file that locks up on opening and opening it with a text editor then coping the lines from there into a new .scad file also renders just fine.

something in the saved file itself???

**Comment by kintel** [comment]
@spicetraders If your original file still locks up, could you post that exact file somewhere? (e.g. zip it, so it remains exact)

**Comment by spicetraders** [comment]
[cap_with corners copy.scad.zip](https://github.com/openscad/openscad/files/356144/cap_with.corners.copy.scad.zip)

**Comment by spicetraders** [comment]
[minkowski test.scad.zip](https://github.com/openscad/openscad/files/356147/minkowski.test.scad.zip)

This one I did the cut and paste from above posting and it worked once then I save and reopended and it locks up as does the original.

**Comment by kintel** [comment]
@spicetraders Two questions:
1) Could you clarify what "locks up" really means, e.g. how long did you wait before giving up? It takes 1m30s on my i7 MacBook Pro. If you have a significantly slower computer it can take quite a bit longer.

Note: When posting code, you need to enclose them in three backslashes before and after, like this:
```
   // this is code
```

..otherwise, special characters in your code will trigger text formatting, making it impossible to copy&paste without looking at the 'source' of your comment

**Comment by kintel** [comment]
Another note: To clarify what @t-paul said: If you're using preview (F5), it will execute synchronously and lock up the GUI until it's done. When using Render (F6), it will run mostly in the background and your should at the very least see a progress bar in the lower right corner.

If you run out of memory, this will, of course, not help and you might lock up the GUI anyway, until processing is done.

**Comment by spicetraders** [comment]
"Locks Up" to me is when the rainbow wheel starts spinning for more then a few minutes and where I pull down from the "APPLE"  Force Quit and the listing shows OPENSCAD as (not responding).  I also do not see the blue progress line that would normally be seen when render is running.  The Force Quit report show non-responsive in its summary.
If I paste a copy of the lines into a newly opened window and render they render in about a minute or two, (seeing the blue progress line).  But after saving and reopening they go right into a lock up.

I will install OPENSCAD on my wife's MACBOOK when I can kick her off it and see if it fails there, and try on my old MAC mini as soon as the 3D print I am pushing runs its course.  

Will note the "// this is code" for future  and that is three 3?

**Comment by kintel** [comment]
Yep, it's three (3) _backslashes_, around every code block.

Your problem is a bit puzzling. There is a small chance that this is a new bug only visible on OS X 10.11.x. I can try to give that a quick spin - just need to dig up an appropriate computer.

**Comment by doug-moen** [comment]
I have the same problem, on my 2010 Macbook Air, with version 2016.01.27.
It locks up for more than 5 minutes, the first time I run the script, using
F5 preview. For the first minute, other applications are also affected, and
the entire system becomes very sluggish for a while (I'm running El Capitan
with 4GB ram). After it has been run once, the geometry is in the geometry
cache, and the same model renders quickly. Quitting OpenSCAD, restarting
and reloading the script results in an empty geometry cache, so the problem
reoccurs.

Marius has already explained why this happens. It's a particular problem
with minkowski(), since that invokes geometry rendering during F5 preview,
and minkowski() on concave solids is very slow.

Based on Marius's comments, I'd guess this is a known problem, but it's
still a bug. It should be fixed by making F5 preview not lock up the GUI,
using the same strategy that allows F6 render to not lock up the GUI.

**Comment by spicetraders** [comment]
I just install OPENSCAD on my MAC Mini and it is also repeating the problem.  The first cut and past in a new editor window renders with out issue.
But save the file and reopen and it ends in program not responding.
I notice the console never makes it to the rendering polymesh

**Comment by spicetraders** [comment]
@doug-moen After reading your post, I put my patience on hold to just use force quit and walked away from the screen for a bit and after returning the render did finish.  ---

NOTE: both renders on a fresh paste in a new window and renders on reopening of the save file that had the long delay before finishing, have the Console showing both as taking 1 min and 43-44secs rendering time.

ALSO, can some one tell me what the polygon anomalies that are seen on the X axis only of the outer cylinder lower shell?  These should not be there by my understanding.  And I had one copy of the file that did not show them occurring.
