### ISSUE TITLE
boost assert fail

### ISSUE THREAD

**Issue by TomConlin** [openscad/openscad#1117]
i5 laptop running up to date Mint 
OpenSCAD version 2013.05.28    (most current via apt-get install)
libboost is most current via apt-get (v1.53)

when reading in, or attempting to render my openscad files generated a year ago 
on another system (worked perfectly back then)

```
$ openscad
openscad: /usr/include/boost/smart_ptr/shared_ptr.hpp:653: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = CSGTerm; typename boost::detail::sp_member_access<T>::type = CSGTerm*]: Assertion `px != 0' failed.
Aborted
```

**Comment by TomConlin** [comment]
Changing my OS from Mint16 to  (bleeding edge) Mint17 does allow installing openscad from the Ubuntu PPA with the latest stable (2014.03) release which does not report boost errors and does correctly handle modules using "children()". 
I suspect you were never t asked 
but pinning Ubuntu apt to a development snapshot was poor planning by someone.

**Comment by kintel** [comment]
Thanks for the heads-up. Btw., do you know if there is a good way of finding out which version of OpenSCAD is included with which Linux Mint version and who is the package maintainer?

**Comment by TomConlin** [comment]
Mint is just Ubuntu with the gaudy bits stripped back a bit 
so any issue with Mint will be fixed for free 
by addressing any (larger) Ubuntu package maintainer issue.  
With the cavate Mint tends to remain useable longer.

A mapping of Mint versions to the Unbuntu it is base on is found on 
http://www.linuxmint.com/oldreleases.php

**Comment by kintel** [comment]
Oh, in that case, your problem was likely that older Ubuntu had a bug in the OpenSCAD package script which reported the version as the build date rather than the release version of OpenSCAD.
