### ISSUE TITLE
Windows Build (openscad_win32_res.o not built automatically)

### ISSUE THREAD

**Issue by sbguthery** [openscad/openscad#1120]
The Windows build ("qmake openscad.pro CONFIG-=debug") seems to expect openscad_win32_res.o in /objects but /objects is empty after "git clone git://github.com/openscad/openscad.git"
Cheers, Scott
##

**Comment by bgks** [comment]
```
$ windres -i openscad_win32.rc -o objects/openscad_win32_res.o --include-dir=

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.
Assertion failed!

Program: C:\msys64\mingw64\bin\windres.exe
File: ../../binutils-2.25.1/binutils/windres.c, Line 767

Expression: *p != '\0'
```

**Comment by kintel** [comment]
@bgks You shouldn't run windres manually. Our build system should do this. The error you just posted is windres itself crashing. To hunt that down, perhaps start here: http://ehc.ac/p/mingw/bugs/search/?q=windres

**Comment by bgks** [comment]
@kintel: the build system fails (as well as the precompiled binary, that crashes throwing quite the same message).
```
$ qmake openscad.pro CONFIG0-=debug
Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
WARNING: Failure to find: objects/openscad_win32_res.o
Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
WARNING: Failure to find: objects/openscad_win32_res.o
```

**Comment by t-paul** [comment]
So far this are only warnings (and a typo in CONFIG). What's the error message when building?

**Comment by bgks** [comment]
@t-paul: qtcreator fails with
```
:-1: Fehler: No rule to make target '../openscad/objects/openscad_win32_res.o', needed by 'release/openscad.exe'.  Stop.
```
I tried windres from the cross-binuntils package that provides a more elaborative error statement
```
$ /opt/bin/x86_64-w64-mingw32-windres.exe -i openscad_win32.rc -o objects/openscad_win32_res.o --include-dir=
assertion "*p != '\0'" failed: file "/build2/mingw-w64-cross-binutils/src/binutils-2.25/binutils/windres.c", line 766, function: windres_add_include_dir
Aborted
```
I can create [sorry, just hacking] a `openscad_win32_res.o` by dropping the `--includedir=` argument.
```
windres -i openscad_win32.rc -o objects/openscad_win32_res.o
```
Once I created an `openscad_win32_res.o` manually the build completes with 143 warnings. Nevertheless, the compiled release binary has like the precompiled one the 'Microsoft Visual C++ Runtime Library' crashing with an 'Runtime Error' explained as 'This application has requested the Runtime to terminate it in an unusual way. Please contact the application's support team for more information.'

**Comment by kintel** [comment]
Thanks for the clarification. The initial issue looks like we're triggering a crash bug in _windres_ which we could avoid by tweaking the build system.

Btw., are you saying that our precompiled Windows binaries have a problem? That sounds like a separate issue; could you make sure you use the latest binaries (2015.03-2) and if that fails, open a new issue?

**Comment by bgks** [comment]
@kintel: I'm not used to openSCAD nor to QT/qtcreator nor to SYS2. I don't understand the importance of `--includedir=` nor the impact of an external build of `openscad_win32_res.o`. An assumable correspondence to the topic was that an `openscad_win32_res.o` from a different build configuration might persist in a build system that builds a couple of configurations, thus hiding the crash of windres. 
 
Right now I only see the stack of the runlib-error dialog waiting for user-ok in the debug version. I'll dig into that, later. Up to now I tried the precompiled `OpenSCAD 2015.03-2 x86 (64-bit)` on Windows 1511 Pro [nx on] with OpenGL 4.4 SLI Gfx and the debug accordingly to [OpenSCAD User Manual/Building on Microsoft Windows](https://en.wikibooks.org/w/index.php?title=OpenSCAD_User_Manual/Building_on_Microsoft_Windows&oldid=2995800) on the same machine

**Comment by kintel** [comment]
@bgks I didn't quite understand the issue. You're mentioning that your self-build debug version immediately fails with the mentioned "c++ runtime" error.
Is the precompiled release version of 2015.03-2 exhibiting the same problem?

**Comment by donbright** [comment]
im guessing the original issue is regarding a qmake warning on msys2 qt5 windows10, not anything that prevents a build.

i have seen the same, and it looks like a bug in qmake qt5 on msys2 inside window10

(guessing the original poster used msys2 because thats the only time instructions call for CONFIG-=debug)

it looks like this when you run qmake
```
WARNING: Failure to find objects/openscad_win32_res.o
```

if you run `qmake -d -d -d` you see this

```
DEBUG 3: Fixed[0,1] C:/msys64/mingw64/share/qt5/mkspecs/features/uic.prf :: to :: ../../../../mingw64/share/qt5/mkspecs/features/uic.prf [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[0,1] C:/msys64/mingw64/share/qt5/mkspecs/features/resolve_config.prf :: to :: ../../../../mingw64/share/qt5/mkspecs/features/resolve_config.prf [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[0,1] C:/msys64/mingw64/share/qt5/mkspecs/features/default_post.prf :: to :: ../../../../mingw64/share/qt5/mkspecs/features/default_post.prf [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[0,1] C:/msys64/mingw64/share/qt5/mkspecs/features/link_pkgconfig.prf :: to :: ../../../../mingw64/share/qt5/mkspecs/features/link_pkgconfig.prf [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[0,1] C:/msys64/home/hmbri/openscad/openscad.pro :: to :: ../openscad.pro [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] objects/openscad_win32_res.o :: to :: bin2/objects/openscad_win32_res.o [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] objects/ :: to :: bin2/objects [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 1: C:\repo\mingw-w64-qt5\src\x86_64\qtbase/qmake/generators/makefile.cpp:324 Failure to find objects/openscad_win32_res.o in vpath (C:/msys64/home/hmbri/openscad/bin2)
WARNING: Failure to find: objects/openscad_win32_res.o
DEBUG 3: Fixed[3,1] ../src/scintillaeditor.cpp :: to :: src/scintillaeditor.cpp [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] ../src/scadlexer.cpp :: to :: src/scadlexer.cpp [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] ../src/AST.cc :: to :: src/AST.cc [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] ../src/ModuleInstantiation.cc :: to :: src/ModuleInstantiation.cc [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]
DEBUG 3: Fixed[3,1] ../src/expr.cc :: to :: src/expr.cc [C:/msys64/home/hmbri/openscad::C:/msys64/home/hmbri/openscad/bin2]

```

for some reason when 'fixing' paths it is trying to look for openscad_win32_res.o which of course hasn't been created yet at qmake time. It is just a warning, so building after this warning proceeds as normal.

re-running qmake also doesn't show the warning, because the file gets built properly during 'make'

solution is to print a "ignore this warning" message during qmake on msys

**Comment by kintel** [comment]
Closing as this doesn't sounds like a bug
