### ISSUE TITLE
Clarify Render vs. Preview icons in the toolbar

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1121]
A typical beginner's error is to hit the wrong button in the toolbar when trying to preview.
The instinct seems to be to hit the "Play" button, which is Render, because the Preview button doesn't have a clearly recognizable icon.

-> Redraw or otherwise clarify the icon function. One idea could be to include a subtitle per icon. This is a very common UI guideline.

**Comment by atartanian** [comment]
how about something like this (dashed for preview, solid line for render):
![screen shot 2015-01-19 at 11 38 15 am](https://cloud.githubusercontent.com/assets/1625877/5803936/11b0f7b8-9fd0-11e4-9d87-a0a7a4cfdbc4.png)

or maybe this for render to be more explicit:
![screen shot 2015-01-19 at 11 40 51 am](https://cloud.githubusercontent.com/assets/1625877/5803948/2162240c-9fd0-11e4-84e9-f053ce2e63fc.png)

**Comment by atartanian** [comment]
or more in the vein of @kintel 's suggestion of a clock...

![screen shot 2015-01-19 at 3 30 27 pm](https://cloud.githubusercontent.com/assets/1625877/5807334/325299c0-9ff0-11e4-8778-6b8d110656ff.png)

**Comment by MichaelAtOz** [comment]
Nice work. Personally I like the first preview (KISS) and the second render (ie sandglass).

**Comment by t-paul** [comment]
I like the last version. I'll try to see how those look in the application scaled to 32x32...

Also we had the crazy idea for later to create a set of icons based on OpenSCAD scripts :-). Those two should be nicely convertible to *.scad.

**Comment by kintel** [comment]
I like the last version too!

One minor improvement might be to lower the view angle of the cube to make it look a bit less symmetric.
..but the key is how well it looks in typical toolbar resolutions.

 -Marius

**Comment by atartanian** [comment]
ah ok didn't know the resolution... i can try to make optimized 32x32 versions

**Comment by atartanian** [comment]
![preview_black](https://cloud.githubusercontent.com/assets/1625877/5821970/11a94dbe-a09e-11e4-96a7-25b6021cf209.png)
![preview_white](https://cloud.githubusercontent.com/assets/1625877/5821969/11a6668a-a09e-11e4-9c81-27355fe81012.png)

**Comment by kintel** [comment]
@atartanian Looks good - See #1171. Could you confirm that the icons can be licensed as CC0?

**Comment by atartanian** [comment]
yup go for it

**Comment by kintel** [comment]
@atartanian Do you happen to have drawn those icons in a vector program? I'm looking into ways of scaling them better for retina displays.
