### ISSUE TITLE
DEPRECATED: should be colored as warning in Console

### ISSUE THREAD

**Issue by Scalpel78** [openscad/openscad#1143]
When using a function that is deprecated you get a line in the Console saying something like; 

DEPRECATED: child() will be removed in future releases. Use children() instead.

That line should be colored in the same way as WARNING: does.
![image](https://cloud.githubusercontent.com/assets/1316578/5647361/7ec7238a-9685-11e4-84e1-258b8bd11fe7.png)

**Comment by kintel** [comment]
Agreed

**Comment by t-paul** [comment]
Added to #1142 as this would otherwise conflict.
