### ISSUE TITLE
Error using Surface command

### ISSUE THREAD

**Issue by magotheobroma** [openscad/openscad#1146]
When I use the Surface command always I get an error.
As example, with this code
![err1-b](https://cloud.githubusercontent.com/assets/10440988/5660163/363da434-971d-11e4-9ff9-16c2d9aa7bb1.JPG)
I get this error:
![err1-a](https://cloud.githubusercontent.com/assets/10440988/5660183/67bc03de-971d-11e4-933b-236d95260a9e.JPG)

**Comment by MichaelAtOz** [comment]
surface() with .png is only supported in development snapshots ATM. Looks like you are on 2014.03?

**Comment by magotheobroma** [comment]
Yes, I'm on 2014.03. Thanks.

Da: "Michael" notifications@github.com
A: "openscad/openscad" openscad@noreply.github.com
Cc: "Roberto Caraceni" roberto@corsicioccolato.it
Data: Thu, 08 Jan 2015 01:25:19 -0800
Oggetto: Re: [openscad] Error using Surface command (#1146)

**Comment by t-paul** [comment]
The crash should be fixed too, trying with some random data (using /dev/urandom) a warning message is shown as expected.
```
WARNING: Illegal value in '/dev/urandom': bad lexical cast: source type value could not be interpreted as target
```
