### ISSUE TITLE
GUI issues

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#1149]
- [x] Some icons are not working with a dark theme
- [x] Welcome screen is unreadable in dark theme
- [x] The font for the info window should only use bold so it reacts to user settings

![he7f4f6](https://cloud.githubusercontent.com/assets/1330241/5674608/c3dd79f0-97ad-11e4-9825-757ae5ff8088.png)

![snapshot1](https://cloud.githubusercontent.com/assets/1330241/5681985/327ae0ea-981d-11e4-8e96-5ae9fcd0b4c4.png)

**Comment by MichaelAtOz** [comment]
Should the extra warning ONLY show when the console is hidden?

**Comment by t-paul** [comment]
No, I don't think it should depend on the console visibility. There might be other ways like hide it after some time or even make it configurable.

**Comment by t-paul** [comment]
See #1150...

**Comment by MichaelAtOz** [comment]
> There might be other ways like hide it after some time or even make it configurable.

Perhaps when there is activity in the editor window?

But configurable would be good, I usually have the console open so it would be superfluous for me.
