### ISSUE TITLE
Syntax highlighting: # affects the whole line

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1172]
This is likely due to QScintilla's C++ parser tagging the whole line as a preprocessor directive.
The solution is probably to write our own parser component for QScintilla.

![screen shot 2015-01-21 at 19 13 38 pm](https://cloud.githubusercontent.com/assets/186094/5848010/a506ffe4-a1a1-11e4-8169-f927fec8f049.png)
##

**Comment by ChrisCoxArt** [comment]
The problem is in the scintilla CPP lexer used by Qscintilla.

QScintilla/scintilla/lexers/LexCPP.cpp LexerCPP::Lex()
```
			} else if (sc.ch == '#' && visibleChars == 0) {
				// Preprocessor commands are alone on their line
				sc.SetState(SCE_C_PREPROCESSOR|activitySet);
```
The logic after setting the preprocssor state is very C/C++ specific and not very customizable.
The rest of the state machine under 	
```
		case SCE_C_PREPROCESSOR:
```
is also veryC/C++ specific and non-customizable.

We can do a little better and highlight everything after the first word by setting 
        newLexer->setStylePreprocessor(true);
in the OpenSCAD code (ScintillaEditor.cc / void ScintillaEditor::setColormap() ). That will highlight everything after the first word, but the first word will remain unhighlighted until there is a change to the scintilla code.

**Comment by t-paul** [comment]
For reference, the separate lexer code is in branch: https://github.com/openscad/openscad/tree/lexertl

**Comment by ChrisCoxArt** [comment]
Relevant bits of the branch (which hasn't been updated since 2015):
qscintillaeditor.cpp
scadlexer.cpp
lex.cc
lex.h
lexertl/*

**Comment by ChrisCoxArt** [comment]
The lexertl library could be added to the dependency downloads, but homebrew doesn't list it, which would break the homebrew builds.
I guess it could go into source/ext or somewhere in the openscad tree.

**Comment by t-paul** [comment]
It's a not too big header only library, so integrating into src/ext should be ok. I guess we would need to switch to the C++14 version though, which seems to be maintained https://github.com/BenHanson/lexertl14.

**Comment by ChrisCoxArt** [comment]
Do we want a partial fix for the time being (allow syntax coloring for everything after the first word after the '#'), or wait for a complete fix ?
The partial fix is one line
```
 newLexer->setStylePreprocessor(true);
```

**Comment by t-paul** [comment]
If it helps a bit, why not. I would assume it can't make it worse than it is now. Does it also help with the auto completion on that line?

**Comment by ChrisCoxArt** [comment]
OK, give me a few minutes to find a branch that isn't already waiting on a pull request.
As far as I can tell, auto completion is already working on # lines.

**Comment by ChrisCoxArt** [comment]
and now we wait an hour for all the checks to run...

**Comment by ChrisCoxArt** [comment]
All checks done after 103 minutes.
If I'd know that, I would have ordered dinner at the start...

**Comment by ChrisCoxArt** [comment]
ok, got lexertl14 sorta working.  Biggest problem right now is that the categories in the current and lexertl descriptions don't match up at all.  I'll have to see what sort of temporary mapping I can come up with.

**Comment by t-paul** [comment]
Yes, we could extend the color schemes with a dedicated new section which allows for the features lexertl can support an keep the other ones until we fully switch.

**Comment by ChrisCoxArt** [comment]
I've gotten things much closer to working, and only really needed one new color category (variables).

What remains: getting the new lexer to load custom keyword sets from the json files (only one example uses them).  Do I try to replace the predefined language set, or add them as additional keyword sets?   The current code replaces the default set, which is not the best of ideas.

**Comment by t-paul** [comment]
Adding new sounds like a safer way. Once all looks good with the new code, we can just remove the old ones.

**Comment by ChrisCoxArt** [comment]
OK, the new lexer and colors are working well. What is the next step to get this tested?

**Comment by t-paul** [comment]
Nothing special, just a normal pull request.

**Comment by ChrisCoxArt** [comment]
Also, is it better to leave the old code commented out, just in case of a massive bug, then remove the old code later.  Or go ahead and remove the old code now, before testing?

**Comment by t-paul** [comment]
I'd say it's fine either way, the old code is still in history too. But if you feel more comfortable to leave it in place for a bit, that's ok.
