### ISSUE TITLE
Allow multi-line indenting

### ISSUE THREAD

**Issue by itsrachelfish** [openscad/openscad#1181]
In many text editors, highlighting a section and pressing tab will indent the entire selected area. Pressing shift + tab will remove an indent from the entire selected area.

It would be nice if OpenSCAD could provide this functionality, especially when adding new functions around existing parts of code. For example, if you have a complex shape and want to rotate the entire thing, you currently have to go onto each line and add tabs individually.

To get around this, I usually edit my OpenSCAD files in other text editors.

Thank you!

**Comment by kintel** [comment]
This was implemented a while ago. Please try out the latest development snapshot.
