### ISSUE TITLE
ComboBoxes are not translated

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#1188]
I was testing my updated Czech translation before I create a pull request and I realized that ComboBoxes are not translated, see:

![translation](https://cloud.githubusercontent.com/assets/2401856/5935434/4cf73578-a6db-11e4-93e0-bd62f0c3328a.png)

All of those string are translated in .mo, but are shown in English.

**Comment by kintel** [comment]
It looks like it's missing the translation in the cs.po file..

**Comment by hroncok** [comment]
It's not. That's the issue. See #1189

**Comment by t-paul** [comment]
It's possible that the initialization code for the settings runs too early, I'll have a look...

**Comment by t-paul** [comment]
Fixed in #1200.
