### ISSUE TITLE
Xfce: Window has no icon

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#1203]
The OpenSCAD main window has no icon and thus appears with default icon in window manager.

![openscad-noicon](https://cloud.githubusercontent.com/assets/2401856/6044231/44d8ebf4-ac92-11e4-9f7d-14314cb7bb41.png)

The most bottom window with default icon is OpenSCAD. Also appears this way with Alt+Tab. Should have the OpenSCAD logo/icon I guess.

**Comment by kintel** [comment]
Could you describe your system and how you installed OpenSCAD (incl. what versions) ?

**Comment by hroncok** [comment]
Oh, OK, sorry.

This is Fedora package from nightly builds. The same happens with latest release. Maybe it my packaging error.

**Comment by kintel** [comment]
The icon works for the Ubuntu nightlies, so I'd investigate a Fedora packaging bug first.

**Comment by hroncok** [comment]
Any tips how to debug this?

**Comment by kintel** [comment]
I was of the impression that the application icon on Linux desktops are managed by the window manager, not the application itself, so it should get its application icon if the appropriate window manager config is installed, e.g. https://github.com/openscad/openscad/blob/master/icons/openscad.desktop.

**Comment by t-paul** [comment]
Yes, I think the application icon should come from
`/usr/share/applications/openscad-nightly.desktop`

and the document icon from
`/usr/share/mime/packages/openscad-nightly.xml`

(paths from my Debian system using the nightly build)

**Comment by kintel** [comment]
Note that the nightly stuff is new in master, after 2015.03.

**Comment by hroncok** [comment]
Well, AFAIK this only affects the icon of app in menu (.desktop) and icon of .scad files (the mime file). Both works here.

**Comment by hroncok** [comment]
So, I've just checked with GNOME and the icon is there. I think the problem is not in Fedora package but that OpenSCAD does not explicitly set the icon for the Window and expects the window manager will use the icon from the desktop file, which might work on GNOME or KDE, but does not work on Xfce.

**Comment by kintel** [comment]
Oh, perhaps Xfce uses the "system tray icon" and defaults to nothing? http://qt-project.org/doc/qt-4.8-snapshot/qsystemtrayicon.html

**Comment by hroncok** [comment]
Well, I don't think tray icon is what's there - tray is something completely different.

What about http://doc.qt.io/qt-4.8/qapplication.html#windowIcon-prop

**Comment by kintel** [comment]
Could give this patch a try?
```
diff --git a/src/openscad.cc b/src/openscad.cc
index 33192ac..f00fc55 100644
--- a/src/openscad.cc
+++ b/src/openscad.cc
@@ -654,6 +654,7 @@ int gui(vector<string> &inputFiles, const fs::path &original_path, int argc, cha
 #else
        QTextCodec::setCodecForCStrings(QTextCodec::codecForName("UTF-8"));
 #endif
+ app.setWindowIcon(QIcon(":/icons/openscad.png"));
        
        // Other global settings
        qRegisterMetaType<shared_ptr<const Geometry> >();
```

**Comment by hroncok** [comment]
Fixes it when running openscad from the source directory. Will check installed RPM after a while.

**Comment by hroncok** [comment]
Yes, that fixes it.
