### ISSUE TITLE
difference and intersection don't work in Windows 10 Pro technical preview (build 9926) !

### ISSUE THREAD

**Issue by lucrol** [openscad/openscad#1219]
This week-end I try to use OpenSCAD version 2014.03 on my ultrabook (Acer Aspire S7-391, Intel  core i7-3517U, RAM 4 Go, video Intel Graphics HD4000, SSD 256 Go) running the Windows 10 Pro technical preview (build 9926).
The difference and intersection statements don't work : no display
Same code works fine on my Workstation (Windows 8.1U1  enterprise) ...

Luc
##

**Comment by t-paul** [comment]
Can you please try the DEV Snapshot from http://files.openscad.org/snapshots/OpenSCAD-2015.02.15-x86-64.zip (That's Release Candidate 3 for the next release) and post the output of the "Help -> Library Info" Dialog.

The problem is likely the graphics driver, the info dialog should list some details about the OpenGL driver.

**Comment by lucrol** [comment]
Thanks Paul
This Release Candidate 3 feel great, but I've the same problem using Windows 10 Technical preview.
I join the images containing the output of Help / Library info.

Luc
![openscad_on_win10_ 1](https://cloud.githubusercontent.com/assets/11027079/6285755/b02a14d6-b8ff-11e4-8a1e-a48894e2749c.png)
![openscad_on_win10_ 2](https://cloud.githubusercontent.com/assets/11027079/6285753/b023e7a0-b8ff-11e4-852f-44d3e8545d44.png)
![openscad_on_win10_ 3](https://cloud.githubusercontent.com/assets/11027079/6285754/b0289f20-b8ff-11e4-9c7f-31e7f79a253d.png)
![openscad_on_win10_ 4](https://cloud.githubusercontent.com/assets/11027079/6285756/b02c6d1c-b8ff-11e4-8664-a785ba8029a5.png)
![openscad_on_win10_ 5](https://cloud.githubusercontent.com/assets/11027079/6285757/b02f6666-b8ff-11e4-9b03-88139ec84916.png)

**Comment by kintel** [comment]
@lucrol Windows previews tend to have problem with OpenGL. Could you try the following:
1) Upgrade to OpenSCAD-2015.02.25
2) Upgrade your OpenGL drivers to the latest version

**Comment by lucrol** [comment]
Hello,
I do the upgrade so :
- Simple use of difference and union works now,
- but nested difference don't.
OpenGL drivers are Embedded in Win 10, 
No specific video driver for this preview from cer or intel.
Windows Update is up to date.
Many thanks.

Luc

**Comment by kintel** [comment]
@lucrol Have you tried to update the drivers yourself? https://downloadcenter.intel.com/download/24593/Intel-HD-Graphics-Driver-for-Windows-7-8-8-1-64-bit

**Comment by t-paul** [comment]
Please check again with latest snapshot builds. Updated OpenCSG now uses different rendering that might help with Intel drivers (see #1409).
