### ISSUE TITLE
Warning: Ignored unknown module text in Mac OS X

### ISSUE THREAD

**Issue by cyberjoac** [openscad/openscad#1220]
Hi,

I'm using OpenScad in Mac OS X and I cannot use the module text()
I'm getting the error message "Warning: Ignored unknown module text in Mac OS X"

Thanks a lot for your help.

**Comment by t-paul** [comment]
The text() module is only supported in the version that is about to be released. Please try the dev-snapshots from http://www.openscad.org/downloads.html (Release should be almost around the corner now).
