### ISSUE TITLE
Preview on headless servers without GPU

### ISSUE THREAD

**Issue by cyberjoac** [openscad/openscad#1222]
Hi,

I'm looking for a way to render a preview of the .scad file in a headless server WITHOUT GPU.
Most of the servers around are without a proper GPU so no access to OpenGL.

Are you aware of any workaround for this?
Thanks

**Comment by t-paul** [comment]
The test framework uses Xvnc or Xvfb to allow preview rendering, e.g. on Travis. That essentially allows OpenGL software rendering via Mesa (Assuming a Linux/Unix environment).
