### ISSUE TITLE
Regression with surface()

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#1223]
Multiple regressions, as well as some weird corner-case image behavior:
* [x] PNG surfaces alway scale their maximum intensity value to have height 100. We should use the intensity values directly, where max intensity is at h=100 and min intensity is at h=0.
* [x] PNG surfaces are 1 unit larger in the Y dimension than the pixel data. This is probably an off-by-one bug
* [x] PNGs should behave in the same way as .dat: Floor at -1 when 0 values are present, floor at 0 otherwise.

From the originally reported issue, the case where there are missing value is covered by the above list; missing values are treated as zeros.

Old Text:
If all values are > 1, the bottom is still at 0 in 2014.03 but at min(values) - 1 for master
```
9 6 7
6 8 9
5 3 2
```
![openscad-surface-regression-1](https://cloud.githubusercontent.com/assets/1330241/6316368/39244872-ba24-11e4-82ca-f74576574604.png)

The behavior for missing values (e.g. in the last line) is different
```
9 6 7
6 8 9
5 3 2
2
```
![openscad-surface-regression-2](https://cloud.githubusercontent.com/assets/1330241/6316369/392510cc-ba24-11e4-8c40-b60b601d659e.png)

**Comment by kintel** [comment]
@t-paul Please have a look if you agree with my solution. I slightly changed behavior, but it's now more in-line with .dat files.
