### ISSUE TITLE
Camera angle too wide

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1236]
From [mailing list](http://forum.openscad.org/Wide-angle-camera-tt11548.html).

We changed the camera angle from 45 to 90 degrees sometime after the 2014.03 release.
This causes a bit intense perspective when looking at 3D objects on a screen.

-> Revert to 45 degrees or so.

**Comment by Matteomt** [comment]
I'd like some $fov variable to set the camera angle as I need
