### ISSUE TITLE
SVG export has unclear or incorrect units/resolution

### ISSUE THREAD

**Issue by matthijskooijman** [openscad/openscad#1253]
Exporting an SVG seems to use "pixels" as the export unit, which wasn't quite what I had expected. When exporting a DXF, it seems to use mm, so I had expected the SVG export to do the same.

Was this intentional or an oversight? Does OpenSCAD need a way to explicitely specify the output unit perhaps?

**Comment by t-paul** [comment]
As of #1600 the SVG export uses fixed mm units. This should be available in the development snapshots.

Options to allow export format specific are subject of #649. If you have additional comments or just want to follow that topic, you can register for updates there.
