### ISSUE TITLE
Support patch level releases of major versions

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1259]
As OpenSCAD tends to get a major release relatively seldomly (1-2 times a year), it would be beneficial to the community if we could release patch level updates with fixes for critical issues, without having to wait a full release cycle. This could also be particularly interesting for Linux distribution packaging.

Things needing resolution && TODO:
* [x] Version numbering scheme: First attempt: use -N, e.g. 2015.03-1
* [x] Auto-update behavior (OS X): We use a date-tagged release. Make sure this doesn't clash with snapshot updates
* [x] How should version number scheme co-exist with Linux packages, which tend to have their own patch level release number scheme? Just append package patchlevel per distribution guidelines
* [x] Define branching & tagging scheme on the git repos: branch: ```YYYY.MM``` tag: ```openscad-YYYY.MM-N```
* [x] Update release checklists
* [x] Update build system to handle new release numbering scheme
* [x] Mac build scripts
* [x] Windows build scripts
* [x] Sanity check with external package managers

**Comment by hroncok** [comment]
I would appreciate if the version is just 2015.03.x without any dash. But
that would, of course, conflict with devel versions based on date.

If you choose to use 2015.03-x I can append the patch level release number
like this. 2015.03-x.y.

Also, those releases would be great,so +1000 from me.

For git branch, why just not name the branch 2015.03.x or 2015.03-x
depending on the version scheme? With actual letter x in there, here I
don't mean it as a placeholder.

**Comment by kintel** [comment]
I feel that 2015.03.x would be too confusing as the x would represent a patch-level incremental number rather than a date.

**Comment by hroncok** [comment]
I agree.
