### ISSUE TITLE
(SVG) export of 3D Models

### ISSUE THREAD

**Issue by htho** [openscad/openscad#1267]
It would be nice to be able to export the "current view" true in scale to SVG. The edges would be the lines.

Some Backgorund:
I want to design casings/frontplates for a PCB. I could check if the drills are in the right position if I could print the top-down/side/bottom view true in scale to paper.
But maybe there is a program that can do this with an exported file?

**Comment by nophead** [comment]
You can use projection() to convert 3D to 2D, so you can then export it in 2D format.

**Comment by htho** [comment]
That was easy! Thanks!
