### ISSUE TITLE
Geometry glitch in openscad 2015.03

### ISSUE THREAD

**Issue by tbuser** [openscad/openscad#1271]
I found this customizer script http://www.thingiverse.com/thing:677959

It used to create a solid heart, but now the heart section has a gap down the center.  You can see it clearly here: http://www.thingiverse.com/thing:731628 vs. an old one here: http://www.thingiverse.com/thing:724620
##

**Comment by kintel** [comment]
Thanks for the test. The reason this fails is that we're a bit more aggressive when merging close vertices in 2015.03 than earlier, and apparently we sometimes fail to handle that properly in all cases.
The reason this particular design triggers this is that it's designed really small; the small heart has a size of 0.2mm.

**Comment by kintel** [comment]
Closing as this has since been fixed.
