### ISSUE TITLE
Automatic reload resets to wrong view

### ISSUE THREAD

**Issue by farbo** [openscad/openscad#1277]
On version 2015.03.22, the automatic reload will change my view on update. The view will change to whatever it was on the latest manual reload. This happens only on a specific, complex assembly, and has been going on for at least about 2 months (as long as I've been using the git version). Small parts work fine, and if I set up a new copy of the whole assembly it works fine too.

This is the project: https://github.com/farbo/bengraver (scad/frame_assembly.scad)

**Comment by t-paul** [comment]
Reproducible (with master / Linux) when touching one of the `use`d files (e.g. `touch bar.scad`).

**Comment by kintel** [comment]
@farbo The latest dev snapshot has a fix for this.
