### ISSUE TITLE
List comprehension example (create polygon points) from documentation does not work

### ISSUE THREAD

**Issue by drillabit** [openscad/openscad#1281]
The following example from the documentation:

// generate ellipse points
function x(a) = 20 * sin(a);
function y(a) = 30 * cos(a);
points = [ for (a = [0 : 5 : 359]) [ x(a), y(a) ] ];
polygon(points);

does not compile in OpenScad 2014.03. There is a Parser Error in line 4 (at the comma between x(a) and y(a))

**Comment by nophead** [comment]
2014.03 is probably too old. It works in 2015.03, the latest release.

**Comment by drillabit** [comment]
Just noticed that this is only available in 2015.03... consider this closed.

**Comment by drillabit** [comment]
Thanks for the comment, just popped up when i found out myself.
