### ISSUE TITLE
Animation Flicker

### ISSUE THREAD

**Issue by davidthings** [openscad/openscad#1284]
Since the last major release (or soon before it) I'm pretty sure Animation has changed for the worse. 

Currently on Mac and Linux (nightly and release) animation flickers quite considerably more than it used to.  I don't think that it's running any slower, I think, perhaps, the screen is being cleared a bit too early? 

I just went back to version 2013.01+dfsg-2.2 and although most of my code didn't  run, (children() spoil everything) what did show up was smooth and flicker free.  Back on the current release, showing only that which displayed on the old version, the display still flickered. 

It's a bummer, because animation was rocking my world. 

I have some pretty crappy video that shows the problem on my machine. 

https://www.dropbox.com/s/47yvwiv123408z9/os_flicker.MOV?dl=0

The video starts and ends at full speed with a slo-mo section in the middle.  I hope this helps.  I'd really like flicker free animation back!

**Comment by TakeItAndRun** [comment]
On Windows with OpenSCAD version 2015.03 it flickers, too.

**Comment by kintel** [comment]
@davidthings The latest dev snapshot has a fix for this. Could you give it a spin?

**Comment by davidthings** [comment]
Already tried!

At least on the Mac, works like a charm.

Thank you SO much.
