### ISSUE TITLE
Openscad 2015.03 (linux) fails to export png

### ISSUE THREAD

**Issue by gratefulfrog** [openscad/openscad#1288]
When running on linux Ubuntu 32bit, I try to export a png, but it captures the screen including the dialog where I choose the filename for the png file.  see attached png resulting from File/Export/Export as image...

This worked fine in the previous version.

![pickupcover04_deeper_grooves](https://cloud.githubusercontent.com/assets/1917335/6893183/1bb962cc-d6cb-11e4-86bb-18207c95aeba.png)

**Comment by ehooo** [comment]
Also for [other Linux](http://www.openscad.org/downloads.html#linux) now only have available version

**Comment by kintel** [comment]
This functionality is currently dependent on the GPU, opengl drivers and window system; we simply read the framebuffer and save it to file. This isn't always safe as each platform manages framebuffer resources differently.
We should probably rewrite this to re-render the current scene into a separate buffer before exporting.

**Comment by gratefulfrog** [comment]
Yes,the current release really fails on linux. Althought, the release
available via the Ubuntu package mgr exports images correctly.

IMHO, this bug was introduced in a recent release.

Thanks for your help!
B

**Comment by kintel** [comment]
The old version exported the second-to-last image, which caused the wrong image to be exported in some cases. The new version exports the correct image, but breaks on platforms where each application windows isn't backed by separate framebuffer resources. To my knowledge this means it's likely to fail on certain X11-based systems.

**Comment by kintel** [comment]
@gratefulfrog Could you tell us more about your system? e.g. Help->Library Info ?
We've tested this on multiple Linux installations without being able to reproduce..

**Comment by gratefulfrog** [comment]
@kintel 

This is my "library Info" : 

OpenSCAD Version: 2015.03
System information: Linux 3.2.0-80-generic #116-Ubuntu SMP Mon Mar 23 17:11:32 UTC 2015 i686 Ubuntu precise (12.04.5 LTS) 4 CPUs 1.72 GB RAM
Compiler, build date: GCC "4.6.3" 32bit, Mar 24 2015
Boost version: 1_46_1
Eigen version: 3.0.5
CGAL version, kernels: 3.9, N4CGAL9CartesianINS_4GmpqEEE, N4CGAL18Extended_cartesianINS_4GmpqEEE, N4CGAL5EpeckE
OpenCSG version: OpenCSG 1.3.2
Qt version: 4.8.1
QScintilla version: 2.6.1
MingW build: No
GLib version: 2.32.4
Application Path: /usr/bin
Documents Path: /home/bob/.local/share
Resource Path: /usr/share/openscad
User Library Path: /home/bob/.local/share/OpenSCAD/libraries
User Config Path: /home/bob/.config/OpenSCAD
Backup Path: /home/bob/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/bob/.local/share/OpenSCAD/libraries
/usr/share/openscad/libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.6.0
OpenGL Version: 3.3.0 NVIDIA 304.125
GL Renderer: ION/integrated/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8880), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Using QGLWidget

GL Extensions:
GL_ARB_ES2_compatibility
GL_ARB_base_instance
GL_ARB_blend_func_extended
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_provoking_vertex
GL_ARB_robustness
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_separate_shader_objects
GL_ARB_shader_bit_encoding
GL_ARB_shader_objects
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sync
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_compression
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_storage
GL_ARB_texture_swizzle
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_texture_type_2_10_10_10_REV
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_x11_sync_object
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KTX_buffer_region
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NV_ES1_1_compatibility
GL_NV_alpha_test
GL_NV_blend_minmax
GL_NV_blend_square
GL_NV_complex_primitives
GL_NV_conditional_render
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_explicit_multisample
GL_NV_fbo_color_attachments
GL_NV_fence
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragdepth
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_gpu_program4
GL_NV_half_float
GL_NV_light_max_exponent
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_shader_buffer_load
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_env_combine4
GL_NV_texture_expand_normal
GL_NV_texture_lod_clamp
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_vdpau_interop
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_OES_compressed_paletted_texture
GL_OES_depth24
GL_OES_depth32
GL_OES_depth_texture
GL_OES_element_index_uint
GL_OES_fbo_render_mipmap
GL_OES_get_program_binary
GL_OES_mapbuffer
GL_OES_packed_depth_stencil
GL_OES_point_size_array
GL_OES_point_sprite
GL_OES_read_format
GL_OES_rgb8_rgba8
GL_OES_standard_derivatives
GL_OES_texture_3D
GL_OES_texture_float
GL_OES_texture_float_linear
GL_OES_texture_half_float
GL_OES_texture_half_float_linear
GL_OES_texture_npot
GL_OES_vertex_array_object
GL_OES_vertex_half_float
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum

**Comment by kintel** [comment]
@gratefulfrog Did you build your own binaries? We cannot reproduce this, but have some ideas which you could try out. If you'd be willing to help, the easiest would be to find me (kintel) on IRC (#openscad on Freenode), and I can provide you with some patches.

**Comment by kintel** [comment]
@gratefulfrog As a start, could you try building the issue1288 branch? https://github.com/openscad/openscad/tree/issue1288

**Comment by gratefulfrog** [comment]
Hello,

I did not build from source I used a .deb from ppa:openscad/releases
installed with apt-get.

I am happy to help, but am away from my computer for 10 days. I will try to
your suggestions when I get back!
Thanks for the response!
Bob

**Comment by gratefulfrog** [comment]
I experienced the same thing again today. Export image captures the screen
including the file name dialog box. This is really a problem...

I will attempt to build from source when I get back in 10 days.

Thanks,
Bob

**Comment by gratefulfrog** [comment]
Closed? Really? Is there a patch I can install?

**Comment by kintel** [comment]
@gratefulfrog The nightly build will have this - sometime tonight.

**Comment by gratefulfrog** [comment]
Thanks!  Sorry to be a noobie, but how to I get the nightly build? Is there
a .deb or  a repo to add to apt-get?

Thanks for all your help,
Bob

**Comment by kintel** [comment]
See http://www.openscad.org/downloads.html#snapshots

**Comment by gratefulfrog** [comment]
Hi,
Thanks I followed those instructions but I am running Ubuntu 12.04 LTS...
and nothing appears in my package manager?

is there repo I can add with apt-get and a package I can fetch?  Any help
would be greatly appreciated.

Cheers,
B

**Comment by kintel** [comment]
@gratefulfrog Oh, 12.04 - sorry, we don't support that version for the snapshot builds.
