### ISSUE TITLE
Export creates non-manifold STLs [$15]

### ISSUE THREAD

**Issue by triffid** [openscad/openscad#13]
example: x-end-motor.scad from http://github.com/prusajr/PrusaMendel/

render succeeds, export to STL succeeds, opening the generated STL in openscad (import_stl) succeeds, compile of stl succeeds, render of stl fails with "ERROR: Illegal polygonal object - make sure all polygons are defined with the same winding order."

Feeding the stl to cloud.netfabb.com and saving the result allows openscad to render successfully.

The object looks identical in openscad's 3d view throughout the entire process

Update Feb 2016:
- [issue13c.scad](https://github.com/openscad/openscad/blob/08154b19215254c5f60f17af3dd8fdd30d41462b/testdata/scad/bugs/issue13c.scad) is currently the only failing testcase. The issue is a collapsed volume (two back-to-back triangles.
##

**Comment by l29ah** [comment]
Is it possible to fix the STLs locally?

**Comment by kintel** [comment]
At some point between 2016 and today, this issue was fixed. Likely by a fix in upstream CGAL.
The tests also work using the current Manifold backend
