### ISSUE TITLE
Pronunciation of OpenSCAD

### ISSUE THREAD

**Issue by adius** [openscad/openscad#1305]
How is OpenSCAD actually supposed to be pronounced?
Is it "Open-SCAD" or Open-S-CAD?
Maybe you should add it to the readme. =P

**Comment by MichaelAtOz** [comment]
Yeh, I asked the same, and I wasn't the first.

Open ess CAD.

**Comment by t-paul** [comment]
Added to FAQ:
https://github.com/openscad/openscad/wiki/Frequently-Asked-Questions#how-is-openscad-pronounced

(according to http://forum.openscad.org/Proper-pronunciation-td5035.html)
