### ISSUE TITLE
Compile Error in Ubuntu 14.04

### ISSUE THREAD

**Issue by ankush1995** [openscad/openscad#1308]
I tried to build the openscad environment on Ubuntu (14.04) , when I ran the command
qmake openscad.pro
I got the following ---->
Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
WARNING: /home/ankush/openscad/scintilla.pri:12: Unable to find file for inclusion qscintilla2
Project MESSAGE: Using local copy of qscintilla2.prf instead.

**Comment by ankush1995** [comment]
Also on running make install command , getting the same message

**Comment by t-paul** [comment]
That's no error, just a warning. The Ubuntu-14.04 dev package of qscintilla2 does not ship the prf file in the correct place. The warning just explains we are trying to work around this issue.

**Comment by ankush1995** [comment]
But I am not able to make the Make file and also not able to run the application.

**Comment by t-paul** [comment]
Then there must be some additional error, the message above is normal and not causes the build to fail.

**Comment by ankush1995** [comment]
After running Make I got----->

/usr/lib/x86_64-linux-gnu/qt4/bin/uic src/MainWindow.ui -o objects/ui_MainWindow.h -tr _
make: /usr/lib/x86_64-linux-gnu/qt4/bin/uic: Command not found
make: *** [objects/ui_MainWindow.h] Error 127

**Comment by t-paul** [comment]
This looks like the `libqt4-dev` package is not correctly installed, this should normally install the dependency `libqt4-dev-bin` which has the `uic` program.

**Comment by ankush1995** [comment]
I am geting the following error on running make command :
In file included from src/scintillaeditor.cpp:6:0:

src/scintillaeditor.h:8:32: fatal error: Qsci/qsciscintilla.h: No such file or directory
 #include <Qsci/qsciscintilla.h>
                                ^
compilation terminated.
make: *** [objects/scintillaeditor.o] Error 1

It seems that I dont have Qsciscintilla on my system. Can u tell me the appropriate linux package for that?

**Comment by t-paul** [comment]
That's `libqscintilla2-dev` (or `libqt5scintilla2-dev` when using Qt5).

**Comment by alankruppa** [comment]
Had the same error when building version 2015-3. Installing libqscintilla2-dev worked for me. Thanks!

**Comment by FluxIX** [comment]
I am trying to build from source and have installed libqscintilla2-dev (I am using Qt 5.2.x), but I still get the following error when I try to compile:
> /home/chris/openscad/src/scintillaeditor.h:8: error: Qsci/qsciscintilla.h: No such file or directory
> #include <Qsci/qsciscintilla.h>
>                                ^

All the dependencies checked by the check-dependencies.sh script have passed.

Any idea what I need to do to resolve this?

**Comment by alankruppa** [comment]
You might try installing libqt5scintilla2-dev for Qt5 mentioned above by t-paul.

**Comment by FluxIX** [comment]
My error. I had meant to say I have libqt5scinitilla2-dev installed and I was seeing the compiler error.

**Comment by alankruppa** [comment]
Gotcha. Did you try making with qmake-qt4?

**Comment by FluxIX** [comment]
Same error at the same location.

**Comment by alankruppa** [comment]
That's all I've got. Good luck with it.
