### ISSUE TITLE
Fails to build with multiple compile errors on Mac OS X 10.10.3 / Xcode 6.3

### ISSUE THREAD

**Issue by opendragon** [openscad/openscad#1314]
Following the instructions provided for building on Mac OS X, which worked prior to Xcode 6.3;  first error is
BEGIN>>
In file included from src/version_check.cc:1:
In file included from src/version_check.h:22:
In file included from /Users/M_M/Documents/git.repositories/openscad/../libraries/install/include/gmp.h:76:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:46:9: error: no member named
      'ptrdiff_t' in the global namespace
using ::ptrdiff_t;
END>>
Second error is
BEGIN>>
In file included from src/version_check.cc:1:
In file included from src/version_check.h:39:
In file included from ../libraries/install/include/eigen3/Eigen/Core:28:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/complex:247:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/sstream:174:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ostream:131:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/ios:216:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__locale:15:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/string:439:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/algorithm:628:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:604:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:402:13: error: unknown type
      name 'ptrdiff_t'
    typedef ptrdiff_t difference_type;
END>>
and so on - this may not necessarily be OpenSCAD specific, except that other projects, which include C++11 projects, compile fine.

**Comment by kintel** [comment]
Looks like an issue with gmplib. I'll try to get xcode 6.3 up and running to test.
