### ISSUE TITLE
STL files not working

### ISSUE THREAD

**Issue by kosme** [openscad/openscad#1317]
Just moved from version 2014.03 to 2015.03 and suddenly all the STL files that are generated seem to contain invalid triangles that cause pycam to fail. If the same source file is compiled in 2014.03, the STL file that is generated works ok.

**Comment by kintel** [comment]
Do you have a small example? Do you know if there are any limitation in pycam in terms of what types of triangles it can accept?

**Comment by kosme** [comment]
Just read a file generated in 2015.03 and all the facet have the same vector 0 0 0, I guess the error is there. This is a link to the source code and the files generated in 2014.03 and 2015.03 https://www.dropbox.com/sh/m59aw39onbffnfx/AADwuA3BdnK9Dt6tlymJJGtAa?dl=0
