### ISSUE TITLE
Snapshot version() returns [0,0,0]

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1329]
Version in status bar is correct.
Noticed with 2015.04.13 & confirmed in 2015.04.25. (64bit)

**Comment by MichaelAtOz** [comment]
Also wrong in 2015.03-1
Note this shows 2015.03 only in the status bar, but 2015.03-1 in Help/About.

version() is OK in 2015.03

**Comment by kintel** [comment]
I left 2015.03 without the "-1" in the status bar to avoid confusing people. the -x releases should only fix bugs, not introduce any new features so it should be transparent to the user.

It looks like the -2 release might come sooner than expected though. Keep testing :)
