### ISSUE TITLE
List points of a mesh ? 

### ISSUE THREAD

**Issue by tart2000** [openscad/openscad#1354]
Hi ! 
Is there a way in OpenSCAD to list all points (nodes) of a mesh ? 
For example, can I import an .stl file and have an array with x/y coordinates of each point ? 
And then run a for() command that would create a sphere at each node... 
Thank you.

**Comment by t-paul** [comment]
No, that's currently not possible. Please subscribe to the discussion in #1324 which has some ideas how to implement something like that.
