### ISSUE TITLE
Syntax simplification

### ISSUE THREAD

**Issue by Steinhagelvoll** [openscad/openscad#1371]
Some commands can get really long. So it would be nice if one could omit the * sign, like it is done in math:

2*r = 2r

**Comment by kintel** [comment]
This is likely to open a large wormhole of confusion and ambiguous syntax - I'd rather not go there.
..unless someone authors a comprehensible document covering all cases and manages to convince us it's actually a good idea :)

**Comment by t-paul** [comment]
I think it's not really possible with the current syntax as it's conflicting with the exponential notation.
```
echo(2e3); ==> ECHO: 2000
```

**Comment by MichaelAtOz** [comment]
Identifiers can start with numbers:

```
2r=3;
echo(2r);
```

```
Compiling design (CSG Tree generation)...
ECHO: 3
```

So not possible.

**Comment by Steinhagelvoll** [comment]
Ok I have to agree this would just be a big mess. I believe to have seen it on wolframalpha, but they haven't got a full programming language.

**Comment by FluxIX** [comment]
I'm also not convinced it would save all that much space on a line.

**Comment by MichaelAtOz** [comment]
@Steinhagelvoll can this be closed?

**Comment by Steinhagelvoll** [comment]
yes
