### ISSUE TITLE
Implement Error Statement

### ISSUE THREAD

**Issue by FluxIX** [openscad/openscad#1374]
Implement an `error` statement, similar to `echo`, but which also causes a compiler error associated with the `error` statement.

This is useful when passing an enumerated value into a function or module and the input is not a supported enumerated value.

**Comment by MichaelAtOz** [comment]
Issue #381 similar.

**Comment by t-paul** [comment]
Closed as duplicate. Ignoring the different name suggested in #381, the logic described there should cover the expected behavior. It's likely going to be a run-time error though as the error/assert function would be called when evaluating the script.
