### ISSUE TITLE
Linear extrude plus infinite twist causes crash instead of just an error.

### ISSUE THREAD

**Issue by christakahashi** [openscad/openscad#1378]
when I run the following:
    foo = 1/0;
    linear_extrude(height = 10, center = true, convexity = 10, twist = foo)
	square(3);

I get openSCAD to crash instead of giving an error message.

![image](https://cloud.githubusercontent.com/assets/1870494/8422625/0b6acb44-1e93-11e5-9398-4849d7d21a35.png)

**Comment by FluxIX** [comment]
Why ignore the parameter? This will make debugging difficult. Why not have a compile error (not program crash) instead?

**Comment by t-paul** [comment]
It can't be a compile error, as the syntax is valid. It could be a run-time error and produce a warning. Right now the common behavior is to ignore invalid values.
I think changing this behavior should go into a specific issue (e.g. #596) and not as side-effect into a crash fix.

**Comment by FluxIX** [comment]
I feel a run-time error is strongly preferential. NaN is not a value which should be ignored, as it indicates the value is invalid for an operation. Either infinity with an extrusion is the same argument.

Ignoring bad values and using a default instead is poor practice. Silently using defaults is very bad practice.

**Comment by t-paul** [comment]
Yes, I agree. The patch addresses the crash issue only. That does not mean there are no other things that need improvement.
