### ISSUE TITLE
behavior of undef in min() and max() of vectors [$15]

### ISSUE THREAD

**Issue by blobule** [openscad/openscad#1389]
There is an inconsistency in the behavior of min() and max() of vectors in the presence of non-numbers.

```
    echo(min([undef,3,4,5]));   // output undef
    echo(min([3,4,5,undef]));   // output 3
```

The output depends if `undef` is first or not in the vector.
When not using vectors, we get a consistent behavior (any non-number present force a `undef`):

```
    echo(min(undef,3,4,5));   //  output undef
    echo(min(3,4,5,undef));   // output undef
```

Also, the behavior in the presence of true or false is unpredictable (altough could be considered ok):

```
    echo(min([false,0,1,3])); // output false
    echo(min([0,false,1,3])); // output 0
```

Both problems a related to the initialization of the loop searching for the min (or max) and lack of type checking.

I propose to skip any non-number inside a vector, so the behavior becomes:

```
    echo(min([undef,3,4,5]));  // output 3
    echo(min([3,4,5,undef]));  // output 3
    echo(min([false,0,1,3])); // output 0
    echo(min([0,false,1,3])); // output 0
```

Of course we could decide to skip only `undef` inside a vector and use the natural conversion value for the rest (false==0, true==1). Then, a result of `false` or `0` must be considered equal.

Making min/max skip undef (or non-number) is very useful when, for example, you want to rescale and preserve aspect ratios on some axis... since you have to compute a single scale factor `s=min([sx,sy,sz])`, the presence of undef will naturally be interpreted as skip an axis for the computation of the aspect ratio. Inversely, doing `s=min(sx,sy,sz)` (without a vector) will return the unusable result of `undef` if any axis is tagged as unused.

The behavior I suggest can be obtained by changing these lines (in `builtin_min()`, in func.cc) from

```
    Value min = v0->toVector()[0];
    for (size_t i = 0; i < v0->toVector().size(); i++) {
               if (v0->toVector()[i] < min) min = v0->toVector()[i];
     }
```

to

```
    Value min = Value::undefined;
    for (size_t i = 0; i < v0->toVector().size(); i++) {
          if (v0->toVector()[i].type()!=Value::NUMBER ) continue;
          if (!min.isDefined() || v0->toVector()[i] < min) min = v0->toVector()[i];
     }
```

Before I submit this change, any opinion on what the correct behavior of min() and max() should be over vectors containing undef (or non-numbers)?
##

**Comment by MichaelAtOz** [comment]
Personally, I think any parameter containing nan it should return nan, any undef should return undef.

true/false is debatable, currently they are considered 1/0 in only some logical expressions, see wiki quote below. In min/max context I'm happy with ignore or return nan. There was discussion re treating true==1 etc, and expanding the areas where the type coercion happens to all expressions, the community generally didn't like the idea.

Wiki/Booleans "and as the arguments to the logical operators '!' (not), '&&' (and), and '||' (or).
In all of these contexts, you can actually pass any type of value. Most values, when used in a Boolean context, are equivalent to 'true', but there are a few that are equivalent to 'false'.
