### ISSUE TITLE
Allow Control+Y to redo

### ISSUE THREAD

**Issue by Pikamander2** [openscad/openscad#1397]
Currently, control+Y doesn't seem to be bound to anything. Can we bind it to Redo, since that's what it does in most text editors and browsers?

**Comment by gaganjyot** [comment]
@kintel this seems to be solved, so should we close it?

https://github.com/openscad/openscad/blob/176a1e87364be36d6cf28a58303c1fc7589e0d47/src/scintillaeditor.cpp#L137

**Comment by kintel** [comment]
thx - forgot to close this..
