### ISSUE TITLE
Once you are in a document there's no obvious way to do an open recent

### ISSUE THREAD

**Issue by devonjones** [openscad/openscad#1403]
with the new interface, if I have already started openscad, there's no apparent way to open recent documents.  You have to exit entirely and start again to be able to see your recent models.  This can be a real pain for multi-file projects

**Comment by t-paul** [comment]
Are you running Ubuntu by any chance?

Then have a look at [I'm not getting any menubar when running OpenSCAD in Ubuntu, how can I get it back?](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#I.27m_not_getting_any_menubar_when_running_OpenSCAD_in_Ubuntu.2C_how_can_I_get_it_back.3F)

**Comment by devonjones** [comment]
Ah ha, yes, I am

**Comment by devonjones** [comment]
Yep, that was it, I'll close these out.  Thanks!
