### ISSUE TITLE
Minkowski reduces facets in arc

### ISSUE THREAD

**Issue by dlaw** [openscad/openscad#1426]
When I take a Minkowski sum, arcs are not rendered with the correct number of facets. Each corner in this model should have hundreds of facets but here there are clearly only five.

![2015-08-20-150121_952x529_scrot](https://cloud.githubusercontent.com/assets/606010/9392725/5d5f9fa6-474c-11e5-9958-96c15e8d3641.png)
```
$fn=1000;
minkowski() {
  circle(1);
  square(1);
}
```

I observed this issue in openscad 2015.03.01-3 from the Arch Linux repositories. The issue did not occur with whatever version of openscad I was using in late 2013.

Please let me know what other tests I can carry out or information I can provide to assist with tracking down this issue.

**Comment by t-paul** [comment]
That's probably a duplicate of #999 and caused by the vertex cleanup mentioned there in the comments.

**Comment by dlaw** [comment]
This is definitely a duplicate of that issue. Thanks.
(I searched before posting, but only under keyword "minkowski".)

I will close this issue and contribute to #999 instead.

**Comment by t-paul** [comment]
Cool, thanks.
