### ISSUE TITLE
Feature request: preserve individual shapes which overlap

### ISSUE THREAD

**Issue by elnerd** [openscad/openscad#1439]
Consider the following openscad code:

circle(r=10);
circle(r=5);
circle(r=2.5);

The way openscad currently handles this, is by silently performing a union of these primitives (if I understand it correctly). The resulting shape is a single circle with radius = 10.

It would be nice if openscad would preserve the individual circles, as I use them as cutting paths for a laser-cutter.

If this feature would be consider, I am not sure what the best way to implement it would be.
Perhaps:
individual() {
 circle(r=10);
 circle(r=5);
 circle(r=2.5);
}

In the meantime, I do the following:
module tube(r1,r2) {
difference() {
circle(r=r1);
circle(r=r2+0.01);
}
}
tube(10,5);
tube(5,2.5);
tube(2.5,0);

The drawback here, is that the material will be cut twice at the intersecting tubes - possibly ruining the material.

I hope you understand what I am asking.

Regards Leikarne
##

**Comment by jordanbrown0** [comment]
What you really want is a way to represent a circle as a line, rather than as a filled figure.  #99 and #508 talk about this.

**Comment by elnerd** [comment]
I am closing this issue as its duplicate of others with better descriptions.
