### ISSUE TITLE
Missing dependencies ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by bigbear3001** [openscad/openscad#1453]
When building on my almost freshly installed ubuntu 14.04.3 not all needed dependencies where added by uni-get-dependencies.sh.

Missing dependencies that where not present on my system:
* qt4-qmake
* libqscintilla2-dev

Error message on clean ubuntu (docker image)
```
root@0fc7b508e0a9:~/openscad# qmake
qmake: could not find a Qt installation of ''
```

**Comment by bigbear3001** [comment]
i guess the error message for libqscintilla2-dev was just a warning message:
```
root@358f6fd07a66:/opt/openscad# qmake
Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
WARNING: /opt/openscad/scintilla.pri:13: Unable to find file for inclusion qscintilla2
Project MESSAGE: Using local copy of qscintilla2.prf instead.
```

**Comment by bigbear3001** [comment]
This can also be solved by installing qt5-default which sets qt5 as default for qmake.

Closing because i'm not sure if qt5-default should be added as a dependency.

**Comment by donbright** [comment]
if it is this confusing, it is a bug. it is supposed to "just work". i will take a look this week.

**Comment by donbright** [comment]
fixed by https://github.com/openscad/openscad/pull/1486 see also #1474
