### ISSUE TITLE
Difference code not working on laptop

### ISSUE THREAD

**Issue by durgesh5597** [openscad/openscad#1457]
I on my laptop it won't reconginize the difference code but if I uses the same file on my desktop it works. Please fix it. suppose to look like this.
![pratice 4](https://cloud.githubusercontent.com/assets/15213395/10607089/18b12152-7705-11e5-9ed5-4aebb39dbb7c.png)

But it shows like on my laptop. 
![incorrect](https://cloud.githubusercontent.com/assets/15213395/10607126/65361e7e-7705-11e5-8cef-f030f8f453d2.png)

**Comment by t-paul** [comment]
Please add the information listed in https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#How_do_I_report_bugs.3F including the OpenGL information.

What happens with a full render (F6) - this will drop the color information, but does it also show different results?

**Comment by kintel** [comment]
@durgesh5597 Any more info from you to help us locate this?

**Comment by t-paul** [comment]
Closing as there is not enough information to reproduce the issue.
