### ISSUE TITLE
passing functions as parameters

### ISSUE THREAD

**Issue by iplayfast** [openscad/openscad#1460]
Just putting it out there for discussion. 
```
module test1()
{ 
cube([30,40,50]);
}
module test2(h)
{
cylinder(h,50);
}
module wow(n)
{
 do a bunch of stuff.
n;
do a bunch more of stuff
}

wow(test1());
wow(test2(6));
```

for example wow would take the function passed in and any arguments (functions themselves?) and would call those functions in the middle.

**Comment by kintel** [comment]
You can do this using the ```children()``` statement:
```
module wow(n) {
  children();
}

wow() test1();
wow() test2(6);
```

Passing real references to unevaluated functions and modules is proposed for OpenSCAD2.

**Comment by iplayfast** [comment]
wow!
