### ISSUE TITLE
Feature request: visualize scale.

### ISSUE THREAD

**Issue by rewolff** [openscad/openscad#147]
I've had a few times now that I've made a mistake with the scale of objects I've designed. They are so featureless and could be any scale. (mostly due to me confusing radius and diameter of cylinders and spheres). 

Suggestion: 
Find common (household?) objects that normally are a certain size. 
Picture them, at the curent scale,  just like the axes in the corner. Find a different object for every factor-of-three change in scale. So picture a watch for 3cm, a wallet for 10cm, a dinner-plate for 30cm,  and a chair for 1m. etc. etc. 

Of course, with a perspecitve projection, there is no real "scale".

**Comment by TDeagan** [comment]
The numbered scale markers are now merged into the master, see #1131 for pictures.  This is arguably sufficient to close this issue.  thoughts?

**Comment by rewolff** [comment]
Nice work, thanks! ... I'd vote for "yes". 
(I guess my vote also counts for something as I started this. :-) )
