### ISSUE TITLE
Entering FPS value for animation crashes instantly

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1481]
I open a new blank script.  Type `cube($t);` then click View->Animate.  Focus cursor in the FPS box to type a value, and as soon as first digit is pressed, it crashes with floating point exception.

It seems to work ok if you enter a value for "Frames" first, then the FPS.

On Linux Mint 17.2, based on Ubuntu 14.04 repos
OpenSCAD Version: 20151109T211236.git8819d6b

**Comment by kintel** [comment]
Need to reopen: Now, setting FPS first and then Steps causes animation to never start
