### ISSUE TITLE
Saving during compile cancels text output

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1488]
During a long compile I often remember to save via Ctrl-S, but after doing this there are no further compile messages logged to console.
##

**Comment by kintel** [comment]
This is probably due to the hack we use to manage the console output. This could really need a rewrite, perhaps use (or take ideas from) some logging framework? See setCurrentOutput() and clearCurrentOutput in MainWindow (https://github.com/openscad/openscad/blob/master/src/mainwin.cc#L2760)

**Comment by thehans** [comment]
I confirm that this has been fixed.  Closing.
