### ISSUE TITLE
 Error rendering in preview

### ISSUE THREAD

**Issue by dbeavers** [openscad/openscad#1494]
Using version 2015.03-1  The following does not render properly in Preview but is correct in Render:
module S(){
    translate(v = [-1.19, 79, 39])
    rotate(a = 180, v = [1, 0, 0])
    polyhedron(points = [ [0,0,0],[0,0,50],[0,41,50],[0,41,25],[0,15,0],[2.38,0,0],[2.38,0,50],[2.38,41,50],[2.38,41,25],[2.38,15,0] ], faces = [ [0,1,2,3,4],[5,9,8,7,6],[0,5,6,1],[1,6,7,2],[3,2,7,8],[4,3,8,9],[0,4,9,5] ], convexity = 2);
}

module L(){
translate(v=[0,-18,-9])
cube([19,125,46], false);
}

difference() {
    L();
    S();
}

**Comment by thehans** [comment]
The polyhedron is inside out, all the face normals are backwards.  You can
see this if you preview S by itself, and use thrown together mode (F12).

In thrown together mode, a magenta face means you are looking at the wrong
side of it.  Try reversing the vertex order of your faces.
