### ISSUE TITLE
Transparent objects render faces out of order

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1496]
When viewing a transparent object, the preview has artifacts due to the faces being drawn in uncontrolled order.

This shows up as a strange seam in cylinders for example:
![screenshot from 2015-11-19 12 00 58](https://cloud.githubusercontent.com/assets/252233/11279311/4ebeee38-8eb5-11e5-9d31-9a5a75056de3.png)

It looks much better if the back faces are drawn before the front faces.  This can be accomplished with `glEnable(GL_CULL_FACE);` and `glCullFace` calls.  Drawing the object with the front culled first, then again with the rear culled.
![screenshot from 2015-11-19 13 05 34](https://cloud.githubusercontent.com/assets/252233/11281057/716d441c-8ebe-11e5-8c4c-d1fb60add0e9.png)

The downside to this is that it could possibly make preview rendering slower.  I haven't found any noticeable slowdowns based on my subjective interactive testing, but if there are any suggested performance tests, I would be willing to try them.

To mitigate some of this potential slowdown the rear faces can be only drawn when color alpha < 1.  And only draw the front faces when when not rendering cutouts.
##

**Comment by kintel** [comment]
I'm slightly concerned about performance degradation.
Otoh, rendering lots of transparent objects probably isn't a major workflow.

**Comment by thehans** [comment]
Fixed by #1497
