### ISSUE TITLE
No ambient light in preview when edges shown

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1502]
I noticed that when edges are shown, all the faces look a little darker, and under some orientations go completely black.  The edges use a shader while no edge rendering uses the fixed function pipeline.  The difference is that the fixed function version has ambient lighting enabled.  The default ambient shading component in this mode is (0.2,0.2,0.2,1.0)

So, not sure this is worth a pull request for a one line change, but 

Changing this line in the vertex shader code:
https://github.com/openscad/openscad/blob/master/src/GLView.cc#L275
`      "  shading = abs(dot(normal, lightDir));\n"`
to 
`      "  shading = 0.2 + abs(dot(normal, lightDir));\n"`

Makes the faces match exactly between the two modes.

**Comment by t-paul** [comment]
We could try https://help.github.com/articles/editing-files-in-another-user-s-repository/ :-).

**Comment by kintel** [comment]
cool, I didn't know about that feature.

**Comment by kintel** [comment]
@thehans Could you give an example where this happens? I'm not able to casually reproduce this issue..

**Comment by thehans** [comment]
Its specifically in Preview mode with "Show Edges" checked.  If you toggle Show edges on and off you can see the shading change.  
![shading](https://cloud.githubusercontent.com/assets/252233/11606080/a52c5e24-9ad9-11e5-80da-96b6ef473f10.gif)

**Comment by kintel** [comment]
ah, I somehow thought you meant the shading of the wireframe. thx!

**Comment by kintel** [comment]
Fixed by #1509
