### ISSUE TITLE
Add update number to version shown in GUI window status bar

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1511]
Just now I was testing between 2015.03-1 & 2015.03-2 and noticed that the -1 & -2 was not shown.
It is in Help/About.
##

**Comment by t-paul** [comment]
I think that's intentional... @kintel ?

**Comment by MichaelAtOz** [comment]
well it makes it hard when testing...

**Comment by kintel** [comment]
It should show in help-about. But perhaps we didn't add it to the window title?

**Comment by MichaelAtOz** [comment]
I mean bottom right
![update version](https://cloud.githubusercontent.com/assets/1972961/11616427/fd7b06b0-9cce-11e5-8c78-4210f2602423.JPG)

I suppose you could add it to the About window title, but that is a bit redundent.

**Comment by kintel** [comment]
Right, I left it out of the bottom right to avoid showing too much info to people. 2015.03 would define the feature set, the patchlevel release should just be about bugfixes.

**Comment by MichaelAtOz** [comment]
Closing
