### ISSUE TITLE
difference seems to break preview

### ISSUE THREAD

**Issue by tcurdt** [openscad/openscad#1521]
I have the following model which consists of a sweep path and two cubes that get subtracted via `difference()`. When those cubes are shown with `%` all looks fine. Simplified:

    difference() {
      sweep(...)
      % translate(...) cube(...)
      % translate(...) cube(...)
    }

![screen shot 2015-12-16 at 21 28 31](https://cloud.githubusercontent.com/assets/13697/11854481/67ac2ae2-a444-11e5-973e-7df6484097a1.png)

When I remove the `%`

    difference() {
      sweep(...)
      translate(...) cube(...)
      translate(...) cube(...)
    }

the preview is broken:

![screen shot 2015-12-16 at 21 28 43](https://cloud.githubusercontent.com/assets/13697/11854514/a808062e-a444-11e5-96da-d73b5e2fbc42.png)

It renders fine though!

The code is [here](https://gist.github.com/tcurdt/e90cd374c1ac44af4cf9). I first tried on stable and now are running 2015.12.02 (git 97e9742).

**Comment by MichaelAtOz** [comment]
Note that F6 with the cubes removed (via '*' or '%') shows
```
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
PolySet has nonplanar faces. Attempting alternate construction
PolySet has nonplanar faces. Attempting alternate construction
...
```

**Comment by Neon22** [comment]
Which sweep are you using ?
Check F12 to see if right side orientation ?

**Comment by MichaelAtOz** [comment]
@Neon22 Was that directed at me? Yes F12 shows purple.
I got sweep from https://github.com/openscad/list-comprehension-demos/blob/master/sweep.scad

**Comment by tcurdt** [comment]
Interesting. The rotations makes it purple. Basically you can switch the purple by toggling `left`. So it really is the side orientation. I didn't think a rotation in the transforms would cause that.

I guess I could just manually flip the side - but question is (especially if this happens more dynamic) if the sweep should take care of this.

**Comment by tcurdt** [comment]
Properly reversing the shape before the sweep solves this issue for me.
But I guess this really is a problem for rotations within a sweep.
Should I open a bug for this in the list-comprehension-demos repo?

**Comment by kintel** [comment]
@tcurdt This is a weakness of sweep(). We don't have a good way of analyzing your intentions and you need to construct both the polygon and path in the "natural" order (which isn't documented). This is another issue we need to resolve before making sweep() a builtin. Opening an issue on list-comprehension-demos would make sense.
