### ISSUE TITLE
Crash looking up unknown variable

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1538]
Looks like this was introduced in OpenSCAD 2015.03-2. This causes a crash, reported on both Windows and Mac:

```
use <MCAD/stepper.scad>
echo(motorWidth(Nema17));
```

**Comment by mickvav** [comment]
Linux, 2015.02-2, 2016.01.03 (rebuilt from sources) - not affected.

**Comment by kintel** [comment]
Closing as duplicate of #1528
