### ISSUE TITLE
Viewport size on status bar.

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#1553]
In order to recreate a view shown in the GUI using the command line it is necessary to know the size of the viewport in pixels. This can be found by manually exporting an image and inspecting it but it would be more convenient if it was shown with the other viewport data. That would also allow the viewport pane to be dragged to a specific size to match a command line generated image. Currently I have to repeatedly drag and save images.

**Comment by kintel** [comment]
Fixed in a9288da6ec31fd0540bee0a93d5dd2b892556347
