### ISSUE TITLE
Strip downloads from git repo

### ISSUE THREAD

**Issue by KOLANICH** [openscad/openscad#1563]
Don't store large binary files in git repo. Every time you make a commit every file in your repo is copyed. That's why it is 184 MiB now. Use Github Releases to store downloads and use [git-lfs](https://git-lfs.github.com/) to store large files and blobs.

**Comment by t-paul** [comment]
Can you point to anything specific? I'm not aware of any releases stored in the repo.

**Comment by KOLANICH** [comment]
Sorry, I wrote to the wrong project. I meant BOLTS.

**Comment by t-paul** [comment]
Ok, no worries...
