### ISSUE TITLE
Backgrounded objects persist after being removed

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1567]
Using the nightly, 2016.1.23

Preview this simple example 
```
difference() {
  cube(2);
  %translate([1,1,1]) cube(2);
}
```
One of the cube is backgrounded as expected.  

Now remove the % character and preview again, it is still backgrounded.

**Comment by oysteinkrog** [comment]
I can confirm, on master (085167bfae0b01a1f8c72d23ad5838c33dde6eaa).

**Comment by kintel** [comment]
Thanks for reporting - looks like fallout from #1527. We don't have automated tests which render twice : /
