### ISSUE TITLE
Cannot build with gcc-c++ 6.0.0

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#1575]
For 2015.03-2:

Full build log: [build.log](https://kojipkgs.fedoraproject.org/work/tasks/1021/12801021/build.log)
Versions of stuff installed: [root.log](https://kojipkgs.fedoraproject.org/work/tasks/1021/12801021/root.log)

For master:

[build.log.gz](https://copr-be.cloud.fedoraproject.org/results/churchyard/openscad-devel/fedora-rawhide-x86_64/00157679-openscad/build.log.gz)
[root.log.gz](https://copr-be.cloud.fedoraproject.org/results/churchyard/openscad-devel/fedora-rawhide-x86_64/00145145-openscad/root.log.gz)

I think this is caused by gcc-c++ 6.0.0.

Error message 2015.03-2:

```
/usr/include/c++/6.0.0/type_traits:143:12: error: invalid use of incomplete type 'std::conditional<true, std::is_constructible<CGAL::Plane_3<CGAL::Simple_cartesian<double> >, CGAL::Plane_3<CGAL::Simple_cartesian<double> >&&>, std::is_constructible<CGAL::Sphere_3<CGAL::Simple_cartesian<double> >, CGAL::Sphere_3<CGAL::Simple_cartesian<double> >&&> >::type {aka struct std::is_constructible<CGAL::Plane_3<CGAL::Simple_cartesian<double> >, CGAL::Plane_3<CGAL::Simple_cartesian<double> >&&>}'
     struct __and_<_B1, _B2>
            ^~~~~~~~~~~~~~~~
/usr/include/c++/6.0.0/type_traits:1115:12: note: declaration of 'std::conditional<true, std::is_constructible<CGAL::Plane_3<CGAL::Simple_cartesian<double> >, CGAL::Plane_3<CGAL::Simple_cartesian<double> >&&>, std::is_constructible<CGAL::Sphere_3<CGAL::Simple_cartesian<double> >, CGAL::Sphere_3<CGAL::Simple_cartesian<double> >&&> >::type {aka struct std::is_constructible<CGAL::Plane_3<CGAL::Simple_cartesian<double> >, CGAL::Plane_3<CGAL::Simple_cartesian<double> >&&>}'
     struct is_constructible
            ^~~~~~~~~~~~~~~~
In file included from /usr/include/c++/6.0.0/bits/stl_algobase.h:64:0,
                 from /usr/include/c++/6.0.0/bits/stl_tree.h:63,
                 from /usr/include/c++/6.0.0/set:60,
                 from src/CGAL_workaround_Mark_bounded_volumes.h:27,
                 from src/cgal.h:23,
                 from src/cgalutils.h:3,
                 from src/cgalutils.cc:3:
```

For master:

```
...
                 from src/cgal.h:15,
                 from src/cgalutils.h:3,
                 from src/cgalutils.cc:6:
```

**Comment by hroncok** [comment]
Reported to CGAL issue tracker as well as https://github.com/CGAL/cgal/issues/726

**Comment by GilesBathgate** [comment]
Seems a bit unfair to report it to CGAL when the error is coming from CGAL_workaround_Mark_bounded_volumes.h which is not part of the CGAL project. (unless I am mistaken)

**Comment by hroncok** [comment]
Closed the CGAL issue.

**Comment by kintel** [comment]
I'm not sure why we wouldn't be allowed to store a Volume_handle in a set.
It looks similar to this bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=65760

We could write a stand-alone minimal example storing a Volume_handle of a cube or smth. in a set (or any other container) and submit that to CGAL. Perhaps that opens some doors.

Submitting this as a gcc bug would require us to reproduce without CGAL, which might be a bit of work..

**Comment by kintel** [comment]
@hroncok Btw., do you know of any easy way to get a VM image with a minimal gcc-6 distro?

**Comment by GilesBathgate** [comment]
Just for reference [CGAL_workaround_Mark_bounded_volumes.h](https://github.com/openscad/openscad/blob/master/src/CGAL_workaround_Mark_bounded_volumes.h)

**Comment by hroncok** [comment]
@kintel Would Docker work? You can get the rawhide image. https://hub.docker.com/r/library/fedora/tags/

**Comment by hroncok** [comment]
Or https://fedoraproject.org/wiki/Releases/Rawhide#Nightly_images

**Comment by djdelorie** [comment]
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=70437

**Comment by hroncok** [comment]
This has been fixed in upstream gcc.

**Comment by t-paul** [comment]
Nice, thanks for the follow-up.

**Comment by hroncok** [comment]
And now in Fedora. Thanks for all suggestions and help.
