### ISSUE TITLE
Variables defined within a group() {} doesn't work

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1576]
From the [mailing list](http://forum.openscad.org/dxf-and-stl-import-rendering-issue-tp15979p16057.html):

```
a = 1;

group() {
    a = 2;
    b = 3;
    echo(a,b);
}

echo(a);
```

WARNING: Ignoring unknown variable 'b'.
ECHO: 1, undef
ECHO: 1

I expected group to force { ...} to make an new scope but it does something weird instead. However union() does force a new scope:

```
a = 1;

union() {
    a = 2;
    b = 3;
    echo(a,b);
}

echo(a);
```

ECHO: 2, 3
ECHO: 1
##

**Comment by runsun** [comment]
Could be very useful. Thx.

It seems many other group-ish commands work, too, like hull, translate,  or
even color()

On Thu, Feb 4, 2016 at 5:37 PM, Marius Kintel <notifications@github.com>
wrote:

> From the mailing list
> <http://forum.openscad.org/dxf-and-stl-import-rendering-issue-tp15979p16057.html>
> :
>
> a = 1;
>
> group() {
>     a = 2;
>     b = 3;
>     echo(a,b);
> }
>
> echo(a);
>
> WARNING: Ignoring unknown variable 'b'.
> ECHO: 1, undef
> ECHO: 1
>
> I expected group to force { ...} to make an new scope but it does
> something weird instead. However union() does force a new scope:
>
> a = 1;
>
> union() {
>     a = 2;
>     b = 3;
>     echo(a,b);
> }
>
> echo(a);
>
> ECHO: 2, 3
> ECHO: 1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openscad/openscad/issues/1576>.
>



-- 
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Runsun Pan, PhD
[Fax] 832-534-3213
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by thehans** [comment]
Handled by #2323, closing.
