### ISSUE TITLE
Import() exposed as a function

### ISSUE THREAD

**Issue by TLC123** [openscad/openscad#1585]
If Import were exposed as a function, points and faces returned as lists could be subjected to some arbitrary operation  before drawn as polyhedron

My_polymesh  = import("somemeshfile.stl"); 
returns [points = [ [x, y, z], ... ], faces = [ [p1, p2, p3..], ... ]] for polyhedron.

**Comment by t-paul** [comment]
Closing as duplicate of #1324 (although I like the using `import()` more than creating a new name `read()`).
