### ISSUE TITLE
Export colors to .amf files.

### ISSUE THREAD

**Issue by terrylm** [openscad/openscad#1593]
As AMF files support color, and as OpenSCAD has partial support for color, and as 3D printing is about to move to multi-color (mixing nozzles), it would seem to make sense to export color values to the AMF files.

On the same note, for the last reason, it might also make sense for OpenSCAD to move to AMF as it's main file format, instead of STL?

**Comment by bobc** [comment]
Hmm, deja vu again :)

Once #1608 is done, then multi-color AMF, STL etc becomes quite possible. 

There isn't really a "main format", the conversion to STL is the last step of export, it is not used as an internal representation. So all you could do is change the order of entries on the "Export" menu.

**Comment by terrylm** [comment]
Interesting, I am glad to hear that last part. #1608 look quite long, so will read it another time, as I am quite tired...

**Comment by kyrreaa** [comment]
Any progress on this?

**Comment by jschobben** [comment]
Let me risk a bit of necromancy and shameless plugging:

Recently I put a script on github that allows exporting a given model as AMF/3MF, with colors preserved. Perhaps it can be helpful, until OpenSCAD can handle this natively.

It can be found here: https://github.com/jschobben/colorscad

**Comment by xtemp09** [comment]
Any progress?

**Comment by tpimh** [comment]
Also this can be beneficial for WRL export for the purpose described in #1304

**Comment by t-paul** [comment]
Agreed that it would be nice for other formats. Considering the dead state of AMF, I'm going to close this specific issue. There's not much chance AMF support will get updates.
