### ISSUE TITLE
Question: usage of "class" in method arguments

### ISSUE THREAD

**Issue by mcraveiro** [openscad/openscad#1614]
Hi,

Bit of a silly question really - noticed that a lot of the methods in OpenSCAD use ```class``` in the arguments, like so:

```
CSGTreeEvaluator(const class Tree &tree, class GeometryEvaluator *geomevaluator = NULL)
```

What is the purpose of class in this context? Wasn't even aware this was valid C++ actually.

Many thanks for your time.

Marco

**Comment by t-paul** [comment]
It's a forward declaration of the class.

Similar to what's shown in http://stackoverflow.com/questions/4194734/declare-a-c-class-without-defining-it-in-the-current-translation-unit

**Comment by mcraveiro** [comment]
Ah wow, an "inline" forward declaration! Thanks!
