### ISSUE TITLE
Create signed version of Mac binaries

### ISSUE THREAD

**Issue by larsrc** [openscad/openscad#1616]
I have a company-issued MacBook and would like to use OpenSCAD on it. Unfortunately, the security policy only allows installing apps from App Store and identified developers. While I can understand not wanting to deal with the App Store weirdnesses, could you perhaps start signing the DMGs you make available for download? Instructions are here: https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by t-paul** [comment]
Closing as duplicate of #880.

**Comment by kintel** [comment]
@larsrc Please follow the original issue #880. I've been fearing a showstopper related to this. I'll see what I can do..
