### ISSUE TITLE
Crash when exporting to AMF

### ISSUE THREAD

**Issue by nairaner** [openscad/openscad#1625]
Happens on latest development build on Windows. I only get the usual "Program has stopped working".
`
polyhedron(points = [[0, 0, 0], [-8, -8, 8], [4, 0, 0], [-6, -10, 10], [0, 4, 0], [-10, -6, 10]], faces = [[0, 1, 3, 2], [3, 2, 4, 5], [5, 4, 6, 7], [0, 1, 5, 4], [0, 2, 4], [0, 4, 6], [1, 3, 5], [1, 5, 7]], convexity = 1);
`

**Comment by kintel** [comment]
Crash confirmed on Mac as well.

FYI: Your polyhedron has some flipped faces, making it invalid for export (render with F12 - flipped faces are shown in pink). If you fix that, the export should work.
