### ISSUE TITLE
Valid object is "destroyed" by CSG operations

### ISSUE THREAD

**Issue by gskillas** [openscad/openscad#1628]
Hello together,

I have a watertight object to which I want to add or subtract cylinders. 
Executing the SCAD script generates following output:

CGAL Cache insert: union(){import(file="curve.stl",layer="" (2040880 bytes)
CGAL Cache insert: difference(){union(){import(file="curve. (2040880 bytes)
WARNING: Exported object may not be a valid 2-manifold and may need repair

The resulting exported STL is indeed weird.

[curve.stl.gz](https://github.com/openscad/openscad/files/231318/curve.stl.gz)
[curve.scad.gz](https://github.com/openscad/openscad/files/231319/curve.scad.gz)

**Comment by kintel** [comment]
Your STL file isn't manifold (watertight); it has small cracks on the top and bottom edges of the end caps.
You can verify that the cylinder doesn't influence his on the cmd-line, by creating a file containing only ```import("curve.stl")```:

```openscad curve.scad -o out.stl --render-cgal```

You can also open it in e.g. Blender's 3D printing toolbox it will highlight non-manifold edges.
