### ISSUE TITLE
Animate with dump pictures from command line

### ISSUE THREAD

**Issue by nairaner** [openscad/openscad#1632]
Adding option to use animation would be useful for specifying output image resolution, which would allow downsampling for better animation, as well as animation of more complicated models.

**Comment by t-paul** [comment]
Animation is basically a GUI feature, but it's possible to just give the $t parameter manually on command line like `openscad -D$t=0.2 -o out.png in.scad` which should have pretty much the same effect when calling multiple times with varying values.

**Comment by nairaner** [comment]
It works, but it is very slow due to reload of all files when making each file

**Comment by t-paul** [comment]
The idea is to provide some means for persistent caching which would help for multiple use cases including this one.

**Comment by kintel** [comment]
I guess it's conceivable to have a cmd-line option to specify animation parameters, and run the preview-to-png renderer in a loop. It's kind of crossing into application scripting though.

**Comment by Hexelena** [comment]
I would like to add that when running in a shell like bash, you have to put the $t=0.2 in quotation marks like:
`openscad` -D'$t=0.2' -o out.png in.scad`
Otherwise it will be interpreted as shell variable.

**Comment by spuder** [comment]
For anyone else looking how to animate an STL into still images (which could be converted into a video). I've [published a bash script on S.O.](https://stackoverflow.com/a/70468907/1626687)
