### ISSUE TITLE
OpenSCAD + Bullet Physics Simulation

### ISSUE THREAD

**Issue by koppi** [openscad/openscad#1639]
Hi, I've created a marble run with Duplos,
see https://www.youtube.com/watch?v=IwdbtfiEo0A .

Background: Yesterday, I've integrated OpenSCAD into my physics simulation software:
* The Bullet Physics Playground: https://github.com/bullet-physics-playground

Here's some recent Video recordings:
* A basic CSG testing scene: https://www.youtube.com/watch?v=WbElbcZ6Sa0
* Experiments with gears and motors: https://www.youtube.com/watch?v=xy7qDgStMXk
* Experiment with various OpenSCAD scripts I've found on Thingieverse
https://www.youtube.com/watch?v=c8glPDbG1FI

Gitter chat at https://gitter.im/bullet-physics-playground/bpp

**Comment by t-paul** [comment]
Very nice! I'm not sure why this is posted here. I'd suggest to post on the Forum and/or G+ Community.

**Comment by koppi** [comment]
@t-paul where is the G+ community?

I have this link: https://plus.google.com/+openscad/posts but there is no content.

**Comment by t-paul** [comment]
[OpenSCAD Google+ Community](https://plus.google.com/u/0/communities/112968258499418200895)

**Comment by koppi** [comment]
@t-paul see https://github.com/openscad/openscad/issues/1640 .

**Comment by polkovnikov-ph** [comment]
This place is handy too.
