### ISSUE TITLE
Fix link to G+ community

### ISSUE THREAD

**Issue by koppi** [openscad/openscad#1640]
The link under "g+" on the left on the page links to https://google.com/+openscad

![screenshot from 2016-05-06 18-11-48](https://cloud.githubusercontent.com/assets/9458631/15078953/14a1fe08-13b6-11e6-80c8-6caf5bc0dcb6.png)

But the community is acually found at: https://plus.google.com/u/0/communities/112968258499418200895

Please fix the link on the page accordingly.

**Comment by kintel** [comment]
The owner of that Google+ community is missing in action. We're trying to get in touch with him so we can get that link updated. Any help would be appreciated.

**Comment by koppi** [comment]
@kintel https://google.com/+openscad is not a community but a personal G+ user account.

**Comment by kintel** [comment]
@koppi I know - the goal was to use that link for the G+ community, but without admin access I cannot do that. A workaround would be to accept the weird URL for now.

**Comment by MichaelPFrey** [comment]
for those that have not yet gotten the news:
https://www.blog.google/technology/safety-security/project-strobe/

> Finding 1: There are significant challenges in creating and maintaining a successful Google+ product that meets consumers’ expectations.
> 
> Action 1: We are shutting down Google+ for consumers.

So, within in a year, this issue will self resolve.
