### ISSUE TITLE
Is there a 2015.03-3 install package for Linux?

### ISSUE THREAD

**Issue by WZ9V** [openscad/openscad#1643]
The most recent install I could find to use with Linux was 2015.03

I'd like to get the missing syntax highlighting that looks like it was fixed in 2015.03-2

**Comment by kintel** [comment]
@hyperair Looks like the latest PPA release is 2015.03-1. Is there an easy way to bump that to 2015.03-2?

FYI: 2015.03-3 is a Mac-only security fix.

**Comment by WZ9V** [comment]
I don't know who maintains the PPA but yes it is one version behind and that version has syntax highlighting broke when using the new editor.  I'm trying to compile my own right now but it would be much easier if the PPA were up to date.

**Comment by hyperair** [comment]
Mm okay. I didn't realize there was an update.

**Comment by leoheck** [comment]
I am using, version 2015.03-1 from the OpenScad PPA in Ubuntu 16.04 and the syntax highlight is ok and it is a very good stuff... However, I found a plugin for sublime text that has command completion, and syntax highlight which can also be used.

**Comment by leoheck** [comment]
Maybe this issue can be closed.
