### ISSUE TITLE
Dependencies on Ubuntu Xenial

### ISSUE THREAD

**Issue by EiNSTeiN-** [openscad/openscad#1661]
I ran into a couple issues compiling OpenSCAD on Xenial (16.04), so I thought I'd report them here.

I ran `./scripts/uni-get-dependencies.sh` and then `./scripts/check-dependencies.sh` as per the readme, but there are a few issues with it:
- I have Qt 5.6, and QT_VERSION_STR is located in `qconfig.h` but the check-dependencies script looks in `qglobal.h` so it fails to detect the version number.
- libcgal-qt5-dev libopencsg-dev libglew-dev libeigen3-dev were needed but not installed by ./scripts/uni-get-dependencies.sh
- the uni-get-dependencies script tries to install libXi-dev but the name is libxi-dev

**Comment by leoheck** [comment]
Oh, I just saw this now... and it is related to the issue #1725. Sorry for duplicate it but I always forget the Ubuntu nasty names, I prefer to use numbers instead.

**Comment by donbright** [comment]
please try again i just updated the build script. thanks.

**Comment by t-paul** [comment]
Fixed, script is used for building AppImages: https://github.com/openscad/docker-openscad/blob/master/appimage/appimage-x86_64-base/Dockerfile
