### ISSUE TITLE
windows 7: screen realestate wasted on top of editor + console (2015.03-2)

### ISSUE THREAD

**Issue by sgserg** [openscad/openscad#1668]
It's quite clear what the views mean, so their description is rather redundant.
The space, on the other hand, is wasted (and a bit "uglified").
Please see red markings on attached screenshots:

![console](https://cloud.githubusercontent.com/assets/5439847/16172049/11307c88-3588-11e6-8ba0-c5c41b36a70a.png)

![editor](https://cloud.githubusercontent.com/assets/5439847/16172048/112deec8-3588-11e6-8ea4-cf92800987d7.png)

**Comment by t-paul** [comment]
This is not redundant, it's the handle to drag the windows to other places.

You can disable that in "Preferences->Advanced"

**Comment by sgserg** [comment]
Thanks for the tip!

Not sure I've seen such UI element usage under MS Windows, btw.
Usually, to mark a viewport dock-able and its docking options, well-known icons are used, e.g. debugging window of Firefox:

![examples](https://cloud.githubusercontent.com/assets/5439847/16357106/ff9009da-3af5-11e6-8ed2-b11443acec75.png)
