### ISSUE TITLE
STL file error

### ISSUE THREAD

**Issue by swethmandava** [openscad/openscad#1721]
minkowski(){
    import("windmill_meshlab.stl", convexity=10);
    sphere(2);
}

`
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 326 
Geometries in cache: 32
Geometry cache size in bytes: 277064
CGAL Polyhedrons in cache: 16
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized CSG tree has 1 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds
`

None of my stl files seem to work. Can't figure out why, is there something I'm missing?
Meshlab says no non manifold vertices or edges. I tried netfabb as well. attached all three stl files

but strangely this works: Any idea why?
minkowski(){
    hull(){
    import("windmill_meshlab.stl", convexity=10);
    }
    sphere(2);
}
[stl_models.zip](https://github.com/openscad/openscad/files/339605/stl_models.zip)

**Comment by MichaelAtOz** [comment]
I'm not sure what this is, but it doesn't look good: (the...repaired.stl)
![issue 1721 netfabb 2](https://cloud.githubusercontent.com/assets/1972961/16477906/41af571c-3ed9-11e6-9f41-97d4f6d804bf.JPG)
The other STLs have it too, and other problems.
Unfortunately CGAL is fussy about such things.
Also note the number of shells, some of the vanes are not connected, that could affect what you are trying to do to it.

**Comment by swethmandava** [comment]
I fixed this. still doesn't work :(
[windmill.off.zip](https://github.com/openscad/openscad/files/340763/windmill.off.zip)

**Comment by MichaelAtOz** [comment]
That zip file just has a .off file?
