### ISSUE TITLE
Ubuntu 16.04 - uni-get-dependencies.sh missing dependencies

### ISSUE THREAD

**Issue by leoheck** [openscad/openscad#1725]
Running on Ubuntu 16.04.

Why do not to add all stuff into the script?

![screenshot from 2016-07-02 18-29-20](https://cloud.githubusercontent.com/assets/1277920/16542541/21ad689a-4083-11e6-9d44-bf5c88401d72.png)

Installing missing regular packages:

```
sudo apt install libcgal-dev
sudo apt install libeigen3-dev
sudo apt search install libopencsg-dev
sudo apt search install libopencsg1v5
```

And, installing `OpenCSG`:

```
git clone https://github.com/openscad/OpenCSG.git
cd OpenCSG
make 
sudo make install
```

![screenshot from 2016-07-02 18-38-19](https://cloud.githubusercontent.com/assets/1277920/16542571/2da4bfee-4084-11e6-97a2-02448dc39f95.png)

**Comment by t-paul** [comment]
It's supposed to add all packages, it's currently simply not possible to catch up with lots of distributions.

**Comment by leoheck** [comment]
After a loong make process...

``itstool`` is a new missing dependency.

Solved with:

```
sudo apt install itstool
```

Terminal output... 

```
Compiling language files...
msgfmt -c -v -o ./locale/fr/LC_MESSAGES/openscad.mo ./locale/fr.po
268 translated messages.
msgfmt -c -v -o ./locale/ru/LC_MESSAGES/openscad.mo ./locale/ru.po
268 translated messages.
msgfmt -c -v -o ./locale/de/LC_MESSAGES/openscad.mo ./locale/de.po
268 translated messages.
msgfmt -c -v -o ./locale/cs/LC_MESSAGES/openscad.mo ./locale/cs.po
266 translated messages, 2 untranslated messages.
msgfmt -c -v -o ./locale/es/LC_MESSAGES/openscad.mo ./locale/es.po
225 translated messages, 41 fuzzy translations.
itstool missing, won't apply translations to openscad.appdata.xml
```

**Comment by t-paul** [comment]
Yes, it's optional, so no error message. It's mainly interesting for distribution packaging.

**Comment by WZ9V** [comment]
The Debian 7 dependency rule is missing also when running on Mint 17 or 18.  On Mint 18 I just had to install the dependencies myself in order to build 2015.03-2.  By the way the PPA still has 2015.03-1 that has syntax highlighting missing in the editor.

**Comment by donbright** [comment]
please try again i just updated the ubuntu16 get dependencies script thanks.

**Comment by kaefert** [comment]
Hey there! I'm running Linux Mint 18.1 (based on Ubuntu 16.04) and had the following problems:
after running `sudo ./scripts/uni-get-dependencies.sh` the dependency `fontconfig` was still reported as missing by the `check-dependencies.sh` script.
Installed it manually by running
`sudo apt-get install libfontconfig1-dev`

Afterwards my first run of
`qmake openscad.pro` reported `No package 'libzip' found`
had to install that manually with
`sudo apt-get install libzip-dev`

currently I'm waiting on the results of `make` :)

**Comment by t-paul** [comment]
Fixed, script is used for building AppImages: https://github.com/openscad/docker-openscad/blob/master/appimage/appimage-x86_64-base/Dockerfile
