### ISSUE TITLE
Use Qt 5 by default

### ISSUE THREAD

**Issue by ec1oud** [openscad/openscad#1736]
The readme has

`* [Qt4 (4.4 ->)](http://www.qt.nokia.com/)`

It should say 

`* [Qt (4.4 -> 5.x)](http://qt.io/)`

This has apparently been misleading for packagers (and the nokia URL has anyway been wrong for about 4 years now).  For example the Arch Linux package of OpenSCAD still links with Qt 4, for apparently no good reason, since it builds and runs fine with Qt 5.

**Comment by t-paul** [comment]
There is nothing wrong with Qt4, it's still supported for now. Qt5 still shows various small but annoying issues that do not happen with Qt4.
