### ISSUE TITLE
editor section - text distortion

### ISSUE THREAD

**Issue by nebulousdog** [openscad/openscad#1738]
![screenshot_2016-07-16_01-35-49](https://cloud.githubusercontent.com/assets/2218331/16893724/a77c976c-4af5-11e6-9370-6e6df3083ded.png)

ubuntu studio 16.04. openscad is version `2015.03-1`. using `functions.scad` as an example after opening.

let me know if you need any other information, or know a section of the docs to point me to! thanks

**Comment by t-paul** [comment]
Please check `Edit` -> `Preferences` -> `Editor` -> `Font` - which font is that?

Initial font selection is based on Qt font matching, which seems to have failed. I'm not sure if there's an easy way to find out why it returned this font.

It might help to have a look at the full list of installed font, but that can be quite long:
```
fc-list -v : | bzip2 -9 > /tmp/font-list.gz
```

**Comment by digitalvapor** [comment]
thanks for the quick reply!

Editor Type: QScintilla Editor
Font: 10.15 Saturday Night BRK, 12
Color syntax highlighting: For Light Background

I swapped to good old `Monospace` and it looks normal again.

**Comment by paulirotta** [comment]
![image](https://user-images.githubusercontent.com/3486467/53552041-2b7d7280-3b43-11e9-8a73-19e06814f617.png)

I'm seeing similar distortion in Windows 10 when changing from laptop to external monitor. QScintilla editor, Courier 10.

This doesn't happen with Simple Editor.

**Comment by t-paul** [comment]
That sounds much more related to #1624.

This one is about selecting the wrong font on Linux and I believe it's actually fixed by https://github.com/openscad/openscad/commit/cc50662036ae33a033247d3c180e9d4ac03be690 so I'm closing this issue here.
