### ISSUE TITLE
comlilation error

### ISSUE THREAD

**Issue by joinalahmed** [openscad/openscad#1749]
when i'm compiling wit qmake, i.m getting error
![ss](https://cloud.githubusercontent.com/assets/14151006/17076134/e19db890-50c7-11e6-84a9-5b2f2ee9137d.png)
@amarjeetkapoor1

**Comment by amarjeetkapoor1** [comment]
Error message says it all. Check whether all the dependences are available by running: 
./scripts/check-dependencies.sh

if not than install them using:
sudo ./scripts/uni-get-dependencies.sh

And I would suggest you to discuss any problem you are facing on organizations IRC channel as some developer would always be present their and your problems will be solved much faster their.
