### ISSUE TITLE
Parser error should report actual line in file

### ISSUE THREAD

**Issue by oysteinkrog** [openscad/openscad#1750]
If there is a parser error, it should report the line of the file, not the total line (including included files).
The current behavior makes it a nightmare to track down syntax errors:
```
ERROR: Parser error in line 36113: syntax error 
ERROR: Compilation failed! 
```
In a file that is ~1600 lines...

**Comment by doug-moen** [comment]
That's fixed; try using a development snapshot.
http://www.openscad.org/downloads.html#snapshots

**Comment by oysteinkrog** [comment]
Ah, I was using the previous snapshot:
OpenSCAD version 2016.05.12 (git 7b8265a) 

I've confirmed it reports the correct line now, thank you and whoever fixed it as well.
