### ISSUE TITLE
Parameters: Slider updates although still being dragged

### ISSUE THREAD

**Issue by stylesuxx** [openscad/openscad#1761]
I encounter this problem on my notebook when working with the touchpad. It is very hard to pin a number with the slider when in auto preview mode. I have the feeling that the slider is updating when it registered no movement for some time. I think it would be better to only update when the slider is not being dragged any more.

I am willing to contribute, just let me know if this is a welcomed change.

**Comment by amarjeetkapoor1** [comment]
Thanks @stylesuxx for feedback and I have solved this issue.

**Comment by amarjeetkapoor1** [comment]
@t-paul , Should same thing also be applied to spin-box and vector input widget?

**Comment by t-paul** [comment]
Yes, if that makes the UI more responsive, I think that would be a good idea.
