### ISSUE TITLE
Preview not rendering correctly

### ISSUE THREAD

**Issue by bond4u** [openscad/openscad#1763]
It seems to be hardware issue.
It was working fine on my old Dell Latitude, but it isn't rendering now on my new Dell Precision.
[_dell_latitude_lib_info.txt](https://github.com/openscad/openscad/files/399921/_dell_latitude_lib_info.txt)
[_dell_precision_lib_info3.txt](https://github.com/openscad/openscad/files/399922/_dell_precision_lib_info3.txt)
![oscad-preview](https://cloud.githubusercontent.com/assets/66413/17373801/8652ed18-59b2-11e6-90e0-19f448473c54.png)
![oscad-render](https://cloud.githubusercontent.com/assets/66413/17373805/8864ad26-59b2-11e6-851c-e461884bfc5e.png)

**Comment by MichaelAtOz** [comment]
For others, note the above .txt files is the Help/Library_info.

As it is 'GL Renderer: Intel(R) HD Graphics 4600' on Windows, try Edit/Preferences/Advanced/Enable_Goldfeather

**Comment by bond4u** [comment]
Got it working.
I had latest AMD driver, but not Intel driver.
support.dell.com driver detection offered new Intel Graphics driver.
After installing that OpenSCAD started crashing, but at the same time I got tooltip in systray saying that I need to assign a processor to application.
Once I did that, OpenSCAD started working and preview is rendering correctly now.

**Comment by t-paul** [comment]
Thanks for the follow-up, I'll close the issue as that seems to be resolved with the updated driver.
