### ISSUE TITLE
echo() escaped character & HTML conflict

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1765]
1000 words;
![escape and html](https://cloud.githubusercontent.com/assets/1972961/17421241/acc1b756-5aeb-11e6-84a7-c353195ca861.JPG)
Some `escaped characters` (newline in this case, not tab) prevent `HTML` from being displayed.
Conversely, lines 11 &12, `HTML` prevents `escaped tab` from being displayed.

I haven't tried other escape sequences.

In OpenSCAD 2015.3-2 and 2016.07.20 on Win7.

**Comment by t-paul** [comment]
Someone on IRC asked about this issue, so I guess it would make sense to also define what the expectation is. I never really expected the console to render HTML. It might be useful in some cases but is both risky in the long run (do we maybe want to support loading scripts directly from the web?) and sort-of conflicts with command line usage where HTML is not directly usable.

As mid-term solution, maybe split console (= for messages generated by the app) and output (= messages generated by the scripts)?

**Comment by doug-moen** [comment]
My expectation is that I can use echo for debugging, and for printing the values of variables, including string variables. This means that echo should print strings literally, and not interpret them as HTML. The current behaviour should be considered a bug.

If we want to support HTML output to the console, then we should create a new function for that. The small number of people who want this will also want the ability to print to the console without having "ECHO:" preprended to the output.

**Comment by MichaelAtOz** [comment]
The current behavior (baring bug in this report) is not a bug, and is useful. It is built into Qt, so eliminating it would presumable be more work.
During debug it is very useful to format output.
I seem to recall someone having quite extensive use of html, I think it was runsun  [e.g. BOM - forum](http://forum.openscad.org/OpenSCAD-and-Woodworking-td13966.html)

**Comment by MichaelAtOz** [comment]
> but is both risky in the long run (do we maybe want to support loading scripts directly from the web?) and sort-of conflicts with command line usage where HTML is not directly usable.

It is a [subset](http://doc.qt.io/qt-5/richtext-html-subset.html) of html

**Comment by bulgakovk** [comment]
I noticed that If I use only one tab symbol - HTML still renderes correct but tab replaces by empty symbol.
![2016-09-13 22-21-41](https://cloud.githubusercontent.com/assets/8983736/18488108/b3b307d4-7a00-11e6-8d0d-c5f7bb598d06.png)

HTML with two tabs still works nice but all tab symbols replace by only one space.
Is it problem with QT widget or something wrong with printing functions? Probably you can give me advice where I can see this code?

>Someone on IRC asked about this issue
It was me btw.

**Comment by MichaelAtOz** [comment]
> Probably you can give me advice where I can see this code?

echo() does:
https://github.com/openscad/openscad/blob/02439847dc0a98cf7e6ba7095b64d521ab3f6553/src/control.cc#L261
	PRINTB("%s", msg.str());

https://github.com/openscad/openscad/blob/master/src/printutils.h
void PRINT(const std::string &msg);
#define PRINTB(_fmt, _arg) do { PRINT(str(boost::format(_fmt) % _arg)); } while (0)

PRINT basically does:
https://github.com/openscad/openscad/blob/master/src/printutils.cc
	fprintf(stderr, "%s\n", msg.c_str());

boost::format() doesn't seem to do much as it is %s (string), so I presume Qt does the escape chars as well as html.

**Comment by bulgakovk** [comment]
I tried to use fprintf from printutils.cc with "\n<b>Hello</b>" argument and bug still happens (escaped character prevents HTML).
Does it mean that It's something wrong with Qt Widget?

**Comment by MichaelAtOz** [comment]
> Does it mean that It's something wrong with Qt Widget?

Presumably, or GCC/Runtime.

**Comment by bulgakovk** [comment]
I've solved the problem with **\n** and **\t** symbols. Can someone tell me if there are any other tags which I should add to my code? Thanks.

**Comment by MichaelAtOz** [comment]
Wiki says

> To include a " character in a string literal, use \". To include a \ character in a string literal, use \\. The following escape sequences beginning with \ can be used within string literals:

    \" → "
    \\ → \
    \t → tab
    \n → newline
    \r → carriage return
    \u03a9 → Ω - see text() for further information on unicode characters

**Comment by MichaelAtOz** [comment]
Partial work-around. Newline tab and bold (& presumably other html) work, but 'pre' has a blank line before/after - inconsistently (see after bold).

echo("<pre>String, \nnewline, \t\ttab, <b>bold</b></pre>");
echo("First<pre>Second</pre>Third");

**Comment by ChrisVesters** [comment]
What are the opinions about this? I understad that trying to have full HTML support is difficult. It might have side-effects for people who do not try to write html, but do so by accident?

Should we have a separate echo function for formatted text? By just saying 'formatted'  text we can decide ourselves what we do and do not support.

echoFormatted()

**Comment by kintel** [comment]
When designing this, perhaps think about ANSI escape codes (and whatever the DOS prompt equivalent is) for people running this in a shell.

**Comment by t-paul** [comment]
HTML render in console is disabled now.
