### ISSUE TITLE
WARNING: $fs too small - clamping to 0.010000

### ISSUE THREAD

**Issue by l29ah** [openscad/openscad#1773]
https://github.com/openscad/openscad/blob/master/src/primitives.cc#L42
What's the idea behind this magic value? Is it safe to lower it?

**Comment by kintel** [comment]
It limits the maximum precision as an attempt to keep people from shooting themselves in the foot. It's based on a common convention in 3D printing that the unit of modeling is 1mm. Apparently, this is not universal ;)

We have other, similar, magic values, and it would be good to be able to at least control them at run-time, or implement other ways of avoiding runaway computation if people happen to type in a too low value by accident.
