### ISSUE TITLE
Windows 10 is not reported correctly in library info

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#1800]
It seems the version detection is broken with Win10 again (reported in #1409).

> I'm running Win10 anniversary edition, which is incorrectly reported in the lib info window as WIn 8:
> System information: Windows 8 (v6.2.0.0) 4 CPUs 5.93 GB RAM

We used https://bitbucket.org/AnyCPU/findversion to detect the Win8 versions that are not reported by the old (and now deprecated) interface but this fails on Win10.

**Comment by donbright** [comment]
sorry about that, fixed now

**Comment by kintel** [comment]
Fixed by #1817
