### ISSUE TITLE
Download URL of Qscintilla wrong

### ISSUE THREAD

**Issue by tobiasvogel** [openscad/openscad#1816]
the script "macosx-build-dependencies.sh" tries to download the sources for Qscintilla from:
curl -LO http://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-$version/QScintilla-gpl-$version.tar.gz
however, before the "gpl" there is no dash in the filename but a underscore instead:
curl -LO http://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-$version/QScintilla_gpl-$version.tar.gz
likewise the script tries to unpack sources that are named accordingly wrong.

**Comment by t-paul** [comment]
Should be fixed by #1804 already.
