### ISSUE TITLE
regression test throwntogethertest polygontest failing under certain situation

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#182]
On the 'polygontest' regression test, specifically the degenerate polygon 

    polygon( [[0,0] [1,1] [2,2]] )

the results involve unusual rendering as the 'fberror' ThrownTogether rendering code is triggered and draws magenta (rgb 255 0 255) mixed with the ordinary yellow rendering color. In normal GUI mode, the rendering of this polygon looks somewhat similar to 'zfighting' in other OpenGL situations (for example coincident faces of a box/cylinder). 

This results in the regression test failing under clang / eigen3 / boost 1.50 /32bit when it passes under gcc / eigen2 / boost 147 because the magenta is on the 'left side' of the polygon instead of the 'right side'. 

OpenCSG does not have this problem because OpenCSGRenderer.cc doesnt use the same code as throwntogetherrenderer.cc and in fact doesn't do 'magenta' surfaces for situations like this. 

I am not sure if ThrownTogether should really 'fail' this test, since if you load up the GUI you couldn't tell a difference, its just a jumble of magenta and yellow that slides back and forth over each other. I haven't been able to find exactly where the difference is between clang/eigen3/boost150 and the 'normal' build. The polysets are the same, the CSG chains are the same, etc.

**Comment by kintel** [comment]
Handling of degenerate triangles has been improved since then, so this isn't an issue any longer
