### ISSUE TITLE
Image export on Travis-CI

### ISSUE THREAD

**Issue by syky27** [openscad/openscad#1826]
Hi, I am sorry for creating a new issue but, I have nowhere else to ask.

I have problem with exporting images from openscad, while running tests on Travis-CI.

I suppose that this relates to missing X11, I noticed that you use travis, so I figured I would ask if you have any idea how could I achieve exporting images on Travis-CI.

Thank you very much for any help.

**Comment by t-paul** [comment]
See https://github.com/openscad/openscad/blob/master/tests/virtualfb.sh

This runs Xvfb as X11 display. Note that latest travis images install the AMD drivers breaking OpenGL, so those need to be deinstalled.

**Comment by syky27** [comment]
Hi, thanks I have tried it without any luck :(

**Comment by donbright** [comment]
```
Xvfb :1 -screen 0 800x600x24 &
export DISPLAY=:1
openscad x.scad -o x.png

```

https://en.wikipedia.org/wiki/Xvfb#Usage_examples

**Comment by syky27** [comment]
```
[dix] Could not init font path element /usr/share/fonts/X11/cyrillic, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi/:unscaled, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/100dpi, removing from list!
[dix] Could not init font path element /usr/share/fonts/X11/75dpi, removing from list!
```

Didn't seemed to do the trick :(

**Comment by syky27** [comment]
@t-paul how can I uninstall those drivers?

**Comment by t-paul** [comment]
We use `sudo apt-get purge -qq fglrx` in [`.travis.yml`](https://github.com/openscad/openscad/blob/master/.travis.yml). Obviously that needs `sudo` enabled for the Travis worker which we need for other reasons too. I don't know if there's a way to remove the packages without the need for `sudo`.

**Comment by syky27** [comment]
I used OSX on Travis and it started working...
