### ISSUE TITLE
Feature request: Print stack trace if assert() fails

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#1828]
See comment: https://github.com/openscad/openscad/issues/381#issuecomment-187260087

Moved here so we could close the main issue.

@doug-moen 

> Here's the problem. I'd like an implementation of assert that doesn't require me to include messages and labels. I don't want to spend time iteratively cluttering up my assertions with labels and messages until there is enough information printed so that I can distinguish one assertion failure from another. You're telling me there are two different kludgy ways to label asserts, and that I will need to use them.
> 
> The problem is that the assertion failure message contains no context, other than the condition that evaluated to false. There must be some additional context that we can print.
> 
> Here are some ideas.
> 
> In parser.y, when we construct the parse tree node for an assertion, store the file name and line number of the assertion. When the assertion fails, print the file name and line number. Based on Torsten's code, we'd add file,line arguments to ExpressionFunctionCall::create().
> 
> Print a stack trace when an assertion fails. In principle, we should be able to print filename, linenumber, function name, arguments, for each function call in the call stack.
> 
> The Context structure already contains a parent pointer, so we could walk the Context chain to produce the stack trace. We'll need to add another data member to Context that is non-null for function call contexts, which contains stack trace information for that function call. This new member will be an EvalContext*.
> An EvalContext holds the evaluation context for a function or module call. So add stack trace information to this structure (file name, line number, function or module name, or a pointer to an object that contains this information). ExpressionFunctionCall::evaluate creates the EvalContext for a function call, and the ExpressionFunctionCall object contains this information.
>     Function::evaluate constructs a context c, then calls c.setVariables with the EvalContext as the second argument. Modify Context::setVariables to store a pointer to the EvalContext in the Context structure; this marks the Context as a function call context, and provides access to the information needed to print the stack trace when we walk the Context chain.
> 
> In order to print the values of variables referenced by the false condition, we'd need to add a virtual printVariables() member function to Expression, which is passed a Context. The default implementation, Expression::printVariables, just calls this function recursively on its children. ExpressionLookup::printVariables overrides the default implementation, and prints name=value. That's pretty crude, because the same variable might get printed multiple times, but we could clean that up by remembering which variables have been printed already.
> 
> I've never actually modified the OpenSCAD evaluator before, so I may have misunderstood how the data structures work, and there may be a better way.

**Comment by MichaelPFrey** [comment]
Let me break this down.

> In parser.y, when we construct the parse tree node for an assertion, store the file name and line number of the assertion. When the assertion fails, print the file name and line number. Based on Torsten's code, we'd add file,line arguments to ExpressionFunctionCall::create().

done with #1910,  #2322 and #2341

> Print a stack trace when an assertion fails. In principle, we should be able to print filename, linenumber, function name, arguments, for each function call in the call stack.

see #2645. note that printing arguments is actually harder then it sounds and sometimes, the problem is not a parameter, but an other variable in the context.

> ...
> I've never actually modified the OpenSCAD evaluator before, so I may have misunderstood how the data structures work, and there may be a better way.

see #2645. Exceptions seam to do the trick.
