### ISSUE TITLE
Customizer: Save As does a compile (preview) after saving

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1836]
version 2016.10.05 (git 4b59170)  GSoC - so presumably side effect of customizer(?).
2015.03-2 doesn't do it.

**Comment by kintel** [comment]
-> add to blocker in #1781

**Comment by amarjeetkapoor1** [comment]
The reason for this behavior is that on Save As FileName is set and its the same point where the customizer picks name of JSON file to read and after reading it creates the combo-box for set of parameters. On creating Combo-box index of current selected item gets changed. So, It emits signal to recompile it.
Possible solution is that we disconnect Combo-box at https://github.com/openscad/openscad/blob/master/src/parameter/ParameterWidget.cc#L104 and reconnect after https://github.com/openscad/openscad/blob/master/src/parameter/ParameterWidget.cc#L105.
