### ISSUE TITLE
Customizer GUI Improvements

### ISSUE THREAD

**Issue by amarjeetkapoor1** [openscad/openscad#1845]
Moved from #1781 
- [ ] Make whole parameter display a bit more compact (borders, name only bold not bigger font size...)
- [ ] Match Window border width with other windows (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Fix font sizes in Windows (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Check vertical spacing (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Fix slider paging (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18743))
- [ ] Replace labels "+" and "-" with three separate labels ( someone found them misleading):
  1. New - for a new Preset.
  2. Update - to update the current Preset with the current parameter values.
  3. Delete - to delete the current Preset (after a confirmation).
- [ ] Check mouse scrolling behavior (parameter pane vs. range controls) (see [forum post](http://forum.openscad.org/GSoC-OpenSCAD-project-td18102i20.html#a18761))

**Comment by amarjeetkapoor1** [comment]
Should buttons be used for New, Update and Delete or icons?

**Comment by kintel** [comment]
Starting with buttons makes sense to me, to get good functionality in place. Then we can look into making it pretty.
