### ISSUE TITLE
"each each" causes a crash

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1851]
From the [mailing list](http://forum.openscad.org/each-each-td18863.html)
Example:
```
a = [ for (a=1) each each a];
```

-> Should we support `each each` ?

As a side effect this also causes a crash:
```
a=[each for(i=[1,2]) i];
```

-> This should be a syntax or run-time error

**Comment by kintel** [comment]
Update: Not related to the crash in #1839

**Comment by kintel** [comment]
Moving discussion about whether or not we should support `each each` to #1559

**Comment by RonaldoCMP** [comment]
a=[each for(i=[1,2] i];
also causes a crash in 2016.11.11
