### ISSUE TITLE
Error in Location

### ISSUE THREAD

**Issue by amarjeetkapoor1** [openscad/openscad#1852]
For e.g.
```
a="as
as";
b=1;
```
then location of `a` should be firstLine=1 and lastLine=2 and for `b`  firstLine = 3 but Its  firstLine=1 and lastLine=1 for `a` and for `b` firstLine = 2.

Scanner is not counting the occurrence of new line inside the string which  will create problem for customizer if someone used string like this.

Plus there is problem in firstColumn variable also.
for e.g.
```
#123
a=1;
```
for above FirstColumn should be 1 but its shown as 6 it also count column for

**Comment by kintel** [comment]
Thanks, this looks like a bug. Perhaps we should write a simple test program which we could use to add to the test framework.
