### ISSUE TITLE
Accept assert() as stable

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1860]
TODO:
- [x] Documentation
- [x] Cheat Sheet
- [x] Examples
- [x] Remove from experimental
- [x] Update syntax highlighting (scadlexer.cpp and highlighter.cc)

**Comment by MichaelPFrey** [comment]
I would like to add
- [ ] update syntax highlighting
- [ ] scadlexer.cpp
- [ ] highlighter.cc
to the list

I am working on the documentation:

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features#assert

**Comment by t-paul** [comment]
Good point, thanks. Added to he main list.

**Comment by MichaelPFrey** [comment]
color-schemes/editor/visualstudio.json has its own keyword list (unlike all the other color schemes).
Those keywords are effective (as in they are applied)

I do not know which of this two alternatives is more sensible:
- Remove the Keyword List from color-schemes/editor/visualstudio.json (prevents further inconsistency, but I do not know if there are side-effects and/other usages of this file)
- Update the Keyword List in color-schemes/editor/visualstudio.json (please check all keywords, for e.g "children" is also missing)

**Comment by MichaelPFrey** [comment]
In OpenSCAD, I can overwrite build in functions. Example:
function sin() = true;
echo (sin(1));

but I can not overwrite assertion:
function assert() = true;
echo (assert(1));

**Comment by t-paul** [comment]
Added new issue #2506 as followup on the function override comment. I think that's not just specific to `assert()`.
