### ISSUE TITLE
Simple mesh validation on import/polyhedron

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1864]
Perform a basic mesh validation when importing external files, or when creating polyhedrons.
Things we want to report:
* manifoldness
* zero are triangles

**Comment by MichaelAtOz** [comment]
Note my comment from elsewhere, may be useful, seems many STLs have self intersects.


kintel in my travels I came across [this](http://doc.cgal.org/latest/Polygon_mesh_processing/#title18)

>Self intersections can be detected from a triangle mesh, by calling the predicate CGAL::Polygon_mesh_processing::does_self_intersect(). Additionally, the function CGAL::Polygon_mesh_processing::self_intersections() records all pairs of intersecting triangles.

**Comment by kintel** [comment]
@MichaelAtOz Thanks - we've avoided using the Polygon_mesh_processing thus far, as it requires a pretty recent version of CGAL, which has limited availability. Perhaps time to reconsider that..

**Comment by kintel** [comment]
Closing this, as we currently do basic mesh repair on import when using the Manifold backend.
