### ISSUE TITLE
uic builds two-argument _() calls

### ISSUE THREAD

**Issue by chrysn** [openscad/openscad#1872]
uic 5.7.1, when invoked with the 2015.03-2 (and -3) openscad.pro option `uic.commands += -tr _` as `uic -tr _`, produces intermediate c++ files that look like this:

    OpenCSGWarningDialog->setWindowTitle(_("OpenGL Warning", Q_NULLPTR));

gettext doesn't have a two-argument _ form, and the build fails with error messages like [debian's 844881](http://bugs.debian.org/844881). i've worked around this in a not-beautiful-but-small-patch way by creating a lambda that strips the second argument; creating a small wrapper i printutils.h might be a better option; ideal would be some uic option that allows continued easy gettext interoperability.

**Comment by t-paul** [comment]
I just got the update to Qt5.7 on my system, so I can reproduce that now. I'll have a look. I guess the small wrapper you propose is probably the easiest option.
