### ISSUE TITLE
Polyhedron: zero area triangles

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#1876]
Zero area triangles in a polyhedron fails to render.
To test: `openscad file.scad -o out.png --render=cgal`

**FIXME**: This test case has a duplicate triangle `[7,8,9]` causing the issue. Try to find another zero area triangle test to highlight the issue.

```
polyhedron(points=[
[0,0,0],
[0,40,0],
[0,30,0],
[0,20,0],
[-10,0,0],
[-10,40,0],
[10,0,0],
[10,40,0],
[0,20,-20],
[10,20,0]
], faces = [
[9,8,6],
[7,8,9],
[7,8,9],
[1,8,7],
[5,8,1],
[4,8,5],
[0,8,4],
[0,6,8],
[2,1,7],
[3,2,7],
[3,7,9],
[3,9,6],
[0,3,6],
[0,5,1],
[0,4,5],
[0,2,3],
[0,1,2],
]);
```

**Comment by palasiks** [comment]
The face [7,8,9] is listed twice. Is that intentional? Because if I delete one copy then it renders fine.

**Comment by kintel** [comment]
Good catch! I'm pretty sure the title of this issue is accurate, but the test case might be broken.
I'll have another look

**Comment by kintel** [comment]
Status as of 2024-03-24: Even the broken example works with Manifold.
Closing as this issue stalled (failed to remember what I was trying to prove)
