### ISSUE TITLE
Shortcut Keys not working.

### ISSUE THREAD

**Issue by amarjeetkapoor1** [openscad/openscad#1884]
Some Shortcut keys are not working for actions like saveAs, Reload, close, Comment, uncomment, past veiwport translation, All find commands.
I observed this on ubuntu.

**Comment by MichaelAtOz** [comment]
In 2016.11.11 on Windows they are working (Ctrl-S, Ctrl-R etc.)

**Comment by kintel** [comment]
@amarjeetkapoor1 Since when are they not working (OpenSCAD version, Linux version) ?

**Comment by t-paul** [comment]
Could be also some Ubuntu/Desktop-Environment issue, I did not try all, but the shortcuts are working for me on Debian/testing running Gnome 3 with the latest OpenSCAD nightly build (Qt4).

**Comment by amarjeetkapoor1** [comment]
I found it on both Ubuntu 14 LTS and 16 LTS both  with default environment (I think its unity). 
I found this on both 2015.03-1 version and also latest build with qt5.

**Comment by t-paul** [comment]
Assuming that was specific to Unity (messing with Qt menu bars) which is pretty much dead now, so closing the issue.
