### ISSUE TITLE
Critical error for unclosed block comment

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#1890]
TODO:
* [x] Make sure customizer doesn't crash
* [ ] Make the OpenSCAD output a parser error for unclosed `/*`
* [ ] Make the OpenSCAD output a parser error for unclosed `"`

When this code is previewed:
`/*`

OpenSCAD pops up this alert:
![screenshot from 2016-12-11 19 38 40](https://cloud.githubusercontent.com/assets/252233/21085612/9fe2f362-bfd9-11e6-9610-6834463b0434.png)

The application no longer previews or renders after fixing the error and adding geometry.

Ideally this error would be notified through the console, and handled such that OpenSCAD would continue to function.

**Comment by kintel** [comment]
Thx - this is a bug in the customizer comment parser.
@amarjeetkapoor1 Does this look easy to fix?

**Comment by kintel** [comment]
@thehans FYI: This bug only triggers if the customizer feature is turned on.

**Comment by amarjeetkapoor1** [comment]
I have corrected this by adding more condition checking but I have written comment.cpp with assumption that whole file will be syntacticly correct and It only runs only if parser doesn't produce error and `/*` is something which  should be syntacticly wrong. I think for `/*` parser should produce error message stating "unterminated comment "  but It doesn't produce I any error.  Similar is case for `" ` although their is no crash but it should produce error.

**Comment by amarjeetkapoor1** [comment]
I think that remaining two issues can be solved by adding following rule to 
`<cond_string>` and `<cond_lcomment>` states:

```<<EOF>>  { BEGIN(INITIAL); return TOK_ERROR;  }```

But I am not getting the expected result. Any comments?

**Comment by kintel** [comment]
@amarjeetkapoor1 Can you take a look at #1992 ?

**Comment by amarjeetkapoor1** [comment]
Yes, sure
