### ISSUE TITLE
CSG Tree dump via CLI

### ISSUE THREAD

**Issue by syky27** [openscad/openscad#1893]
If possible I would like to request a new feature.

I would love to be able to get CSG Tree dump using command line.

I teach 3D Printing @3DprintFit, and I would like to use this feature for source code similarity checks.

Thank you!

**Comment by kintel** [comment]
@syky27 Could you be a bit more specific? i.e. what about the following existing cmd-line options are not doing what you want?

`openscad file.scad -o out.csg`
`openscad file.scad -o out.ast`

**Comment by syky27** [comment]
@kintel I have somehow missed this in documentation.

I am sorry for wasting your time, this is exactly what I need.

Thank you
