### ISSUE TITLE
Bad syntax still works

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1895]
```
%cube(10);
translate([5,5,,,,5]) // any number of extra commas
  #cube(10);
```
It actually uses 5 for z.
I would have thought it would have looked after the second comma for the z value, and either used zero, or got an error, not keep going along the parameter list.

**Comment by t-paul** [comment]
Any reference to the "still"? Was this supposed to be changed somewhere in the past? The parser has lots of places where it explicitly ignores multiple commas.

**Comment by MichaelAtOz** [comment]
> where it explicitly ignores multiple commas

Wasn't aware of that. This was the first I came across it.

**Comment by t-paul** [comment]
I'm not sure it was intended to cover this case though, it's common enough to ignore trailing commas. Maybe the definition for that got a bit out of hand. I suspect it's hard to change now, although it might be possible to separate wanted and unwanted cases and warn for the unwanted ones.
