### ISSUE TITLE
minkowski shifts object - bug or feature?

### ISSUE THREAD

**Issue by PHolzwarth** [openscad/openscad#1902]
Consider the code below. When using union() in line marked with "// ++++++", the object is where I would expect it. When using minkowski() instead, the object jumps to the right. Bug or feature?

quarterPipeR(20, 10, 20, 0.4);

// a quarter of a pipe with rounded edges
module quarterPipeR(outerRadius, thickness, height, rounding= 1) {
    minkowski() { // ++++++
    // union() {
        quarterPipe(outerRadius-rounding,
              thickness-2*rounding,
              height-2*rounding);
        translate([outerRadius-rounding, 0, 0]) 
            sphere(r=rounding, $fn=25*  rounding);
    }
}

// a quarter of a pipe
module quarterPipe(outerRadius, thickness, height) {
    difference() {
        cylinder(h=height, r=outerRadius);
        translate([0,0,-0.1]) 
            cylinder(h=height+0.2, r=outerRadius-thickness);
        translate([-outerRadius, -outerRadius, -0.1]) 
            cube([2*outerRadius, outerRadius, height+0.2], center=false);
        translate([-outerRadius, -0.1, -0.1]) 
            cube([outerRadius, outerRadius+0.1, height+0.2], center=false);
    }
}

**Comment by t-paul** [comment]
Yes, that's intentional. Basically the origin of the 2nd object is moved along the outside of the 1st object.
