### ISSUE TITLE
Update site, Debian repo and latest binary distibution for linux

### ISSUE THREAD

**Issue by redfast00** [openscad/openscad#1911]
I would like to use `$vpd`, but I am still on 2014.03. I wanted to upgrade to 2015.03, but there is no binary distribution of that available for Linux (see [here](http://www.openscad.org/downloads.html#linux)). It would be nice if the Debian repo and the files would get updated. Thanks!

**Comment by t-paul** [comment]
There is a nightly build for Debian 8 and the soon to be released Debian 9 (currently still `testing`) also has 2015.03.

Pinging @chrysn in case there are some additional official words from the maintainer of the Debian package :-).
