### ISSUE TITLE
Automatic Reload and Preview doesn't work properly with multiple documents open. 

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#1928]
If the documents share modules the first window will see the changes and update but the second window doesn't see the changes because includesChanged() and handleDependencies() only return true once for each set of file changes.

**Comment by nophead** [comment]
To state the bug more concisely: If two windows are viewing files which share a common subtree of dependencies then only one widow will update when any of those dependencies change. Changing non-shared files will update the correct window.

**Comment by kintel** [comment]
Fixed by #1929
