### ISSUE TITLE
Customizer shows values from included libraries but not from used ones

### ISSUE THREAD

**Issue by SparkyCola** [openscad/openscad#1939]
Hi, on my [current Project](https://github.com/SparkyCola/SparkyScreen) that uses and includes [@JohnK](https://github.com/JohK/)'s [nutsnbolts library](https://github.com/JohK/nutsnbolts). The Customizer has been a huge help there but it shows the variables from the _<include>d_ libraries too in the first tab (Backside) and in the General Options (the latter is OK afaik) even though they included before that and adds comments of the Backside tab (like "height of 2nd...") to them:
![customizer](https://cloud.githubusercontent.com/assets/6294585/22864178/d237601a-f14c-11e6-838d-c8219981792d.png)
I'm using the newest nightly version from the Ubuntu-repo (version 2017.02.11.nightly (git e990ac4)). I don't know if this behavior is planned (showing the options of the included but not the used libraries, not the displaying in the wrong tab) and if it is it should be mentioned in the WikiBook (I'd like to add it, just tell me)

**Comment by amarjeetkapoor1** [comment]
This is a issue and customiser is not supposed to do that.
#1840

**Comment by kintel** [comment]
Closing as duplicate

**Comment by SparkyCola** [comment]
sorry, didn't find that one

**Comment by t-paul** [comment]
As workaround you could try moving the includes to the end.

**Comment by SparkyCola** [comment]
> As workaround you could try moving the includes to the end.

Good idea but does unfortunately not work, changes neither the customizer nor includes them so the model won't work correctly. What works is to use `<use>` rather then `<include>` but their not the same and `<use>` does not work for all libraries in my case.
