### ISSUE TITLE
Customizer crashes when trying to add a preset

### ISSUE THREAD

**Issue by SparkyCola** [openscad/openscad#1940]
Hi, I just tested the customizer on this tiny test: 

`/* [Test] */`
`//test`
`x = 5;`
`cube(x);`

and get the following error when on the console when I hit the "+"-key and enter a name (nothing fancy, only lower-case ascii without any spaces):

`openscad-nightly: /usr/include/boost/optional/detail/optional_reference_spec.hpp:108: T& boost::optional<T&>::get() const [with T = boost::property_tree::basic_ptree<std::__cxx11::basic_string<char>, std::__cxx11::basic_string<char> >]: Assertion `ptr_' failed.
Aborted (core dumped)`

I'm using version 2017.02.11.nightly (git e990ac4) on Ubuntu 16.10 64-bit.

**Comment by kintel** [comment]
Fixed by #1948
