### ISSUE TITLE
No Version number in ABOUT dialog

### ISSUE THREAD

**Issue by MarcusWolschon** [openscad/openscad#1941]
The help->about dialog shows no obvious  version number/build date/commit .
There is a tiny and easy to miss version number in the title of the window.
However that is hard to see above the giant OPENSCAD - THE PROGRAMMERS SOLID.... text.

**Comment by t-paul** [comment]
Please add some details... like which OS, compiled how, downloaded where? Screenshot?

**Comment by nophead** [comment]
[image: Inline images 1]

**Comment by t-paul** [comment]
I'm getting this for the nightly build on Debian/testing...

![screenshot from 2017-02-13 20-21-47](https://cloud.githubusercontent.com/assets/1330241/22899150/1e025260-f22a-11e6-9563-03faad4edc85.png)

**Comment by t-paul** [comment]
@nophead are you having that issue too? Github decided to drop the attached image...

**Comment by Ma-XX-oN** [comment]
Um, what about the "OpenSCAD version 2017.02.11.nightly (git e990ac4)"?

**Comment by nophead** [comment]
@t-paul,
   No it works fine for me on Win7 and looks like the picture you posted.

**Comment by MarcusWolschon** [comment]
You are right. I completely missed that year+month while looking for something like "0.2" or something.
The text was already scrolled down a bit when it apeared on screen. Probably happened while I was trying to enlarge it to fill more then 10% of the screen (17" 4K. Probably used pixe-counts for initial dimensions instead of physical sizes and DPI reported by OS) to real the text.

**Comment by temoto** [comment]
@MarcusWolschon would you close the issue then?
