### ISSUE TITLE
STL Filename truncated when exporting a model

### ISSUE THREAD

**Issue by Angel996** [openscad/openscad#1953]
Hello.

If the original .scad filename has a dot character other than the one that goes before the file extension, the  filename suggested for the STL file when exporting gets truncated up to it. For example, if project name is `Model X1.7 ver 12.scad`, the STL filename OpenSCAD suggests when exporting is `Model X1.stl` whereas it should be `Model X1.7 ver 12.stl`. So, the correct name has to be typed in manually.

The problem has existed in all versions of OpenSCAD and still exists in version 2015.03-2 (Win64).

**Comment by t-paul** [comment]
I think that's fixed in the nightly builds.

**Comment by MichaelAtOz** [comment]
Fixed by #1552
