### ISSUE TITLE
Warnings and error messages only shown five times

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#1961]
This line: https://github.com/openscad/openscad/blob/4a0ac7b2fa6e8ca390e3b95e1c2d2541cf9d77af/src/printutils.cc#L62 prevents the same message being printed more than five times consecutively. The bug is that the ring buffer is not reset at the start of compilations, so a single error or warning in a project will only be shown for the first five compilations.

See http://forum.openscad.org/Strange-behaviour-with-assert-tt20545.html

**Comment by kintel** [comment]
Fixed by #1962
