### ISSUE TITLE
Difference between cylinders

### ISSUE THREAD

**Issue by goganchic** [openscad/openscad#1966]
I want to draw difference between two cylinders. So, I use such code:

```
difference() {
    cylinder(h=100, r=100);
    cylinder(h=100, r=50);
}
```

I expect to see through hole, but the picture differs.

<img width="516" alt="screen shot 2017-03-04 at 16 59 27" src="https://cloud.githubusercontent.com/assets/193946/23579356/d4e6c728-00fc-11e7-971b-d6ca4024c748.png">

It looks like some pixels were not substracted from first cylinder. If I incease size of internal cylinder

```
difference() {
    cylinder(h=100, r=100);
    translate([0, 0, -1])
        cylinder(h=102, r=50);
}
```

then everything works fine

<img width="506" alt="screen shot 2017-03-04 at 17 07 22" src="https://cloud.githubusercontent.com/assets/193946/23579361/1c9a21a0-00fd-11e7-9966-4120fa9859e5.png">

Is it ok or bug?

**Comment by nophead** [comment]
It is a known limitation of OpenCSG. Coincident faces cause Z fighting because the Z values get rounded to integers in the hardware Z buffer of your graphics card.

**Comment by goganchic** [comment]
Does some known workaround exists?

**Comment by nophead** [comment]
Yes, exactly what you did, i.e. subtract a longer cylinder, so there are no coincident faces.

To avoid the translate I often centre the second cylinder and make its height twice the first one plus 1.

Or you can use render() to compute the geometry with CGAL, so the OpenCSG preview only has to draw a tube, not fake one by drawing two cylinders.

**Comment by alexrj** [comment]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_are_those_strange_flickering_artifacts_in_the_preview.3F

**Comment by goganchic** [comment]
ok, thanks!
