### ISSUE TITLE
Filenames with spaces

### ISSUE THREAD

**Issue by chrlg** [openscad/openscad#1969]
"make" fail while trying to call translation-make.sh

The reason is that there is a space in the homedir name. 
"Don't put space in dirnames" would be an acceptable answer in my view.
But in this case this is so simple to solve :  

just replace the line
QMAKE_POST_LINK += $$PWD/scripts/translation-make.sh
(line 584 in my version)
by
QMAKE_POST_LINK += \"$$PWD/scripts/translation-make.sh\"

**Comment by kintel** [comment]
Thx!
Was this the only hurdle you experienced with space in your homedir path?
