### ISSUE TITLE
Feature: extend function norm to nD vectors

### ISSUE THREAD

**Issue by RonaldoCMP** [openscad/openscad#1972]
Why just 2D and 3D vectors are accepted by function norm()?
Yes, I know I can implement it in users code:

`function norm(a) =   sqrt([for(ai=a) ai*ai]*[for(ai=a) 1]);`

but for a sake of completeness, it should accept other dimensions like scalar product of vectors does. I would expect that it works even with 1D vectors.

**Comment by DrCodeWizzard** [comment]
I tried the following:

v1 = [1,2,3,4,5,6,7,8];
x = norm(v1);
echo(x);

and it worked fine on my version of openscad:
version 2015.03-2

**Comment by kintel** [comment]
Good point - that's indeed implemented as requested.
