### ISSUE TITLE
colors when using difference

### ISSUE THREAD

**Issue by tcurdt** [openscad/openscad#1978]
I am cutting an object in half which then removes the color on the cut surface.

![screen shot 2017-03-28 at 05 04 53](https://cloud.githubusercontent.com/assets/13697/24387302/ae7939f6-1374-11e7-9949-ecfc535a25c1.png)

**Comment by MichaelAtOz** [comment]
OpenSCAD shows a difference()'d surface in another color if not specified.

See this example (also shows how to get rid of z-fighting)
```
difference() {
  color("blue") cube(10);
  translate([5,0,0])
    color("red") cube(10);
}

translate([0,20,0])
  difference() {
    color("blue") cube(10);
    translate([5,-1,-1])
      color("red") cube(12);
  } 

translate([0,40,0])
  difference() {
    color("blue") cube(10);
    translate([5,-1,-1])
      color("blue") cube(12);
  } 
```
![z-fighting 3](https://cloud.githubusercontent.com/assets/1972961/24387952/cce56a96-13c3-11e7-8b29-3795cf2531c0.PNG)

**Comment by thehans** [comment]
Also see https://github.com/openscad/openscad/issues/501

**Comment by t-paul** [comment]
Closing as duplicate.
