### ISSUE TITLE
Difference rendering error, partial render of removed geometry in preview.

### ISSUE THREAD

**Issue by comwizz2** [openscad/openscad#1984]
Using the difference command is not fully removing the geometry from preview for me.
I did find some old  bugs on this, but they seemed to be complaining about older versions of software or Intel specifically, I am using Nvidia on X64 Windows.

![image](https://cloud.githubusercontent.com/assets/5807486/24638166/10373d50-18ac-11e7-8ae6-c066d31957f1.png)

    armThickness = 3;
    baseWidth = 20;
    
    module arm (length=100) {   
        translate([0, 5, 0]) 
            rotate([0, 0, 180])
                cube([length, 10, armThickness]);
    }
    
    difference() {
        translate([0,-5,0]) 
            cube([3, 10, 10], false);
        translate([0,0,5]) 
            rotate([0,90,0]) 
                cylinder(3, 1, 1, $fn=15);
    }
    
    difference() {
        translate([-8.5, baseWidth / -2, 0]) cube([20, baseWidth, armThickness]);
        arm();
    }

[LibInfo.txt](https://github.com/openscad/openscad/files/891888/LibInfo.txt)

**Comment by MichaelAtOz** [comment]
That is [Z-fighting](https://en.wikipedia.org/wiki/Z-fighting).
When differencing you need to make sure you don't have co-incident faces.
Generally you want the negative object to extend beyond the face you want to remove.
Like so.
```
armThickness = 3;
baseWidth = 20;
s=0.5; // smidgeon for difference
module arm (length=100,thick=armThickness) {   
    translate([0, 5, 0]) 
        rotate([0, 0, 180])
            cube([length, 10, thick]);
}

difference() {
    translate([0,-5,0]) 
        cube([3, 10, 10], false);
    translate([-s,0,5]) 
        rotate([0,90,0]) 
            cylinder(3+2*s, 1, 1, $fn=15);
}

difference() {
    translate([-8.5, baseWidth / -2, 0]) cube([20, baseWidth, armThickness]);
    translate([0,0,-s]) arm(thick=armThickness+2*s);
}
```
