### ISSUE TITLE
difference() with union() CSG Normalization goes feral

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#1988]
See [Forum](http://forum.openscad.org/difference-module-operator-with-strange-behaviour-td21146.html).

```
difference()
{
    cube([10, 15, 6], center=true);
    //union()
        {
        translate([10, 0]) cylinder(r=2, h=20,  center=true);
        translate([-10, 0]) cylinder(r=2, h=20, center=true);  // works with translate([20, 0])
        }
 
} 
```

Uncomment the union() gets:
```
Compiling design (CSG Products normalization)...
WARNING: Normalized tree is growing past 800000000 elements. Aborting normalization. 
WARNING: CSG normalization resulted in an empty tree 
Normalized CSG tree has 0 elements
Compile and preview finished.
Total rendering time: 0 hours, 3 minutes, 42 seconds
```
Note that is after I doubled the elements in preferences.
#484 #319 may be similar.

**Comment by woferry** [comment]
I'll just note that I could reproduce this on the Mac 2017.02.08 (git 2ef5333) build, but I could NOT reproduce on the released build, 2015.03.

**Comment by kintel** [comment]
Looks like this regression happened sometime after 2015.09.14

**Comment by kintel** [comment]
Git bisect points at this commit: 97cab4589bc995fdacc43383433040d3953b316b
