### ISSUE TITLE
ERROR: Parser error in file .... memory exhausted 

### ISSUE THREAD

**Issue by oysteinkrog** [openscad/openscad#1991]
Hi,

I'm having some trouble with a memory exhaustion problem in the parser, it seems like I'm hitting a hardcoded limit :/

I suspect this is because I've organized my design in a very modular fashion.
In particular I've landed on a design pattern where I have "data" files that contain arrays of object definitions, e.g. bearings, screw threads etc. The problem is that I include these data files in many of my sub-modules/files, and when I in turn try to use these modules the underlying files are probably "included" several times.
Is there any kind of cache for included files?

If anyone wants to take a look my project is here: https://github.com/oysteinkrog/kmax1/
It's easy to reproduce the problem by opening main.scad and reverting the last commit ("temp fix").

Regards
Øystein

**Comment by thehans** [comment]
This parser error should be fixed by #2343 which was included in the latest stable release of OpenSCAD.  
@oysteinkrog Give it a try if you like, feel free to re-open if you still experience any issues.  

Closing.
