### ISSUE TITLE
OpenSCAD freezes when zooming in

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#2014]
Steps to reproduce:
1) Open OpenSCAD
2) mousewheel zoom in for a little bit, maybe about one order of magnitude
The application becomes unresponsive and requires the process to be killed.

2017.04.29.nightly (git a322fc8) 
Linux Mint 18.1 w/ Cinnamon Desktop 
NVIDIA Corporation GM107GLM [Quadro M1000M] (rev a2)

**Comment by t-paul** [comment]
Sounds like https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=858904

**Comment by thehans** [comment]
It happens exactly when the distance of the next frame would be less than 10.  

It also happens when zooming out past a certain point.  Attached is a screenshot of where it froze from zooming out.
![frozen](https://cloud.githubusercontent.com/assets/252233/25558783/95db4d4c-2cf3-11e7-9b23-76626332b731.png)

This issue is not present in 2015.03-1, the only other version I have installed.   I think this behavior is from a very recent change, It seems like I would have noticed it pretty quickly.

**Comment by t-paul** [comment]
Hmm, is that with the proprietary driver or with nouveau? Anything in `dmesg` from the driver?

**Comment by t-paul** [comment]
Ok, I suspect a bug in the number display. I can reproduce it with scale numbers on, but not if those are disabled.

**Comment by thehans** [comment]
Same here, disabling scale markers works around the issue.

I am using nvidia proprietary drivers by the way

**Comment by kintel** [comment]
Idea for debugging:
* Look at https://github.com/openscad/openscad/blob/master/src/GLView.cc#L507
* Comment out all `gl*` function calls -> verify that it fixes the problem
* Replace all `gl*` function calls with `printf`'s -> inspect the output looking for trouble
* If still necessary: Call all `gl*` functions with the `printf` output, verify that it still fails and post here.

**Comment by t-paul** [comment]
It's the loop in [`showScalemarkers()`](https://github.com/openscad/openscad/blob/master/src/GLView.cc#L507). Needs a closer look to find out which parameters turn it into an endless loop...

**Comment by kintel** [comment]
I can reproduce on OS X as well. Will look at it.
