### ISSUE TITLE
Customizer causes "critical error" when removing from empty parameter set

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2018]
Steps to reproduce:
* Open OpenSCAD
* Save to a new file (the file may be empty or contain some code; doesn't matter)
* Open Customizer
* Click "-" button

-> "A critical error was caught. The application may have become unstable:
No such node (parameterSets)"

Looks like it comes from here: https://github.com/openscad/openscad/blob/master/src/parameter/ParameterWidget.cc#L75

**Comment by amarjeetkapoor1** [comment]
I was able to reproduce and  will correct it.

**Comment by kintel** [comment]
Fixed by #2042
