### ISSUE TITLE
Grid causes degenerate meshes

### ISSUE THREAD

**Issue by ijackson** [openscad/openscad#203]
I have a file which produces this error:

CGAL::Polyhedron_incremental_builder_3<HDS>::
add_vertex_to_facet(): input error: disconnected facet complexes at vertex 224:
           involved facets are: 11394 11166 10938 10710 10482 10254 10026 9798 9570 9342 9114 8886 8658 8430 8202 7974 7746 7518 7290 7062 6834 6606 6378 6150 5922 5694 5466 5238 5010 4782 4554 4326 4098 3870 3642 3414 3186 2958 2730 2502 2274 2046 1818 1590 1362 1134 906 678 450 222 (closed cycle) and.
CGAL error in CGAL_Build_PolySet: CGAL ERROR: assertion violation!
Expr: check_protocoll == 0
File: /usr/include/CGAL/Polyhedron_incremental_builder_3.h
Line: 199

To reproduce, process the attached file "pawn.scad" with "openscad -o t.stl pawn.scad" on Debian wheezy (openscad 2011.12-3, libcgal9 4.0-4).

(Hmm, I can't see how to attach the file.  I will try to do that after I submit this issue.  If I fail I will post a url for it instead.)

**Comment by kintel** [comment]
This was fixed a while ago. Note that rotate_extrude() requires the 2D object to have only positive X coordinates, otherwise, the resulting object will be an inside-out volume.

**Comment by MichaelAtOz** [comment]
> requires the 2D object to have only positive X coordinates

Wiki 
> The 2D shape needs to be either completely on the positive or negative side of the X axis.

??

Also, is it completely positive, what about zero?

(for the wiki)

**Comment by kintel** [comment]
The latter is technically allowed, but the geometry will be inside-out.
The object is allowed to touch the X axis but not cross it.
