### ISSUE TITLE
Feature Request: Command Line, Image export, option to include View features [$50]

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2032]
I'm producing images using the png export in the GUI, and like to include the axes (which includes the three colour axis pointer, and the axis markers (dashes & numbers).
I need to make the image larger/higher resolution. On my new monitor I can get the GUI to ~1300 pixels high, but I'd like higher resolution to put the images on a T-shirt without pixelation.

I can do that with the command line, but I can't get the axes etc.

Of the View Menu options, I'd like Show Axis & Show Scale Markers.
That leaves Show Edges & Show Crosshairs, these should be added for consistency, but I'm in no hurry for them.
Whether anyone would want Wireframe as an option may need to be considered.

Current command line options re images are:
~~~
[ --viewall ] \
[ --imgsize=width,height ] 
[ --projection=(o)rtho|(p)ersp] \
[ --render | --preview[=throwntogether] ] \
~~~

If Wireframe is included, perhaps
~~~
[ --render[=(w)ireframe | --preview[=throwntogether] ] \
~~~

For the new stuff
`[--view=[(a)xis] [(s)cale] [(e)dges] [(c)crosshairs] ]`   <-- with commas, I just couldn't think of the right syntax

If doing that, perhaps consider adding `[(o)rtho] [(p)ersp] [all]` and deprecating the `--viewall` & `--projection` options??

[$50 Bounty](https://www.bountysource.com/issues/45350511-feature-request-command-line-image-export-option-to-include-view-features)

**Comment by MichaelAtOz** [comment]
I had a ligh-bulb-moment :bulb: changed my monitor to portrait.
![portrait](https://cloud.githubusercontent.com/assets/1972961/26572852/d67e1b08-455e-11e7-89bb-17454dccf9a0.PNG)
I got a bit bigger image, but I should have got the full 4K monitor, I want 
:zap: Mooore :zap:  /play bezos ha ha ha ha cue-spooky-music /play horror /play bezos 
(/ play is the markup emoji sound effect for those reading this via email, don't know it it works here)

I need to adjust my workstation...my neck is killing me
![not ready to share imag1715](https://cloud.githubusercontent.com/assets/1972961/26574058/49fec2ea-4563-11e7-9d3d-edd2e6c87853.jpg)
(yes it has been a cold almost winter day, cabin fever...)

**Comment by kintel** [comment]
I'll have a stab at the axis aspects of this.

**Comment by MichaelAtOz** [comment]
Thanks, I'll test when a snapshot is available.

**Comment by MichaelAtOz** [comment]
@kintel can this be merged into master so I can test via a snapshot. I'll do the doco then & local testing and see if I can help with the test suite tests. You can claim the bounty. 
(I'm going thru the bounty list as it's getting closer to the "No fees for 60 days!")

**Comment by kintel** [comment]
@MichaelAtOz This is really only hinging on whether there are more options that should be added to `--view` before merging, but I'd be happy to merge early and leave that as a future task.

**Comment by MichaelAtOz** [comment]
@kintel Merge, close, claim. I'll raise another issue to cover tidying up the other command line options as it isn't time sensitive & low-hanging for someone. 
Now I have my hand back I'll do some more T-shirt stuff, the new `--view` will be immediately useful.

**Comment by t-paul** [comment]
CI-Builds:
32-bit: https://circleci.com/gh/openscad/openscad/275#artifacts/containers/0
64-bit: https://circleci.com/gh/openscad/openscad/276#artifacts/containers/0

Those should be accessible without login... for some reason the "Artifacts" tab does not show up but it seems to still work via the direct link.
Maybe we can find a way to put that on the download page (as every new branch will have windows builds :smile:)

**Comment by MichaelAtOz** [comment]
Thanks. Anyone want to claim the bounty?
