### ISSUE TITLE
Releases, tags

### ISSUE THREAD

**Issue by hurzl** [openscad/openscad#2033]
The latest release was over two years age, the latest tag is more than one year old. I don't think anybody is still using these old versions. Please make a tag or release of a newer state of the program. Thanks. 
There are "2017.01.20" downloads, from what state are they?

**Comment by kintel** [comment]
2015.03-3 is the latest release - that's probably what the majority are ussing. Everything subsequent are development snapshots, which are quite stable, but with some functionality not finished.
See here for the TODO list for the next release - help is welcome: https://github.com/openscad/openscad/projects/1
