### ISSUE TITLE
Union of manifold STL files produces non-manifold output

### ISSUE THREAD

**Issue by Jip-Hop** [openscad/openscad#2034]
I've batch exported several cubes from Blender to STL and unioned them in OpenSCAD.
Each STL contains just a cube and is manifold.
OpenSCAD doesn't give any errors when rendering and exporting to STL.
However the result of the union is non-manifold according to blender and Meshlab.
```
union(){
    import("0019.stl");
    import("0018.stl");
    import("0017.stl");
    import("0016.stl");
    import("0015.stl");
    import("0014.stl");
    import("0013.stl");
    import("0012.stl");
    import("0011.stl");
    import("0010.stl");
    import("0009.stl");
    import("0008.stl");
    import("0007.stl");
    import("0006.stl");
    import("0005.stl");
    import("0004.stl");
    import("0003.stl");
    import("0002.stl");
    import("0001.stl");
}
```
I realize I could generate the cubes directly in OpenSCAD but I'm investigating a workflow to generate models suitable for 3D printing and ran into this issue. Reason I'm using OpenSCAD is union, hollowing with wall thickness and rounding edges. This doesn't work reliably in Blender. But what I miss from Blender is the ease of interactivity and dragging some objects around. Therefore I'm interested in OpenSCAD <-> Blender round-tripping.

[non-manifold-output.zip](https://github.com/openscad/openscad/files/1013919/non-manifold-output.zip)

**Comment by nophead** [comment]
A CSG union of manifolds does not necessarily produce a manifold. For example simply unioning two cubes with a shared edge produces a non-manifold result.

**Comment by Jip-Hop** [comment]
I wasn't aware of this restriction. I thought such issues would only arise with difference or intersection, not union. But now that I look at your example I get it.

I'm extruding 2D shapes and then OpenSCAD doesn't give a warning. These two pieces of code produce the same shape.
```
linear_extrude(height = 1){
    union(){
        square([1,1]);
        translate([1,1,0]){
            square([1,1]);
        }
    }
}
```
```
union(){
    cube([1,1,1]);
    translate([1,1,0]){
        cube([1,1,1]);
    }
}
```
But only in the second case OpenSCAD warns me about this issue: `WARNING: Object may not be a valid 2-manifold and may need repair! `.

Can you mention all the exceptional cases that could prevent manifold output when using the union modifier? I'm making 3D models consisting of just stacked cubes, based on some data. Cases like you mentioned, two cubes with a shared edge, will be present at times. I didn't program any checks to work around this limitation because I didn't realize it would cause issues.

<img width="638" alt="b8zbj" src="https://cloud.githubusercontent.com/assets/2871973/26246519/e986e98c-3c99-11e7-8c57-cadb59df2a59.png">

I've been having issues with this in Blender for a while ([posted on Stack Exchange](https://blender.stackexchange.com/questions/79023/union-partially-overlapping-cubes-without-boolean-modifier)) and thought I solved it by switching to OpenSCAD. But seems I'm going to have the same issues.

So far I've detected these cases:

- (partially) shared edge
<img width="594" alt="schermafbeelding 2017-05-19 om 13 54 10" src="https://cloud.githubusercontent.com/assets/2871973/26246717/d24e559c-3c9a-11e7-8655-803f3829d437.png">
<img width="586" alt="schermafbeelding 2017-05-19 om 13 53 58" src="https://cloud.githubusercontent.com/assets/2871973/26246718/d2870b08-3c9a-11e7-9a3e-ac1907aa300e.png">

- shared vertex
<img width="579" alt="schermafbeelding 2017-05-19 om 13 54 16" src="https://cloud.githubusercontent.com/assets/2871973/26246721/d6455aba-3c9a-11e7-9b59-78a33a57e983.png">


It's still a bit strange, because to me this looks perfectly 3D printable although it isn't a manifold mesh:
<img width="319" alt="schermafbeelding 2017-05-19 om 13 58 48" src="https://cloud.githubusercontent.com/assets/2871973/26247019/51a35382-3c9c-11e7-8f03-b54e5f200a16.png">

**Comment by RonaldoCMP** [comment]
I gess that the union of two cubes is a non-manifold only if their
intersection is a point or a straight line segment.

Em 19 de mai de 2017 9:08 AM, "Jip-Hop" <notifications@github.com> escreveu:

**Comment by nophead** [comment]
Also if they share part of a face. They must overlap with a finite volume, or not overlap at all. If they only share a vertex, edge or face the overlap is not a 3D shape and has no volume.

**Comment by Jip-Hop** [comment]
Thanks for the lesson. Clearly this isn't an issue with OpenSCAD then. In my program I now check for these cases and increase the scale by a tiny amount so the cubes actually intersect instead of just touch. I think it's working now.
