### ISSUE TITLE
Don't output "echo:" in .echo files

### ISSUE THREAD

**Issue by PRouzeau** [openscad/openscad#2036]
It is now possible to build files in batch mode with .echo extension containing echo() messages content.
That is useful to create specifications, BOM, lists, batches, etc. which can be selected with a variable
However, the "echo:" leading text is still part of the output, which is an annoyance. 
So, for output in files, it will be useful to removes these prefixes, giving a much cleaner file.

**Comment by t-paul** [comment]
There might be an actual output window at some point, but there are no plans on changing `echo()` and/or add formatting to console output.
