### ISSUE TITLE
OpenSCAD becomes nonresponsive during preview rendering

### ISSUE THREAD

**Issue by hexane360** [openscad/openscad#2048]
OpenSCAD's GUI stops responding completely while CSG is rendering a preview (F5). This is especially a problem when I use render() commands, because those greatly increase the preview rendering time.

I've observed this same root problem on Ubuntu 16.04 and Windows 10, although the symptoms of a nonresponsive window are slightly different between the OSes.

Full (F6) renders work completely fine.

**Comment by t-paul** [comment]
Duplicate of #1195.
