### ISSUE TITLE
Validation Failed: Current draw framebuffer is invalid

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#205]
On Mac OS X (only tested on 10.7.5 so far), this message shows up on startup:

OpenGL Program Validation results:
Validation Failed: Current draw framebuffer is invalid.

The message comes from GLView::initializeGL() in glview.cc:315 

It somehow seems that the framebuffer hasn't been made available yet by the system. Need to investigate if this is related to Qt or a recent Mac OS X version, or if we've just been lucky so far.
##

**Comment by kintel** [comment]
This looks like a Qt bug: https://bugreports.qt.io/browse/QTBUG-36802
Not sure when it will arrive in Qt - perhaps 5.4.1 ?

**Comment by kintel** [comment]
Note: This was fixed in Qt, but still shows up in OpenSCAD. Needs further investigation

**Comment by thehans** [comment]
@kintel Is this issue still relevant?

**Comment by kintel** [comment]
Looks fixed now.
