### ISSUE TITLE
GPL-3.0+ licensed files

### ISSUE THREAD

**Issue by ismail** [openscad/openscad#2059]
The following files are licensed under GPL-3.0+ which makes openscad license GPL-3.0+:

src/CGAL_Nef3_workaround.h
src/CGAL_workaround_Mark_bounded_volumes.h
src/convex_hull_3_bugfix.h

Is this intended?

**Comment by t-paul** [comment]
That makes the resulting binary GPL3, it does not change the license of the OpenSCAD source files.

**Comment by ismail** [comment]
Yes and that's my question. Is this intended? Because this effectively makes it GPL-3.0+ software (I am just asking from a license clarification perspective).

**Comment by t-paul** [comment]
It's a fact and not changeable as long as CGAL is used as geometry kernel.

**Comment by ismail** [comment]
Thanks, that answers my question.
