### ISSUE TITLE
openscad-nightly no longer available for 14.04LTS?

### ISSUE THREAD

**Issue by mwoliver** [openscad/openscad#2073]
It appears that openscad-nightly is no longer available for 14.04LTS, yet it's still listed on the downloads page. I sought clarification in the IRC channel, unsuccessfully, so am posting this here in hopes that someone can clarify this situation by either restoring the builds for 14.04LTS or removing "Ubuntu 14.04 LTS" from Development Snapshots on the Downloads page. Thank you!

**Comment by t-paul** [comment]
[OBS](https://build.opensuse.org/) does not accept builds for 14.04LTS anymore, so we had to delete those. Download page is updated.

**Comment by mwoliver** [comment]
That sucks, but thanks for the update and fixing the download page, much appreciated!
