### ISSUE TITLE
wrong height with minkowski function

### ISSUE THREAD

**Issue by Gurkengewuerz** [openscad/openscad#2075]
If you use the minkowski() function the height is also added.
I used the example code from the wiki. I expected a height of 1 but there was a height of 2.
```
minkowski()
{
  cube([10,10,1]);
  cylinder(r=2,h=1);
}
```
OpenSCAD Version 2015.03-2

If the function is right the wiki should be updated with a hint.

**Comment by nophead** [comment]
Minkowski is short for Minkowski sum, which means all dimensions get added. The resulting shape will be 14 x 14 x 2

**Comment by t-paul** [comment]
That's exactly what the [documentation](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#minkowski) also explains.

> (note that the outer dimensions of the box are now 10+2+2 = 14 units by 14 units by 2 units high as the heights of the objects are summed)
