### ISSUE TITLE
OSX won't build

### ISSUE THREAD

**Issue by Corona688** [openscad/openscad#2081]
The OSX build instructions on the GIT mainpage are incomplete and don't build openscad by themselves.

I was told to try ./scripts/release-common.sh after the dependencies were built, which does actually begin building openscad, then dies with this error:

src/SparkleAutoUpdater.mm:15:10: fatal error: 'Sparkle/Sparkle.h' file not found
#include <Sparkle/Sparkle.h>

How can one circumvent this error?

**Comment by kintel** [comment]
Did you try `qmake openscad.pro` followed by `make` ?

**Comment by Corona688** [comment]
You are correct, and feel a little silly for not realizing those were generic instructions instead of part of the linux instructions.  Thanks.
