### ISSUE TITLE
File Loading Warning in 2017 windows snapshots

### ISSUE THREAD

**Issue by runsun** [openscad/openscad#2103]
File loading warning in 2017 window snapshots:
(Windows 10 standard edition, 64 bit)

An error message about "Parameter Set" shows up in pink in the console for a sec then disappears. Supposed we are loading "c:/myOpenScad/file1.scad", the error message is : 

``
ERROR: Cannot open Parameter Set:'c:/myOpenScad/file1.json': c:/myOpenScad/file1.json: cannot open file 
Loaded design: c:/myOpenScad/file1.scad
``

That is, when loading `whatever.scad`, it complains it can't find `whatever.json`. 

This appears to be a non-lethal error and everything seems to proceed as usual. 

This error was introduced since OpenSCAD-2017.01.20-x86-64-Installer.exe 

Here are some snapshots I tested: 

2015.03-2 (latest release)
OpenSCAD-2015.10.17-x86-64-Installer.exe 
OpenSCAD-2016.01.26-x86-64-Installer.exe   
OpenSCAD-2016.02.01-x86-64-Installer.exe 
OpenSCAD-2016.02.09-x86-64-Installer.exe  
OpenSCAD-2016.04.06-x86-64-Installer.exe  
OpenSCAD-2016.05.12-x86-64-Installer.exe  
OpenSCAD-2016.07.20-x86-64-Installer.exe  
OpenSCAD-2016.09.18-x86-64-Installer.exe  
OpenSCAD-2016.10.04-x86-64-Installer.exe   
OpenSCAD-2016.11.11-x86-64-Installer.exe   
OpenSCAD-2017.01.20-x86-64-Installer.exe : Warning 
OpenSCAD-2017.08.30-x86-64-Installer.exe : Warning

**Comment by t-paul** [comment]
Can you please create separate issues for different errors?

**Comment by t-paul** [comment]
@kintel I guess that would need to go into the "next release" bucket?

**Comment by runsun** [comment]
As you guys would expect, no more warning after turning off the Customizer

**Comment by MichaelPFrey** [comment]
isn´t this issue a duplicate of #1927?

**Comment by kintel** [comment]
Closing as duplicate of #1927
