### ISSUE TITLE
Minkowski on non-convex objects produces geometry errors

### ISSUE THREAD

**Issue by a-ludi** [openscad/openscad#2108]
I ran across some error with minkowski with non-convex objects as can be seen in this [example](https://gist.github.com/a-ludi/76632913dbd221769f9eb8f9ee749edc). The error is produced by a difference of some object with a minkoski sum of multiple unified convex objects and a single convex object. In some cases I was able to observe errors even without the difference operation.

I am working with commit 959b9c4b712ed5db6938fc6ebdf2c1cb58df6c4f.

**Comment by kintel** [comment]
Closing as known behavior

**Comment by a-ludi** [comment]
@kintel Is there another issue on this topic where I can track the status?

**Comment by nophead** [comment]
It isn't an issue with OpenSCAD, it is a problem in your example and I posted the solution there.
