### ISSUE TITLE
Overriding variables on cmd-line doesn't work for USE'd modules

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#211]
From nophead 2012-08-22:

  Here is a simple example. I have global flag defined in conf.scad that I include in my main file. It is also included in a.scad and used in module a(). When I override the flag with -D flag=true it changes the value in test.scad but not in module a. The attached STL has both a sphere and a cube.

test.scad:

``` C
include <conf.scad>
use <a.scad>

echo("flag in test.scad",flag);

if(flag) sphere(10);
else cube(10);

translate([30, 0, 0])
    a();
```

a.scad:

``` C
include <conf.scad>

module a() {
    echo("flag in a:", flag);
    if(flag) sphere(10);
    else cube(10);
}
```

conf.scad:

``` C
flag = false;
```

**Comment by nophead** [comment]
So it appends the -D options to all used files. But that only sets it at file scope everywhere. When you set the same variable in a module it overrides it. When it is a $variable it has dynamic scope visible in the children of that module and the modules it calls.  Surly that should override file scope definition in used modules as well.
