### ISSUE TITLE
Is it possible to build openscad for Maemo5 (n900) 

### ISSUE THREAD

**Issue by chuckis** [openscad/openscad#2111]

**Comment by donbright** [comment]
yes it is possible

i estimate about 1000 hours of work.

100 hours to backport OpenCSG GL rendering

100 hours to backport OpenSCAD GL rendering

100 hours to completely re-think OpenSCAD UI and create a 'touch based' one for Maemo

100 hours to rip out QT gui linkage and write new GUI and get it integrated to OpenSCAD engine

400 hours to backport all dependency libraries to Maemo5

500 hours to fix unforseeable bugs

Oh.. those don't add up to 1000? Theres the first unforseeable bug.

**Comment by chuckis** [comment]
Thanks!
