### ISSUE TITLE
Return dimensions from resize() when 'auto' parameter is true

### ISSUE THREAD

**Issue by pomeroyb** [openscad/openscad#2115]
I currently am writing a script where I know almost nothing about the size of the model generated. The script is a text generator where the user is allowed to select the font, font size (letter height), and text. I am setting the letter height using the 'resize()' function with the 'auto' parameter
```
resize([0,textHeight,0], auto=true)
```
I need to know how long the the resized text is in the X direction. I am aware of the limitations of needing to run a render in order to know the locations of points, but in this case the render has already occurred to calculate the 'resize()'. Is it possible to return these lengths as vector or the like?

**Comment by kintel** [comment]
We currently cannot. This issue is covered in #301 and #2076.
Closing as duplicate
