### ISSUE TITLE
Syntax errors don't display the file show an incorrect line number

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#214]
A syntax error message gives just a line number but it is not the line number in the current file. It includes all the lines in included files, so is no use for locating the error. Indeed the error might be in one of the included files, so it needs to display a file name in that case as well.

With a large project finding where the syntax error is is like trying to find a needle in a hay stack. One has to create a deliberate error and see if the reported number is less and them move it around to home in.

**Comment by kintel** [comment]
Fixed by #1637
