### ISSUE TITLE
Import paths not relative to the file with the import.

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#217]
They seem to be relative to the top level file so one cannot use a module with a relative import from more than one directory.

**Comment by DanNixon** [comment]
Has this issue reappeared?

I'm having what seems to be exactly this issue with version 2015.03-1: I import a DXF relative to a file in a library and cannot use that module in anything other than the directory that contains the module.

**Comment by kintel** [comment]
@DanNixon It should work - could you provide an example?

**Comment by DanNixon** [comment]
I have the directory structure:
```
.
├── DXF
│   └── HDDs
│       ├── HDD25_Bottom.dxf
│       ├── HDD25_Side.dxf
│       ├── HDD35_Bottom.dxf
│       └── HDD35_Side.dxf
└── SCAD
    ├── HDD25.scad
    └── HDD35.scad
```

Where the `SCAD` folder is added as a library in `.local/share/OpenSCAD/libraries`.

`HDD25.scad` and `HDD35.scad` contain modules that import the shown DXF's using a relative path, when I have a file (`test.scad`) in the `SCAD` directory as follows I get what I expect:

```
include <SCAD/HDD25.scad>;
HDD25();
```

If I place `test.scad` anywhere else I get:

```
WARNING: Can't open DXF file '/home/dan/../DXF/HDDs/HDD25_Bottom.dxf'. 
WARNING: Can't open DXF file '/home/dan/../DXF/HDDs/HDD25_Side.dxf'. 
```

[This](https://github.com/DanNixon/CAD-Library/blob/master/SCAD/HDD25.scad) is one of the modules causing the issue.

**Comment by kintel** [comment]
You have to use ```use <SCAD/HDD25.scad>``` rather than ```include...```. When using ```include```, you use the context of where the included module lives. That's a separate issue and is not likely to be improved until we redesign the module inclusion mechanism.

**Comment by DanNixon** [comment]
@kintel Ah thanks, that is working for me now.
