### ISSUE TITLE
Prevent HTML interpretation in Customizer description

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#2184]
Some Qt elements support limited HTML display, this should not exposed to the user as side-effect of how the UI is implemented internally as that might make changes to UI very difficult later on.

**Comment by MichaelPFrey** [comment]
It has now been off for almost have a year and no one asked for getting HTML interpretation in the customizer back.
In therms of thingiverse compatibility, encouraging/supporting the use of HTML in costumizer description would be a slippery slope.
Turning it off was/is the right call.
It having been enabled was presumably unknowingly,
