### ISSUE TITLE
[depends] Qt build broken with latest Xcode

### ISSUE THREAD

**Issue by droomurray** [openscad/openscad#2188]
qcocoahelpers.mm:658:39: error: use of undeclared identifier 'InvalidContext'
    require_action(inContext != NULL, InvalidContext, err = paramErr);
                                      ^
qcocoahelpers.mm:659:38: error: use of undeclared identifier 'InvalidBounds'
    require_action(inBounds != NULL, InvalidBounds, err = paramErr);
                                     ^
qcocoahelpers.mm:660:37: error: use of undeclared identifier 'InvalidImage'
    require_action(inImage != NULL, InvalidImage, err = paramErr);

:-( 

Upstream issues:
[Qt 5.6](https://bugreports.qt.io/browse/QTBUG-63401)
[Qt 5.9](https://bugreports.qt.io/browse/QTBUG-62266)

**Comment by kintel** [comment]
Looks like it's fixed in Qt-5.9.2
