### ISSUE TITLE
Font list example is incorrect

### ISSUE THREAD

**Issue by Eibwen** [openscad/openscad#2212]
This is a minor bug, with an easy fix, and I'd be happy to fix it but thought I'd create an issue before attempting to fix it in case I can get guidance before sending a pull request.

In version 2015.03-2 at least

When you pull up the Font List from the Help menu
At the top it has

> Example:
>    text(t = "OpenSCAD", font = "DejaVu Sans");
>    text(t = "OpenSCAD, font = "Liberation Sans:style=Italic");

But if you type that into the editor and hit preview, nothing shows up.

It is due to the first parameter not being `t` but being `text`

So the example on the Font List should be updated to be either
```
text("OpenSCAD", font = "DejaVu Sans");
text("OpenSCAD, font = "Liberation Sans:style=Italic");
```
or
```
text(text = "OpenSCAD", font = "DejaVu Sans");
text(text = "OpenSCAD, font = "Liberation Sans:style=Italic");
```

The code file is here:
https://github.com/openscad/openscad/blob/master/src/FontListDialog.ui
but its also in all of the localized text packages, so not sure how that is handled

**Comment by kintel** [comment]
A fix would be appreciated. It should probably be updated also in the localized packages.
Anything checked into git are human editable source files.
