### ISSUE TITLE
"Self assignment" not working

### ISSUE THREAD

**Issue by speendo** [openscad/openscad#2223]
This is not working:

    a = "someValue";
    a = a;
    echo(a); // undef
    // WARNING: Ignoring unknown variable 'a'.

Why?

**Comment by t-paul** [comment]
See FAQ: [Why am I getting an error when writing a = a + 1?](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_am_I_getting_an_error_when_writing_a_=_a_+_1?)

**Comment by speendo** [comment]
I understand. Sorry and thanks for pointing that out.
