### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by digitalentity** [openscad/openscad#2225]
Latest release is 4 years old now. Any plans to make a new one? Especially interested in x86 (32 and 64-bit) build.

**Comment by t-paul** [comment]
Latest release is from mid 2015 which is too long but not 4 years. It's obviously known that a new release is much needed, but things are moving slowly with limited developer resources.

You can try the [development snapshots](http://www.openscad.org/downloads.html#snapshots) to see the changes that were made up to now.

In case you refer to the generic Linux packages, those are not recommended, it's always advisable to try the version (hopefully) provided by the distribution. There is an experimental [AppImage version for 2015.03 for Linux-64bit](https://download.opensuse.org/repositories/home:/t-paul/AppImage/OpenSCAD-Release-latest-x86_64.AppImage), the Linux-32bit build is currently not working and is waiting for help to fix that.
