### ISSUE TITLE
Clarify the canonical repo for MCAD?

### ISSUE THREAD

**Issue by lostapathy** [openscad/openscad#2257]
Discovered this while working on #2256 

It's tricky to figure out which MCAD repo is supposed to be the canonical repo.  I assume it's now [openscad/MCAD](https://github.com/openscad/MCAD), but that repo shows it's forked from [SolidCode/MCAD](https://github.com/SolidCode/MCAD).  Our [README](https://github.com/openscad/openscad/blob/master/README.md) links to a [reprap page](http://reprap.org/wiki/MCAD) that links back to the [SolidCode/MCAD](https://github.com/SolidCode/MCAD) repo.

If [openscad/MCAD](https://github.com/openscad/MCAD) is current canonical source, a project owner here should contact [GitHub Support](https://github.com/contact) and they can update the "forked from" relationships so that this repo shows as the current root and resolves this confusion.

I can also follow up and update both the reprap wiki and our README to make everything match.

**Comment by kintel** [comment]
Github support has been contacted.

**Comment by kintel** [comment]
If you'd take on updating the docs, that would be awesome!

**Comment by t-paul** [comment]
via #2265.
