### ISSUE TITLE
Preview with difference() does not match render

### ISSUE THREAD

**Issue by matthew-viglione** [openscad/openscad#2262]
I am using a difference() to create a void in the red layer shown below. On "Preview" I get this strange crosshatching at an angle (1st image), and nothing when looking straight on (2nd image). When I render, the voids are created as expected, although they are hard to see (3rd image). In this case, the coloring available in the preview is very important to be able to see the different features and the preview isn't being correctly calculated. 

I have seen similar issues throughout the issues section which were resolved by updating OpenCSG from 1.4.0 to 1.4.2. I was at 1.4.0 when I first observed this issue, and have since updated to 1.4.2 but the issue remains. When running `./scripts/check-dependencies.sh` I do get these warnings, which lead me to believe this may be somehow related (maybe I didn't install OpenCSG correctly): 

`Warning: you have a copy of opencsg.h under /usr/local/include`
`Warning: you have a copy of libopencsg under /usr/local/lib`
`Please verify these local copies don't conflict with the system`

The code used to generate these pieces is included below, followed by my Library Info. I have tried both the installation from apt-get, as well as building from source (which is my current installation, built yesterday). 

![image](https://user-images.githubusercontent.com/19675897/34841929-1d577794-f6c7-11e7-930f-cd42917d0a24.png)

![image](https://user-images.githubusercontent.com/19675897/34841960-400bdb36-f6c7-11e7-86fb-fa98c7d51e34.png)

![image](https://user-images.githubusercontent.com/19675897/34842059-91fdceae-f6c7-11e7-966d-09c58f4a2577.png)

     module spring(len, height, arm_width, arm_len, stub_len, c) {
       color(c){
          total_arm_width = (len - arm_len)/2;              // total width of all three parts of arm connection (stub-arm-stub)`
          stub_width = (total_arm_width - arm_width)/2;     // width of stubs  (x)

          difference() {
               // full membrane
               translate ([-len/2, -len/2, 0]) cube([len, len, height], center=false);

               // center piece
               translate ([-arm_len/2, -arm_len/2, 0]) cube([arm_len, arm_len, height], center=false);

               // left arm inner (towards square)
               translate ([-arm_len/2-stub_width, -arm_len/2, 0]) cube([stub_width, stub_len, height], center=false);

               // left arm main
               translate ([-arm_len/2-stub_width-arm_width, -arm_len/2, 0]) cube([arm_width, arm_len, height], center=false);

               // left arm outer (away from square)
               translate ([-len/2, arm_len/2 - stub_len, 0]) cube([stub_width, stub_len, height], center=false);

               // right arm inner
               translate ([arm_len/2, arm_len/2 - stub_len, 0]) cube([stub_width, stub_len, height], center=false);

               // right arm main
               translate ([arm_len/2+stub_width, -arm_len/2, 0]) cube([arm_width, arm_len, height], center=false);

               // right arm outer
               translate ([arm_len/2 + stub_width + arm_width, -arm_len/2, 0]) cube([stub_width, stub_len, height], center=false);
          }
       }
     }

OpenSCAD Version: 2018.01.10
System information: Linux 4.13.0-26-generic #29~16.04.2-Ubuntu SMP Tue Jan 9 22:00:44 UTC 2018 x86_64 Ubuntu 16.04.3 LTS 4 CPUs 7.68 GB RAM
Compiler: GCC "5.4.0 20160609" 64bit
Boost version: 1_58
Eigen version: 3.2.92
CGAL version, kernels: 4.7, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.6.2
QScintilla version: 2.10.2
MingW build: No
GLib version: 2.48.2
libzip version: 1.0.1
Application Path: /usr/local/bin
Documents Path: /home/matthew/.local/share
Resource Path: /usr/local/share/openscad
User Library Path: /home/matthew/.local/share/OpenSCAD/libraries
User Config Path: /home/matthew/.config/OpenSCAD
Backup Path: /home/matthew/.local/share/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
/home/matthew/.local/share/OpenSCAD/libraries
/usr/local/share/openscad/libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
GLEW version: 1.13.0
OpenGL Version: 3.0 Mesa 17.2.4
GL Renderer: Mesa DRI Intel(R) Sandybridge Desktop 
GL Vendor: Intel Open Source Technology Center
RGBA(8880), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8880), depth(0), stencil(0)

GL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_draw_buffers_blend
GL_AMD_seamless_cubemap_per_texture
GL_AMD_shader_trinary_minmax
GL_ANGLE_texture_compression_dxt3
GL_ANGLE_texture_compression_dxt5
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compressed_texture_pixel_storage
GL_ARB_conditional_render_inverted
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_objects
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sync
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_draw_buffers
GL_ATI_separate_stencil
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_copy_texture
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_gpu_program_parameters
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_subtexture
GL_EXT_texture
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_IBM_multimode_draw_arrays
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_INGR_blend_func_separate
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_robustness
GL_MESA_pack_invert
GL_MESA_shader_integer_functions
GL_MESA_texture_signed_rgba
GL_MESA_window_pos
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_light_max_exponent
GL_NV_packed_depth_stencil
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_env_combine4
GL_NV_texture_rectangle
GL_OES_EGL_image
GL_OES_read_format
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_border_clamp
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays

**Comment by thehans** [comment]
This is called z-fighting and is a known behavior of OpenCSG.  The solution is that your negative shapes should not share faces with the positive shape, make them extend slightly past the face instead.

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_are_those_strange_flickering_artifacts_in_the_preview?

And color information is only displayed during preview, not CGAL.  This is intended behavior.

**Comment by matthew-viglione** [comment]
I did not see this when looking through the documentation. Thanks for the help!
