### ISSUE TITLE
Feature: Load other formats

### ISSUE THREAD

**Issue by simon1tan** [openscad/openscad#2270]
It would be nice to be able to load other file formats(STL, DWG, etc) and be able to add/modify. I know modifying might be tough but even being able to add would be great.

**Comment by justbuchanan** [comment]
OpenSCAD does allow you to import STL files (and other formats), although it doesn't support DWG. See the manual entry for `import` here: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/STL_Import_and_Export. Does that cover what you're trying to do?

**Comment by kintel** [comment]
You can also modify imported objects:
```
difference() {
  import("myfile.stl");
  cube(100);
}
```
