### ISSUE TITLE
difference() operation behaves unexpected

### ISSUE THREAD

**Issue by crazyimp** [openscad/openscad#2289]
The difference() operation yields different results if the 3. and 4. parameter object are swapped (see clipA and clipB in the code). The last argument (4. argument in this case) is ignored in the rendering process. In preview, everything looks as expected. Exchanged the .stl file with some solid, everything works fine, so it's likely related to the stl import (or the stl file).

Steps to reproduce:
1. use the code below,
2. download the TO-92-2.stl file mentioned in the code,
3. preview the objects, it should look like ![preview](https://user-images.githubusercontent.com/9559308/36061762-35a58c96-0e5f-11e8-8782-d94182978fbc.png)
4. render the objects, it will now look like ![rendered](https://user-images.githubusercontent.com/9559308/36061763-35be0cc6-0e5f-11e8-8e7f-1310e343e0fb.png)

Expected result:
No change between both objects and no such difference between preview and render - OR - an error message that something is wrong with the .stl file.

Code:
```
$fa = 0.1;
$fs = 0.1;
$pipe_diameter=21;
module to92(){
    // from https://github.com/FreeCAD/FreeCAD-library/raw/master/Electrical%20Parts/electronic-components/transistors/TO-92-2.stl
    import("TO-92-2.stl");
}
module to92_on_pcb(){
    union(){
        translate([0,0,7.5])to92();
        // create pcb
        translate([0,0.7,0])cube([5,0.8,20], center=true);
    }
}
module pipe(){
    cylinder(d=$pipe_diameter, h=50, center=true);
}
module clipA(){
    difference(){
        translate([0,-7,10])cylinder(d=30, h=20, center=true);
        pipe();
        translate([0,-10,0])cube([6,3,50], center=true);
        translate([0,-$pipe_diameter/2-1,0])scale(1.05)to92_on_pcb();
    }
}
module clipB(){
    difference(){
        translate([0,-7,10])cylinder(d=30, h=20, center=true);
        pipe();
        translate([0,-$pipe_diameter/2-1,0])scale(1.05)to92_on_pcb();
        translate([0,-10,0])cube([6,3,50], center=true);
    }
}
// clipA and clipB are the same, except the last two lines in the difference() call are swapped.
// preview of both looks the same, the rendering does not.
// difference to clipA: to92 and the groove are swapped
clipA();
translate([40,0,0])clipB();
```

**Comment by kintel** [comment]
This is most likely due to the imported STL file not being a proper mesh. It looks like a collection of intersected objects. To do this you'd probably have to merge the objects in FreeCAD, or model them separately and union them together in OpenSCAD.
