### ISSUE TITLE
OpenCSG problems with gallium drivers

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#230]
Several new linux distros are using 'gallium' 'llvmpipe' video card drivers instead of drivers that previous releases used, which is causing some OpenCSG problems, especially on objects like Example 8. I don't have a detailed log/test result yet but I posted an image below. Here is a link where others discuss gallium issues in ubuntu 12

http://askubuntu.com/questions/183305/graphics-driver-being-reported-as-gallium-0-4-on-llvmpipe-llvm-0x300-instead-o

The 'stopgap' i use is to set software rendering

```
export GALLIUM_DRIVER=softpipe
export DRAW_USE_LLVM=n
export LIBGL_ALWAYS_SOFTWARE=1
openscad
```

The problem with this  is that using software rendering is just massively slow, approximately 0.3 FPS (about 3 seconds to update the frame) on drawings like Example008.scad

![problem](https://f.cloud.github.com/assets/896858/28174/f373f29c-4bcf-11e2-9e9c-78535b646d00.png)

Note that Goldfeather and SCS rendering both have issues with Example008.
##

**Comment by kintel** [comment]
This could probably need a refresher. What's the current state of Linux rendering?

**Comment by t-paul** [comment]
I have not seen those issue for quite some time.
