### ISSUE TITLE
Crash compiling example006: builtin_textureGradOffset: Process /usr/bin/openscad was killed by signal 6

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#231]
Hi,
I've build packages for Fedora and we have first bug report from Automatic Bug Reporting Tool: https://bugzilla.redhat.com/show_bug.cgi?id=889785 (look at the attachments)

If I test it on my machine, I can render [F6] the example, but cannot compile [F5] it. Openscad doesn't crash, but it hangs up after CSG Products normalization.

The build is 1 commit behind master (b04734cbf5) and the last commit seems Linux irelevant.

I can reproduce the hang at development version downloadable from openscad.org.

Thanks a lot for help.

**Comment by kintel** [comment]
Closing as it was a Mesa bug
