### ISSUE TITLE
Feature request: Break-away console and editor

### ISSUE THREAD

**Issue by korpx** [openscad/openscad#233]
It would be useful with an option to undock/break away the console and editor from the main window to allow for a dynamic layout. Nice in multi monitor setups for example, or on small screens where you want the console available but not to take space away from the render view.

**Comment by ede1998** [comment]
In case anyone else stumbles upon this: At least for me, break-away to extra windows was disabled by default and had to be enabled in `Preferences>Advanced>User Interface>Enable undocking of Editor and Console to separate windows`. Took me a while to figure out because I missed it in the settings.

**Comment by gtoal** [comment]
It took me a little time to work out how to take advantage of the feature described above, so I thought it only right to share the result.  Users of Emacs with the above might want to add this to their .emacs file to have emacs automatically save changes, so that OpenSCAD will also update the display automatically.  (There may be better ways of doing this, I'm a novice at emacs coding. Getting this much to work was a bit of trial and error...)

```
(auto-save-visited-mode +1)
(setq auto-save-visited-interval 1)
(setq auto-save-visited-predicate (lambda () (and (eq major-mode 'org-mode)
                                                  (when (string-equal (file-name-extension (buffer-file-name)) "scad")))))
```

**Comment by t-paul** [comment]
@gtoal how does that relate to https://github.com/openscad/emacs-scad-mode ? Would it make sense to add it to the readme there?

**Comment by gtoal** [comment]
> [@gtoal](https://github.com/gtoal) how does that relate to https://github.com/openscad/emacs-scad-mode ? Would it make sense to add it to the readme there?

I hadn't seen that before, looks useful (and it led me on a little sidetrack just now to where I found out about 'flymake' and 'flycheck' for the first time, which will be really useful for a different non-scad-related project I'm working on, so thanks for that!).

On an initial reading it looks like emacs scad mode takes a different approach, so I wouldn't add the code above to that package, but I don't see any reason why you shouldn't quote it in the README if you want to.
