### ISSUE TITLE
not able to run openscad on arch linux.

### ISSUE THREAD

**Issue by prrraveen** [openscad/openscad#2331]
I get the following error `openscad: error while loading shared libraries: libmpfr.so.6: cannot open shared object file: No such file or directory`

I tried installing it from AUR but the build fails. Anybody else had the same issue.

**Comment by t-paul** [comment]
Please report this in the Arch issue tracker, without additional info that sounds like a distribution specific issue.

Maybe check if you are running the binary you intend to run (e.g. using full path), maybe PATH points to some older installation.
