### ISSUE TITLE
Problem with #include

### ISSUE THREAD

**Issue by NateTG** [openscad/openscad#2334]
It seems like #include doesn't like lists in files.

version 2018.01.22
Debian 9.3

[testa.scad.txt](https://github.com/openscad/openscad/files/1791444/testa.scad.txt)
[testb.scad.txt](https://github.com/openscad/openscad/files/1791445/testb.scad.txt)

Attempting to run testb gives the error:

ERROR: Parser error in file "/home/nate/Desktop/scad/openscaddsna/testa.scad", line 1: syntax error 
ERROR: Compilation failed!

**Comment by MichaelAtOz** [comment]
In 2015.03 too.

**Comment by NateTG** [comment]
It's been a *long* time since I've done anything with C.

I'd be happy for that kind of stuff to be a syntax error.

**Comment by t-paul** [comment]
Yes, `#` is only defined as operator in front of a module instantiation.

**Comment by MichaelAtOz** [comment]
I think he means the syntax error is correct.
OpenSCAD has always been troubled reporting the file/line number of errors.
I think there were changes to improve that, this could be a corner case bug. ?

**Comment by t-paul** [comment]
There is no `#include`. It's 2 things, a `#` debug-operator and `include<>` which is executed. The resulting text which is parsed is:
```
#test=[1];
```
If you put `cube()` in the included file, it works.

If you want to include that `test=[1];` just remove the `#` and it works.

**Comment by t-paul** [comment]
Hmm, not sure about the error message though. If it's in one file, the parse error is at the `[` char currently.
