### ISSUE TITLE
function.h and module.h improper nullptr test

### ISSUE THREAD

**Issue by coldelectrons** [openscad/openscad#2335]
Both files have a method `is_enabled`:
`virtual bool is_enabled() const { return (feature == nullptr) || feature->is_enabled(); }`

This could return true if `feature` is a `nullptr`, which does not strike me as proper.  

It could also attempt to call the `feature->is_enabled()` when `feature` is `nullptr` leading to Undefined Behaviour.

If I understand the intent correctly, it should be rewritten as:
```
    if (feature == nullptr) {
      return false;
    } else {
      return feature->is_enabled();
    }
```

Or more tersely:
```
    return (feature) ? feature->is_enabled() : false;
```

**Comment by MichaelPFrey** [comment]
I have a rough idea of what is going on: "feature" actually means experimental feature, which means feature that are work in progress and that can be enabled over the preference dialog by the user.

Only experimental functions and modules to have this feature attribute.
Functions and modules that do not have a feature attribute (meaning `feature == nullptr`), are stable and  always enabled (which should be in the majority).

So the check for nullptr
``(feature == nullptr)``
means something "if it is not an experimental feature, it is always enabled". The next check is only executed when, when it is an experimental feature (` || `is short circuit or):
``feature->is_enabled()``
So, only if it is an experimental function/module, it is checked if it the experimental feature is enabled.

Again: If it those not have the feature attribute (read experimental feature), it is stable and thus always enabled.

Yes, it looks strange out of context. If the attribute  `feature`  would be called  `experimental_feature` it would read more natural:
``virtual bool is_enabled() const { return (! experimental_feature) || experimental_feature->is_enabled(); }``
But it would not be a good idea to change that variable name, as some features are work in progress in a feature branch.
