### ISSUE TITLE
[Feature Request] nested /* ... */ comments

### ISSUE THREAD

**Issue by NateTG** [openscad/openscad#2349]
Would make the /*  ... */ style comments a bit easier to use.

**Comment by thehans** [comment]
I don't believe I've seen *any* programming languages treat block comments in this way, and would make OpenSCAD an outlier of abnormal comment handling as opposed to the way people are accustomed to.

**Comment by NateTG** [comment]
I guess I should just use the editor for block commenting.

**Comment by MichaelAtOz** [comment]
@NateTG I sympathise, that hits me so often, it's a wonder it has not been fixed over the decades in those other languages, but I agree with @thehans. (suggest closing this?)
When my new keypad arrives, I'm going to have '/*' & '*/' keys...

**Comment by MichaelAtOz** [comment]
Markup removed the asterisks...`/*` & `*/` keys.
