### ISSUE TITLE
Baidu engine detects "Win32.Trojan.WisdomEyes.16070401." in OpenSCAD-2015.03-2-x86-64-Installer.exe

### ISSUE THREAD

**Issue by HaraldMuehlhoffCC** [openscad/openscad#2358]
Firstly thanks for a great tool! So far I've only installed OpenSCAD on a Hyper-V VM because the Baidu engine on virustotal.com detected the "Win32.Trojan.WisdomEyes.16070401." in OpenSCAD-2015.03-2-x86-64-Installer.exe download from http://www.openscad.org/downloads.html. My local scanners - Windows Defender on Windows 10 & Malwarebytes - didn't detect anything.

I tried to submit a false positive report to Baidu but the web interface didn't work (Edge & Chrome) (http://antivirus.baidu.com/en/submit-url.php).

Link to the Virustotal scan: https://www.virustotal.com/#/file/316b95c1fc029bdf493b752d9917cd895dbfb5ddf9a4561b27efb3728d3d74e4/detection

PS: I wonder why the Virustotal SandBox (Behavior tab) finds a System.dll file written to. 

```
Files written
C:\DOCUME~1\<USER>~1\LOCALS~1\Temp\nsb2.tmp\System.dll
```

**Comment by kintel** [comment]
I deem this a false positive. Baidu will eventually get it right.
I guess that the System.dll is a side-effect of the scanner itself.

**Comment by choller** [comment]
System.dll is part of your installer. From what I understand it is a generic NSIS plugin to run arbitrary code during installation. Do you use this plugin to do anything during installation?

**Comment by kintel** [comment]
@choller Thx, good to know. I haven't looked too closely at the Windows installer, but that's all part of our sources: https://github.com/openscad/openscad/blob/master/scripts/installer.nsi

We do write to the registry. Perhaps some virus scanners don't like that.

**Comment by donbright** [comment]
NSIS itself might be a problem. https://bugzilla.mozilla.org/show_bug.cgi?id=709738

https://www.scmagazine.com/microsoft-malicious-nsis-installers-used-to-disperse-ransomware-evolve-and-grow-in-number/article/644849/

we really should be using more modern system... and signing our code somehow

**Comment by donbright** [comment]
step 1 eval alternatives
step 2 implement experimental x-build
step 3 test
step4 integrate w build scripts

- [ ]

**Comment by t-paul** [comment]
Ok, closing this as it never was an actual infection and leaving that open for changing the installer looks confusing. I'll move the suggestion to a new issue with a clear topic line.
