### ISSUE TITLE
Possible Improvement using CGAL "Polygon Mesh Processing" for booleans and more?

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#2360]
OpenSCAD is currently using CGAL Nef Polyhedra for boolean operations, which can be quite slow for complex models.

I was looking at other options within CGAL and I found this section about mesh "corefinement" and booleans:
https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#Coref_section

It sounds like this could be much faster than Nef processing, though maybe not as robust in some ways?
Although even if not intrinsically as robust, this also looks like it may be capable of better detecting and even possibly fixing mesh errors with the various functions provided (the [Hole Filling](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPHoleFilling) section looks pretty impressive).

According to the package [overview page](https://doc.cgal.org/latest/Manual/packages.html#PkgPolygonMeshProcessingSummary), this was introduced in CGAL 4.7.  
OpenSCAD currently only requires CGAL 3.6, so this would be a large bump to our required version if this change were made.

**Comment by kintel** [comment]
I did some early experimentation with this back in 2013 (see https://github.com/openscad/openscad/tree/epec-fast). The corefinement stuff appears to be slightly less robust than Nef3 polyhedrons, but it feels like something we may be able to work around.
The CGAL requirement was a bit of a showstopper back then, but this has been available for a while now, so perhaps time to give it another shot.

**Comment by MichaelAtOz** [comment]
How about 4.8? [Multithreading???](https://doc.cgal.org/4.8/Manual/devman_multithreading.html)

**Comment by kintel** [comment]
I haven't looked into whether corefinement is thread-safe, but since they use the same datatypes as Nef3 polyhedrons, my guess is that the same limitations apply.

**Comment by thehans** [comment]
@kintel Was the epec-fast branch in a state that built and ran at any point or was it still WIP last time you left it?

I checked it out for a quick test but the build fails looking for `Dock.h`.  

Do you have some recommendations for next steps to move this forward?  I could give it a shot rebasing the branch to get it up to date with master?

**Comment by kintel** [comment]
I cannot remember how I left it. It was really just a quick and dirty test, without any performance optimizations as I converted everything back and forth to Nef3 polyhedrons. My goal was to determine the CSG operation stability implications of using corefinement, but I had too many other things on my list..
The large missing piece to integrate properly is to better hide the interface to the underlying geometry engine classes. One of the challenges there is that caching may need a bit of a rewrite. See #1399 for an early external attempt at doing this.

**Comment by dpellegr** [comment]
I think that the time is mature for this.

I used PyMesh to manipulate a pretty complex model which was failing/taking forever in OpenSCAD.
PyMesh allows to seamlessly switch between various rendering engines such as corefinement, nef3, igl, carve, cork.

I really pushed them with A LOT of complex differences operation. In my experience corefinement is now not only the fastest (by a couple of order of magnitude compared to nef3) but also the most stable and reliable.

**Comment by ochafik** [comment]
I believe I've found a good balance of speed (10x to 100x in my little [grid benchmarks](https://gist.github.com/ochafik/2db96400e3c1f73558fcede990b8a355)) and robustness 
(avoiding cases that break Polygon Mesh Processing and reverting to Nefs transparently) in https://github.com/openscad/openscad/pull/3641
