### ISSUE TITLE
Feature request: Font list on console

### ISSUE THREAD

**Issue by ospalh** [openscad/openscad#2369]
I would like a way for OpenSCAD to list the fonts when invoked from the command line. Maybe `openscad --fontlist`.
Recently, i wanted to change the font used in a project and then render it without the GUI, but, without X running on the Linux machine at the time, couldn’t get to the Help→Font List window and the exact name of the font and style.
Version used: 2015.03-3, on Fedora Linux, installed via package manager.

**Comment by t-paul** [comment]
It's just using the system fonts managed by `fontconfig`. You can list all fonts with `fc-list`

**Comment by ospalh** [comment]
Thanks.
But it’s not in the manual page.

**Comment by t-paul** [comment]
Added note to wiki, this produces similar list as the GUI shows
```
fc-list -f "%-60{{%{family[0]}%{:style[0]=}}}%{file}\n" | sort
```
