### ISSUE TITLE
View/View_All infiite loop with import() [with DXF at least]

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2382]
Windows, 2018.04.01/64, does not happen with 2015.03-2.

`import(file = "example009.dxf", layer = "unknown");`

!!! SAVE ANY WORK !!!
Click the View All icon.

Interestingly it manages to use most of 2 CPU cores, on my 2 core system, haven't tried on my 8 core yet...

**Comment by kintel** [comment]
This sounds like a duplicate of #2062

**Comment by MichaelAtOz** [comment]
Yep, sorry I did search a bit...
Closing.
