### ISSUE TITLE
Ignore: I'm tracing bountysource flow

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2389]
(oops keyboard battery low)

**Comment by MichaelAtOz** [comment]
@kintel 
It look like they [fixed it](https://github.com/bountysource/core/issues/1096).
![boutys work](https://user-images.githubusercontent.com/1972961/39404330-c5b16860-4b80-11e8-9ed7-acb9697ccb3f.JPG)

Can you check the plugin at [bountysource/tools](https://www.bountysource.com/tools), or via your icon at top/right if the link doesn't get you there.
![bounty plugin](https://user-images.githubusercontent.com/1972961/39403834-11b95a62-4b75-11e8-9e71-c72496ab00b1.JPG)

It isn't clear, but I suspect you should see the install button then authorise, if not try unclicking all the options, logout of both bounty source & github, then back in and see what it looks like then.

**Comment by kintel** [comment]
@MichaelAtOz It was showing up as "locked". I unlocked it and it should (hopefully) work again now.

**Comment by MichaelAtOz** [comment]
It even went back, and eg did this issue, see OP.

I did a bounty cycle for #2284 and it works.
It left the message below, seems incomplete, but maybe intentional in case another claimant sees it??
`Did you help close this issue? Go claim the $10 bounty on Bountysource.`
Small wins...

**Comment by MichaelAtOz** [comment]
Closing
