### ISSUE TITLE
Debian package for stretch (Devuan Ascii) lack of an icon

### ISSUE THREAD

**Issue by onekk** [openscad/openscad#2397]
The nightly build lacks of an icon in the view selection

see the image below.

![2018-05-21-120659_1920x1080_scrot](https://user-images.githubusercontent.com/7129964/40302895-f7fb8f2c-5cf0-11e8-9564-17d40be8d642.png)

I have put also the info screen.

Feel free to ask some other details, if needed.

Thanks for your work and Best Regards

Carlo D.

**Comment by t-paul** [comment]
Oops, thanks, that got lost in some clean-up earlier. Should be back after the build server picked up the change...
