### ISSUE TITLE
MinGW Runtime Assertion

### ISSUE THREAD

**Issue by nyponen** [openscad/openscad#2402]
I got this using OpenSCAD version 2018.04.06 (git 64673e1) on Windows 10. I was updating a comment line before an assignment statement that was used by the Customizer. I haven't been able to recreate it.

![assert](https://user-images.githubusercontent.com/17462467/40521066-896ecaac-5f7e-11e8-8251-874731e53748.jpg)

**Comment by t-paul** [comment]
Found one crash case when using [[]] in comments. The error message does not give enough information to verify any fix unfortunately, so this issue will be closed once that fix is merged.

**Comment by nyponen** [comment]
I did have [[]] in the comment, so that was probably the problem.
