### ISSUE TITLE
lists.openscad.org is down EDIT: Everythings is now UP

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2407]
Is this hosted by someone, or a mailmonkey etc on 'OpenSCAD' managed servers, or something else?

**Comment by MichaelAtOz** [comment]
So is openscad.org & forum.openscad.org.
Did someone pay the DNS registry bill?

**Comment by MichaelAtOz** [comment]
Not that, Registry Expiry Date | 2019-08-04T10:11:22Z.
Looks like name servers are down.

**Comment by MichaelAtOz** [comment]
Everything is back up.

**Comment by t-paul** [comment]
Not sure what's going on, but something seems to be fishy, see #2403 2 days ago.

That said, I did not see any warning from Pingdom which would look like
```
PingdomAlert DOWN:
openscad.org (openscad.org) is down since 11/22/2016 12:09:02PM.
```
I don't know if that would cover also the sub-domains though.

**Comment by MichaelAtOz** [comment]
OK, good to see the world-wide shift kick-in. G'night
