### ISSUE TITLE
Preview error

### ISSUE THREAD

**Issue by nyponen** [openscad/openscad#2408]
This code should display a half sphere. When you rotate the object,  sometimes you see a half sphere, sometimes you see a whole sphere. If you zoom out until the object is very small, preview works correctly. Render works correctly. I'm using OpenSCAD version 2018.04.01 (git e7c0851)  on Windows 10.

difference() {
    sphere(d=20);
    translate([0, -100, -100]) cube([200, 200, 200]);
}

**Comment by nophead** [comment]
Preview mode works by drawing all the objects in various graphics modes. That includes the negative objects. For it to work all the objects need to fit in the clipping volume. When you zoom in past the boundary of the cube it gets clipped, so it no longer subtracts.

If you want the correct result add render() before difference. That will compute the actual geometry.

**Comment by thehans** [comment]
For what its worth, if you use orthogonal view, this type of issue is avoided.

**Comment by kintel** [comment]
Closing as this is a well-known artifact of rendering negative objects
