### ISSUE TITLE
No features tab in settings on macOS

### ISSUE THREAD

**Issue by maccesch** [openscad/openscad#2420]
I built the latest version but when I access the preferences there is no "Features" tab or whatever that would be called in German.

I'd like to enable the customizer.

![bildschirmfoto 2018-06-20 um 22 08 29](https://user-images.githubusercontent.com/380881/41684860-a7657854-74d6-11e8-85a8-0bd36606744c.png)

**Comment by kintel** [comment]
This tab is only available for experimental builds. `qmake CONFIG+=experimental`

**Comment by maccesch** [comment]
I see. Thanks for the clarification!
