### ISSUE TITLE
Customizer isn't usable until a preview has been made

### ISSUE THREAD

**Issue by DrLex0** [openscad/openscad#2426]
OS: OS X 10.11.6
Version: 2018.03.17 (git 3e7fbfff)

When I load a file, even if it has a valid .json file with customizer presets, the customizer interface remains grayed out until I hit the Preview or Render button. This is very unintuitive especially for first time users, and annoying for complex scad files that take a long time to render. I am the author of [this](https://www.thingiverse.com/thing:2812634) and I would like to make the list of instructions simpler instead of having to describe a different magic dance with every new release.
The customizer UI should be enabled after loading a customizable file.

**Comment by kintel** [comment]
What do you mean by "The customizer UI should be enabled after loading a customizable file"?
..just make sure that the customizer window is available in a tab somewhere?

Note that the Features preferences will go away when built in release mode, once the customizer is generally available.

**Comment by t-paul** [comment]
I think the solution would be to allow parsing only process so that the AST is generated but no preview/render is triggered.

**Comment by DrLex0** [comment]
> What do you mean by "The customizer UI should be enabled after loading a customizable file"?
..just make sure that the customizer window is available in a tab somewhere?

I'm not talking about the requirement to enable the feature in Preferences. Even when it has already been enabled, opening a file that is customizer-compatible yields this:

![current](https://user-images.githubusercontent.com/16401844/42249064-55244266-7f29-11e8-9908-17592a827e80.jpg)

while it should look like this:

![desired](https://user-images.githubusercontent.com/16401844/42249068-5e7a2510-7f29-11e8-85f0-19315170098d.jpg)

**Comment by kintel** [comment]
OK, makes sense. @MichaelPFrey Are you still working through your list of Customizer enhancements? Does this belong on that list?

**Comment by MichaelAtOz** [comment]
> allow parsing only process so that the AST is generated but no preview/render is triggered.

Or, if Customizer Automatic Preview is ticked, do a Preview on load, just like Automatic Reload and Preview.

**Comment by t-paul** [comment]
That does work, but could be massively annoying if the file has a big `minkowski` and preview needs a couple of minutes. Separating the parser would also later help picking up module names for auto-complete and similar stuff.

**Comment by t-paul** [comment]
Tested with the included examples. Works nicely.
