### ISSUE TITLE
Feature: add special $preview variable

### ISSUE THREAD

**Issue by mrvn** [openscad/openscad#2429]
I often want to preview my designs with a low $fn for speed but render them later with a higher $fn to get smooth curves. At the moment I have to always edit the source to change the value before rendering.

It would be nice if $preview would be true if openscad generates a preview and false when rendering. That way it would be easy to for example use:

     $fn = $preview ? 12 : 72;

**Comment by nophead** [comment]
Already done 18 months ago by myself and works exactly as you propose. You just need a more recent snapshot as there hasn't been a release since then.

**Comment by mrvn** [comment]
Great.

**Comment by MichaelPFrey** [comment]
for reference see #1963
