### ISSUE TITLE
qt5 causes certain windows machines to crash on start

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#2442]
on machines with certain Intel graphics chips, a file called **ig4icd32.dll** causes OpenSCAD to immediately crash directly after clicking "new" or trying to load a file, on Windows

see also

https://bugreports.qt.io/browse/QTBUG-40991

A workaround is as follows, to have Qt use its software renderer, 'angle'

```
    c:\program files\openscad
    set QT_OPENGL=angle 
    openscad.exe
```
windows crash report files:

[WEREAED.tmp.txt](https://github.com/openscad/openscad/files/2280731/WEREAED.tmp.txt)
[WERI8880.tmp.txt](https://github.com/openscad/openscad/files/2280732/WERI8880.tmp.txt)

Note that this does not affect openscad on the command line - rendering to a PNG from command line works fine. This issue is an interaction between certain versions of Qt5 and the graphics drivers on some windows machines

```
MATCHING_FILE NAME="ig4icd32.dll" 
SIZE="6042112" 
CHECKSUM="0xA2E9596D" 
BIN_FILE_VERSION="8.15.10.1808"
BIN_PRODUCT_VERSION="8.15.10.1808" PRODUCT_VERSION="8.15.10.1808" FILE_DESCRIPTION="OpenGL(R) Driver for Intel(R) Graphics Accelerator" 
COMPANY_NAME="Intel Corporation" 
PRODUCT_NAME="Intel Graphics Accelerator Drivers for Windows 7(R)" FILE_VERSION="8.15.10.1808" ORIGINAL_FILENAME="iglicd32" INTERNAL_NAME="OpenGL" LEGAL_COPYRIGHT="Copyright (c) 1998-2009 Intel Corporation." VERDATEHI="0x0" VERDATELO="0x0" VERFILEOS="0x10004" VERFILETYPE="0x2" MODULE_TYPE="WIN32" PE_CHECKSUM="0x5C888D" LINKER_VERSION="0x10064" UPTO_BIN_FILE_VERSION="8.15.10.1808" UPTO_BIN_PRODUCT_VERSION="8.15.10.1808" LINK_DATE="06/03/2009 17:41:05" UPTO_LINK_DATE="06/03/2009 17:41:05" EXPORT_NAME="ig4icd32.dll" VER_LANGUAGE="English (United States) [0x409]" EXE_WRAPPER="0x0"
```

**Comment by donbright** [comment]
closing, qt5 is nearing end of life if not already there

**Comment by MichaelAtOz** [comment]
It is in the current OpenSCAD release 2021.01. (Comment for posterity...)
