### ISSUE TITLE
linear_extrude() with angle (XY displacement of top face)

### ISSUE THREAD

**Issue by pwnage2apps** [openscad/openscad#2459]
My suggestion is to allow to change the direction of a linear_extrude(), instead of "z only", allow to send a vector where Z is the current height and X and Y are the displacement of the end of extrusion. For example: [3,2,5] will create a extrusion where the top face is displaced 3 and 2 units in X and Y, the height is 5 units.

I know that there is a "generalized extrusion" proposal, but my idea would be easier to use when the path is just a straight line that doesn't follow the Z axis:
https://github.com/openscad/openscad/issues/114

The only problem is how to manage when Z is 0.

At this moment, we can use "twist" from a very far point, but it's leaves a small twist.

**Comment by thehans** [comment]
If i'm understanding correctly, what you want would be the same as a regular linear_extrude plus a skew operation.  There's no native skew module but you can perform skew operation by using a transform matrix, documented here: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#multmatrix

**Comment by pwnage2apps** [comment]
Thanks, it worked well.

**Comment by l29ah** [comment]
@pwnage2apps can you show the code you ended up using?

**Comment by pwnage2apps** [comment]
Yes, but I haven't uploaded the latest version yet:
https://www.thingiverse.com/thing:3043241

I hope that I can upload it tomorrow, I will notify you.

**Comment by pwnage2apps** [comment]
I have updated the code, the multimatrix is at line 181:
https://www.thingiverse.com/thing:3043241

**Comment by t-paul** [comment]
Closing as it's working without core language extensions.
