### ISSUE TITLE
Stop serving binaries via http

### ISSUE THREAD

**Issue by radex** [openscad/openscad#2493]
The current URL to download the binary of OpenSCAD is (in my case) `http://files.openscad.org/OpenSCAD-2015.03-3.dmg`.

Damn, it's 2018, and this is frankly really bad. Anyone can intercept HTTP traffic and serve a malware version of the app.

There are two easy solutions for this:

- Serve binaries via GitHub releases
- Get https://letsencrypt.org

**Comment by radex** [comment]
@t-paul why did you close the issue? don't you think it's a trivial fix for something potentially serious?

**Comment by kintel** [comment]
@radex ..because it's fixed

**Comment by radex** [comment]
@kintel Apologies. I checked 10 minutes ago, and it was still HTTP, but checked again, and it's now fixed :)
