### ISSUE TITLE
clean up the experimental options in tests/CMakeLists.txt

### ISSUE THREAD

**Issue by MichaelPFrey** [openscad/openscad#2514]
As a general note: ~~due to #2499~~ we should remove experimental options that have become stable in the mean time:
https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L1032 

features that became most recently stable: #2505 #2504 

So fare I think we  ~~need to~~ should remove `"--enable=assert" "--enable=echo" from https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L1032

**Comment by t-paul** [comment]
The option itself (which is just `--enable`) is not going away. It will always be available with `CONFIG+=experimental`. So there should be no issue with #2499.

**Comment by MichaelPFrey** [comment]
@t-paul you are correct, there is no link to #2499 - I confused my self by not building openscad with the experimental option `CONFIG+=experimental.` I will update the issue accordingly. Cleaning up the option still makes sense tough.

**Comment by t-paul** [comment]
Sure, cleanup is already in progress :-).
