### ISSUE TITLE
Sudden Rendering Flaws

### ISSUE THREAD

**Issue by iceblu3710** [openscad/openscad#254]
I was using OpenSCAD yesterday and it worked flawlessly but today none of the commands like difference have an effect but only visually on the top half of the screen?!

Picture to make it clear:
![openscad_issue](https://f.cloud.github.com/assets/187394/101854/805dc80c-68f6-11e2-9003-161d0265d4c8.jpg)

What the heck happened?

**Comment by kintel** [comment]
Is this still an issue, or can we close this blaming old GPUs with bad drivers?

**Comment by iceblu3710** [comment]
Closed. I'm on Ubuntu 14.04 and the same hardware without issues.
