### ISSUE TITLE
get ctest -C All in an representable state

### ISSUE THREAD

**Issue by MichaelPFrey** [openscad/openscad#2564]
#2490 did not regenerate all tests.
some tests just need to be regenerated: ( #2565)
   * issue13
   * issue13b
   * issue13c
   * issue584
   * issue945
   * issue945b
   * issue945c
   * issue945d
   * issue945e
   * issue945f

Some tests need to be readjusted:
   * issue1580-back-to-back
   * issue1580-import-back-to-back

some may need to be readjusted
   * issue791
   * issue1876
(depending on what part of the geometry is critical)

may need manual generation/copying files around:
   * issue591

But I think we generally tend to overlook `ctest -C All`, but it would be good to go trough them before the next release.

**Comment by kintel** [comment]
Closed by #2783
