### ISSUE TITLE
Preview bug with intersection and difference

### ISSUE THREAD

**Issue by chill1n** [openscad/openscad#2592]
This bug seems different from #1803 (which has been resolved).

The following code shows the issue in preview, but the rendered result is fine (see attachments).
I reproduced this using 2015.03 and nightly build 2018.11.15.

d=10;

intersection()
{
    cube([d, d, 2]);
    linear_extrude(2) {
        difference()  {
            square([d, d]);
            translate([d/2, d/2])
                circle(d=d/2, $fn=6);
        }
    }
}

![intersection_render_results](https://user-images.githubusercontent.com/12458908/48671350-e484e780-eb26-11e8-9f5e-133555a4fed0.png)
![intersection_bug_in_preview](https://user-images.githubusercontent.com/12458908/48671351-e484e780-eb26-11e8-89db-137341ae2b9a.png)

**Comment by t-paul** [comment]
You need to specify `convexity=2` for the `linear_extrude()`.

See also the [FAQ entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_are_some_parts_(e.g._holes)_of_the_model_not_rendered_correctly?) for that.
