### ISSUE TITLE
Update the OpenSCAD About Dialog

### ISSUE THREAD

**Issue by MichaelPFrey** [openscad/openscad#2595]
I think hosting and resources are not fully uptodate:
```
Hosting & resources 
Source code repos and website hosted on Github
Downloads hosted by Joshua Holbrook
CI hosted on Travis-CI 
Laurent Guerby and the GCC Compile Farm, with OSUOSL, IRILL, FSF France, AMD, Intel, IBM, &c. 
```
Would it make sense to mention/add
- AppVeyor
- CircleCI
- Coverity
?

Maybe other things are also out of date.

Maybe we should update http:// Links to https where possible?

**Comment by t-paul** [comment]
Just for the record, I collected the [CI setup](https://github.com/openscad/openscad/wiki/CI-Setup) into a separate wiki page some time ago.
