### ISSUE TITLE
Slic3r AppImage fails to start GUI

### ISSUE THREAD

**Issue by mderouss** [openscad/openscad#2614]
Attempting to start Slic3r-1.3.1-dev-26b2a1e-x86_64.AppImage ( dated 2018-11-10 19:17 ) in Xubuntu 18.04 ( fully patched ) with freeglut3 v 2.8.1-3 installed, results in the following terminal output -

libGL error: unable to load driver: nouveau_dri.so
libGL error: driver pointer missing
libGL error: failed to load driver: nouveau
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
The program 'slic3r.pl' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 569 error_code 2 request_code 155 minor_code 24)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the --sync command line
   option to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)

This problem also occurs with Slic3r-1.3.0-dev-435fa6f-x86_64.AppImage.
The system is using the nouveau drivers for an NVidia Quadro 4000 card. Other AppImages work fine, including the Prusa version of Slic3r ( Slic3rPE-1.41.2+linux64-full-201811221508.AppImage ).

**Comment by t-paul** [comment]
Wrong repo, Slic3r is at https://github.com/slic3r/Slic3r
