### ISSUE TITLE
Expand children when passing to sub module?

### ISSUE THREAD

**Issue by jamessynge** [openscad/openscad#2635]
I'm trying to create a module that will accept several children, and will pass some of them (all but the first) to another module that it uses. But the inner module only gets a single child, even if I pass several children using:
```
 children([1:1:$children-1])
```
Here is an example of what I'm trying to do:
```
outer() {
   cube(size=4);
   sphere(r=4);
   cylinder(r=3,h=5);
}

module outer() {
  echo("outer children:", $children);
  color("blue") children(0);
  translate([10,0,0])
    inner() children([1:1:$children-1]);
}

module inner() {
  echo("inner children:", $children);
  color("red") children(0);
  translate([0,10,0]) color("green") children(1);
}
```
This produces an error when executing because the inner module receives one child, essentially a union (?) of both the sphere and the cylinder, and not two children as intended.

Is there a way to either:
- Have outer() pass multiple children to inner()?
- Have inner() break the one child it gets into its components?

**Comment by MichaelAtOz** [comment]
See #350.

**Comment by jamessynge** [comment]
Yup, that's the issue. I'll close this one as a duplicate of #350.
