### ISSUE TITLE
Output same info from GUI via command line [$50]

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2639]
As per [forum](http://forum.openscad.org/Get-console-information-in-order-to-store-it-tp25022.html), the output in the console from render:
```
Compiling design (CSG Tree generation)...
ECHO: version = [2018, 11, 4]
Rendering Polygon Mesh using CGAL...
Geometries in cache: 5
Geometry cache size in bytes: 754208
CGAL Polyhedrons in cache: 3
CGAL cache size in bytes: 26485440
Total rendering time: 0 hours, 0 minutes, 21 seconds
   Top level object is a 3D object:
   Simple:        yes
   Vertices:     4276
   Halfedges:   20384
   Edges:       10192
   Halffacets:  11816
   Facets:       5908
   Volumes:         2
Rendering finished.
```
should be able to be collected somehow via command line.

Similarly the preview info would also be useful
```
Compiling design (CSG Tree generation)...
ECHO: version = [2018, 11, 4]
Compiling design (CSG Products generation)...
Geometries in cache: 5
Geometry cache size in bytes: 754208
CGAL Polyhedrons in cache: 3
CGAL cache size in bytes: 26485440
Compiling design (CSG Products normalization)...
Compiling highlights (1 CSG Trees)...
Normalized CSG tree has 4 elements
Compile and preview finished.
Total rendering time: 0 hours, 0 minutes, 0 seconds
```

Note @nophead comment 'The statistics about edges and times, etc, are generated by the GUI code in mainwin.cc, so simply don't exist in command line mode.'

Having the output would also be useful to expand the test suite and for performance comparisons between releases.

Discussion on format;  plain text output or would an encoded format be more useful, presumably JSON?

**Comment by t-paul** [comment]
@Fat-Zer Thanks! Sorry for the delay. With the PR merged and this issue closed, you should be able to claim the bounty on BountySource.
