### ISSUE TITLE
Compilation. 

### ISSUE THREAD

**Issue by rewolff** [openscad/openscad#2655]
Trying to compile openscad on my niece's raspberry pi. Gcc sometimes warns about behavior of some source code constructs that is going to change in the next GCC release (7.1). Maybe the pi is using a quite-new compiler that nobody else is getting this, but IMHO someone with C++ knowledge should look into this. 

I'll update this when I get another example of that warning message.

**Comment by rewolff** [comment]
The current compilation run is running for 2.5 hours. Before that I had a few runs that partially compiled the tree. So I'll be updating this once I get a chance to recreate the message. Or do you want me to start over?

**Comment by t-paul** [comment]
I don't mind either way, reopen with the details or create a new issue. But there is no point in having open issues which do not have enough details to work with. This will waste time of people browsing open issues.
