### ISSUE TITLE
Accept 3D printing integration as a stable feature

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2664]
TODO:
* [x] Handle Qt4 builds
* [x] Resolve handling of async response (busy loop vs. dialog vs. background)
* [x] Dialog for initial run (for enabling the feature)
* [x] Managing upload size (too big, progress, cancel)
* [x] Manage maximum QJsonObject size
* [x] Decide on shortcut to access service
* [x] ~If possible, remove trailing slash in service endpoint URL (not possible, needs new API version)~
* [x] Clean up uses of `sprintf()` - use stringstream instead.
* [x] Go through and clean up debug output and error handling
* [x] Use SSL to access files.openscad.org resources
* [x] Move the toolbar icon to the right of and into the same group as "Export STL"
* [x] Generic error "Cannot 3D Print due to errors." appears on stdout/stderr. Can we just will this generic error message and replace it with a real, concrete error message in the OpenSCAD console?
* [ ] ~On initial 3D print, this error is printed to stderr: `QFSFileEngine::open: No file name specified`~ this comes from `QTextBrowser::setHtml()` so I'll call that a QT bug at this point
* [ ] Can we make the 3D Print service selection UI a bit more friendly? Right now it's a radio box with a bunch of HTML above, with no direct connection between the HTML content and the radio boxes. This is likely just a question of UI tweaks, so it could be deferred..

**Comment by t-paul** [comment]
See #2688.

**Comment by kintel** [comment]
In terms of shortcut, I like the suggestion to make `F7` STL export and `F8` 3D printing.
In the future we may implement toolbar editing to allow F7 to be bound to other export formats.

**Comment by printathing** [comment]
> In terms of shortcut, I like the suggestion to make `F7` STL export and `F8` 3D printing.
> In the future we may implement toolbar editing to allow F7 to be bound to other export formats.

Agreed!

**Comment by t-paul** [comment]
I'd leave the UI details till we got some feedback, everything else should be covered by #2708.
