### ISSUE TITLE
appimage needs absolute path for filenames

### ISSUE THREAD

**Issue by mknj** [openscad/openscad#2666]
OS ubuntu 18.10
Versions:  OpenSCAD-Nightly-0-Build2689.2.glibc2.14-x86_64.AppImage OpenSCAD-Release-0-Build36.41.glibc2.14-x86_64.AppImage

Expected:
test.scad is opened and displayed

The following file does not open the file:
```
$ OpenSCAD-Nightly-0-Build2689.2.glibc2.14-x86_64.AppImage test.scad
```

Workaround:
```
$ OpenSCAD-Nightly-0-Build2689.2.glibc2.14-x86_64.AppImage $PWD/test.scad
```

The problem also occurs with the Release-0 build. It seems that the current working directory is set to / when using AppImage.

**Comment by t-paul** [comment]
Fixed by latest AppImage build.
