### ISSUE TITLE
Install an SSL certificate on files.openscad.org

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2684]
e.g. using Let's Encrypt.

**Comment by kintel** [comment]
`/etc/letsencrypt/live/files.openscad.org/fullchain.pem`
`/etc/letsencrypt/live/files.openscad.org/privkey.pem`
The cert will expire on 2019-04-07.
Backup of /etc/letsencrypt was taken

**Comment by MichaelAtOz** [comment]
Typo or expires in 3 months?

**Comment by kintel** [comment]
https://letsencrypt.org/2015/11/09/why-90-days.html

**Comment by kintel** [comment]
That said, we don't have such automation yet.
