### ISSUE TITLE
Accept 3MF export/import as stable features

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2700]
This feature is almost ready. 

TODO:
* [x] Make sure this is tested on Windows

**Comment by nophead** [comment]
I don't think it works on Windows, all the tests fail.

**Comment by t-paul** [comment]
Oh? I did test that not long ago and that was fine, hmm...

**Comment by t-paul** [comment]
Right, as said before, there is no lib3mf package for MSYS2, so tests can't work there. The only criteria is the official MXE based build which shiould have it enabled.

**Comment by kintel** [comment]
@nophead Is it possible to run the MSYS2 test suite using the MXE binary with some manual file copying you think? Asking you since you appear to own a Windows box :)

**Comment by nophead** [comment]
I could have yesterday but now I am a few thousand miles nearer the equator for a month.

**Comment by t-paul** [comment]
I'll have a look if my Win10 VM is still working.

**Comment by t-paul** [comment]
Simple case works in interaction with Win10 3D Builder.

Export from OpenSCAD -> 3D Builder
![3mf-export](https://user-images.githubusercontent.com/1330241/51288654-76ad4d00-19fd-11e9-86ad-dd03ae5aac71.png)

3D Builder -> Import in OpenSCAD 
![3mf-import](https://user-images.githubusercontent.com/1330241/51288655-76ad4d00-19fd-11e9-82fb-81896d10f2da.png)
