### ISSUE TITLE
Accept Customizer as a stable feature

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2703]
TODO:
* [ ] Do some manual testing of the current feature set
* [x] Investigate unnecessary JSON file creation, and suggest a resolution
* [x] If necessary: Resolve JSON file creation
* [x] Remove experimental flag

**Comment by kintel** [comment]
@MichaelPFrey You may have a better idea what's absolutely needed for this to become stable, or is it already good enough?. We have two issue with a lot of suggestions: #1781 and #2316, that may need some cleanup

**Comment by MichaelPFrey** [comment]
Good question. I currently see no blocking issue. The main benefit of the experimental status is, that the feature can quickly be disabled when it makes problem. I have most experimental features on all the time, so I assume that the customizer now plays pretty nicely with the other subsystems. I'll do some manual testing over the weekend

On thing I think I observed is, is that the customizer is creating unnecessary json files again. But I am not sure and even if: This is not a big deal.

**Comment by kintel** [comment]
Thanks. I think investigating the JSON issue makes sense.  I've updated the TODO list.

**Comment by t-paul** [comment]
I think the JSON file creation issue is fixed by https://github.com/openscad/openscad/pull/2776/commits/1aeb0a2b51532072a8a320e45be42ad4da7646d3.
