### ISSUE TITLE
Accept InputDriver as stable feature

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#2704]
See  #2710.

I think we should not release the DBus driver yet. It's useful but did not get much testing. Also it's much harder to change as it provides an external API.

TODO:

- [x] Remove experimental flag for everything except the DBus driver

**Comment by MichaelPFrey** [comment]
I like the simplicity of the todo list :smiley: The one for getting it merged was a lot longer - but off-course a development branch had its own benefits as it lead to a pretty clean interface to the other software parts, as the PR always showed the whole impact that inputdriver has/had on the whole.

DBus is kind of a developer tool right now anyway and I think it will remain that for a while.

It is awesome to develop drivers with it, as you don't have to recompile or even restart openscad.
It will be an awesome stepping stone for future drivers.
But given the fact that is aims it self at developers under linux, it remaining experimental is the right thing.

On a related side note: Any interest in adding https://github.com/MichaelPFrey/openscad-dbus-reference to the openscad project?

**Comment by t-paul** [comment]
Sure, we can move the repo into the organization. That might make it a bit easier to discover. If I'm reading the docs right, we'd need to enable repo creation temporarily as that is normally disabled.
