### ISSUE TITLE
Crossing beams cause excessive compile time, and finally crash

### ISSUE THREAD

**Issue by bmcage** [openscad/openscad#280]
Here a script, which is a bunch of beams. 
It compiles fine.
Now change parameter
second_skew = 160;
into 
second_skew = 180;
and it no longer succeeds to compile. Somehow, all the beams crossing in a single point cause big problems.

scad file:

// Licence: Creative Commons, Attribution
// Created: 16-02-2013 by bmcage http://www.thingiverse.com/bmcage

// An attempt at customizable math art: Stick Bowl

//Make it a bowl or not
add_bottom = "no";  //[yes, no]
//If a bowl, size of the bottom
bottom_height = 1; //[1:20]

//Form of the sticks to use
base_form = "beam";  // [beam, cylinder, hexagon, triangle]
//Size of the sticks
size = 2; //[1:20]

//start radius
r0 = 2; //[2:200]

// number of sticks per ring
nrsticks = 24; //[4:50]
grad_per_stick = 360 / nrsticks;

// radius of the first ring
first_radius = 50; // [0:200]
// extend beyond radius of first sticks
first_extend = 1;  //[0:100]
//how skewed (rotated) first ring is in degrees
first_skew = 0;    //[-360:360]
// height if the first ring
first_height = 0;  // [0:300]

// radius of the second ring (0 for no ring)
second_radius = 50; // [0:200]
// extend beyond radius of first sticks
second_extend = 1;  //[0:100]
//how skewed (rotated) first ring is in degrees
second_skew = 160;    //[-360:360]
// height if the first ring
second_height = 120;  // [0:300]

// radius of the second ring (0 for no ring)
third_radius = 0; // [0:200]
// extend beyond radius of first sticks
third_extend = 2;  //[0:100]
//how skewed (rotated) first ring is in degrees
third_skew = -360;    //[-360:360]
// height if the first ring
third_height = 120;  // [0:300]

// radius of the second ring (0 for no ring)
fourth_radius = 0; // [0:200]
// extend beyond radius of first sticks
fourth_extend = 1;  //[0:100]
//how skewed (rotated) first ring is in degrees
fourth_skew = 9;    //[-360:360]
// height if the first ring
fourth_height = 1;  // [0:300]

// radius of the second ring (0 for no ring)
fifth_radius = 0; // [0:200]
// extend beyond radius of first sticks
fifth_extend = 2;  //[0:100]
//how skewed (rotated) first ring is in degrees
fifth_skew = -27;    //[-360:360]
// height if the first ring
fifth_height = 20;  // [0:300]

// radius of the second ring (0 for no ring)
sixth_radius = 0; // [0:200]
// extend beyond radius of first sticks
sixth_extend = 5;  //[0:100]
//how skewed (rotated) first ring is in degrees
sixth_skew = 90;    //[-360:360]
// height if the first ring
sixth_height = 40;  // [0:300]

use <MCAD/regular_shapes.scad>;
use <utils/build_plate.scad>;

//for display only, doesn't contribute to final object
build_plate_selector = 0; //[0:Replicator 2,1: Replicator,2:Thingomatic,3:Manual]

//when Build Plate Selector is set to "manual" this controls the build plate x dimension
build_plate_manual_x = 100; //[100:400]

//when Build Plate Selector is set to "manual" this controls the build plate y dimension
build_plate_manual_y = 100; //[100:400]

//build_plate(build_plate_selector,build_plate_manual_x,build_plate_manual_y); 

bottomstart = -bottom_height; //-first_extend*first_radius/sqrt(pow(first_height,2)+pow(first_radius,2));

module baseform(length){
  if (base_form == "beam") {
    translate([-size/2, -size/2, 0]) cube(size=[size, size, length]);
  } 
  if (base_form == "cylinder") {
    cylinder(r=size, h=length, $fn=20);
  }
  if (base_form == "hexagon") {
    linear_extrude(height=length) hexagon(size);
  }
  if (base_form == "triangle") {
    linear_extrude(height=length) triangle(size);
  }
}

module ringbaseform(r1, h1, skew1, r2, h2, skew2, extend){
  // a form with correct length if first ring is at r1, h1, and 
  // second at r2, h2, and extend is extend
  //
  // P = (r1, 0, h1), Q = (r2 cos(skew2), r2 sin(skew2), h2)
  // dir_new = (P-Q) / norm(P-Q) = (a,b,c)
  // rotate to new direction, euler angles
  // th_x = atan2(b,c); th_y = atan(-a, sqrt(b*b+c*c)) ; th_z = 0
  rotate([0,0,skew1])
  translate([r1, 0, h1]) 
  help_ringbaseform(r2*cos(-skew2)-r1, r2*sin(-skew2), h2-h1, extend);
}

module help_ringbaseform(a, b, c, extend)
{ 
  rotate([atan2(b/sqrt(pow(a, 2) + pow(b, 2) + pow(c, 2)), 
                c/sqrt(pow(a, 2) + pow(b, 2) + pow(c, 2))), 0, 0])
  rotate([0, atan2(a/sqrt(pow(a, 2) + pow(b, 2) + pow(c, 2)),
     sqrt(b*b/(pow(a, 2) + pow(b, 2) + pow(c, 2))
          +c*c/(pow(a, 2) + pow(b, 2) + pow(c, 2)))), 0])
  translate([0,0,-extend]) 
  baseform(sqrt(pow(a, 2) + pow(b, 2) 
                    + pow(c, 2)) + 2*extend);
}

module ring(ringnr){
  union() 
    {
    for (i = [0:nrsticks]) {
      rotate([0,0,i*grad_per_stick]) {
        if (ringnr == 1) {
          ringbaseform(r0, 0, 0, first_radius, first_height, 
                       first_skew,  first_extend);}
        if (ringnr == 2){
          ringbaseform(first_radius, first_height, first_skew,
                       second_radius, second_height, second_skew,  
							  second_extend);}
        if (ringnr == 3)
          ringbaseform(second_radius, second_height, 
                       first_skew + second_skew,  
                       third_radius, third_height, third_skew,
							  third_extend);
        if (ringnr == 4)
          ringbaseform(third_radius, third_height,
							  first_skew + second_skew + third_skew,  
                       fourth_radius, fourth_height, fourth_skew,
							  fourth_extend);
        if (ringnr == 5)
          ringbaseform(fourth_radius, fourth_height,
  first_skew + second_skew + third_skew + fourth_skew,  
                       fifth_radius, fifth_height, fifth_skew,
							  fifth_extend);
        if (ringnr == 6)
          ringbaseform(fifth_radius, fifth_height, 
  first_skew + second_skew + third_skew + fourth_skew + fifth_skew,  
                       sixth_radius, sixth_height, sixth_skew,
							  sixth_extend);
      }
    }
  }
}

module bottom(){
  if (add_bottom == "yes") {
    translate([0,0,bottomstart]) 
      cylinder(r = r0+size, h=bottom_height);
  }
}

module bowl(){
union() 
  {
  bottom();
  ring(1);
  if (second_radius > 0) {
  ring(2);}
  if (third_radius > 0) {
  ring(3);}
  if (fourth_radius > 0) {
  ring(4);}
  if (fifth_radius > 0) {
  ring(5);}
  if (sixth_radius > 0) {
  ring(6);}
}
}

//bowl();
difference(){
  bowl();
  translate([-250,-250,-500+bottomstart]) cube(size=[500,500,500]);
}

**Comment by kintel** [comment]
With the latest development snapshot, the problematic version renders (F6)  in ca. 50 seconds.
@bmcage Could you give it a spin?

**Comment by MichaelAtOz** [comment]
Works for me (set to 180). F6 1m2s.

**Comment by MichaelAtOz** [comment]
Don't want to open a can of worms, but if I do 2 consecutive F6s they take the same time???

**Comment by kintel** [comment]
It shouldn't, unless your cache size is set smaller than the resulting object size 23MB on my machine.

**Comment by MichaelAtOz** [comment]
You're right again, I had reduced my cache for some reason. Now 2nd F6 is 0m0s.

**Comment by ingegno** [comment]
Yes, It compiles in under a minute now. Good job! This is fixed.

**Comment by bmcage** [comment]
Sorry, was on the account of my way. As I said, fixed
