### ISSUE TITLE
Syntax error not detected, silently ignoring some primitives

### ISSUE THREAD

**Issue by MoonCactus** [openscad/openscad#2804]
_OpenSCAD version 2019.01-RC2 (git 35858ea)_ but the error exists at least since OpenSCAD version 2015.03-2  (running linux)
Forgetting the semicolon after a primitive before another primitive produces no syntax error. Only the first primitive is generated and shown. I would expect the parser to fail as it makes debugging the typo much harder otherwise.
```
cube()        // misses the syntax error, only primitive shown
cylinder();   // does not show up
```
Here is a second example:
```
sphere()     // misses the syntax error, only primitive shown
cylinder()   // does not show up
cube();      // does not show up
```

**Comment by t-paul** [comment]
The syntax is valid, so this can't be a parser error, however there could be an additional check which modules do actually evaluate child modules. That is covered by #596.

**Comment by MoonCactus** [comment]
Oh, right! I should have thought twice about it from another angle, and looked for children-related issues in github indeed, not syntax-related!
