### ISSUE TITLE
I can't open 2019.02.20 (macOS 10.11.6)

### ISSUE THREAD

**Issue by proto-user** [openscad/openscad#2805]
Suggested by Marius in the mailing-list, the output when launched from the command line is:
Sorry, "OpenSCAD" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.

Benjamin

**Comment by t-paul** [comment]
Meanwhile you should be able to run 2019.01.30 (which is effectively 2019.02-RC2). This does run on my MacBookPro which has also 10.11.6:

![openscad-info](https://user-images.githubusercontent.com/1330241/53184730-d8189b00-35fd-11e9-9c2e-d6fe2e38298f.png)

**Comment by proto-user** [comment]
Yes,
Thanks. Contrary to what I said this morning 2019.01.30 is fine.

**Comment by kintel** [comment]
That makes more sense, as I revamped the dependencies for the 2019.02.20 build

**Comment by kintel** [comment]
Turns out Qt doesn't support 10.11 any longer, as it's too old for them.
I'll see if I can patch the Qt build system a bit, but we won't guarantee good behavior as we'd be pushing the Qt envelope a bit.

**Comment by kintel** [comment]
@proto-user Try OpenSCAD-2019.02.23

**Comment by proto-user** [comment]
You're incredible! I can't count the times you've saved my computer from obsolescence. I know it can't last for ever.
You're the only ones to care about us. Thank you.
