### ISSUE TITLE
OpenCSG: pbuffer failing large number of tests

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#281]
This particular system (a distro released in 2012) doesn't have stencil buffer for the very-common Intel 915 chip. Most other distros on the same machine are OK, but this one doesn't have it for some reason. 

OpenCSG falls back to using pbuffers, but these appear to fail. 

Report uploaded here:

http://dangqiwu.sourceforge.net/openscad_tests/linux_i686_mesa-dri-intel_r__hbwu_report.html

GL Renderer: Mesa DRI Intel(R) 915G 
GL Vendor: Tungsten Graphics, Inc
OpenGL Version: 1.4 Mesa 7.11

GL_ARB_framebuffer_object: no
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: no

---

Strangely enough, when vieweing in normal GUI mode, everything appears to be fine.
##

**Comment by kintel** [comment]
Can this be closed now?
