### ISSUE TITLE
Work towards a functioning MSVC Build

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#2814]
I've been working on getting a Windows build to work natively within Visual Studio 2017 Community Edition.   

My changes are here if anyone wants to try for themselves:
https://github.com/thehans/openscad/tree/msvc_build

This is attempting to use [VCPKG](https://github.com/microsoft/vcpkg) for dependencies, since it seem to support nearly all OpenSCAD dependencies, aside from OpenCSG and Lib3MF.

Below are the current steps I've used to build OpenSCAD.
I have not tested it extensively, but it builds and runs for all current configurations: x86/x64 Debug/Release 

Mainly the test build, and console app `openscad.com` still need to be worked out.

I will update/edit this top post with more instructions as new things are figured out.

1) Get Visual Studio 2017 Community Edition (this has some integration with cmake)
https://visualstudio.microsoft.com/downloads/

2) Get Chocolatey for flex/bison tool packages:
https://chocolatey.org/install#installing-chocolatey
choco install winflexbison3

3) Set up VCPKG
```
git clone https://github.com/Microsoft/vcpkg.git
cd vcpkg
.\bootstrap-vcpkg.bat
# Next command integrates VCPKG with VS somehow (will prompt for elevated priviledges)
.\vcpkg integrate install
# Set an environment variable for your vcpkg path (current directory).  
# OpenSCAD's CMakeSettings.json will set CMAKE_TOOLCHAIN_FILE based on this
setx VCPKG_PATH %cd%
# Will need to restart Visual Studio (if already open) to pick up new environment variable
```
4) Configure `VCPKG_DEFAULT_TRIPLET` environment variable
vcpkg defaults to target: `x86-windows` which is 32bit, shared libraries.
If you want a 64bit build, you must run: `setx VCPKG_DEFAULT_TRIPLET x64-windows`
There are also `x86-windows-static` and `x64-windows-static` for statically linked libraries but these are not yet possible due to https://github.com/Microsoft/vcpkg/issues/4560 and https://github.com/Microsoft/vcpkg/issues/3409
Run: `.\vcpkg help triplet` to see a list of supported targets.  
Targets for other platforms such as osx, linux, arm exist but those are far out of the scope of this issue.

5) Build/Install OpenSCAD dependencies with VCPKG
```
.\vcpkg install boost-assign boost-thread boost-program-options boost-filesystem boost-system boost-regex cgal double-conversion eigen3 fontconfig freetype glew glib harfbuzz libxml2 libzip mpfr opencsg qscintilla qt5-base qt5-multimedia qt5-gamepad
```

6) Open OpenSCAD project
git clone https://github.com/thehans/openscad/
cd openscad
git checkout msvc_build
Start Visual Studio 2017
File -> Open -> Folder...
Select your openscad folder

7) Try building
I have commited a `CMakeSettings.json` file which is used by Ninja which handles the different cmake build configurations.  VS2017 will read this and provide 4 Configuration options in the toolbar dropdown, `(x86|x64)-(Debug|Release)` make sure the correct architecture is selected based on the your `VCPKG_DEFAULT_TRIPLET`.
Then to start the build, click the menu: CMake -> Build All

**Comment by thehans** [comment]
Just a note, I've been tinkering around a lot with `CMakeLists.txt` for this, so I know its in a bad state for other platforms right now.  I will attempt some cleanup/refactoring once the Windows build is better nailed down.

**Comment by thehans** [comment]
So I was having issue finding `gettext` but realized its AKA `libintl`, so those linker errors are gone.  

The one remaining linker error at the moment is something with the comment_lexer.

Initially, in order to get the build past various compile errors, I added these two options:
 `--wincompat` and `--nounistd` when calling `win_flex.exe`

And also copied this little piece of preprocessor checks from `lexer.l` into `comment_lexer.l`:
https://github.com/thehans/openscad/commit/ea8ed6b28ef835d5456559b5f8d88c0e84fb4d96#diff-230bba01c91025e179018f2ab6f56d90

I guess those three things aren't the exact correct solution to the issue, I'll have to dig more into understanding whats going on here.

**Comment by thehans** [comment]
Also I've done some work towards creating a VCPKG port for OpenCSG here: 
https://github.com/thehans/vcpkg/commit/2f86663b3e13f0d2f5961ed26069bd679126ce1c

I had to change a single character from upstream OpenCSG because vcpkg expects UTF-8 and it had an odd high ASCII symbol in the comments of opencsg.h 
So my fork of VCPKG pulls opencsg from my own fork of OpenCSG for now.  
If you check out my fork of VCPKG to try it, you have to run 
`.\vcpkg install opencsg --head`, to make it grab from head without a specific release package/checksum.

I have the build close to working(it compiles), but honestly don't understand a whole lot about the proper way to create a library with cmake.  Attached is the output from vcpkg complaining that my DLLs don't export anything: [vcpkg_install_opencsg.log](https://github.com/openscad/openscad/files/2900373/vcpkg_install_opencsg.log)

**Comment by kintel** [comment]
I'm not sure OpenCSG supports being build as a DLL. Try building it as a static library

**Comment by thehans** [comment]
OK, made the package static only and it seems to be good now!  I removed `-DNULLGL` from build configs and fixed a few other compile errors that popped up.  Basically just that comment_lexer linking issue is remaining.

**Comment by thehans** [comment]
Got the builds working reliably for me now, briefly tested both x86 and x64, Debug and Releases and rendered a few scripts without crashing.  

A few remaining things to do:
- Lib3MF support is still disabled, need to create a vcpkg port for that.
- Its not copying any of the subdirectories into the build output path: "colorschemes", "examples", etc
- No build for console application `openscad.com`
- Still need to get `tests\CMakeLists.txt` running
- Need to test openscad\CMakeLists.txt` on linux, other platforms again to see if I broke anything there.  Could probably still use some cleanup/refactoring now that windows build works.

**Comment by kintel** [comment]
We could set up an occasional cmake build for Linux and Mac on Travis. A nightly (or even weekly if we're short on build resources) build should be enough to eventually catch build system bugs

**Comment by thehans** [comment]
Well there is PR #2764 that I started working on.  Have you seen it?  Its not quite ready and working yet.  For some reason AMF tests were crashing or something on Trusty, but not Xenial.  More comments about it in the PR, but I kinda got stuck there.

**Comment by kintel** [comment]
k, I'll take a look at that when I have some time to burn :)

**Comment by thehans** [comment]
Yay, my opencsg port was merged into Microsoft's repo!  Instructions in first post have been updated to clone directly from them now.

**Comment by Scopeuk** [comment]
I have replicated this with windows 10 home.
Its worth noting during the visual studio community install you have to select your language tool (c++ in this case) and confirm you have cmake in the list of things that will be installed on the right hand side.
Curriously on loading a model the preview didn't render until i hit f5.

**Comment by nophead** [comment]
I have just merged a fix for that into master. #2821

**Comment by nophead** [comment]
I also got this to build and run on Win7/64, thanks.

Is it ready for a merge into master?

**Comment by thehans** [comment]
@nophead Just about ready I think; requesting comments now for one last thing that was bugging me.  Also I just commited a couple fixes for linux cmake so that it builds and passes all tests again.

There's also still the remaining tasks from my comment above, but I suppose I can track those in a separate issue: https://github.com/openscad/openscad/issues/2814#issuecomment-468119651

**Comment by nophead** [comment]
Great. I am in transit ATM but I will try to test the latest on my laptop
tomorrow. I did manage to build it yesterday ok.

Btw msys2 is currently broken by gcc8.3.0 failing to compile some Qt stuff
with an internal compiler error.

**Comment by thehans** [comment]
Closing this since the changes are merged now, created new home for further development: #2857
