### ISSUE TITLE
Missing warning about double assignment

### ISSUE THREAD

**Issue by knielsen** [openscad/openscad#2817]
OpenSCAD outputs a warning if a variable is assigned twice. However, the
logic doesn't handle absolute vs. relative path correctly for the input
file.

This can be seen from the "include-overwrite-main.scad" file in the testsuite:

    $ ./openscad testdata/scad/misc/include-overwrite-main.scad -o /tmp/1.echo ; cat /tmp/1.echo
    WARNING: overwritten was assigned on line 12 of "include-overwrite-main.scad" but was overwritten on line 16
    WARNING: overwriteInuse was assigned on line 1 of "include-overwrite-use.scad" but was overwritten on line 2

    $ ./openscad $(pwd)/testdata/scad/misc/include-overwrite-main.scad -o /tmp/1.echo ; cat /tmp/1.echo
    WARNING: overwritten was assigned on line 12 but was overwritten on line 16
    WARNING: after was assigned on line 15 of "include-overwrite-main.scad" but was overwritten on line 2 of "include-overwrite-after.scad"
    WARNING: overwriteInuse was assigned on line 1 of "include-overwrite-use.scad" but was overwritten on line 2

When a relative path is used, a warning is missing. When an absolute path is
used, the problem does not appear.

The logic for outputting the warning (in src/parser.y) generally uses
absolute paths, but the name of input file (mainFilePath) starts out
relative if a relative path is given on the command line. But a `use'
statement in the code causes the mainFilePath to be changed to an absolute
path, which confuses later comparisons.

A proposed patch for the problem is here:

  https://github.com/openscad/openscad/pull/2816

Note: This was found trying to get the testsuite to pass without errors for
Debian packaging. I think Debian runs the testsuite out-of-tree using
relative paths while the native `make test` uses absolute paths; so this
could be the reason the issue is only seen in the Debian packaging.

I'm planning to carry the linked patch in Debian until the issue can be
fixed upstream, unless someone can see a problem with it.

**Comment by kintel** [comment]
Fixed by #2816
