### ISSUE TITLE
Mac app opened in Spanish

### ISSUE THREAD

**Issue by rgov** [openscad/openscad#2818]
I downloaded OpenSCAD 2015.03-3 for the first time today on macOS Mojave and was greeted with a Spanish user interface.

My primary language is set to English, though I do have Spanish configured. It should pick my primary language, though.

<img width="780" alt="screen shot 2019-02-25 at 12 36 26 pm" src="https://user-images.githubusercontent.com/108767/53356724-0ea22e80-38fa-11e9-9958-476b7e2d5e12.png">

**Comment by t-paul** [comment]
See #1813 for a workaround, or try with the snapshot version (which is almost ready for release).
