### ISSUE TITLE
shift-middledrag (camera distance modification) should be expomential

### ISSUE THREAD

**Issue by chrysn** [openscad/openscad#282]
when moving the camera to or away from the screen center, the absolute camera movement is linear to the mouse distance. this is

* counter-intuitive, as the perceived mouse-to-world-coordinate ratio is changing during the operation
* imprecise when viewing objects from very close
* impractical with large objects (try with distances > 6000)

on my screen, dragging from top to bottom moves the camera by 450 world units; i'd prefer it to roughly double with one screen drag independently of the distance.

(this might or might not be an issue with mouse wheel zooming too -- for lack of one, i can't try.)

observed on openscad 2013.01.

**Comment by kintel** [comment]
This was improved recently
