### ISSUE TITLE
Simple Editor -> "save" to reload after every Customizer change

### ISSUE THREAD

**Issue by paulirotta** [openscad/openscad#2827]
![image](https://user-images.githubusercontent.com/3486467/53576292-0822e980-3b7c-11e9-8017-f48000b1b2a0.png)

The Customizer is greyed out in Windows 10 after successfully updating and making a change. It re-appears after CTRL S save.

This happens in the Simple Editor but not QScintilla Editor. This happens even in the Simple Editor view is closed (having Simple Editor set in Preferences is sufficient to surface the problem).

**Comment by MichaelAtOz** [comment]
> successfully updating and making a change

Does this mean typing then F5?  Or changing Customizer value?

**Comment by MichaelAtOz** [comment]
Confirmed on W7/64.
Grey's out on changing item in Customizer, image is refreshed, stays grey.
Ditto typing in editor.
Note  grey's out when typing in the QScintilla too, but I presume this is intention, as it goes away after F5.

**Comment by paulirotta** [comment]
F5 is not needed to trigger it- just a Customizer value

**Comment by t-paul** [comment]
Closing as the simple editor will not be included in the next release anymore.
