### ISSUE TITLE
File not rendered until change detected (Mac 2019.02.23)

### ISSUE THREAD

**Issue by DAKarp** [openscad/openscad#2835]
To reproduce:

1. Start OpenSCAD 2019.02.23 on MacOS
2. Open any scad file
3. Observe empty viewport (except for a axes, scale markers, etc.)
4. Make any arbitrary change in the editor (e.g., whitespace change) and save
5. Observe model is finally rendered

This is 100% repeatable. It was not happening in the prior Mac snapshot.

**Comment by nophead** [comment]
Should be fixed by https://github.com/openscad/openscad/pull/2821. You will need a later snapshot.

**Comment by kintel** [comment]
I'll build a new snapshot soon
