### ISSUE TITLE
Symbol redeclared as different kind of symbol on Ubuntu 18.04 ARM64

### ISSUE THREAD

**Issue by hominoids** [openscad/openscad#2836]
I get lots of these errors during compile on Ubuntu 18.04 on ARM64, any pointers on how to fix?
Dependencies all were met according to script.
g++ -c -pipe -DSTACKSIZE=8388608 -fno-strict-aliasing -std=c++11 -O2 -std=gnu++11 -I/usr/lib/aarch64-linux-gnu/libzip/include -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/aarch64-linux-gnu/glib-2.0/include -DEIGEN_DONT_ALIGN -frounding-math -D_REENTRANT -Wall -W -Wno-unused-local-typedefs -fPIC -DOPENSCAD_VERSION=2019.03.03 -DOPENSCAD_SHORTVERSION=2019.03.03 -DOPENSCAD_YEAR=2019.0 -DOPENSCAD_MONTH=03.0 -DOPENSCAD_DAY=03.0 -DDEBUG -DSTACKSIZE=8388608 -DUSE_QOPENGLWIDGET -DENABLE_DBUS -DENABLE_JOYSTICK -DUSE_SCINTILLA_EDITOR -DQSCINTILLA_DLL -DENABLE_LIBZIP -DENABLE_OPENCSG -DENABLE_CGAL -DQT_NO_DEBUG -DQT_PRINTSUPPORT_LIB -DQT_WIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_GUI_LIB -DQT_CONCURRENT_LIB -DQT_NETWORK_LIB -DQT_DBUS_LIB -DQT_CORE_LIB -I. -Isrc -Isrc/ext/libtess2/Include -isystem /usr/include/aarch64-linux-gnu/qt5 -isystem /usr/include/aarch64-linux-gnu/qt5/QtPrintSupport -isystem /usr/include/aarch64-linux-gnu/qt5/QtWidgets -isystem /usr/include/aarch64-linux-gnu/qt5/QtMultimedia -isystem /usr/include/aarch64-linux-gnu/qt5/QtGui -isystem /usr/include/aarch64-linux-gnu/qt5/QtConcurrent -isystem /usr/include/aarch64-linux-gnu/qt5/QtNetwork -isystem /usr/include/aarch64-linux-gnu/qt5/QtDBus -isystem /usr/include/aarch64-linux-gnu/qt5/QtCore -Iobjects -isystem /usr/include/eigen3 -I/usr/lib/aarch64-linux-gnu/qt5/mkspecs/linux-g++ -o objects/src/LibraryInfo.o src/LibraryInfo.cc
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopengl.h:105:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:49,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from src/QGLView.h:7,
                 from objects/ui_MainWindow.h:35,
                 from src/MainWindow.h:6,
                 from src/input/InputDriverManager.h:34,
                 from src/LibraryInfo.cc:6:
/usr/include/GLES3/gl31.h:528:60: error: ‘void __glewActiveTexture(GLenum)’ redeclared as different kind of symbol
 GL_APICALL void GL_APIENTRY glActiveTexture (GLenum texture);
                                                            ^
In file included from src/system-gl.h:4:0,
                 from src/QGLView.h:3,
                 from objects/ui_MainWindow.h:35,
                 from src/MainWindow.h:6,
                 from src/input/InputDriverManager.h:34,
                 from src/LibraryInfo.cc:6:
/usr/include/GL/glew.h:16749:40: note: previous declaration ‘void (* __glewActiveTexture)(GLenum)’
 GLEW_FUN_EXPORT PFNGLACTIVETEXTUREPROC __glewActiveTexture;
                                        ^~~~~~~~~~~~~~~~~~~
In file included from /usr/include/aarch64-linux-gnu/qt5/QtGui/qopengl.h:105:0,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/qopenglwidget.h:49,
                 from /usr/include/aarch64-linux-gnu/qt5/QtWidgets/QOpenGLWidget:1,
                 from src/QGLView.h:7,
                 from objects/ui_MainWindow.h:35,
                 from src/MainWindow.h:6,
                 from src/input/InputDriverManager.h:34,
                 from src/LibraryInfo.cc:6:
/usr/include/GLES3/gl31.h:529:74: error: ‘void __glewAttachShader(GLuint, GLuint)’ redeclared as different kind of symbol
 GL_APICALL void GL_APIENTRY glAttachShader (GLuint program, GLuint shader);

**Comment by t-paul** [comment]
You have a Qt version that is compiled against GLES (the mobile API) but OpenSCAD is only compatible with desktop OpenGL. I'm not sure if there's a way to easily change that in OpenSCAD, so the only known way is to use Qt built with desktop OpenGL.
