### ISSUE TITLE
Write manual tests for stop on first error + reload

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2851]
In #2843, we changed some of the logic for how to handle "stop on first error". This logic is a bit convoluted and it's easy to break it again during future refactoring.

-> Write up some manual tests that would fail prior to applying #2843, similarly to how module cache testing is done (https://github.com/openscad/openscad/blob/master/testdata/modulecache-tests/README.txt).

**Comment by nophead** [comment]
I think the module cache tests cover it. Before #2843 the tests which include errors would say "execution aborted" but then carry on, saying it up to three times. Specifically what are now tests 16  and 17.
