### ISSUE TITLE
OS X 10.14.2 [objects/lexer.cxx] Error 1

### ISSUE THREAD

**Issue by ScaredyCat** [openscad/openscad#2859]
I'm not sure where to go with this one, a general error that I can't find anything to give me hints at what's causing this. Any clues?

[Makefile.txt](https://github.com/openscad/openscad/files/2949565/Makefile.txt)

> $ qmake openscad.pro
> Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
> Project MESSAGE: Using ccache
> Project MESSAGE: Using QOpenGLWidget
> Project MESSAGE: Using libc++11
> Project MESSAGE: Using C++11
> Project MESSAGE: 3MF Import/Export disabled
> gort:openscad$ make
> flex -o objects/lexer.cxx --header-file=objects/lexer.hxx src/lexer.l
> make: *** [objects/lexer.cxx] Error 1

Ran it interactively with -v which generated the results below. In both situations the output objects/comment_lexer.cxx is zero bytes. The manual version doesn't appear to generate an error message at all.

> gort:openscad$ flex -vvvvvvv -o objects/comment_lexer.cxx  src/comment_lexer.l
> flex version 2.5.37 usage statistics:
>   scanner options: -vI8 -Cem -oobjects/comment_lexer.cxx -Pcomment_lexer
>   131/2000 NFA states
>   52/1000 DFA states (279 words)
>   20 rules
>   Compressed tables always back-up
>   2/40 start conditions
>   82 epsilon states, 46 double epsilon states
>   32/100 character classes needed 547/750 words of storage, 0 reused
>   459 state/nextstate pairs created
>   107/352 unique/duplicate transitions
>   55/1000 base-def entries created
>   101/2000 (peak 120) nxt-chk entries created
>   6/2500 (peak 66) template nxt-chk entries created
>   0 empty table entries
>   6 protos created
>   3 templates created, 25 uses
>   22/256 equivalence classes created
>   2/256 meta-equivalence classes created
>   0 (1 saved) hash collisions, 60 DFAs equal
>   1 sets of reallocations needed
>   590 total table entries needed

**Comment by t-paul** [comment]
Check where that `flex` binary is coming from or if there are multiple versions installed? Maybe it's calling one from some older install which is now confused by changed shared libs or something.

**Comment by thehans** [comment]
Maybe try a `make clean` then make sure objects dir is empty before running qmake then make again.

**Comment by kintel** [comment]
Also, there's a difference between `lexer.l` and `comment_lexer.l` - make sure you test the right thing

**Comment by kintel** [comment]
Also, where did you get flex? `flex version 2.5.37`
I've got `flex version 2.5.35 Apple(flex-31)`

**Comment by ScaredyCat** [comment]
Ok, I had a version here:

> gort:openscad$ which flex
> /opt/local/bin/flex

So onvestigated, looks like it came from an old macports install. 
> gort:openscad$ which flex
> /usr/bin/flex

> gort:openscad$ flex -V
> flex 2.5.35 Apple(flex-31)

I haven't used macports for a very long time, so much so that I had to upgrade for it to even work. Part of htat process involved uninstalling everything that macports installed - which fixed this issue. 

Thanks for the heads up on the version numbers, I'd totally forgotten about ports being installed :/ - sorry for the error on my part.
