### ISSUE TITLE
Change CFLAGS

### ISSUE THREAD

**Issue by baerbock** [openscad/openscad#2865]
I don't redistribute my binaries, so I would like to compile openscad with

`ccache g++ -c -pipe -DSTACKSIZE=8388608 -fno-strict-aliasing -std=c++11 -O2 -march=native -mtune=native -O3 `
instead of
`ccache g++ -c -pipe -DSTACKSIZE=8388608 -fno-strict-aliasing -std=c++11 -O2 -march=x86-64 -mtune=generic -O2 `

Where are the CFLAGS for Linux defined? I could only find them for OS X.

Thanks in advance!

**Comment by kintel** [comment]
Try `QMAKE_CXXFLAGS += -O3`

**Comment by baerbock** [comment]
@kintel Does `-O3` in a gcc command override a `-O2` in the same line?

**Comment by kintel** [comment]
I'm not sure. Both gcc's and qmake's behavior should be relatively well documented though. Best way is probably to try it.

**Comment by thehans** [comment]
https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Optimize-Options.html

    If you use multiple -O options, with or without level numbers, the last such option is the one that is effective.

**Comment by thehans** [comment]
Also I think you can remove unwanted flags similarly: `QMAKE_CXXFLAGS -= -O2`
