### ISSUE TITLE
QCoreApplication::postEvent: Unexpected null receiver

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#2866]
I see this message from Qt pretty much every time I close OpenSCAD when it was started at command prompt on linux mint 19.  

Don't know if there's any way to debug, there's no exception to catch or anything, just a slightly annoying message.

**Comment by kintel** [comment]
It should be possible to get a stack trace if you build with address sanitation, but I haven't tried that myself

**Comment by kintel** [comment]
It was also mentioned in #2393 as a possible Qt 5.10 issue

**Comment by thehans** [comment]
Yeah it seems to be related to the QSound::play call, and the bug linked from that discussion:
https://bugreports.qt.io/browse/QTBUG-66910

It only happens if I do a render.  If I build with the QSound call commented out it doesn't happen.

I have 5.9.5, looks like the fix applies to 5.9.7.  I'll just close this as its an upstream issue and pretty inconsequential.
