### ISSUE TITLE
Crash on external .scad file change

### ISSUE THREAD

**Issue by paulirotta** [openscad/openscad#2870]
Editing a file in VSCode resulted in a crash. Running PR3.1. I haven't seen the previously with the same workflow on Linux Mint so it may be a recent regression. The editor in OpenSCAD was not visiable. I'll update if I find a more reproducible scenario.

**Comment by t-paul** [comment]
Please try with RC4, there's a crash fix related to warning messages that could be related.

**Comment by paulirotta** [comment]
Not seen so far in RC4. Will update if that changes.

**Comment by t-paul** [comment]
As there's no new report, I'm assuiming it's fixed in RC4 and later.
