### ISSUE TITLE
Allow console window behind others

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2871]
I wanted to have the detached console just poking out the side of the editor/preview.
But console stays in front when the other window is active.
![Capture-console-in-front](https://user-images.githubusercontent.com/1972961/54471724-bf249380-4811-11e9-86bf-0157802ae8dd.JPG)

**Comment by css911** [comment]
@MichaelAtOz, Hi... I Chetan Shinde, a gsoc aspirant can I work on this issue?

**Comment by MichaelAtOz** [comment]
@kintel ?

**Comment by t-paul** [comment]
I'm not sure that is possible. This is how Qt handles the dockable windows. Maybe there's some new stuff in Qt5 we can investigate after dropping Qt4.

**Comment by kintel** [comment]
If you find a way, sure, but this is likely to require significant knowledge of Qt.

**Comment by RomitKumar** [comment]
Resolved at PR #2930

**Comment by MichaelAtOz** [comment]
@RomitKumar Thanks.
