### ISSUE TITLE
Polyhedron does not render when rendering with another object

### ISSUE THREAD

**Issue by xesxen** [openscad/openscad#2873]
Given this SCAD file, the prism is showing on the preview render, but it disappears when rendering.

Sometimes, the console shows `UI-WARNING: Object may not be a valid 2-manifold and may need repair!` (only two triangles of the polyhedron will be visible in that case when rendering), but most of the times it will say `ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /usr/include/CGAL/Nef_S2/SM_const_decorator.h Line: 330` (with the polyhedron not rendering at all)

```OpenSCAD
union(){
    cube([5,2,4]);
    translate([0,0,4])
    triangular_prism(5,2,3);
}

module triangular_prism(x, y, z)
polyhedron(
    points=[
        [0,0,0], [0, y, 0], [0, y, z],
        [x, 0, 0], [x, y, 0], [x, y, z],
    ],
    faces=[
        [0,1,2],
        [3,4,5],
        [0,2,5,3],
        [0,1,4,3],
        [1,2,5,4]
    ]
);
```

**Comment by t-paul** [comment]
The polyhedron has some faces pointing in the wrong direction. See related [FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_is_my_model_showing_up_with_F5_but_not_F6?) entry.
