### ISSUE TITLE
Allow trailing comma in let() or lists

### ISSUE THREAD

**Issue by adrianVmariano** [openscad/openscad#2882]
Other languages like C++ and Python allow a trailing comma in contexts where comma separated lists occur.  This makes it easier to move code around, or add and remove things.  So for example it would be nice to be able to write

    let(
        a=<expression>,
        b=<expression>,
        c=<expression>,
    )

and then if I deleted the third expression, or exchange the order the code still works.  Similarly, it would be nice if I could write

    points =  [
               [1,1],
               [2,2],
               [3,3],
              ]

for the same reason.

**Comment by kintel** [comment]
The second example is already possible, no?

I think it makes sense to extend to other list-like constructs, unless we find conflicting hidden bugs/features that people are abusing : /

**Comment by adrianVmariano** [comment]
Hmm.  Yes, the second example does work.  I thought I had checked it.  The one that's really been driving me crazy is the last comma in let().  

The only other context I can think of is argument lists to functions and modules, and it would probably be nice to allow it there as well.   Are there any other list-like constructs?

**Comment by adrianVmariano** [comment]
I must say that the comma situation in let() statements remains the cause of about 75% of my syntax errors.   It looks like somebody fixed this an issues a PR for it.
