### ISSUE TITLE
REOPENED Can't override include variables

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#289]
While using the Write.scad library, I wanted to change the 't' variable defined in the library by setting it to another variable. I had issues, so I reproduced it in this simple code.

testlib.scad

```
i=1;
```

test.scad

```
include <testlib.scad>      // only has i=1
echo(str(version()));
j=3;
echo("Step 1, i=",i,",j=",j);

/*
 * uncomment step 2 and i becomes undef
 */

/*
// Step 2
i=j;
echo("Step 2, i=",i,",j=",j);
*/
```

Is this intended?

This was also in conjunction with Thingiverse Customisation too, I couldn't use 't' as the customisation variable either, I don't know whether it passes command-line variables or inserts assignment statements inline to override.

**Comment by gaellafond** [comment]
I just found this issue. It's pretty old but still relevant. Thanks @kintel for explaining the distinction between `include` and `use`. I though it was a bug, but it's apparently working as designed.
