### ISSUE TITLE
Animation dumps images with wrong file names.

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#2893]
Capturing discussion on IRC:

> anyone know how to make openscad dump animation png files as ascii numbers and not just increment past the alphabet
> it has non-character values in the filenames so there's newlines and backspaces in the middle of the filename lol

Fix suggestion:

> QString::arg requires a base as the third parameter for int. Without the base apparently that forced the int to a char, and matched it to arg(char a, int fieldWidth = 0, QChar fillChar = QLatin1Char(' '))
> Changing it to QString filename = QString("frame%1.png").arg(this->anim_step, 5, 10, QChar('0')); should fix it.

**Comment by rcolyer** [comment]
Typo fix for clarity: the quoted comment from me explaining the theory of the bug should have read "forced the int to a char".

**Comment by t-paul** [comment]
Thanks, updated.

**Comment by t-paul** [comment]
Hmm, that seems to depend on some version of Qt or gcc or whatever. I can't reproduce that with a local build, but the AppImage fails.

**Comment by t-paul** [comment]
Yep, that change seems to work fine... https://circleci.com/gh/openscad/openscad/2453#artifacts
