### ISSUE TITLE
Incorrect tokenization for negative constants 

### ISSUE THREAD

**Issue by jcoehoorn** [openscad/openscad#2894]
As first seen here:

> https://3dprinting.stackexchange.com/questions/8534/why-is-2-2-2-equal-to-2-in-openscad-mathematical-order-of-operations

This expression:
  
     2 / -2 / 2 

results in `-2`. The expected result is `-.5`.  You can see this with a new empty project with only this statement:

    echo(2 / -2 / 2);

We believe what happens is the expression is evaluated right-to-left, where you first have `2 / 2` from the right side (resulting in `1`), then the `-` operator is applied (now `-1`), and finally the leading division (`2 / -1`) becomes `-2`. Or perhaps it works left-to-right where the bug is the first `/` operator trying to resolve the right-hand side to an integer.

What should happen is the lexer should see the inner `-2` as the same token, so you have a single literal `-2` value hit the parser.

**Comment by t-paul** [comment]
Right, it seems the unary precedence is missing (e.g. like in [this example](https://www.gnu.org/software/bison/manual/html_node/Infix-Calc.html)). Same issue also with `echo(2 / +2 / 2);`
