### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#2905]
Release new version of OpenSCAD.
TODO:
* [x] Decide on final name -> OpenSCAD-2019.04
* [x] Make a final pass of the github Project: https://github.com/openscad/openscad/projects/1
* [x] Make a decision which of the approved PRs should be included (mostly influenced by what would potentially be a blocker for merging into Debian)
* [x] Release notes 
   * [x] complete/cleanup
   * [x] Add the (shift-)alt-arrow shortcuts
* [x] Do a test release to validate the release checklist and scripts. Update docs/scripts as needed
   * [x] Done for macOS / release-common
* [x] Go through all necessary binaries we deliver and validate that they can be built automatically in release mode or be built manually
   * [x] macOS: manually
   * [x] Windows: manually using docker images
   * [x] Linux AppImage: manually using docker image
   * [x] Linux Snap (currently no repo for release, only nightly - probably needs branch)
   * [x] Linux Flatpak (@cosimoc)
* [x] Internal documentation
   * [x] New cmd-line args to man page: https://github.com/openscad/openscad/blob/master/doc/openscad.1 
* [x] Decide on/Create Signing Key
* [x] Make release
* [x] Announce
* [x] Update all signatures and hashes on the download page

**Comment by MikeBenza** [comment]
@kintel Please review #2904 for inclusion in the new release.  I think it'd be a real shame for there to be a major release with a significant (IMHO) UX issue on OS X.

**Comment by kintel** [comment]
@MikeBenza Thx, will do

**Comment by tpimh** [comment]
Flatpak already published by @cosimoc and it is very good, no problems with it.

**Comment by t-paul** [comment]
@tpimh thanks, added a pointer in the checklist.

**Comment by t-paul** [comment]
Flatpak is still just 2015.03 release though. I don't know if it's possible to also add RCs for the upcoming release without overwriting the old release.

**Comment by donbright** [comment]
i would highly recommend not use Docker for official realase, its a massive security risk. 

they just got hacked, actually.

**Comment by darkworks** [comment]
please update windows build exe on official site

thanks

**Comment by tpimh** [comment]
Flatpak is still not updated. @goncalossilva tried, but as far as I know there were no successful builds.

**Comment by t-paul** [comment]
You already opened an issue on the flatpak repo, which is the correct place. Not much that can be done here other then pointing there.
