### ISSUE TITLE
text() do not support Chinese

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#2910]
Change Chinese to unicode can not display too.

**Comment by nophead** [comment]
Which version?

The latest version seems to:

![image](https://user-images.githubusercontent.com/566149/55326404-90e4bc00-547f-11e9-9fd2-2bdeb5808fe9.png)

**Comment by t-paul** [comment]
Please share a specific example. Also note that OpenSCAD has no layout engine for `text()` which means only text shaping is supported, but no automatic layout and font substitution. So you have to specify a font which actually contains glyphs for the characters given.

**Comment by sonichy** [comment]
I know, if non-english should set font parameter.
And preview is sucess, render is flat when do not rotate, disappear when rotate.

**Comment by MichaelAtOz** [comment]
Note that text() is 2D, if you want it to have height make it 3D with linear_extrude()

**Comment by sonichy** [comment]
**text() is 2D, if you want to make it 3D should add linear_extrude()** should be written in wiki.
It is OK now.
```
rotate([90,0,0])
linear_extrude(height=5)
text("海天鹰",font="华文行楷");
```

**Comment by t-paul** [comment]
Where is that information missing? It's in the first paragraph in the [manual](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Text). Any other place that should be added?
