### ISSUE TITLE
How to export big image?

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#2917]
How to export big image in Preview and Render mode ?

**Comment by kintel** [comment]
Please use #openscad on freenode or the mailing list as a support channel

**Comment by MichaelAtOz** [comment]
@sonichy See [this](http://forum.openscad.org/Registration-amp-Subscription-Info-READ-THIS-FIRST-td21660.html) to register to the [forum](http://forum.openscad.org/).

**Comment by t-paul** [comment]
I've seen that question before, so I've added a [FAQ entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#How_can_I_export_screenshots_with_higher_resolution_than_the_current_window) for this too.

**Comment by sonichy** [comment]
Why not support a gui to set export ?

**Comment by kintel** [comment]
It's not that simple. As a Qt developer I'm sure you can follow the threads starting here: https://github.com/openscad/openscad/blob/master/src/mainwin.cc#L2598

We do accept patches though :)

**Comment by sonichy** [comment]
After seen https://github.com/openscad/openscad/blob/master/src/mainwin.cc#L2598 , the GUI exprot image is
```
QImage QOpenGLWidget::grabFramebuffer()
```
Where is the command line export source code ?
```
openscad --imgsize 16000,16000 -o CSG.png CSG.scad
```

**Comment by kintel** [comment]
https://github.com/openscad/openscad/blob/406dd378003018fd01281787382acd3c1037c57d/src/export_png.cc#L54

**Comment by sonichy** [comment]
openscad build failed, fatal error: glib.h: No such file or directory
But I made a demo: https://github.com/sonichy/QOpenGL
```
QSize size = openGLWidget->size();
openGLWidget->resize(spin_width->value(),spin_height->value());
QImage image = openGLWidget->grabFramebuffer();
image.save(path,0,100);
openGLWidget->resize(size);
```
