### ISSUE TITLE
Editor treats hash # modifier as a comment

### ISSUE THREAD

**Issue by stgnet** [openscad/openscad#2929]
When adding a hash # modifier to a line of code, the editor treats it as a comment.  The line is greyed out, and if there is a { on the line then adding a } later in the same block will be incorrectly indented (since it doesn't believe the { is valid code as it's in a comment).

The edit should instead mostly ignore the # modifier, which would result in normal coloring and correct braces.

**Comment by t-paul** [comment]
Duplicate of #1172.
