### ISSUE TITLE
Copy viewport rotation produces scientific notation numbers with low precision

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#2940]
![image](https://user-images.githubusercontent.com/566149/57044238-d6a0ca00-6c61-11e9-97b3-5189db7a3b4e.png)

[ 2.6e+02, 0, 3.3e+02 ]

It seems to occur when the numbers exceed 99.

**Comment by nophead** [comment]
Looks like this commit broke it. https://github.com/openscad/openscad/commit/2bed5189ddeb1fccc7c6c709ac6c881d9d38d639

**Comment by donbright** [comment]
automatic regression test for the GUI would help catch this stuff. 

sprintf  should be replaced with asprintf not something that behaves differently. 

https://doc.qt.io/qt-5/qstring-obsolete.html

**Comment by t-paul** [comment]
It actually says: "Use asprintf(), arg() or QTextStream instead.". So `arg()` is one of the options officially proposed as replacement. The problem seems to be that `arg()` is too heavily overloaded so in some cases it's picking a different implementation not the intended one (see #2897).
