### ISSUE TITLE
Variable = variable multiplied by something

### ISSUE THREAD

**Issue by dimitre** [openscad/openscad#2945]
Hello, first of all this project is awesome!
I'm having an issue trying to multiply one variable and reassigning it.

Not sure if this is the intended way OpenSCAD is meant to work but I can use this in any other programming language, example:
```c++
scale = 1.0;

for (a = [0:5]) {
    scale = scale * .9;
    echo (scale);    
}
```
Result:
```
ECHO: 0.9
ECHO: 0.9
ECHO: 0.9
ECHO: 0.9
ECHO: 0.9
ECHO: 0.9
```

Trying to create a minimal example now:
```c++
raio = 1.0;
echo (raio);
raio = raio * 0.9;
echo (raio);
```

results
```
WARNING: raio was assigned on line 1 but was overwritten on line 3
Compiling design (CSG Tree generation)...
WARNING: Ignoring unknown variable 'raio', in file ./, line 3.
ECHO: undef
ECHO: undef
```

And it would be great if we could use this too
```c++
raio *= 0.9;
```

Cheers, 
Dimitre

**Comment by nophead** [comment]
See https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_Language#Variables.

This is intended behaviour.
