### ISSUE TITLE
localization in parameters panel

### ISSUE THREAD

**Issue by JSkrat** [openscad/openscad#2958]
Can I please have dot as decimal point to be allowed in parameters panel instead of or along with comma despite openscad picked russian language? 
Not-english decimal point is useless as code in english with dot as decimal point.

Btw, disabling localization does not affect that, delimiters are still localized(

**Comment by t-paul** [comment]
Can you please clarify if you see a bug that makes the Customizer parameter non-functional or if this is more about fixing the display to be the same in both places.

Using this example...
![grafik](https://user-images.githubusercontent.com/1330241/58735612-34f4d000-83fb-11e9-85cf-faf4384f6641.png)
I see the display effect you describe, but it does generate the correct values for the model generation, e.g. while the Customizer GUI shows `3,4`, it's actually using `3.4` value for the cube.

**Comment by t-paul** [comment]
Closing, no feedback.

**Comment by JSkrat** [comment]
sorry for long reply. 
It is about consistency. I always should remember that this field requires comma, despite everywhere else (in code) i'm using dot. I can get used to it, but why?

**Comment by t-paul** [comment]
I still don't get what you mean, sorry.
Setting the locale to english, the customizer shows `3.4` in the customizer window and uses value 3.4. When setting the language to German (which has ',' as decimal separator), the customizer shows `3,4` and the value used is 3.4.

So are you saying you want to set the language to russian (which I suppose also uses `,` as decimal separator) but still want the GUI control to use 3.4?

**Comment by JSkrat** [comment]
at the computer with russian system locale customizer shows and (the most importantly) accepts only comma, despite the localization settings of the openscad itself. Dot even can not be entered.

Also, while trying i've found that if initial value of the parameter is round (tried even 25.0), you can not enter part after the comma/dot, field does not accept anything after comma. Not sure if it is bug or not

**Comment by JSkrat** [comment]
and yes, personally i hate that different locales has same digits, but different decimal separator, so for me it would be much more convenient if the field for every locale will accept dot too :)

**Comment by JSkrat** [comment]
@t-paul can you reopen please? 9_9

**Comment by t-paul** [comment]
You are asking for a change in Qt, so reopening here would not help.
