### ISSUE TITLE
implement an optmizer module for 2d panels

### ISSUE THREAD

**Issue by felipesanches** [openscad/openscad#296]
Very often I use openscad for designing projects for the laser cutter. One common problem faced is that we need to position the 2d shapes in a panel for production in a laser cutter.

Nowadays I manually position the 2d shapes. Ideally I think it would be awesome to have an openscad module that implemented an optmization algorithm to have the best usage of the laser cutter panel.

I would be happy to mentor this as a google summer of code project if there's any student interested in implementing it. Otherwise, please consider it as a usual feature request. I may even try implementing it someday when I have some free time.

happy hacking,
Felipe Sanches
##

**Comment by t-paul** [comment]
I think we can close this. I'd agree that it's still a bit out of scope for OpenSCAD and no progress for 5 years.

**Comment by nophead** [comment]
https://svgnest.com/ Open Source nesting will do it as a post process, which is where I think it belongs.
