### ISSUE TITLE
emacs scad-mode crashes on lines starting with #

### ISSUE THREAD

**Issue by adrianVmariano** [openscad/openscad#2969]
The contrib directory provides a mode for emacs, scad-mode.el.  This mode has lead to random mysterious crashes of emacs.  I managed to repeat the problem: if I open a new file and type "#a=(" then emacs crashes.  

The cause of the problem is that 

     (c-init-language-vars scad-mode)

is never called.   The documentation for c-basic-common-init indicates that you must call c-init-language-vars first.   The above line needs to be inserted above the line that reads 

     (c-basic-common-init 'scad-mode (or scad-indent-style "k&r"))

**Comment by t-paul** [comment]
The contrib directory, as the name implies, is external contributed stuff which is not maintained in this repo but provided here for convenience.

So if someone who can actually test this change could provide a pull request that would be great.

**Comment by adrianVmariano** [comment]
So I've noticed that I'm getting an error message from the line I added.  So I think it's not actually the solution to the problem, unfortunately.  It "fixed" the problem by breaking the mode.

**Comment by henwist** [comment]
I have tested this and can confirm that emacs locked and put CPU on 100% when input "#a=(" in the editor's window.

> I am on  GNU Emacs 26.1 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.4) of 2019-02-03, modified by Debian buster/unstable

**Comment by adrianVmariano** [comment]
I've done further testing and found that just typing "#(" causes the crash, and actually instead of '(' any one of []{}() will do the job.   But I have not managed to figure out the correct way to fix it.
