### ISSUE TITLE
OpenSCAD (Not Responding)

### ISSUE THREAD

**Issue by agnunez** [openscad/openscad#2980]
Just intalled OpenSCAD-2019.05-x86-64 in windows 10 and I work with it for one day withiot problem. Next day, it opens and I can load my scripts or even examples, but just after few second it hangs showing (Not Responding). Re-installed both, msi and zip. Unplug 3dconnexion hand controller, just in case it was the cause. No error in Event Viewer. Only way to exit is to "End Task" in Task Manager.
Any place to look for error logging to solve it?

**Comment by thehans** [comment]
If you run `openscad.com` from the command line does it print out anything to the console?
If openscad directory is not in your PATH, then you may need to give the full path: 
```"c:\Program Files\OpenSCAD\openscad.com"```

Also you can try `openscad.com --debug all` to which will log a ton of various messages to console.

Lastly, pasting the output from Help -> Library Info here might help narrow things down some.

**Comment by agnunez** [comment]
I did openscad.com --debug all  in its directory within CMD. It opesn the program, pop up choice for projects works, choose anyone (Basic/logo.scad), and log many setting options lines to the console until it stop at the middle of word SettingWriter ....
....
SettingsWriter: SettingsWriter D: input/button0
SettingsWriter: SettingsWriter D: input/button1
SettingsWriter: SettingsWriter D: input/button2
Settin
...
full listing: https://drive.google.com/file/d/14r0Rc3Z8ZMahC2b270Yxv3YVEqxdGzVY/view?usp=sharing

Mouse change to waiting icon and (Not Responding) at top program name.

Thanks

**Comment by MichaelAtOz** [comment]
One would question why it goes through SettinsWriter sooo many times...

> Unplug 3dconnexion hand controller

Which specific device, they have different driver parameters.
Do you have the 3Dconnection drivers loaded (ie for some Windows app)?

Were you running any of the 2019 pre-release snapshots with SpaceMouse, or came straight from 2015.03?

> Lastly, pasting the output from Help -> Library Info here might help narrow things down some.

**Comment by thehans** [comment]
Another thing I would recommend trying is to disable/enable the different input drivers from OpenSCAD preferences and see if any of those are the cause (change and then restart OpenSCAD).  

If you can't get to the menu before freezing, you can toggle these in registry settings: 
run regedit.exe
Look under `Computer\HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\input` and try setting the enable* registry keys to false/true.

Some past issues with input driver related code have caused similar problems: #2854 #2578

**Comment by agnunez** [comment]
> One would question why it goes through SettinsWriter sooo many times...
> 
> > Unplug 3dconnexion hand controller
> 
> Which specific device, they have different driver parameters.
> Do you have the 3Dconnection drivers loaded (ie for some Windows app)?
> 
> Were you running any of the 2019 pre-release snapshots with SpaceMouse, or came straight from 2015.03?
> 
> > Lastly, pasting the output from Help -> Library Info here might help narrow things down some.

I installed stable 2015.03. Previously my W10 was having the 3DConnexion SpaceMouse Compact edition. Do you recommend to test any pre-release version? Thanks

**Comment by agnunez** [comment]
> Another thing I would recommend trying is to disable/enable the different input drivers from OpenSCAD preferences and see if any of those are the cause (change and then restart OpenSCAD).
> 
> If you can't get to the menu before freezing, you can toggle these in registry settings:
> run regedit.exe
> Look under `Computer\HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\input` and try setting the enable* registry keys to false/true.
> 
> Some past issues with input driver related code have caused similar problems: #2854 #2578

Sorry, but I don't have input key as children of OpenSCAD one. Only register keys are 3dview, advanced, desing, editor, launcher, view, window
Editor contains ctrlmousewheelzoom true. Switched of to false, and relaunched, with no effect.
Thanks

**Comment by agnunez** [comment]
> If you run `openscad.com` from the command line does it print out anything to the console?
> If openscad directory is not in your PATH, then you may need to give the full path:
> `"c:\Program Files\OpenSCAD\openscad.com"`
> 
> Also you can try `openscad.com --debug all` to which will log a ton of various messages to console.
> 
> Lastly, pasting the output from Help -> Library Info here might help narrow things down some.

I tried a zip of 2019.05.19.ci2704 version with same frozen result. This time log stops later:
QSettingsCached: QSettings::setValue(): recentFileList = ''
QSettingsCached: QSettings::setValue(): view/hideEditor = 'false'
QSettingsCached: QSettings::setValue(): view/hideEditor = 'false'
QSettingsCached: QSettings::setValue(): view/hideCustomizer = 'false'
QSettingsCached: QSettings::setValue(): view/hideCustomizer = 'true'
QSettingsCached: QSettings::setValue(): view/hideConsole = 'false'
QSettingsCached: QSettings::setValue(): view/hideConsole = 'false'
QSettingsCached: QSettings::setValue(): view/hideConsole = 'false'
QSettingsCached: QSettings::setValue(): view/hideEditor = 'false'
QSettingsCached: QSettings::setValue(): view/hideToolbar = 'false'
QSettingsCached: QSettings::setValue(): view/hideCustomizer = 'true'
QSettingsCached: QSettings::setValue(): view/showAxes = 'true'
QSettingsCached: QSettings::setValue(): view/showScaleProportional = 'true'
QSettingsCached: QSettings::setValue(): view/orthogonalProjection = 'false'
QSettingsCached: QSettings::setValue(): design/autoReload = 'true'

but freeze anyway.  I cannot access to help->library menu because it hang before allowing me to...
thanks

**Comment by MichaelAtOz** [comment]
> I installed stable 2015.03. Previously my W10 was having the 3DConnexion SpaceMouse Compact edition. Do you recommend to test any pre-release version? Thanks

Pre-release versions? No, not at this stage. As you came from 2015.03, you had not had any previous SpaceMouse OpenSCAD use.

@t-paul did you get exposed to the 'compact edition'? 

> Previously my W10 was having the 3DConnexion SpaceMouse Compact edition. 

So, as you were NOT using SpaceMouse for OpenSCAD, you were presumably using it for some other Windows app?
Reason I ask, to do so you must have loaded the 3dconnextion Windows Driver? Correct?

**Comment by agnunez** [comment]
> > I installed stable 2015.03. Previously my W10 was having the 3DConnexion SpaceMouse Compact edition. Do you recommend to test any pre-release version? Thanks
> 
> Pre-release versions? No, not at this stage. As you came from 2015.03, you had not had any previous SpaceMouse OpenSCAD use.
> 
> @t-paul did you get exposed to the 'compact edition'?
> 
> > Previously my W10 was having the 3DConnexion SpaceMouse Compact edition.
> 
> So, as you were NOT using SpaceMouse for OpenSCAD, you were presumably using it for some other Windows app?
> Reason I ask, to do so you must have loaded the 3dconnextion Windows Driver? Correct?

Yes, I use 3dconnexion with other CAD program and was installed previously to  install OpenScad   2015.03 in this pc. I use to work with older version in other computers. The weird thing is that I used for a day or two (without 3dconnexion) and following that, it came this "Not Responding" issue, without altering the configuration.

**Comment by t-paul** [comment]
Not sure if all issues are solved. It should be detected and at least do something. The tests were on MacOS though: http://forum.openscad.org/Inputdriver-on-MacOS-td25528i20.html

**Comment by MichaelAtOz** [comment]
You can get the Help->Library info from the command line `openscad --info`

> I don't have input key as children of OpenSCAD one. Only register keys are 3dview, advanced, desing, editor, launcher, view, window

`input` only appears after you check any `Driver selection` boxes in `Preferences/Axis`.
But `InputDriver` should be there.
It is hanging at `QSettingsCached: QSettings::setValue(): design/autoReload = 'true'` the next registry key is `editor`...it is not getting to output the `InputDriver` key. However, I just tried `--debug all` and got to `New`, t crashed, but theere was only a sort debug outout, so I think there is some output lost. But apparently it was working for a day, so I don't know why those keys are NOT there... 

So start simple.
Change  registry key `HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\design\autoReload` to false.
This will prevent auto F5 after loading a .scad.
Run OpenSCAD, select 'New', if it starts, do File/Exit. This hopefully writes a full set of registry keys.
Try again, type `cube();` press F5. Press F6. This is trying to see at what step it hangs.
If that works load something complex, F5, F6.

**Comment by agnunez** [comment]
> You can get the Help->Library info from the command line `openscad --info`
> 
> > I don't have input key as children of OpenSCAD one. Only register keys are 3dview, advanced, desing, editor, launcher, view, window
> 
> `input` only appears after you check any `Driver selection` boxes in `Preferences/Axis`.
> But `InputDriver` should be there.
> It is hanging at `QSettingsCached: QSettings::setValue(): design/autoReload = 'true'` the next registry key is `editor`...it is not getting to output the `InputDriver` key. However, I just tried `--debug all` and got to `New`, t crashed, but theere was only a sort debug outout, so I think there is some output lost. But apparently it was working for a day, so I don't know why those keys are NOT there...
> 
> So start simple.
> Change registry key `HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\design\autoReload` to false.
> This will prevent auto F5 after loading a .scad.
> Run OpenSCAD, select 'New', if it starts, do File/Exit. This hopefully writes a full set of registry keys.
> Try again, type `cube();` press F5. Press F6. This is trying to see at what step it hangs.
> If that works load something complex, F5, F6.
here it is:

openscad --info
OpenSCAD Version: 2019.05
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 12 CPUs 15.85 GB RAM
User Agent: OpenSCAD/2019.05 (Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833)
Compiler: GCC "7.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.11, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.2
QScintilla version: 2.10.4
InputDrivers:
GLib version: 2.50.2
lodepng version: 20180910
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.0.2
lib3mf version: 1.8.0
Application Path: C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05
Documents Path: C:\Users\anunez\Documents
User Documents Path: C:\Users\anunez\Documents
Resource Path: C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05
User Library Path: C:/Users/anunez/Documents/OpenSCAD/libraries
User Config Path: C:\Users\anunez\AppData\Local/OpenSCAD
Backup Path: C:/Users/anunez/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  C:/Users/anunez/Documents/OpenSCAD/libraries
  C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  C:/Windows/fonts
  C:/Users/anunez/.local/share/fonts
  C:/Users/anunez/.fonts


GLEW version: 1.12.0
OpenGL Version: 4.5.0 - Build 25.20.100.6374
GL Renderer: Intel(R) UHD Graphics 630
GL Vendor: Intel
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes
GL context creator: WGL
PNG generator: lodepng
OS info: Microsoft(TM) Windows(TM) 10 0 17134 0x309ecb4 amd64
Machine: 8664

**Comment by agnunez** [comment]
> You can get the Help->Library info from the command line `openscad --info`
> 
> > I don't have input key as children of OpenSCAD one. Only register keys are 3dview, advanced, desing, editor, launcher, view, window
> 
> `input` only appears after you check any `Driver selection` boxes in `Preferences/Axis`.
> But `InputDriver` should be there.
> It is hanging at `QSettingsCached: QSettings::setValue(): design/autoReload = 'true'` the next registry key is `editor`...it is not getting to output the `InputDriver` key. However, I just tried `--debug all` and got to `New`, t crashed, but theere was only a sort debug outout, so I think there is some output lost. But apparently it was working for a day, so I don't know why those keys are NOT there...
> 
> So start simple.
> Change registry key `HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\design\autoReload` to false.
> This will prevent auto F5 after loading a .scad.
> Run OpenSCAD, select 'New', if it starts, do File/Exit. This hopefully writes a full set of registry keys.
> Try again, type `cube();` press F5. Press F6. This is trying to see at what step it hangs.
> If that works load something complex, F5, F6.

I changed HKEY_CURRENT_USER\Software\OpenSCAD\OpenSCAD\design\autoReload to false, and pass the pop up with "New" (or any sample .scad), but the app windows appear and mouse already is irresponsible and cannot click on File/Exit or any place.
Thanks

**Comment by MichaelAtOz** [comment]
> Resource Path: C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05

Are you trying to run it from that location?
Windows requires programs to be under `C:/Program Files`.

**Comment by agnunez** [comment]
> > Resource Path: C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05
> 
> Are you trying to run it from that location?
> Windows requires programs to be under `C:/Program Files`.

I've tried everything, run with installer from c:/Program Files.. , run zip version from a directory.. run other versions..

**Comment by agnunez** [comment]
> > Resource Path: C:/Users/anunez/Downloads/OpenSCAD-2019.05-x86-64/openscad-2019.05
> 
> Are you trying to run it from that location?
> Windows requires programs to be under `C:/Program Files`.

running from standard installation... same results.

C:\Program Files\OpenSCAD>openscad --info
OpenSCAD Version: 2019.05
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 12 CPUs 15.85 GB RAM
User Agent: OpenSCAD/2019.05 (Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833)
Compiler: GCC "7.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.11, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.2
QScintilla version: 2.10.4
InputDrivers:
GLib version: 2.50.2
lodepng version: 20180910
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.0.2
lib3mf version: 1.8.0
Application Path: C:/Program Files/OpenSCAD
Documents Path: C:\Users\anunez\Documents
User Documents Path: C:\Users\anunez\Documents
Resource Path: C:/Program Files/OpenSCAD
User Library Path: C:/Users/anunez/Documents/OpenSCAD/libraries
User Config Path: C:\Users\anunez\AppData\Local/OpenSCAD
Backup Path: C:/Users/anunez/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  C:/Users/anunez/Documents/OpenSCAD/libraries
  C:/Program Files/OpenSCAD\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  C:/Windows/fonts
  C:/Users/anunez/.local/share/fonts
  C:/Users/anunez/.fonts


GLEW version: 1.12.0
OpenGL Version: 4.5.0 - Build 25.20.100.6374
GL Renderer: Intel(R) UHD Graphics 630
GL Vendor: Intel
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes
GL context creator: WGL
PNG generator: lodepng
OS info: Microsoft(TM) Windows(TM) 10 0 17134 0x309ecb4 amd64
Machine: 8664

**Comment by MichaelAtOz** [comment]
hmmm, I'm grasping at straws now...
Try disabling any antivirus.
Try removing the 3Dconnexion drivers.
Backup the Registry, then delete the whole `HKEY_CURRENT_USER\Software\OpenSCAD` branch.
Try the 32bit version.
See if there is a newer display driver.

**Comment by agnunez** [comment]
Great! At least you indicated me where to grasp. Finally is a interaction with NVDIA GTX 1060 second monitor. If I start with the hdmi of this external monitor unplugged, it works! Later, I can plug in it again and it works even in the second one. I even enabled HIDAPI and SpaceMouse is working. Thanks to your support.

**Comment by MichaelAtOz** [comment]
Great.
For the next time, did you need to do anything, like removing the 3Dconnexion drivers, to fix it, or JUST unplug the 2nd monitor? 
Did you have this 2nd monitor unplugged when it worked for a day?

Could you post a Help/Library info from the GUI, it usually has more monitor info.

**Comment by agnunez** [comment]
Hi,
I got another simpler solution. I actually have 3 monitors (2 external hdmi+displayport+laptop). The problem appears when OpenScad start on one of the external monitors (open the windows on that monitor). For some reason, the 1st day I was working, I shift OS windows to my hdmi monitor and close the app there, so next day I launched, it also tried to open the windows there and cause the issue. 
The first time I unplug the monitor, it again have to start the windows in the laptop internal display and works there, and once is working, I can shift the OS windows to my hdmi larger monitor without problem. So long story short, the solution is just to always close the OS app inside the laptop internal monitor, and open it up again on the same... later.. I can move it anywhere. thanks

This is the help/library info with 3 monitors:

OpenSCAD Version: 2019.05
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 12 CPUs 15.85 GB RAM
User Agent: OpenSCAD/2019.05 (Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833)
Compiler: GCC "7.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.11, Cartesian, Extended_cartesian, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.2
QScintilla version: 2.10.4
InputDrivers: HidApiInputDriver (256f:c635 - 3Dconnexion Space Mouse Compact)*
GLib version: 2.50.2
lodepng version: 20180910
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.0.2
lib3mf version: 1.8.0
Application Path: C:/Program Files/OpenSCAD
Documents Path: C:\Users\anunez\Documents
User Documents Path: C:\Users\anunez\Documents
Resource Path: C:/Program Files/OpenSCAD
User Library Path: C:/Users/anunez/Documents/OpenSCAD/libraries
User Config Path: C:\Users\anunez\AppData\Local/OpenSCAD
Backup Path: C:/Users/anunez/Documents/OpenSCAD/backups
OPENSCADPATH: 
OpenSCAD library path:
C:/Users/anunez/Documents/OpenSCAD/libraries
C:/Program Files/OpenSCAD\libraries

OPENSCAD_FONT_PATH: 
OpenSCAD font path:
C:/Windows/fonts
C:/Users/anunez/.local/share/fonts
C:/Users/anunez/.fonts
GLEW version: 1.12.0
OpenGL Version: 4.5.0 - Build 25.20.100.6374
GL Renderer: Intel(R) UHD Graphics 630
GL Vendor: Intel
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QGLWidgetGL Extensions:
GL_3DFX_texture_compression_FXT1
GL_AMD_depth_clamp_separate
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_cl_event
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_robustness_isolation
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_bit_encoding
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_separate_stencil
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_clip_volume_hint
GL_EXT_compiled_vertex_array
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_polygon_offset_clamp
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shader_framebuffer_fetch
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_compression_s3tc
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_IBM_texture_mirrored_repeat
GL_INTEL_conservative_rasterization
GL_INTEL_fragment_shader_ordering
GL_INTEL_framebuffer_CMAA
GL_INTEL_map_texture
GL_INTEL_multi_rate_fragment_shader
GL_INTEL_performance_query
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_texture_compression_astc_hdr
GL_KHR_texture_compression_astc_ldr
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_primitive_restart
GL_NV_texgen_reflection
GL_SGIS_generate_mipmap
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SUN_multi_draw_arrays
GL_WIN_swap_hint
WGL_EXT_swap_control

thanks

**Comment by 1klap** [comment]
I can confirm this. I have a PC with dual screen setup, and if the OpenSCAD window with the 3d-view is opened on the secondary screen, the program will hang.  Unplugging the second monitor helps. And as @agnunez writes, if the program is closed on one screen, Windows seems to remember to reopen it again on that one, so the monitor does not need to be unplugged every time, as long as OpenSCAD is closed on the main screen.

OpenSCAD Version: 2019.05
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 4 CPUs 15.93 GB RAM
User Agent: OpenSCAD/2019.05 (Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833)
Compiler: GCC "7.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_60
Eigen version: 3.2.5
CGAL version, kernels: 4.11, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.11.2
QScintilla version: 2.10.4
InputDrivers:
GLib version: 2.50.2
lodepng version: 20180910
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.0.2
lib3mf version: 1.8.0
Application Path: c:/Program Files/OpenSCAD
Documents Path: C:\Users\<edited>\Documents
User Documents Path: C:\Users\<edited>\Documents
Resource Path: c:/Program Files/OpenSCAD
User Library Path: C:/Users/<edited>/Documents/OpenSCAD/libraries
User Config Path: C:\Users\<edited>\AppData\Local/OpenSCAD
Backup Path: C:/Users/<edited>/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  C:/Users/<edited>/Documents/OpenSCAD/libraries
  c:/Program Files/OpenSCAD\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  C:/WINDOWS/fonts
  C:/Users/<edited>/.local/share/fonts
  C:/Users/<edited>/.fonts


GLEW version: 1.12.0
OpenGL Version: 4.6.0 NVIDIA 436.02
GL Renderer: GeForce GTX 980 Ti/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes
GL context creator: WGL
PNG generator: lodepng
OS info: Microsoft(TM) Windows(TM) 10 0 18362 0x309ec84 amd64
Machine: 8664

**Comment by jhoffmann2** [comment]
> Great. For the next time, did you need to do anything, like removing the 3Dconnexion drivers, to fix it, or JUST unplug the 2nd monitor? Did you have this 2nd monitor unplugged when it worked for a day?
> 
> Could you post a Help/Library info from the GUI, it usually has more monitor info.

oh my god I had the same issue and this fixed it. What a strange bug! I wish the dev team luck finding it! 🤣
