### ISSUE TITLE
Crosshairs does not follow the zoon in or out (movin with origin? )

### ISSUE THREAD

**Issue by pchar** [openscad/openscad#2982]
On the latest version 2019.5  (mac os x ) cross air does not follow the zoom, 
you must calll the "center" menu to re-allign its 

![image](https://user-images.githubusercontent.com/197608/60461782-db750080-9c47-11e9-9246-015428aec308.png)

**Comment by t-paul** [comment]
Yes, that is what they are supposed to do: https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/The_OpenSCAD_User_Interface#Show_Crosshairs_(Ctrl+3)
