### ISSUE TITLE
difference() doesn't commute

### ISSUE THREAD

**Issue by Vector5233** [openscad/openscad#2985]
Hi,

New to openSCAD, so I apologize if this is user error.

I run this and get desired behavior (image 1):

`translate([-150,-150]) {

difference() {
    color("yellow") square(22);
    color("yellow") translate([2,2]) square(18);
}
color("black", alpha = 0.05) square(size = [355,295], center = false);
color("yellow", alpha = 0.1) translate([-90,162]) square(size = [90,73],center=false);
}`  

I move the difference to a later point and it fails to subtract the inner square (image 2):

`color("black", alpha = 0.05) square(size = [355,295], center = false);

difference() {
    color("yellow") square(22);
    color("yellow") translate([2,2]) square(18);
}
color("yellow", alpha = 0.1) translate([-90,162]) square(size = [90,73],center=false);
}`

![Image 1](https://user-images.githubusercontent.com/13908960/60743799-11183300-9f41-11e9-80ff-6e9643f84a43.png)
![Image 2](https://user-images.githubusercontent.com/13908960/60743800-11183300-9f41-11e9-98f5-75d9962db466.png)

I can work around this by creating the difference first ... but why is it necessary??

**Comment by t-paul** [comment]
I think that is just Z-Figthing ([see FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_are_those_strange_flickering_artifacts_in_the_preview?))

If I zoom in to that area, it start to tear the colors as the graphics card can't decide which of the planes to draw.
![grafik](https://user-images.githubusercontent.com/1330241/60744301-9ae1f380-9f75-11e9-9906-f1469fc9ffbc.png)

**Comment by t-paul** [comment]
Closing as there's no feedback.
