### ISSUE TITLE
File/Recent-files does not handle '&' in filename

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#2988]
at least on Windows.
`&` in menu titles flags the following character as the keyboard shortcut and displays it as underscored.
Having previously opened a file with `&` in the name, shows that file in the Recent-files list, wrongly.
![Recent files](https://user-images.githubusercontent.com/1972961/60945937-41404700-a330-11e9-915b-64800a863de1.png)
Note the actual filename in the title bar.
Whatever the fix is, it should probably be also applied to the examples menu, as it is possible such a file could be there in the future.

**Comment by RomitKumar** [comment]
Made pr #2989 solving the issue.

**Comment by MichaelAtOz** [comment]
![pr2989](https://user-images.githubusercontent.com/1972961/61104208-c8b8c200-a4b8-11e9-9958-1f1e661cbea9.JPG)

Fixed, thanks.

**Comment by MichaelAtOz** [comment]
Should I close such issues or leave open so it gets included in a release, or add it to some list?

**Comment by t-paul** [comment]
Yes, closing is fine. Using `(fixes #2988)' in the checkin comment would even close automatically when merged to master.
