### ISSUE TITLE
len() fails in echo()

### ISSUE THREAD

**Issue by indazoo** [openscad/openscad#2992]
Hi 
I have a simple case:

echo(len(8));

gives : 
"WARNING: len() parameter could not be converted, in file ./, line 1"

Tested in:
OpenSCAD version 2019.05.19.ci2703 (git 92550dec) 
OpenSCAD version 2019.05 (official release)

**Comment by indazoo** [comment]
Never mind, I didn't knew len does not work for numbers but only for strings and vectors.
I use echo(len(str(8)));

**Comment by nophead** [comment]
Yes it used to work and was useful. Now on has to write more code to do the same thing.

**Comment by t-paul** [comment]
From the second comment it sounds more like the warning actually helped preventing unexpected errors.
