### ISSUE TITLE
Customizer: negative list value visual display bug

### ISSUE THREAD

**Issue by sjdevries** [openscad/openscad#2995]
It seems that negative values, for lists only, are displayed as zero in the Customizer.  Note that the actual value stored is correct, only the Customizer GUI display is bugged.

The following code example shows a standard variable displaying correctly, as well as a list with a negative number that does not display correctly.

You can also see the output of the echo statement, which prints the default value without issue.  It also prints out any negative values input into the Customizer correctly.

**Test_List.scad**
```
Test_List  = [1.50, .03, -.03];   // [-100:0.01:100]
echo(Test_List [2]);

Test_Negative = -0.03;   // [-100:0.01:100]
```

**Comment by MichaelAtOz** [comment]
Confirmed in 2019.05 Win7/64.
If you press up-arrow (in GUI) it goes to 0.01 (v's having to press it 4 times 0.01 to get there from -0.03), and then down-arrow goes to 0.00 then -0.01...so it works after that.
