### ISSUE TITLE
PPA is out of date

### ISSUE THREAD

**Issue by jangxx** [openscad/openscad#2997]
OpenSCAD 2019.05 has been out for more than two months now, but the PPA still only contains 2015.03. Are there any plans of updating the PPA? Sure I could use the AppImage, but installing stuff via a package manager is just a lot nicer and it also integrates better into the system.

**Comment by t-paul** [comment]
I'm closing as the PPA is not maintained by the dev team.
However @hyperair is listed on launchpad and might be able to provide some info.
For questions about the PPA, please create tickets there.
