### ISSUE TITLE
Color is not working in render mode / ubuntu (2019.01-RC2)

### ISSUE THREAD

**Issue by reubenfirmin** [openscad/openscad#2999]
Here is my model:

```
color([0,1,0.99]) {
    difference() {
        union() {
            cube([20, 120, 20]);
            translate([60, 0, 0]) {
                cube([20, 120, 20]);
            }
            cube([80, 120, 5]);
            translate([0, 120, 0]) {
                cube([80, 20, 20]);
            }
        }   
        translate([20, 100, 0]) {
            cube([40, 20, 5]);
        }
    }
}
```

In preview I get:

![screenshot-2019-07-20-15-38-27](https://user-images.githubusercontent.com/14217993/61583314-7bfe6800-ab04-11e9-901a-e14aa49fa72c.png)

In render I get:

![screenshot-2019-07-20-15-38-35](https://user-images.githubusercontent.com/14217993/61583317-828cdf80-ab04-11e9-95dd-81c59aadf30e.png)

**Comment by t-paul** [comment]
Color is currently only supported in Preview mode.

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#color

**Comment by reubenfirmin** [comment]
So why not support it in image export? Just because STL has a limitation doesn't mean that you should cripple the application.

**Comment by t-paul** [comment]
It's simply not implemented. It hopefully will be at some point, right now the information is simply not there after the mesh calculation process.

**Comment by MichaelAtOz** [comment]
> So why not support it in image export?

You can File/Export/as-image after F5 preview.

**Comment by nophead** [comment]
You can also do color(...) render() object() in preview mode, which will
give exactly the same view as render but with colour, but will be just as
slow.
