### ISSUE TITLE
Bowl Design, but... UI-WARNING: Object may not be a valid 2-manifold and may need repair!

### ISSUE THREAD

**Issue by freejmao** [openscad/openscad#3001]
I am attempting to create a design on OpenSCAD.
My knowledge is limited.
It gives the message:
UI-WARNING: Object may not be a valid 2-manifold and may need repair!

The shape here is a bowl with a rounded rim and semicircular from the side
The ideal shape should be smooth with no edges, however, the current one has because the rim and the main body cannot align.

Is there a mathematical formula to get the right result?

Here is the code I have created:

$fn=60;
module Bowl(diameter,thickness)
{
    rim=thickness/2;
    half=diameter/2;
    union(){
        // Main Bowl
        difference(){
            // Outer Ball
            sphere(d=diameter);
            // Inner Ball
            sphere(d=diameter-thickness*2);
            // Cutting Cube
            translate([-half-0.5,-half-0.5,-half])
            cube([diameter+1,diameter+1,half+rim]);
        }
        // Rim
        translate([0,0,rim])
        difference(){
            // Torus
            rotate_extrude()
            translate([(diameter-thickness)/2,0,0])
            circle(d=thickness);
            // Cutting Cube
            translate([-half-0.5,-half-0.5,0])
            cube([diameter+1,diameter+1,rim+1]);
        }
    }
}
rotate([0,180,0])
Bowl(7,1);

**Comment by t-paul** [comment]
Closing this as it's also posted on stackoverflow which is be a better place for questions than the issue tracker. Otherwise there's also the forum: http://forum.openscad.org/
