### ISSUE TITLE
Unify setup code in Preferences and AxisConfigWidget

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#3014]
Looks like there's a number of init functions that could be moved to some common place.

https://github.com/openscad/openscad/blob/36c12edc5f198eda8909750f897053cb7dcbc0d1/src/Preferences.h#L118-L125

https://github.com/openscad/openscad/blob/36c12edc5f198eda8909750f897053cb7dcbc0d1/src/input/AxisConfigWidget.h#L77-L88

**Comment by Sharma-Hrishabh** [comment]
Hey @t-paul , I'm working on this issue.
