### ISSUE TITLE
Run integration tests for deployment builds

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#303]
Now that the test frameworks supports using the actual OpenSCAD binary, we should have a way of running al  such tests using the actual deployment build of OpenSCAD as part of the (snapshot) release procedure.

This should be easy enough to script.

As a start, I'm renaming all such tests to start with the string "openscad".
##

**Comment by t-paul** [comment]
Closing as I think that is in place now, including test runs on all 3 main platforms via Travis (Linux + macOS) and AppVeyor (Windows/MSYS2).
