### ISSUE TITLE
Dependency of double-conversion is not being checked by cmake

### ISSUE THREAD

**Issue by mhier** [openscad/openscad#3042]
Observed behavior:

Building openscad on Ubuntu 16.10 gave me the error: `double-conversion/double-conversion.h: No such file or directory`. Installing the dev package for double-conversion fixed this problem.

Expected behavior:

cmake should check whether the header file is available and throw an error otherwise.

**Comment by t-paul** [comment]
Cmake is not the official build system (yet)... Added a note to  #2518 yet.
