### ISSUE TITLE
Multi-Format Export

### ISSUE THREAD

**Issue by runeimp** [openscad/openscad#3051]
Thank you for OpenSCAD! I've just started using it to make models for printing. Very nice!

There is a feature that I'd really like to see though. It would be nice while in the GUI and a major time saver on the command line if we could export multiple file formats and/or all supported formats. I'm already in the habit of making distributions for multiple platforms in my application development and would like to continue the process for model distro building.

Currently in the GUI you have to click through a few layers of the menu system for every format you wish to export. And the command line only allows specify `-o` or `--o` once. Both are very time consuming. GUI takes a large number of "click and wait" cycles, though most files export quickly. The command line option is takes even longer having to run the app multiple times to get the various outputs which requires re-rendering the same SCAD file internally for each format because it does not seem to be saved between runs. Of the two the multiple `-o` options would be the prefered feature if I had to choose one. I love the command line.  👼

**Comment by nophead** [comment]
Why do you need more than one format? 

One way to do it quickly on the command line would be to export say STL and then in another invocation import the STL and export it as another format.

**Comment by runeimp** [comment]
@nophead I create more than one format just so I can (hopefully) provide the prefered format to anyone who might want to use my models. Most 3D software supports STL. But many apps or users may prefer other formats for several reasons. OpenSCAD supports several export options for a reason and it would just be helpful if I could actually export all the formats. Or at least more than one at a time. Just like when I'm coding in Go I can compile to multiple platforms for releases of an app. Not everyone runs macOS. So I try to give a broad (though not exhaustive) list of options.

Your suggestion sounds good. I'll give that a shot as a work around for now. Still, for my automation process it would be nice to just hand the app multiple output option flags.  :-)

**Comment by runeimp** [comment]
Side note to @nophead 's suggestion. From the command line you can not use an STL as the reference file to export (unless I'm missing something, which is entirely likely). But you can import a `.csg` file and that exports almost twice as fast as from the original `.scad` file. Bunus, the `.csg` exports super fast to start off with. Still takes almost 15 minutes to export all formats on my computer. One project I'm modifying recommended `$fn = 360` which all the exports took well over an hour to render. Obviously that setting is probably overkill and something like `$fn = 120` would be fine and take _much_ less time. But any of these would be infinitely faster if OpenSCAD could accept multiple `-o` options and ideally be multi-threaded processing each export on a different thread or coroutine all based off the readonly prerender. Such is the dream anyway.  👼

**Comment by nophead** [comment]
The way I import STL files from the command line is to generate a one line scad file with an import in it, run openscad and then remove it.. 

Example here:https://github.com/nophead/NopSCADlib/blob/master/scripts/render.py#L60 which makes png images from all of my STL files very quickly.

You could probably also use a blank scad file with ```-Dimport("file.stl");```

I am surprised .csg is much faster than scad as it is basically the same with all the expressions converted to constants. Does your code spend a lot of time doing calculations?

I don't think you would gain much by multi-threading as the format conversions don't take long compared to the geometry calculation. 

To implement what you want the command line parser needs be modified to accept multiple -o options and the code here: https://github.com/openscad/openscad/blob/master/src/openscad.cc#L443 needs to loop through them. Not hard but you are probably the only person to want it.

**Comment by runeimp** [comment]
@nophead thanks for the examples. Using an `exporter.scad` with the `import("filename.stl");` works well. Conversion of a simple SCAD to 3MF took 1 minute 23 seconds. The export of STL to 3MF took 23 seconds. MUCH better conversion time. Thank you!

The `-Dimport("file.stl");` with a blank SCAD file didn't work for me. I tried even using `-D cli_imp=aida_20x20.stl` and couldn't get `echo("cli_imp", cli_imp);` from within the otherwise empty SCAD file to work. Kept getting `WARNING: Ignoring unknown variable 'aida_20x20', in file var.scad, line 8.` on a 1 line SCAD file. This is with OpenSCAD version 2019.05.

I have no idea how much time is spent on calculations. Is there a way to get diagnostic info? Probably `--info` would do it? We're talking around 20 or 30 simple expressions mostly involving `varname * 1.2` and the like. Is the math processing of OpenSCAD slow compared to C++ math calculations in general?

Like I said multiple `-o` options and multi-threading is the dream. Given that I can now export significantly faster importing the STL it's definitely good enough as is. Though I wouldn't say no to being able to export all formats in under 40 seconds with one command line. But I know the significance of the code change is hard to justify. And I'll not be submitting a PR to help out given my very limited knowledge of C++. None-the-less, thank you very much for the help getting me this far! 😃

**Comment by MichaelAtOz** [comment]
> The -Dimport("file.stl"); with a blank SCAD file didn't work for me. I tried even using -D cli_imp=aida_20x20.stl and couldn't get echo("cli_imp", cli_imp); from within the otherwise empty SCAD file to work. 

You need to escape the `"`'s, `-D cli_imp=\"aida_20x20.stl\"` 
That's for Windows. See also [wiki](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment#Constants).

**Comment by MichaelAtOz** [comment]
> WARNING: Ignoring unknown variable 'aida_20x20', in file var.scad, line 8. on a 1 line SCAD file. 

It said line 3 for me...

**Comment by runeimp** [comment]
@MichaelAtOz thanks for the pointer but I'm on macOS using a Bash shell. I should have pointed that out earlier. But your wiki link did help me understand what I was missing from the [Command Line docs](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment). The examples were very helpful and I got my `var.scad` test working with

```
$ openscad -D 'cli_imp="aida_20x20.stl"' -o aida_20x20.3mf var.scad
```

and even the `empty.scad` test working with

```
$ openscad -D 'import("aida_20x20.stl")' -o aida_20x20.3mf empty.scad
```
 🎉

**Comment by stefanct** [comment]
There seems to be an interesting bug in Version 2019.01: https://github.com/openscad/openscad/issues/3256
