### ISSUE TITLE
Feature request: Add 'Find' to editor context menu

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3069]
When reading code, particularly someone else's where you have to go hunt for modules etc - like when debugging some gears today, I mostly do it with my trackball with scroll-wheel, with hands AFK. Due to a neck problem I'm laid-back unless I need to be over the keyboard typing.

It would be really handy to be able to select text, then `Right-click/Find` to do the equiv. of `Ctl-F`, rather than having to trackball all the way up to the menubar. Modern screens have a lot more real-estate to cover.

Bonus would be, if Find is active, context menu items of Find-Prev & Find-Next.  

I'm not sure whether any of the 'replace' button functions would be good on the context menu. (?) I don't use it much. But `Right-Click/Replace` would keep the pointer in the vicinity of the code???

p.s. What does the Comp: prefix represent in the Git issue Labels? I'm presuming Comp:GUI is correct here.

**Comment by t-paul** [comment]
Comp is just short for Component. This is meant to roughly group tickets to (probably) affected areas.
