### ISSUE TITLE
GitHub Wiki - where are images?

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3070]
I'd like to add images to a git wiki doc.
If I click the image icon in the editor it asks for a URL ala-markdown, I'd prefer not to externally host them somewhere.

I see this doc has an image:
https://github.com/openscad/openscad/wiki/Editor-Improvements
If I edit it it has the image defined as:
` [[images/notepad-plus-find-replace.jpg]] `
I looked in code/images, it is not there.
Looking at the html shows:
`<img src="/openscad/openscad/wiki/images/notepad-plus-find-replace.jpg">`
Loading that shows it is at:
`https://raw.githubusercontent.com/wiki/openscad/openscad/images/notepad-plus-find-replace.jpg`
So where/how can I upload like that?

**Comment by t-paul** [comment]
The only way I know is to clone the wiki as git repo and add it through direct git commit. https://help.github.com/en/articles/adding-or-editing-wiki-pages#cloning-wikis-to-your-computer

**Comment by MichaelAtOz** [comment]
I don't have git locally. Been on to do list for a while.

Testing something I saw on stackexchange, using images from issues...

![Capture - user request to join](https://user-images.githubusercontent.com/1972961/64660980-14babf80-d486-11e9-8b3f-2cbfbc2b4c3f.JPG)

**Comment by MichaelAtOz** [comment]
No good.
Closing.

**Comment by t-paul** [comment]
You can send me the images via mail and I'll add them.
