### ISSUE TITLE
Incorrect warning for triangles= param in polyhedron

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3072]
EDIT

The recent enhanced warning of incorrect parameters (under #2620 ?) does not cope with `triangles=` in `polyhedron`.

/EDIT - ignore the rest.
This is weird, on my usual Windows 7 (VM) PC with 2019.05 & 2019.08.05 (latest snapshot) using polyhedron with the deprecated 'triangles=' fails:
```
WARNING: variable triangles not specified as parameter, in file tests, line 1
TRACE: called by 'polyhedron', in file tests, line 1.
```
No geometry is shown in preview.
![Capture polyhedron triangles](https://user-images.githubusercontent.com/1972961/64748354-320a8f00-d555-11e9-8410-d826f1a6b558.JPG)

However nightly 2019.08.20 on Debian works:
```
WARNING: variable triangles not specified as parameter, in file mebd, line 1
DEPRECATED: polyhedron(triangles=[]) will be removed in future releases. Use polyhedron(faces=[]) instead.
```

I think the Warning is a flaw in that recent change on parameter checks.
 
I then tried 2019.08.05 on my other (non VM) Windows 7 box. It works, pyramid is shown.
```
WARNING: variable triangles not specified as parameter, in file openscad-2019.08.05.ci3226, line 1
DEPRECATED: polyhedron(triangles=[]) will be removed in future releases. Use polyhedron(faces=[]) instead.
```

So how would the same executable on two Windows PCs (one a VM), with identical scad code, produce two different results?

`TRACE: called by 'polyhedron', in file tests, line 1.`
v's
`DEPRECATED: polyhedron(triangles=[]) will be removed in future releases. Use polyhedron(faces=[]) instead.'

**Comment by kintel** [comment]
> On Sep 11, 2019, at 22:03, Michael <notifications@github.com> wrote:
> 
> This is weird, on my usual Windows 7 (VM) PC with 2019.05 & 2019.08.05 (latest snapshot) using polyhedron with the deprecated 'triangles=' fails:
> 
> WARNING: variable triangles not specified as parameter, in file tests, line 1
> TRACE: called by 'polyhedron', in file tests, line 1.
> 

Perhaps "Preferences->Advanced->Stop on the first warning" is set on one of the machines?

 -Marius

**Comment by MichaelAtOz** [comment]
I compared the help/library-info.
I doubt the OpenGL version explains this.
(VM with fault on left)
![Capture poyl-tri-libs](https://user-images.githubusercontent.com/1972961/64748932-2029eb80-d557-11e9-8de8-214d9dde9eed.JPG)

**Comment by MichaelAtOz** [comment]
> 
> On Sep 11, 2019, at 22:03, Michael ***@***.***> wrote: This is weird, on my usual Windows 7 (VM) PC with 2019.05 & 2019.08.05 (latest snapshot) using polyhedron with the deprecated 'triangles=' fails: WARNING: variable triangles not specified as parameter, in file tests, line 1 TRACE: called by 'polyhedron', in file tests, line 1.
> Perhaps "Preferences->Advanced->Stop on the first warning" is set on one of the machines? -Marius

Yep. Thanks, Closing.

**Comment by MichaelAtOz** [comment]
Re-opening.
Parameter warning incorrectly warns of `triangles=` parameter in `polyhedron`
I'll edit the title.

**Comment by kintel** [comment]
Not sure I follow. `triangles=` is deprecated and attempts to use it yields a warning. This is  correct behavior.
..unless I misunderstood your updated report.

**Comment by MichaelAtOz** [comment]
```
WARNING: variable triangles not specified as parameter, in file pyri-poly.scad, line 1
DEPRECATED: polyhedron(triangles=[]) will be removed in future releases. Use polyhedron(faces=[]) instead.
```
The `DEPRECATED:` is correct, the `WARNING:` is incorrect as `triangles=` is valid until it is removed.
