### ISSUE TITLE
Support out-of-source builds

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#309]
When testing multiple configurations, it sucks having to check out new source code for every time as it makes it hard to quickly test against e.g. debug vs. release and old versions of libraries.

Out of source build works fine, but things like finding MCAD doesn't as it assumes that the library path is relative to the executable. This would need to be configured compile-time instead. There are probably other issues, but this would be a start.

Next step could be to write scripts to compile against misc. permutations of library dependencies and build settings. It would be cool to have something which would be trivial to set up on the misc. linux build services, gcc compile farm, as well as personal infrastructure. Basically light-weight distributed continuous integration using whatever is out there of resources.
##

**Comment by thehans** [comment]
The newer cmake builds function well out-of-source.  Closing
