### ISSUE TITLE
ERROR: CGAL error in CGAL_Nef_polyhedron3(

### ISSUE THREAD

**Issue by Ryan2601** [openscad/openscad#3107]
Hello everyone, I am new to openscad and 3D printing.

Full error:
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e_below != SHalfedge_handle() File: /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Nef_3/SNC_FM_decorator.h Line: 426

I am trying to do difference on 2 parts. One stl file that was sent to me and the other (called "part to reduce" in the zip folder) is made by me.

==============================================================
code used:
```
difference(){
    color("red") import("E:/Downloads_in_E/BombNew_TOP.stl");
    difference(){
        translate([0,0,7]){
            color("green") cylinder(r=18.5,h=20,center = true);
        }
        translate([0,10,7.5]){
            color("yellow") cube([37,18.5,22],center = true);
        }
    }    
}

```

==============================================================
**The second difference function contains code for the "part to reduce" I made.**

[3D_Parts.zip](https://github.com/openscad/openscad/files/3775287/3D_Parts.zip)

**Comment by MichaelAtOz** [comment]
BombNew_TOP.stl is bad, it has self intersections.
![Screenshot at 2019-10-27 09-29-22](https://user-images.githubusercontent.com/1972961/67626811-77ccae00-f89c-11e9-9f81-d09fa72b6a19.png)

**Comment by Ryan2601** [comment]
how can I fix it?

**Comment by MichaelAtOz** [comment]
Unfortunately Self-Intersections are hard with free tools. 
Netfabb Pro for example can do it automatically
I don't think anyone here has it????????????

Otherwise it is a manual process in the likes of MeshLab or maybe Blender, deleting the SI's and trying to close the holes that creates. I've rarely had success with finely detailed models like yours.

Sorry.

**Comment by Ryan2601** [comment]
Can you please list all the tools, known to you, that does it?Free or not.

Netfabb Pro would surely fix it?

**Comment by MichaelAtOz** [comment]
Nothing is guaranteed.
Netfabb used to have an online system where you could upload STLs and it would apply the auto-repair.
It had a high success rate, but not 100%. Whether that would increase using the Pro tool manually, who knows.
That appears to now be [here](https://service.netfabb.com/login.php). I have not signed up, I assume it is similar.
I'm not a tools expert, so in terms of assisted repair, Netfabb is the only one I'm familiar with.
For manually-guided fixing most mesh processing tools will help, like MeshLab, but it is iterative and a PITA, search for 'repair self intersections', but AFAIK there are no miracle guides.

**Comment by MichaelAtOz** [comment]
FYI I checked on Pro pricing a while ago, one user licence $2500 AUD (I think the USD exchange rate back then was close to 1)

**Comment by MichaelAtOz** [comment]
Seems there are other [Netfabb options](https://www.autodesk.com/products/netfabb/compare-products), but i don't know whether 'standard' fixes SI's, maybe try the 'premium' free trial?

**Comment by MichaelAtOz** [comment]
Bad STL. Closing.

**Comment by EmVeeWRK** [comment]
hmm bad stl? i reexported in blender, reverse engineered it in freecad but i am getting still same, finally i edited it in freecad without problems :(((
