### ISSUE TITLE
Color editor

### ISSUE THREAD

**Issue by rsc9421** [openscad/openscad#3123]
Hi!
can I contribute to add custom color editor for code and 3D? I program in qt
regards

**Comment by t-paul** [comment]
Could you elaborate on what you are proposing? OpenSCAD is lacking in color handling currently, so there's probably multiple opportunites for improvement. Maybe a rough description of the workflow? Or a mocked up screenshot?
You can also try to catch someone on IRC for a more interactive discussion...

**Comment by rsc9421** [comment]
yes, give me some days for develop the demo

**Comment by t-paul** [comment]
Flagged as `waiting for feedback`.
