### ISSUE TITLE
Voids missing in 3mf

### ISSUE THREAD

**Issue by dmopalmer** [openscad/openscad#3133]
When I have an airtight void in an object (i.e. a difference() that does not extend to the surface of its enclosing object) and export it as 3mf, the void is missing (solid).

The void does appear when I render as wireframe, and it does appear when I export as stl.  

The 3mf file shows as solid under both Prusa Slicer and Cura.  

When I add an arbitrarily small airhole the void is handled properly.

```
// Cubetest

difference()
{
    cube([20,20,20], center=true);
    cube([18,18,18], center=true);
    // Airhole
    // cube([.0001,.0001,30], center=true);
}
```

OpenSCAD version 2019.10.24 (git 6ec97fda)  on macOS Catalina 10.15.1

**Comment by nophead** [comment]
OpenSCAD used to have that problem with STL, so it is probably the same cause. The winding order of internal faces was wrong.
