### ISSUE TITLE
Text top to bottom

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#3145]
How to write text from top to bottom, not left to right?

![](https://img-blog.csdn.net/20170531164834328?watermark/2/text/aHR0cDovL2Jsb2cuY3Nkbi5uZXQvc2FuZ2ppbmNoYW8=/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70/gravity/Center)

**Comment by t-paul** [comment]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Text

**direction**
    _String._ Direction of the text flow. Possible values are "ltr" (left-to-right), "rtl" (right-to-left), "ttb" (top-to-bottom) and "btt" (bottom-to-top). Default is "ltr".

Again, please respect this is not a forum to ask general questions. There's multiple places for that listed in https://www.openscad.org/community.html
