### ISSUE TITLE
Code hinting shortcut?

### ISSUE THREAD

**Issue by OnkelTem** [openscad/openscad#3151]
I've just installed openSCAD for the first time and I wonder how can I get those cute hints on function parameters?

They appear when I edit the code, but after that I couldn't find a shortcut to show them again. 

And if there is a shortcut (I hope it is) it would be great to have it here: https://github.com/openscad/openscad/wiki/Keyboard-Shortcuts

**Comment by thehans** [comment]
They are triggered by opening parenthesis on a builtin function/module.  If you go back and edit a call, they won't show again unless the `(` is deleted and re-typed.

**Comment by OnkelTem** [comment]
@thehans That I know, but how to trigger it manually? For example, in Intllij products I just hit `Alt+p`

**Comment by t-paul** [comment]
CTRL+Space for autocomplete, SHIFT+CTRL+Space for calltips (function parameters).
