### ISSUE TITLE
Less intrusive autocomplete

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#3155]
The autocomplete editor feature is nice, but I have been getting some false-positive matches recently, which I'm finding tedious to avoid.

For example I needed a function that returns mathematical modulo.  (like `%` operator but always return non-negative values).  So I wrote a function called `mod(x,y)`, but then whenever I type to call the function: `mod(` it automcompletes to `module(`
Also, trying to call a function named `f()` autocompletes to `false(`, or a function named `rot(...`, autocompletes to `rotate(`, etc.

Tab or Enter keys (and maybe others?) already are ways to accept the autocomplete, so I'd rather not have `(` trigger it too.

`module(` isn't even correct syntax anyways (without a module name).

Secondly, I think autocomplete should be disabled when typing inside comments.

**Comment by MichaelAtOz** [comment]
Also, I think the pop-up dialogue should be moved, say, ~2 lines away from the cursor and/or to the right. Frequently you want to see the adjacent lines. Particularly a problem at the bottom of the page:
![Capture autocomplete](https://user-images.githubusercontent.com/1972961/70582205-cac0b180-1c0d-11ea-8a0b-cdb3f1687617.JPG)

**Comment by t-paul** [comment]
I agree that it would be a useful change, but the implementation of those features is inside QScintilla, so the control on our side is limited.
I found that setting the trigger to 2 characters helps a lot with the misfires (but would not help for `mod`). Maybe there's at least some control over the keyboard handling as I think the most problematic part is the auto-accept of the selected value when just typing.

**Comment by Sharma-Hrishabh** [comment]
Hey @t-paul, I want to work on this issue. Can you guide me, from where should I begin?

**Comment by rcolyer** [comment]
Hi @Sharma-Hrishabh, if memory serves these features came in with the merge of PR #2975.  That should point you to the relevant subset of the source code.

**Comment by t-paul** [comment]
Fixed via  #3207.

**Comment by diabl0w** [comment]
how do I enable auto-complete? I cannot find documentation on this anywhere and it is not in preferences from what I can see.

**Comment by Sharma-Hrishabh** [comment]
hey @diabl0w , the option to enable/disable autocomplete is present in Preferences->Editor. [ at the bottom ]

**Comment by diabl0w** [comment]
> hey @diabl0w , the option to enable/disable autocomplete is present in Preferences->Editor. [ at the bottom ]

Thanks for the reply, is there a certain version that is required? The option is not there for me. Under Help-> About, it says I am running version 2019.05 
 
This is what my Preferences -> Editor looks like:

![image](https://user-images.githubusercontent.com/16129074/90107604-0f5d9900-dd17-11ea-8c4d-17a3a6e0dd27.png)

**Comment by MichaelAtOz** [comment]
[Development Snapshot](http://www.openscad.org/downloads.html#snapshots)
