### ISSUE TITLE
Renaming of difference does not work

### ISSUE THREAD

**Issue by espr14** [openscad/openscad#3166]
version 2019.12.21.ci4161 win64

This does not work.
```
d(){
	cube([100,100,100]);
	cube([10,10,100]);
}

module d(){
	difference() children();
}
```

**Comment by t-paul** [comment]
Yes, that's not how it can work. There is an ongoing discussion about #350, specifically #3143 but it's probably still not going to change.

This works:
```
module d() {
	difference() {
        children(0);
        children([1:$children-1]);
    }
}
```

**Comment by espr14** [comment]
This is more safe:

```
module d(){
	if($children==1) children(0);
	if($children>1) difference(){
		children(0);
		children([1:$children-1]);
	}
}
```

**Comment by t-paul** [comment]
Indeed, that's better. Another option would be to guard with something like `assert($children > 1, "module needs at least 2 children");`

**Comment by nophead** [comment]
difference() doesn't need any children, so a replacement for it should not
assert.

**Comment by MichaelAtOz** [comment]
and for debugging, sometimes it is convenient to comment out various children, sometimes leaving one.

**Comment by nophead** [comment]
Indeed and also sometimes some ifs that may leave only one child, for example a conditional hole.
