### ISSUE TITLE
OSX: support for external GPU compute power

### ISSUE THREAD

**Issue by rlmalisz** [openscad/openscad#3167]
Renders for anything round that truly need to be accurate ($fn >= 100) are painfully slow.  It certainly seems since Apple has added support for external GPUs for both graphics and compute support for a while now, it'd be a big improvement to Openscad if it could avail itself of that power.

**Comment by t-paul** [comment]
There's no realistic chance for maintaining special GPU support for MacOS. OpenSCAD does struggle with old render code, should that get updated it might help on MacOS too.
