### ISSUE TITLE
Is it possible to render and export by code?

### ISSUE THREAD

**Issue by cy18** [openscad/openscad#3175]
Constructing parameterized models are very convinient in OpenSCAD, but exporting them are not. Every time I want to export a model with a different parameter (such as different heights), I have to change the  parameter, click the render button, click the export button, then choose the path and filename. It does not cost a lot time, but that's not what a lazy programmer wants to do. If I have a list of models with different parameters, that would be a problem. 

Since constructing model could be done by code, is it possible to render and export model by code, too? i.e., a function render() would render the model, and export_stl("e:/my_model.stl") would export current model to an STL file.

Command line options seem promising, but I think doing it by code is much simpler. Functions such as loop could be easily adopted.

**Comment by t-paul** [comment]
The language is intended to describe models, not as general programming language, so `export()` is out of scope. There might be extensions for the customizer or the GUI export that could give a maybe more limited but similar feature.
