### ISSUE TITLE
OpenSCAD on Mac OS now gives occasional security warning about deprecated use of HTTP instead of HTTPS

### ISSUE THREAD

**Issue by mjparme** [openscad/openscad#3185]
This warning appears on occasion now (maybe due to Catalina upgrade?).

```
You must change the feed URL (http://files.openscad.org/appcast-snapshots.xml) to use HTTPS or disable App Transport Security.

For more information:
https://sparkle-project.org/documentation/app-transport-security/
```

<img width="419" alt="Screen Shot 2020-01-08 at 7 12 45 PM" src="https://user-images.githubusercontent.com/1580996/72029283-0cfc0380-324b-11ea-9d4e-d55f94c2f3b5.png">

**Comment by t-paul** [comment]
Running which version of OpenSCAD?

**Comment by mjparme** [comment]
> Running which version of OpenSCAD?

Sorry, I guess that could be important info, here is my veversion:

```
OpenSCAD version 2019.05 
Copyright (C) 2009-2019 The OpenSCAD Developers
```

**Comment by t-paul** [comment]
Thanks, not sure why that happens. All links I can find are changed to HTTPS before that release. @kintel any idea where that's coming from (and why the release version polls the `*-snapshot.xml` file?

**Comment by kintel** [comment]
That's weird. All links were changed to https ~a year ago (https://github.com/openscad/openscad/pull/2689), months before that release.

Following the link (https://sparkle-project.org/documentation/app-transport-security/), is says: "App Transport Security has other specific requirements too, so please test updating your app on 10.11 even if you already are serving over HTTPS!"

I could install Catalina in a VM for testing, but I don't really want to start on that unless I know it will work, as it's a bit of a time sink.

**Comment by mjparme** [comment]
I installed 2019.12.20 (dev) and haven't seen the warning again.

**Comment by kintel** [comment]
Thanks for the update. Closing as resolved
