### ISSUE TITLE
Feature Request: PDF Export

### ISSUE THREAD

**Issue by sbridger** [openscad/openscad#3188]
There is not (for me at least) a workable way to get a correct size paper 2D drawing from Openscad without pain. 
.
DXF export -> Online-DXF->PDF_Convert results in vanishingly fine lines that do not print on a laser printer.
SVG is not directly printable, nor is PNG or anything else. PDF is the only format that can be universally printed from any computer and give a correct size print.

There are many cases where a 2D design is needed and an accurate template for drilling or cutting is required, or for laser cutting/engraving.
It would also help reduce wastage of 3d printer plastic by allowing much cheaper easier size checking. (today I am 3D printing a 14g ABS jig, that could have been made easier with wood scrap and a drill press - if I could print the paper template)

Export to PDF should have options (in decreasing order of importance to me) to:
 
 1. Print the DXF export outline with specified (configurable), visible line width - OR-
 2. Print the PNG/SVG export view
 3. have an X,Y scale ruler along the edge for calibration, and/or a calibration grid
 4. print all the "echo" output on the page
 5. filename, datetime in footer, Title etc
 6. Multiple Pages: do multiple renders (each adding one PDF page) with an iterator parameter ($t). This is really much the same as the existing Animation functionality. (of course this is also useful for stl export as well, but PDF doesn't need multiple files). This would be very useful for laser cutting multiple parts that make an object up.
7. able to obey color() : https://github.com/openscad/openscad/pull/2035

 6b. This https://github.com/openscad/openscad/issues/98#issuecomment-7512305 was someone elses take on 6

**Comment by t-paul** [comment]
Sorry, this is way to broad a feature request including features that are out of scope for OpenSCAD language (`export()`).
I'd suggest to provide a clearer example/description of the core feature for discussion.

**Comment by sbridger** [comment]
Not sure what is unclear: Print the DXF outline to PDF so it can be printed on paper.

Core feature: is 1 or 2 (either works for a drill template. 1 is probably more important for laser cutter)
Others are in decreasing order of importance and optional options.

3 is fairly important as it's quite easy to print pages with "scale to fit paper" and get a slightly wrong sized print

**Comment by thehans** [comment]
Line thickness is not desirable for laser cutters.  A toolpath is ideally a zero-width line, and most laser cutter software can already load DXF directly.  Adding width to DXF lines would mean that laser would do 2 passes on everything, one for each side of the line.

**Comment by sbridger** [comment]
Perhaps DXF export needs to have configurable linewidth, then the online PDF convertors might be useful to make printable docs.

I would certainly prefer configurable linewidth in PDF's, as sometimes you need fine lines, and sometimes you want them easy to see under swarf and so on.

**Comment by t-paul** [comment]
Talking that much about DXF is not helping much as this is just another export which will have not much in common with a new PDF export.

- the internal 2d model has no line sizes, that's probably not going to change soon
- for configurable line sizes (and other options) we need #649 or annotations that can be extracted at export time
- I'm not sure we want to bring in actual printing, if it's nicely encapsulated (with cross-platform support) in Qt it might be possible to add this, but this ticket should focus on the export first

So to limiting things a bit for an initial implementation could look like:
- Export 2D model to PDF single page portrait, no scaling, origin bottom left, Y vertical
- Have an X,Y scale ruler along the edge for calibration, and/or a calibration grid
- Header/Footer: Title, Filename, Date, Time

Needs also investigation of libraries, so far it's not looking ideal.
- libharu - MXE: yes, Debian: no, Homebrew: no (looking for new maintainer)
- libpodofo - MXE: no, Debian: yes, Homebrew: yes (not much activity, but looks maintained)
- poco-pdf - MXE: yes, Debian: yes, Homebrew: yes (nice availability, big framework, needs closer look)
- cairo - MXE: yes, Debian: yes, Homebrew: yes (nice availability, big framework)
- skia - MXE: no, Debian: no, Homebrew: no (maintained by Google)

**Comment by t-paul** [comment]
Closed via #3266 / #3443.
