### ISSUE TITLE
Release snapshot from CircleCI build

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#3189]
Improve the CircleCI downloader script, or write a companion script, to generate other needed files to make a snapshot release:

* appcast-snapshot.xml
* Files for website update
* Possibly pushing and opening a PR against openscad.github.com

This issue may need to be split into per-platform tickets.

TODO:
* [ ] macOS: Binary sanity check
* [ ] macOS: generate appcast-snapshot.xml (needs ssh key)
* [x] Generate JSONP include files for use on download page

**Comment by t-paul** [comment]
Files are now pulled from CircleCI via `cron` so no authentication required.

**Comment by kintel** [comment]
Closing as done
