### ISSUE TITLE
The editor shows the string "ff" with the width of a single character

### ISSUE THREAD

**Issue by mlochen** [openscad/openscad#3192]
OpenSCAD version: 2019-05
Font used: Nimbus Mono PS

Expected behaviour: The string "ff" should be two characters wide as it consists of two characters.
Actual behaviour: The string "ff" is shown with the width of a single character.
How to reproduce: Select "Nimbus Mono PS" as font for the editor, type any string containing "ff".

![ff](https://user-images.githubusercontent.com/58656110/72665427-a88a3280-3a08-11ea-888b-796857aa56d6.png)

The screenshot shows what happens. It does not happen with other fonts or other letters, and it is also not a conversion to the [ff-digraph](https://en.wikipedia.org/wiki/List_of_Latin-script_digraphs#F) as i can verify with another editor. What makes it even weirder is, that the word "offset" is colored in blue and other variable names are black. This does not happen in comments though.

edit: I found out, that this also happens in other Applications (both QT and GTK), so it is a bug in the font and not in OpenSCAD.

**Comment by kintel** [comment]
FYI: The reason for the color difference is that offset() is a builtin module in OpenSCAD, and the syntax highlighter doesn't seems to distinguish between variable names and module instantiations.
