### ISSUE TITLE
Preview Bug with cylinder() difference() and resize()

### ISSUE THREAD

**Issue by CryptKid** [openscad/openscad#3199]
In an object i'm designing, i have a roof consisting of the of two cylinders and a rotated cube.
When the edge cutten of by the cube is in sight, the entire roof develops holes or vanishes. From other perspectives it looks just fine. Sourcecode is:
```openscad
difference() {
    translate([0,42-28,2]) resize([0,0,11]) rotate([-90,0,0]) difference() {
        cylinder(140.5,40,40);
        translate([0,0,-0.1]) cylinder(146.2,35,35);
        translate([-40,0,-0.1]) cube([80,40.1,190.2]);
    }
    translate([-40,0,0]) rotate([-45,0,0]) cube([80,10,30]);
}
```
Also after being rendered, the roof looks fine from all perspectives, that's why i suspect a bug

The attached pictures are all made without any change to the source, only by rotating
![front_perspective](https://user-images.githubusercontent.com/30263141/73172250-83797c00-40fa-11ea-9d58-ec2157fb5177.png)
![side_perspective](https://user-images.githubusercontent.com/30263141/73172251-84121280-40fa-11ea-9a2f-e94eae326657.png)
![side_higher_perspective](https://user-images.githubusercontent.com/30263141/73172253-84121280-40fa-11ea-86ea-d4a86275640f.png)

After refactoring it to
```openscad
translate([0,42-28,2]) resize([0,0,11])  rotate([-90,0,0])difference() {
     
        cylinder(140.5,40,40);
        translate([0,0,-0.1]) cylinder(146.2,35,35);
        translate([-40,0,-0.1]) cube([80,40.1,190.2]);
    
    translate([-40,0,-25]) rotate([85,0]) cube([80,40,60]);
}
```
Everything works fine but it makes it a lot harder to find the right rotation for the cube

**Comment by nophead** [comment]
Yes it looks like resize() needs a convexity parameter to preview properly, like render().

**Comment by t-paul** [comment]
Yeah, not really possible to say with the tiny screenshots - see also [FAQ entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_are_some_parts_(e.g._holes)_of_the_model_not_rendered_correctly?).

**Comment by nophead** [comment]
The FAQ says set convexity but the bug is that resize has no convexity parameter. I think it needs one as it behaves like render().

**Comment by t-paul** [comment]
Right, found it in https://github.com/openscad/openscad/blob/master/src/cgaladv.cc#L70 which has convexity but does not evaluate it for `resize`.
