### ISSUE TITLE
Application crash on invalid matrix multiplication

### ISSUE THREAD

**Issue by stackcoder** [openscad/openscad#3200]
Steps to reproduce:
1. Insert following code: `echo([1, 1, 1] * [[1, 1, 1], [], []]);`
2. Hit F5 to preview
3. Segmentation Fault

**Comment by MichaelAtOz** [comment]
Confirmed with 2019.05 on W7 & 2020.01.04.nightly (git 552643c) on Debian

**Comment by kintel** [comment]
Fixed by #3206
