### ISSUE TITLE
Feature Request: extract usable data from SVG

### ISSUE THREAD

**Issue by RichyT** [openscad/openscad#3201]
I'm keeping this kind-of nonspecific as I'd like to see some discussion. What I'm thinking is that when we import an SVG, it would be nice to read back some information from the SVG file we're importing and be able to use that in the OpenSCAD script. For example, an item in the SVG might have a tag 'openscad.thickness="5"' where we could then do

linear_extrude(height = thickness) import(file1);

Now, I can see a couple of the issues here but as I say, I'm keeping it loose to see what discussion comes up.

**Comment by t-paul** [comment]
I think that is out of scope for OpenSCAD. I'll leave the ticket open for a bit, but consider this is not a discussion board. Open questions are better placed in the forum.

**Comment by t-paul** [comment]
I'm closing this for now as it's a bit too unspecific. It might come up again once we solved the data structure topic which would allow importing additional data.
