### ISSUE TITLE
Feature Request: Keyboard Shortcuts to view/hide toolbar,editor and console.

### ISSUE THREAD

**Issue by Sharma-Hrishabh** [openscad/openscad#3203]
Keyboard shortcuts are missing for toggling the editor, console and toolbar view.
I observed this when I needed to focus on the editor only, but for toggling the render-window, I need to go to the toolbar to check and uncheck.

**Comment by t-paul** [comment]
That's pretty much #2977 as there's not really a lot of free keys with the fixed mapping. So closing as duplicate.
