### ISSUE TITLE
Command line preview-only app

### ISSUE THREAD

**Issue by ssuchter** [openscad/openscad#3211]
I'm interested in having a command line way to make an interactive preview window for a given .scad file. My use case is to enhance the Intellij plugin to allow quick rendering of a file you're editing in Intellij.

I'm imagining a separate command line app that will create a running app separate than any existing OpenSCAD instances. This app will not have nearly as much interactivity as the main OpenSCAD app - for example, it wouldn't have an editor window, nor any ability to load/save/export files. I also don't think it should have a console window; any console output during the parsing/rendering process should go to stdout, because Intellij has its own console pane.

I couldn't find a way to do this cleanly with existing functionality. If this already exists, I'd love for someone to tell me not to try. I'd also accept words of encouragement or advice on how to accomplish this. (I'm a developer, but not in this codebase.)

**Comment by kintel** [comment]
For such discussions, please open a thread on the mailing list.
