### ISSUE TITLE
Release 2021.01

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#3214]
We want to publish a new release. This issue functions as a release checklist.

Related dates:
* Ubuntu 21.04 "Hirsute Hippo" Import Freeze: [2021-02-25](https://discourse.ubuntu.com/t/hirsute-hippo-release-schedule/18539) 
* Debian 11 "Bullseye": Soft Freeze: [2021-02-12](https://release.debian.org/bullseye/freeze_policy.html)

ToDo
* [x] Update copyright year to 2021 in all place visible within the app
* [x] Update src/AboutDialog.html with changes to libraries, people etc.
* [x] Update doc/openscad.1 with new cmd-line arguments
* [x] Cut a RC branch and build RC binaries
* [x] Update translation files
* [x] Update changelog
* [x] Prepare news entry

Changes:
```
**Language Features:**

* Allow initial seeds to stick between rands calls #3144
* SVG: stroke-linejoin now supported #2971
* Some comparison operator fixes #3164

**Program Features:**

* Add Chinese (china) translation file #3172
* Console messages now only use HTML to highlight errors/warnings. #3141
* Block copy and move #3066
* Enable HIDAPI for MacOS builds #3036
* Range Warnings begin<end #3149
* Added --export-format cmd-line argument #2877

**Bugfixes/Improvements**

* Tail recursion optimization #3020
* Null pointer exception with "#" debug modifier (empty CSG normalizer result) #3085
* Find highlight offset of multibyte characters #3068
* Customizer: negative list value visual display bug #2995
* Don't crash with saved vector parameters with >4 values. #3011
* Application crash on invalid matrix multiplication #3200

**Deprecations:**
**Misc:**
```

**Comment by thehans** [comment]
Oh, speaking of changes to AboutDialog people, I'd like to display my full first & last name while we're at it. :smile: 
"Hans Loeblich"

Just a small thing I didn't bother bringing up before, since the current listing "Hans L" was how I had originally written on my github account.  I've since changed that too.

**Comment by sk8nfool** [comment]
It has been a couple of months. Is this release still coming?

**Comment by t-paul** [comment]
Yes

**Comment by mholiv** [comment]
I'm not sure if this is the right place but I found two regressing in RC5 that I documented here:
https://github.com/openscad/openscad/issues/3614
https://github.com/openscad/openscad/issues/3615

I wanted to let people know before the RC process was finished.

**Comment by t-paul** [comment]
RC is pretty much finished unfortunately. I'm not even sure there's much to do about those 2 cases as those are likely platform/distribution related. We'll see about the details in the specific issues...

**Comment by t-paul** [comment]
Closed via https://github.com/openscad/openscad/releases/tag/openscad-2021.01
