### ISSUE TITLE
Allow resize of console window

### ISSUE THREAD

**Issue by bburdette** [openscad/openscad#3217]
I'm unable to expand the console window, which makes viewing the program output inconvenient - I can only see a couple of lines of text at a time.  I can grab the console window and drag it around, but it goes right back where it was, at the same size that is was before.  There does't seem to be any kind of handle around to grab for resizing the panel.

This is OpenScad v 2019.05.

**Comment by nophead** [comment]
I just hover over the line that is above the word "Console" and the cursor changes to two parallel lines with arrows and then left click and drag moves the division between the two windows. This is the same version on Win7.

**Comment by bburdette** [comment]
wow, how'd I miss that?  I don't have a line over 'console', but the cursor does change there.

**Comment by nophead** [comment]
It looks like this on my PC
![image](https://user-images.githubusercontent.com/566149/74366671-57cbe680-4dc8-11ea-97cf-f52ddcc5281a.png)

**Comment by bburdette** [comment]
I'm on linux, i get this: 
  
![image](https://user-images.githubusercontent.com/157330/74370182-e83c0400-4d93-11ea-9061-732950a0d194.png)

**Comment by t-paul** [comment]
This depends on the theme defined by the system, not an OpenSCAD issue.

E.g. flatpak version on my Debian looks like:
![grafik](https://user-images.githubusercontent.com/1330241/74372783-87d0b500-4ddb-11ea-91c5-9272a75f11d3.png)
