### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by lar3ry** [openscad/openscad#3240]
Seems overkill to post this as an issue, but I didn't know how to do it otherwise.

"more then" instead of "more than" in
2019.02.md
errors-warnings-expected.echo
errors-warnings-included-expected.echo
evalcontext.cc

**Comment by MichaelAtOz** [comment]
@lar3ry  Are you talking about #3202?

**Comment by lar3ry** [comment]
Yes. When I submitted it, I got a message saying it was similar to three others, so I looked at them, but I didn't see #3202.
Sorry about that.
