### ISSUE TITLE
Customizer vectors round floats with initial integer

### ISSUE THREAD

**Issue by rcolyer** [openscad/openscad#3243]
In customizer:
v = [1.1, 2.2, 3.7]; // yields float spinboxes

v = [1.0, 2.2, 3.7]; // and
v = [1, 2.2, 3.7]; // yield int spinboxes, rounding the last two.

This is probably a simple fix, but could also be considered together with #3012.

**Comment by Sharma-Hrishabh** [comment]
Hey @rcolyer , I want to look over this bug. Should I go ahead?
