### ISSUE TITLE
Move the Editor window off-screen

### ISSUE THREAD

**Issue by sclaes** [openscad/openscad#3247]
Why is it not possible to move the editor window off-screen?

It is possible to move the main window and the preferences window off-screen, so why not the editor window?

BTW: I selected both 'Enable docking of Editor and Console in different places' and 'Enable undocking of Editor and Console to separate windows'
If I undock the Console window or the Editor window, I cannot move them off-screen. Why?

**Comment by t-paul** [comment]
This seems to be default behavior for dockable windows. [Example code](https://code.qt.io/cgit/qt/qtbase.git/tree/examples/widgets/mainwindows/dockwidgets?h=5.14) behaves the same.
