### ISSUE TITLE
2019.05 crashes on OS X 10.9.5

### ISSUE THREAD

**Issue by gtkelly** [openscad/openscad#3267]
After setting security preferences to allow any application to run, I get the following when launching 2019.05 (https://files.openscad.org/OpenSCAD-2019.05.dmg):

4/3/20 5:29:33.938 AM OpenSCAD[13192]: *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSPanel setTitlebarAppearsTransparent:]: unrecognized selector sent to instance 0x7f9c59c9a770'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010593625c __exceptionPreprocess + 172
	1   libobjc.A.dylib                     0x000000010a121e75 objc_exception_throw + 43
	2   CoreFoundation                      0x000000010593912d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x0000000105894272 ___forwarding___ + 1010
	4   CoreFoundation                      0x0000000105893df8 _CF_forwarding_prep_0 + 120
	5   libqcocoa.dylib                     0x00000001147a3bbd qt_plugin_instance + 65469
	6   libqcocoa.dylib                     0x000000011479cf9e qt_plugin_instance + 37790
	7   libqcocoa.dylib                     0x000000011479c50b qt_plugin_instance + 35083
	8   libqcocoa.dylib                     0x0000000114796ba4 qt_plugin_instance + 12196
	9   QtGui                               0x0000000106f221cd _ZN14QWindowPrivate6createEby + 269
	10  QtWidgets                           0x0000000106969741 _ZN14QWidgetPrivate10create_sysEybb + 1233
	11  QtWidgets                           0x00000001069683c6 _ZN7QWidget6createEybb + 326
	12  QtWidgets                           0x000000010697b67e _ZN7QWidget10setVisibleEb + 478
	13  QtWidgets                           0x0000000106b3a7cd _ZN7QDialog10setVisibleEb + 125
	14  QtWidgets                           0x0000000106b39f40 _ZN7QDialog4execEv + 240
	15  OpenSCAD                            0x0000000104e7c629 _Z3guiRNSt3__16vectorINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEENS4_IS6_EEEERKN5boost10filesystem4pathEiPPc + 1241
	16  OpenSCAD                            0x0000000104e8159b main + 15979
	17  libdyld.dylib                       0x000000010cbb05fd start + 1
	18  ???                                 0x0000000000000002 0x0 + 2
)

(10.9.5 is my last stop on the Apple train.)

**Comment by t-paul** [comment]
We are now pretty much forced to move to >= 10.13, sorry.
