### ISSUE TITLE
Linear Extrude doesn't support negative extrude distances.

### ISSUE THREAD

**Issue by VendicarKahn** [openscad/openscad#3279]
Extruding downward is a thing.

Similarly extruding counter clockwise.

**Comment by t-paul** [comment]
Last warning, this is getting out of hand. Feature requests are appreciated, but the multiple posts in the last hour are at spam level. I will close this issue now. If you continue creating this same style of issues, the next notification will be a block-notice.

**Comment by VendicarKahn** [comment]
I'm telling you how your program is broken and how it can be fixed. If you are too lazy to fix it, then that is no concern of mine. But it should tell people why your program will never amount to anything other than being a silly little toy. 12.04.2020, 14:31, "Torsten Paul" <notifications@github.com>:
Last warning, this is getting out of hand. Feature requests are appreciated, but the multiple posts in the last hour are at spam level. I will close this issue now. If you continue creating this same style of issues, the next notification will be a block-notice.
