### ISSUE TITLE
lambda generates syntax error

### ISSUE THREAD

**Issue by kamorrissey** [openscad/openscad#3281]
The trivial lambda example in the programming language reference does not compile in 2019.05 Windows release binary:

```
func = function (x) x + x;
echo(func(5));
```

Preview and render complain of a syntax error on line 1. If I add a blank line on top, it complains of a syntax error on line 2 and puts the red block cursor immediately after the keyword  "function".

**Comment by MichaelAtOz** [comment]
Function literals are in the development version, not released yet.
The wiki is deficient in not mentioning that, I'll fix it shortly
If you want to try a dev version you will also need to enable it in preferences/features.

**Comment by MichaelAtOz** [comment]
Wiki updated. Closing.

**Comment by kamorrissey** [comment]
So if I clone today's version and build, it will be there? I wanted to experiment with functional list iterating algorithms.

**Comment by thehans** [comment]
Yes it will be in the current master branch.  You can also download a dev snapshot if you don't want to build it: http://www.openscad.org/downloads.html#snapshots
