### ISSUE TITLE
Function Literals are syntax errors

### ISSUE THREAD

**Issue by DavidPhillipOster** [openscad/openscad#3282]
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/User-Defined_Functions_and_Modules#Function_Literals documents function literals. When I copy and paste from the manual into Mac OpenSCAD version 2019.05

```
func = function (x) x * x;
echo(func(5)); // ECHO: 25
```

I get:

```
ERROR: Parser error in file "test.scad", line 1: syntax error 
```

I tried the latest development snapshot 2019.12.20 (git 2a943a57) It said: 

```
WARNING: Ignoring unknown function 'func', in file , line 2.
```

**Comment by MichaelAtOz** [comment]
Function literals are in the development version, not released yet.
The wiki is deficient in not mentioning that, I'll fix it shortly
If you want to try a dev version you will also need to enable it in preferences/features.

**Comment by MichaelAtOz** [comment]
Wiki updated. Closing.
