### ISSUE TITLE
Option to treat warnings as errors when compiling and rendering a .scad file

### ISSUE THREAD

**Issue by brantmerryman** [openscad/openscad#329]
Currently if you **include** or **use** a file inside of a .scad document, and that file is not found, a warning is generated and the object still renders.

Often this means that a missing include file can cause holes to be the wrong size.

To do:
Add a compiler flag to treat warnings as errors. This should be something similar to the gcc options:
     \* -Werror **treat all warnings as errors**
     \* -Werror= _specific error_ **treat a specific warning as an error**
     \* -Wno-error= _specific error_ **treat a specific warning as a warning even when -Werror is in effect**
We would like to at least cover the case of a missing file.

Add a way to specify this inside of the GUI, possibly as a preferences item: "treat warnings as errors".

**Nice to have, but might be too fancy** Add a way to modify the current compiler flags from code - similar to #pragma.
##

**Comment by 5solids** [comment]
By the way, does anybody know of any way to cause an error that stops the machinery?

For the time being, I could live with defining my own module and simply calling that in case I'am not happy with a configuration parameter or similar. For instance:

module exit(rc) {
    echo(str("RC: ",rc));
    // something that stop the compiler
}

if (foo == 23) {
    echo("ERROR: invalid foo value");
    exit(1);
}

Another alternative could be an assert() function.

Regarding checking if an include worked, it might be work around to add a kind of eye-catcher variable in the include file and to check its value after the import. But then again it would be great if we would have a way to programmatically stop the compile.

**Comment by kintel** [comment]
For assert(), see #381

**Comment by jordanbrown0** [comment]
+1.  It's quite annoying to make a mistake, have F5 immediately point out the mistake, but then have to wait for a known-bad re-render.

**Comment by kintel** [comment]
@MichaelPFrey This could be a great potential add-on to all the great warning work

**Comment by MichaelPFrey** [comment]
allowing a scad file to overwrite hardwarning "on the fly" would have to be at two or three parter, as the implementation has to take into account the different phases of parsing, evaluating and rendering the script.

Specifying which warnings are effected would require labeling all warnings first.

> From Triffid on the mailing list:
> 
> Greg Frost's extruders import STLs of his gears if they're present, for display purposes only. If they're absent, the warning is harmless. FIXME: Link to these models.
> 
> SO, we should have a way to treat it as an error, and have a way to get a mere warning if the import is only there for display purposes and isn't necessary for the actual output
> 
> perhaps %use or %import could trigger warning-only mode or something?

In such a case, we should consider addding a flag to the import module. I prefer to tweak the language, so that people can state their intention in a clean way in the script where things happen (see the undef example above), instead of giving them options to mess with the error/warning reporting/handeling in general.

**Comment by nophead** [comment]
I agree. I don't think adding to the language is a good idea at all as you would have all the scope issues to bear in mind. 

A command line option and a preference setting should be fine and is how all the other things that effect the language are currently set.

**Comment by ringerc** [comment]
I agree that it'd make a lot of sense to be able to make warnings fatal, with the option of it being global or scoped to a given include file. Perhaps extend the `use` directive to allow setting of file-scoped variables like `$

As [I suggested in a comment on #381](https://github.com/openscad/openscad/issues/381#issuecomment-544343769) it'd be great to be able to use the warnings functionality explicitly in modules too, by adding a `warning(...)` function.

**Comment by t-paul** [comment]
Option exists now.

**Comment by dclaze** [comment]
@t-paul how do we use this new option? Could you point to some documentation on what is needed to enable this "treat warnings as errors" behavior?

**Comment by t-paul** [comment]
`Edit` -> `Preferences` -> `Advanced` -> `OpenSCAD Language Features` -> ☑️ Stop on the first warning
