### ISSUE TITLE
Make Error: call to translation-make.sh not escaped/quoted

### ISSUE THREAD

**Issue by bpohl** [openscad/openscad#3290]
When the Makefile is generated it doesn't escape the fully qualified file path to call scripts/translation-make.sh.  It fails if there is a space in the path.  When I edit the Makefile to have either

  `/home/user/Git\ Repositories/openscad/scripts/translation-make.sh`

or

  `'/home/user/Git Repositories/openscad/scripts/translation-make.sh'`

it works fine.  

All other path references are escaped or quoted.  Seems that qmake misses doing so for translation-make.sh.

[And if anyone says `<mocking-voice>`"Just don't put spaces in dir/file names."`</mocking-voice>`, I'm going to kick them in the bytes!  Space is a VALID CHARTER! Don't be a lazy coder.]

**Comment by donbright** [comment]
https://help.github.com/en/github/site-policy/github-community-guidelines

**Comment by bpohl** [comment]
Thanks t-paul.
