### ISSUE TITLE
Openscad fails when stl is not mirrored()

### ISSUE THREAD

**Issue by traverseda** [openscad/openscad#330]
Module cache size: 0 modules
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
CGAL Cache hit: group(){multmatrix([[1,0,0,0],[0,1,0,0], (4981536 bytes)
PolySets in cache: 2
PolySet cache size in bytes: 366192
CGAL Polyhedrons in cache: 13
CGAL cache size in bytes: 64759968
   Top level object is a 3D object:
   Simple:        yes
   Valid:         yes
   Vertices:     2063
   Halfedges:   12076
   Edges:        6038
   Halffacets:   7950
   Facets:       3975
   Volumes:         2
Total rendering time: 0 hours, 0 minutes, 1 seconds
Rendering finished.
CGAL error in CGAL_Nef_polyhedron3::convert_to_Polyhedron(): CGAL ERROR: assertion violation!
Expr: check_protocoll == 0
File: /usr/include/CGAL/Polyhedron_incremental_builder_3.h
Line: 199
STL export finished.

You can find the file here. https://docs.google.com/file/d/0B4AoEIJqeFG5MGZ4SE1TQ1NXQWs/edit?usp=sharing

**Comment by kintel** [comment]
This was fixed recently

**Comment by traverseda** [comment]
Thanks.
