### ISSUE TITLE
Strange preview with linear_extrude

### ISSUE THREAD

**Issue by kjiwa** [openscad/openscad#3301]
Hello. I'm seeing some strange behavior with the following design.

```
difference() {
  linear_extrude(height=10) {
    difference() {
      square(10, center=true);
      square(5, center=true);
    }
  }

  cube(1, center=true);
}
```

The preview ends up having some clipping issues (I'm not sure what the proper terminology is for this).

<img src="https://i.imgur.com/b0iKAlh.png">

The design renders fine though.

<img src="https://i.imgur.com/1EnwRaD.png">

The problem seems to start with that cube at the end. It can be any shape, but everything renders just fine until it is added.

I tested this using the latest development snapshot 2020.04.26.ci4968 compiled for x64. The same behavior exists in the stable build, 2019.05.

**Comment by MichaelAtOz** [comment]
Try `linear_extrude(height=10, convexity=10)`

**Comment by kjiwa** [comment]
Thanks, that helped.
