### ISSUE TITLE
Improve preview rendering performance (Implement VBO renderer) [$175]

### ISSUE THREAD

**Issue by oysteinkrog** [openscad/openscad#3309]
I'm creating this issue so I can post a bounty on completing the WIP VBO renderer in https://github.com/openscad/openscad/pull/1935

**Comment by oysteinkrog** [comment]
https://www.bountysource.com/issues/91399377-improve-preview-rendering-performance-implement-vbo-renderer

**Comment by MichaelAtOz** [comment]
I added $50 from the OpenSCAD pool.

**Comment by mneuhaus** [comment]
i tossed in $50 as well 😄

**Comment by KjellMorgenstern** [comment]
Since #1935 has been merged to master, I think the OpenScad team can claim the bounty.

**Comment by t-paul** [comment]
Thanks for the ping, closing this issue as #1935 is merged. This should make it available for claiming on Bountysource (sometimes takes a few hours to sync).

Most of the work done by @obliviand, please claim the bounty :tada:.
