### ISSUE TITLE
Color Scheme - not used for 2D Render?

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3310]
It seems render (F6) does not use colours from the Color Scheme.
I wanted a black & white scheme.
```
{
    "name" : "B&W",
    "index" : 1420,
    "show-in-gui" : true,

    "colors" : {
        "background" :         "#000000",
        "axes-color" :         "#c1c1c1",
        "opencsg-face-front" : "#ff0000",
        "opencsg-face-back" :  "#0000ff",
        "cgal-face-front" :    "#ffffff",
        "cgal-face-back" :     "#ffffff",
        "cgal-face-2d" :       "#00ff00",
        "cgal-edge-front" :    "#ffffff",
        "cgal-edge-back" :     "#ffffff",
        "cgal-edge-2d" :       "#ffff00",
        "crosshair" :          "#f0f0f0"
    }
}
```
(Note originally most were ffffff, but above values are for testing, not B&W) 

I presume `cgal-face-2d` & `cgal-edge-2d` should be used to paint a 2D render.
But whatever they are set to still gets the standard colours:
![Capture B W F6](https://user-images.githubusercontent.com/1972961/81635630-fa8e1280-9454-11ea-8e1b-ef53924104e1.JPG)

Perhaps due to clipper?
(preview works)
With 2019.05 & 2020.05.06 on W7/64.

**Comment by thehans** [comment]
Fixed in #3326
