### ISSUE TITLE
Crash on start: dbus_connection_unref() bug

### ISSUE THREAD

**Issue by BlueNalgene** [openscad/openscad#3317]
Version: OpenSCAD version 2020.05.16 (nightly snap)
OS: Ubuntu 18.04 Bionic (running KDE 5.44.0)

Problem: The program crashes on start.  Running in terminal throws an error message.

Error message:

> The last reference on a connection was dropped without closing the connection. This is a bug in an application. See dbus_connection_unref() documentation for details.
Most likely, the application was supposed to call dbus_connection_close(), since this is a private connection.
  D-Bus not built with -rdynamic so unable to print a backtrace
Aborted

**Comment by BlueNalgene** [comment]
OpenSCAD runs properly when compiled from source.  There may be a problem with the Snap package since the error message is similar to [https://github.com/snapcore/core18/issues/4](https://github.com/snapcore/core18/issues/4).

**Comment by t-paul** [comment]
Yep, I found that too, trying to revert back to old core16.

**Comment by t-paul** [comment]
Pushed an update to https://snapcraft.io/openscad (which is also affected) so if the build succeeds that should show up in the edge channel in an hour or so. If that works, I'll update the nightly too.

**Comment by t-paul** [comment]
ARM64 is building for hours now, so I published everything else for https://snapcraft.io/openscad-nightly - I guess we have to find out what's going on with `core18`. It seems strange that this does not work on 18.04 but works fine on Debian/Testing.

**Comment by t-paul** [comment]
Ah, ARM64 finally finished too, so everything release. On the plus side, both versions now have 3MF support enabled :grinning:.

**Comment by BlueNalgene** [comment]
Confirmed.  Latest Snap is working.  Thanks.
