### ISSUE TITLE
Clipping artifacts in Preview with shared Z planes and difference()

### ISSUE THREAD

**Issue by 0x00null** [openscad/openscad#3322]
I'm running OpenSCAD 2019.05 on Windows 10 64bit with recent nvidia drivers.
GIven the following simple script (don't judge me too harshly!):
```
difference() {
  union() {
    translate([0, 0, 2.5]) cylinder(h=3, d1=92, d2=88);
    cylinder(h=2.5, d=88);
  }
  cylinder(h=5.5, d1=74, d2=78.5);
}
```

I've got some odd visual artefacts in preview:
![image](https://user-images.githubusercontent.com/1842335/82694278-e4edc980-9c5a-11ea-9385-9465733ce833.png)

This is with Goldfeather turned on. It's more pronounced when disabled.
Changing $fa or $fs doesn't seem to make any difference - it's just smaller triangles showing the clipping.

I assume this is because the two upmost surfaces of the cylinders share the same Z plane (it happens on the bottom, too!), and the rendering pipeline is outputting both surfaces to OpenGL, which is why I'm seeing this.

When rendering proper, all is well:
![image](https://user-images.githubusercontent.com/1842335/82694411-1b2b4900-9c5b-11ea-84d6-9c1a0c911971.png)

If I change the geometry of the solid I'm subtracting slightly so it no longer shares a Z plane, preview works as expected.

For example, changing the subtracted solid to: `translate([0, 0, -0.01]) cylinder(h=5.52, d1=74, d2=78.5);` causes the preview to behave:
![image](https://user-images.githubusercontent.com/1842335/82694935-0ef3bb80-9c5c-11ea-8192-9b06d926f97f.png)

Beyond hacking the geometry of my primitives, is there anything else I can do with this? I'd offer to help on the code front, but my C++ skills are abysmal (I'm a .NET developer, so you'd roast me alive XD)!

**Comment by t-paul** [comment]
No, there is no general way to solve this other than preventing coincident faces. See also [FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_are_those_strange_flickering_artifacts_in_the_preview?).
