### ISSUE TITLE
Step slider in Customizer selects incorrect values when step is not a multiple of the start value

### ISSUE THREAD

**Issue by antoneliasson** [openscad/openscad#3328]
Test case:

~~~
value = 45; // [45:25:195]
echo(value);
~~~

Save the above, open Customizer and hit Preview. The console shows `ECHO: 45`.

Drag the slider for *value* to the left. The console shows `ECHO: 25`. Expected is 45.

Drag the slider all the way to the right. The console shows `ECHO: 175`. Expected is 195.

**Comment by t-paul** [comment]
Woops. Looks like it calculates values somehow 0 based instead of the start value 45.
