### ISSUE TITLE
Feature suggestion: Set export file name

### ISSUE THREAD

**Issue by UrielGuy** [openscad/openscad#3347]
I would like to suggest a way to set the exported filename with a formatted string, either by a command or a variable name.
This should be the default filename when opening the export window, and users will be able to change it there. This will allow for easier use of customizable models where people might have many exported models from a single scad file. 
 examples using variable HEIGHT and WIDTH could be:

WIDTH = 10;
HEIGHT = 20;

$export_filename = str("wires_mount_", WIDTH, "x", HEIGHT");

**Comment by t-paul** [comment]
This collides with the idea of supporting multiple parts and using variables for that makes it awkward as those names are then "reserved for special use".
More general idea to solve that is to attach meta data to the model, see https://github.com/openscad/openscad/wiki/Meta-Data-Use-Cases

I'm closing the issue as it states a specific implementation which is not likely to be used, the feature in general is certainly on the wishlist.
