### ISSUE TITLE
Crash on Quit

### ISSUE THREAD

**Issue by gingerbeardman** [openscad/openscad#3350]
1. load model
2. animate it, choose FPS and Frames
3. edit script whilst animating, I disabled a section using *
4. Cmd+Q to quit
5. Crash

[OpenSCAD_2020-06-07-121928_matt.crash.zip](https://github.com/openscad/openscad/files/4741931/OpenSCAD_2020-06-07-121928_matt.crash.zip)

**Comment by MichaelAtOz** [comment]
Probably #1251.

**Comment by gingerbeardman** [comment]
OK, will close in favour of that.
