### ISSUE TITLE
Incorrect geometry after DXF import

### ISSUE THREAD

**Issue by olemis** [openscad/openscad#3354]
DXF not rendered correctly

**OpenSCAD version** : 2019.05
**Input file**: Octanorm [S-108](https://www.octanorm.com/us/products/product?text=S%20108&id=2101&pbc=1-1-125-500-900-2101) profile section upright (classic system).
**Result with online DXF viewer**

![Octanorm S-108 extrusion section in online DXF viewer](https://user-images.githubusercontent.com/538253/84465240-8063d000-ac44-11ea-8855-594d63897c9d.png)

**Result with OpenSCAD**

![Octanorm S-108 extrusion section DXF imported in OpenSCAD](https://user-images.githubusercontent.com/538253/84465371-cf116a00-ac44-11ea-9fe6-22014da7bed6.png)

![Zoom to coordinate system origin Octanorm S-108](https://user-images.githubusercontent.com/538253/84465417-f0725600-ac44-11ea-84eb-dd7b0c1d6e8c.png)

**Comment by t-paul** [comment]
That file can be downloaded only with login. Please put that somewhere accessible if allowed by license or provide a different test case.

**Comment by olemis** [comment]
@t-paul please check this [alternate download location](https://github.com/cubanmakers/3DPrintModels/blob/master/assets/extrusions/octanorm/official/files/cad/S%20108.dxf).

**Comment by olemis** [comment]
The same issue happens with all extrusion sections (i.e. `.dxf` files) in that folder . Attached picture shows the result of rendering them all after clipping imported volume to expected extrusion width and height. I did so in order to be able to render them altogether without interference of incorrect rectangular area.

![image](https://user-images.githubusercontent.com/538253/84526987-e5064580-acab-11ea-8dc0-9cf8fa2ed60e.png)

 Feel free to try them all as test input once a patch be submitted . I'll a few more soon .

p.s. once this will be fixed (in `master`?) are there `openscad` nightly builds (or equivalent) available for download ?

**Comment by t-paul** [comment]
I'm getting a number of warnings. I guess one of those unsupported objects leave behind some extra data which is coming though as that big rectangle.
```
WARNING: Unsupported DXF Entity 'SEQEND' (1) in "../../tmp/S 108.dxf". 
WARNING: Unsupported DXF Entity 'ATTRIB' (f) in "../../tmp/S 108.dxf". 
WARNING: Unsupported DXF Entity 'VIEWPORT' (1) in "../../tmp/S 108.dxf". 
WARNING: Unsupported DXF Entity 'ATTDEF' (f) in "../../tmp/S 108.dxf". 
WARNING: Unsupported DXF Entity 'TEXT' (17) in "../../tmp/S 108.dxf". 
```
Snapshot builds should show up automatically on the [download page](https://www.openscad.org/downloads.html#snapshots) (MacOS only every 2 days as we don't have enough server time to build more often).

**Comment by olemis** [comment]
> I guess one of those unsupported objects leave behind some extra data

🤔 ... understood . Could you please point me out to the DXF library source code?

**Comment by olemis** [comment]
> Could you please point me out to the DXF library source code?

@t-paul is [dxfdata.cc](https://github.com/openscad/openscad/blob/4ef45b005c0d3c4fa2b6b375652c5bf9ef051df4/src/dxfdata.cc) the right file ?

**Comment by t-paul** [comment]
Currently it's using an old [handcrafted parser](https://github.com/openscad/openscad/blob/master/src/dxfdata.cc) with limited compatibility.

The plan was to move to the BRL-CAD parser but that project is not quite finished (current state in https://github.com/openscad/openscad/issues/3044)

**Comment by olemis** [comment]
For the moment, I found a way to work around this by exporting DXF to SVG using [QCAD command line tools](https://qcad.org/en/products/qcad-command-line-tools) .

**Comment by t-paul** [comment]
That extra geometry is actually the page outline which gets messed up by the importer, but the actual geometry you want is layer `Profil`:
```
import("S 108.dxf", layer = "Profil");
```
