### ISSUE TITLE
Preview on Load, Preview on Save

### ISSUE THREAD

**Issue by robertlugg** [openscad/openscad#3386]
Request is to perform a preview when scad file is opened.  It is non-obvious in GUI tools that actually opening a file requires opening and then a "view" operation.  Instead on load at the very least trigger preview.  Ideally, preview to fit model in view.

Same with saving.  If you hit save and the preview is not up-to-date, you are misled into thinking what you see is what you got.  Instead perform a preview (ideally concurrently) with save (specifically <ctrl> S operation)

**Comment by nophead** [comment]
Set the Automatic Reload and Preview option on the design menu.

**Comment by robertlugg** [comment]
Thank you @nophead  and InPhase.  Yes, that option is what I'm looking for.  I will close this.  a "fit model in view" would also be nice but closing request instead.
