### ISSUE TITLE
GSoC 2020 - Feature-3 : Better Error Reporting &  a separate Error Log

### ISSUE THREAD

**Issue by Sharma-Hrishabh** [openscad/openscad#3388]
This issue is meant for discussion on enhancing the error-reporting of OpenSCAD.
The work during GSoC on this feature will comprise of following phases:
1) Adding New Infrastructure 
2) Converting Places calling warning/error 
3) Remove the old method.

Step-1:
- [x] Make a new function like PRINT, and pass different arguments individually, or we can use JSON objects and pass it after stringifying.
- [x] A separate class for ERRORS and warnings will receive all the new messages.

Step-2: 
- [x] Make the console output compatible with the new print function.

Step-3:
- [x] Code Refactoring and remove the old version of PRINT from the codebase

Step-4:
- [x] Handle failing tests

Step-5:
- [x] Make the messages in log clickable to jump to the location.

Step-6:
- [x] Add a filter on the basis message groups in GUI

Step-7:
- [x] Hyperlink, console messages with their location.

Feedback:
- [x] Combine Output Handlers

Todo:
 - [x] Handle Hyperlinks in Unsaved Files.
 - [x] Set the Default location of ErrorLog Widget as tabbed.

**Comment by Sharma-Hrishabh** [comment]
Existing WorkFlow: 
set_output_handler() -> coupled with console widget
PRINT takes the message and set the output_handler_data.

**Comment by Sharma-Hrishabh** [comment]
<a href="https://ibb.co/svx4hzz"><img src="https://i.ibb.co/jv0Ydss/Screenshot-from-2020-08-06-21-15-02.png" alt="Screenshot-from-2020-08-06-21-15-02" border="0"></a>

**Comment by t-paul** [comment]
Closed via  #3392 / #3435.
