### ISSUE TITLE
openSCAD STL file cannot be sliced correctly

### ISSUE THREAD

**Issue by mobil750** [openscad/openscad#3391]
I try to print an object from Thingiverse designed with openSCAD. The STL object looks fine but after slicing it looks different, in my case a bigger hole in the middle is not cut out. You can see the STL and sliced object in the attached screenshots. 
For slicing I use the newest PrusaSlicer V2.2.0+.
I tried to fix the issue with different rearrangements in the code but with no improvement.
Attached you also find the openSCAD source file

Can anyone help here?

[tray-test.scad.zip](https://github.com/openscad/openscad/files/5015226/tray-test.scad.zip)
[tray-test.stl.zip](https://github.com/openscad/openscad/files/5015227/tray-test.stl.zip)

![Screenshot of imported STL](https://user-images.githubusercontent.com/51677542/89170627-37fbcb00-d580-11ea-98f5-e1d257cfca3d.png)
![Screenshot sliced object](https://user-images.githubusercontent.com/51677542/89170629-392cf800-d580-11ea-8090-20fe1fc6bd28.png)

**Comment by MichaelAtOz** [comment]
That STL has self-intersections (pink) & degenerate faces (brown).
![Capture-tray-test](https://user-images.githubusercontent.com/1972961/89234742-f75b8a80-d62f-11ea-8533-7a1cbead86dd.JPG)

They are generated by OpenSCAD, another case of what I call the 'small number problem', which is confounded by many co-linear faces/edges, further compounded by $fn=360 producing lots of skinny triangles.
You may want to let the author know.

Here is a clean STL of lower triangle count, if the slightly rougher curves are suitable.
[tray-test-II.zip](https://github.com/openscad/openscad/files/5019211/tray-test-II.zip)

![Capture-tray-test-II](https://user-images.githubusercontent.com/1972961/89235025-c0d23f80-d630-11ea-9877-8cfc7cd38f30.JPG)

**Comment by mobil750** [comment]
Thanks for the hints. 

Yesterday I was able to get a correct STL after changing some code (removing for cycles and removing a a cone).

For new projects I will try to reduce the granularity.

**Comment by rcolyer** [comment]
This was the result of previewing that scad file.  One should not attempt to render a design that previews like this, as it indicates a faulty design without well defined surfaces.  As a wish-list item it might be nice if OpenSCAD could somehow detect and warn about this sort of thing during a render attempt, but there is no known way to automatically repair a source file in this state.

![tray-test_preview](https://user-images.githubusercontent.com/1266642/89465212-b94d8c00-d73f-11ea-950e-17556f7cf635.png)

**Comment by MichaelAtOz** [comment]
Ryan,

 

I'm not sure how you got a preview like that.

 

The design does have problems with coincident faces/edges etc. and could be better, but that
doesn't usually result in anything like your blue image.

 

This is what I get (preview not render):

 



 

 

These sort of artefacts generally point to problems:



 

But nothing like what you got.

 

I suspect something is wrong with your system.

 

  _____

**Comment by MichaelAtOz** [comment]
Interesting, I get the blue like messy result on my Linux box, the previous good one was on
Windows7...

 

  _____

**Comment by MichaelAtOz** [comment]
The Linux box has Intel graphics, known to have issues.

I set preferences/advanced to enable Force Goldfeather, it improved it but not perfect:

 



 

You may want to try that.

 

  _____

**Comment by MichaelAtOz** [comment]
Well, looks like the images in my emails went walkabout...

Here is:

Windows 7 clean preview

![Capture-Windows-preview](https://user-images.githubusercontent.com/1972961/89494101-d5613400-d7f8-11ea-8023-018171b3ac6c.JPG)


> These sort of artefacts generally point to problems:

![Capture-Windows-artifacts](https://user-images.githubusercontent.com/1972961/89494256-1d805680-d7f9-11ea-9e1d-2c7cff80bef5.JPG)


> I set preferences/advanced to enable Force Goldfeather, it improved it but not perfect:


![Capture-linux-force-goldfeather](https://user-images.githubusercontent.com/1972961/89494281-2ec96300-d7f9-11ea-88ce-899c30db2e4a.JPG)

**Comment by kintel** [comment]
@mobil750 We've improved STL export quite a bit. If you're still able to test this, please give the latest development snapshots a spin. Also check out Preferences->Features->manifold

Will close soon if we don't get any more response.

**Comment by kintel** [comment]
Closing as fixed due to no further reports
