### ISSUE TITLE
CGAL error in CGAL_Nef_polyhedron3()

### ISSUE THREAD

**Issue by ozasaf** [openscad/openscad#3397]
Hi Guys,
In the middle of my project, this Error started.
Don't know why? no special detail, can someone help?
Thanks
####################################################################
module bomb2() {
     import("C:\\Users\\asafo\\Downloads\\Untitled\\Untitled\\mesh2.stl",convexity=3);
}

module ring3() {
    //difference() {
        color("blue") translate([0,0,-48.5]) cylinder(10-1/128,39-1/128,39-1/128,true,$fn=32);
        //color("green") translate([0,0,-48.5]) cylinder(10,35.5,35.5,true,$fn=16);
    //}
}

union() {
    translate([42,0,30.4]) ring3();
    rotate([0,90,0]) bomb2();
    //ring3();
}

**Comment by nophead** [comment]
Most likely mesh2.stl has self intersections.

**Comment by ozasaf** [comment]
Thanks Chris,
I agree, but this is not my design so.....
I don't have what to do/fix.
My main problem with this error, that stand alone part(render) is OK.
when I add something with union() or something else, I got this error
Thanks again

‫בתאריך שבת, 8 באוג׳ 2020 ב-19:11 מאת ‪Chris‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by nophead** [comment]
When you render it alone OpenSCAD just draws the mesh It doesn't matter if it is non-manifold as it you can always draw a triangle soup. As soon as you do a CSG operation on it it needs to be 2 manifold or CGAL will throw a cryptic error message.

**Comment by ozasaf** [comment]
Thanks a lot Chris

‫בתאריך יום א׳, 9 באוג׳ 2020 ב-10:31 מאת ‪Chris‬‏ <‪notifications@github.com
‬‏>:‬

**Comment by CD1010** [comment]
Ok, i put a similar  bug in for gear library failing. What does this mean "As soon as you do a CSG operation on it it needs to be 2 manifold"  All i do is create a 64 tooth gear using bosl gear() function and i get an error.
What would i do to fix?

**Comment by nophead** [comment]
Post an issue to the BOSL library or use NopSCADlib.

![image](https://user-images.githubusercontent.com/566149/93801658-3b373d00-fc3a-11ea-9485-efdab75d169f.png)

**Comment by kintel** [comment]
This is likely a duplicate, but we cannot verify as the STL file in question isn't available. Closing for now.
