### ISSUE TITLE
Unhide editor for File->New

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#3401]
Suggestion from [forum post](http://forum.openscad.org/Opening-a-second-file-with-the-editor-hidden-tp29874p29881.html).

Creating a new, empty editor is useless with the editor hidden. So `File`->`New` could also force visibility, saving the user from doing that manually.

**Comment by nophead** [comment]
I tried the latest snapshot and found it doesn't work from the welcome dialog. I normally open a new instance and select new from there. If I do that I don't get an editor and if a do new from the file menu I get an editor with two untitled tabs.

**Comment by t-paul** [comment]
PR #3432 forces the editor to visible state for `new` and also when opening examples. The second case is debatable I guess, but right now I can't see a reason for opening an example without the editor visible.
