### ISSUE TITLE
Negative dimensions

### ISSUE THREAD

**Issue by naggie** [openscad/openscad#3402]
When using various 2D and 3D shape functions, I think it would be convenient to specify negative dimensions in some cases, as an alternative to positive dimensions with a negative translation.

For instance, a cube that is required to finish at `x=0` axis instead of starting at `x=0`:

![image](https://user-images.githubusercontent.com/208440/89926945-80a92900-dbfd-11ea-8b24-c73cd1c9bcff.png)

Could be specified as 

```
cube([50,-50,10]);
```
Instead of

```
translate([0,-50,0]) cube([50,50,10]);
```

This example is trivial, but I feel this may be useful in designs which rely upon many different datums and have a lot of CSG operations.

Currently nothing is displayed when negative dimensions are used. There is also no error.

Thanks for your time. OpenSCAD is the best.

**Comment by t-paul** [comment]
This is not planned for the builtin modules, current path is adding warnings for such cases.

It could be handled via a user space module (maybe even at some point with the same name as the builtin one, right now it needs a different name or alternate construction instead of builtin-cube).

**Comment by nophead** [comment]
I think you can override the built in cube with a user module that makes a polyhedron or linear_extrudes a square to avoid calling the original cube. I have my own version of sphere() that rotate extrudes a circle.

**Comment by t-paul** [comment]
Yes, that's what I meant with "alternative construction".

Even slightly crazy stuff would be possible, like
```
module cube(s) { resize(s) rotate(45) sphere(1, $fn = 4); }
```
(Don't do that! :grin:)

**Comment by rcolyer** [comment]
I concur it's a troubling path for the built-ins.  While it's understandable what it means for cube, it grows more sketchy when extended to other built-ins, and this introduces a weird inconsistency to have.  Here's a simple user-level implementation:

```
module NCube(size) { scale([for (s=size) sign(s)]) cube([for (s=size) abs(s)]); }
```
