### ISSUE TITLE
# at the beginning of the line hangs Emacs

### ISSUE THREAD

**Issue by alexander31415926535** [openscad/openscad#3410]
When i try to add # (shift-3 on Mac) at the beginning of the line, emacs hangs. Manual restart is needed. It is possible to add # sign anywhere else but the beginning of the line.

**Comment by t-paul** [comment]
Duplicate of #2969.

**Comment by t-paul** [comment]
Note that the linked issue seems to reference a fix, but I don't see a PR for that here yet. Maybe see if that works for you.
