### ISSUE TITLE
GSoC 2020 - Persistent Cache ability for OpenSCAD

### ISSUE THREAD

**Issue by tbharathchandra** [openscad/openscad#3417]
## About the Project

OpenSCAD is a powerful 3D modeling software, it performs huge computations in the process of rendering a model. The rendered models in the tree are stored in the cache as key-value pairs for avoiding recomputation in the future and to increase the performance. This project adds persistent nature for the existing cache mechanism which was using runtime memory to store the cache before.

This project has achieved the persistent storage ability by serializing (Boost Serialization) every rendered geometry and storing it in the Redis with it's key. A file system based cache storage solution is also developed which can be used in absence of a Redis server running in background.

#### Everything is implemented in a single PR - [Persistent Cache](https://github.com/openscad/openscad/pull/3316) 
Mentors: Torsten Paul - @t-paul  , Marius Kintel - @kintel 

## Work Done

* ### Selection of storage backend
    * After analyzing various storage options and use cases, we decided to provide Redis as a persistent cache storage preference in OpenSCAD.
    * http://forum.openscad.org/Help-me-in-choosing-the-perfect-key-value-datastore-for-persistent-cache-GSOC-2020-td29101.html

* ### Implementation Phases

    * #### Interface between OpenSCAD and Redis
        * we started by creating a generic interface between OpenSCAD and Redis by providing essential functionalities like inserting into the database, retrieving from the database, checking for a specific key's existence in the database and flushing all the keys.
        * files to refer [pcache.h](https://github.com/openscad/openscad/blob/b0ceaad03a13ce089112be72acda3eac5214adec/src/pcache.h) [pcache.cpp](https://github.com/openscad/openscad/blob/b0ceaad03a13ce089112be72acda3eac5214adec/src/pcache.cpp)

    * #### Serialization of Geometries
        * Serialization definitions are provided for every intermediate geometry classes like Polygon2d, PolySet and their internal classes like Vector2d, Vector3d. CGAL's nef_polyhedron_3 is serialized by using nef IO module.
        * files to refer [SCADSerializations.h](https://github.com/openscad/openscad/blob/b0ceaad03a13ce089112be72acda3eac5214adec/src/SCADSerializations.h)

    * #### Integrating Everything
        * Added geometric specific methods for caching and made required changes in GeometryEvaluator's to insert, check and get cache while traversing the tree.
        * Added a new CLI option (cache) and added new GUI under advanced tab in preferences to take in the settings needed. PCSettings class is created to manage this data.
        * Added a section in WIP wikibook of OpenSCAD about persistent cache.
        * [wiki book page](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/WIP#Persistent_Cache)

    * #### File System based Cache
        * A file system based cache option which can be used in place of Redis is developed, which uses the same serialization functionality and stores the cache data into the files on disk. 
        * files to refer [lcache.h](https://github.com/openscad/openscad/blob/b0ceaad03a13ce089112be72acda3eac5214adec/src/lcache.h) [lcache.cpp](https://github.com/openscad/openscad/blob/b0ceaad03a13ce089112be72acda3eac5214adec/src/lcache.cpp)

* #### [Development log](https://brlcad.org/wiki/User:Tbharathchandra/DevLog2020)

## Highlights / Challenges

* Working with the boost serialization package was a challenging job for me in the beginning because of their complex and not so accessible documentation. We have also seen a bug related to serializing a shared_ptr of const class in boost 1.58 , which raised the minimum boost version requirement for persistent cache to 1.59. 

## Future Work
* Developing the file system based cache further by adding some eviction mechanism without promising much with the performance.
* Adding other cache storage backend like memcached. With the serialization capability in place, a new backend can be with ease.
* Need some code cleanup related to retrieving the cache in GeometryEvaluator.

**Comment by t-paul** [comment]
Thank you for all the work put into this GSoC project. With GSoC now finished, I'm closing this issue which is meant a documentation of the final state.
