### ISSUE TITLE
GSoC 2020 - OpenSCAD GUI & Text Editor’s Interactivity Enhancements

### ISSUE THREAD

**Issue by Sharma-Hrishabh** [openscad/openscad#3422]
## About the Project

The project is focussed on enhancing OpenSCAD GUI by adding some new features and widgets, suggested by the OpenSCAD Community.
The following enhancements were proposed for working on during the GSoC 2020 period.
 - Implementing User-Defined Shortcut Feature through GUI
 - Number Scroll via Mouse Wheel in the Text Editor
 - Enhanced Error Reporting & a new Error-Log Widget

#### Following PRs have been made during GSoC- 

 - Shortcuts GUI  : [https://github.com/openscad/openscad/pull/3338](https://github.com/openscad/openscad/pull/3338)
 - Number scroll by mouse : [https://github.com/openscad/openscad/pull/3369](https://github.com/openscad/openscad/pull/3369)
 - Better Error Reporting & a separate Error Log: https://github.com/openscad/openscad/pull/3392 

Mentors: Ryan Colyer -  @[rcolyer](https://github.com/rcolyer)  , Hans Loeblich - @[thehans](https://github.com/thehans)

[Development-Log](https://brlcad.org/wiki/Google_Summer_of_Code/2020)

### 1. [Shortcuts-GUI](https://github.com/openscad/openscad/pull/3338)

-   ##### Polishing the File-Based Approach for Shortcuts, which I made before the commencement of GSoC.
	A simple JSON file can now be used to override the default shortcuts for various actions in OpenSCAD.
	Format:
	
		   {
			  // remove all shortcuts
			  "action1" : "",
			  
			  // overwrite default shortcut
			  "action2" : "CTRL-X", 

			  // overwrite default shortcut with multikey shortcut
			  "action3" : "CTRL-X, CTRL-Y", 

			  // add shortcut leaving the default one active as default
			  "action4" : ["DEFAULT", "CTRL-X"],
			  
			  // set multiple shortcuts
			  "action6" : ["CTRL-X", "CTRL-Y"],
			}	

	Example:

	    {
			"fileActionSaveAs":["DEFAuLT","Ctrl+M"],
			"viewActionShowEdges":"",
			"designActionPreview":"Ctrl+J"
		}

Note: JSON File must be placed	in UserConfig Path, with name - **shortcuts.json**

-   ##### Making a GUI for Shortcut Configuration.
	- Added a GUI for allowing users to set custom-shortcuts.
	- Users can set new shortcuts by selecting the action and pressing the key-sequence.
	- Added a search bar at the top of the widget, to search actions by name.
	- All the shortcuts can be reset to defaults using the 'Reset' button.

	Look and Feel:
	
![Shortcuts-GUI.gif](https://gist.github.com/Sharma-Hrishabh/4a8f6d8192da587dc94b4db414cd14a9/raw/b82ce6d66c3fbb9fe06b7eee4dca2cf3305ed40c/Shortcuts-GUI.gif)

 
    
Future Work:

 - A validator for Pressed Key-Sequences.
 - Import a file from GUI to the user-config path.

<hr>

### 2. [Number Scroll via Mouse Wheel in Text-Editor:](https://github.com/openscad/openscad/pull/3369)
This feature will allow the user to scroll the numbers in the text-editor by scrolling the mouse wheel.

#### What has been done:
- Numerical Values can be changed by mouse wheel scroll with a modifier.
- The modifier can be selected from Editor Preferences. 
- The step size can be configured from Editor Preferences.
- The feature can be disabled from Editor Preferences.

Look and Feel:

![Number-Scroll.gif](https://gist.github.com/Sharma-Hrishabh/4a8f6d8192da587dc94b4db414cd14a9/raw/52ddd29032d261487a047836b0ace6a915b1a815/Number-Scroll.gif)

Future Work:
- Disabling Mouse Movements while changing numbers (causing abrupt jump when the Most-Significant-Digit, changes its size)
- Delay Preview Until Done
<hr>

### 3.  [Better Error Reporting & a new Error Log Widget](https://github.com/openscad/openscad/pull/3392)
The work in this phase can be divided into two steps:

#### a. Introducing a new unified method to accept the messages for Errors, Warnings, Trace, etc from different parts of the application:
 Added a new method LOG() to accept log-messages from different parts and sending them to the console and a new ErrorLog Widget simultaneously.

Format:

	   LOG(message_group, Location, Document Path, Message, Args.....)

e.g. 

	   LOG(message_group::Warning,inst->location(),ctx->documentPath(),"color() expects numbers between 0.0 and 1.0. Value of %1$.1f is out of range");

** All the old PRINT(), PRINTB(), PRINT_DEPRECATION() statements have been replaced with the new LOG() ones, throughout the source-code.

** On the suggestion of mentors, changes in the expected output of tests are kept minimum.
Some outputs contained a ',' (comma), before location info and some don't. For working with the new approach, a uniformity was needed. So, after some discussion, the tests containing the outputs with ',' before location info, were overridden to remove it.

####  b. Making a new GUI Widget for logging all the Errors/Warnings kind of messages:
- A new Dockable Error Log Widget where all the errors/warnings and other messages will be listed in the tabular form.
- The row containing messages are selectable and jump the cursor/caret to the error/warning location inside the text-editor if the location exists.
- An option to Hide/Unhide Error-Log in View menu.
- A filter in the new widget to view messages belonging to a particular group.

Look and Feel:
	
![Error-Log.gif](https://gist.github.com/Sharma-Hrishabh/4a8f6d8192da587dc94b4db414cd14a9/raw/07dd78fd3acff1b0a248fe9b96326502dd2cbfd3/Error-Log.gif)

####  c. Hyperlink the messages in the console, with their locations:
The messages in the console having an appropriate concerning location in the .scad files are now hyperlinked with their locations. Clicking them will take the caret to the location of concern, inside the text editor.

Look and Feel:

![Console.gif](https://gist.github.com/Sharma-Hrishabh/4a8f6d8192da587dc94b4db414cd14a9/raw/59aa8e267c52fb8f5db453e14dd06356d45075a7/Console.gif)

Future Work:

 - Old PRINTB() like statements in the PRs which are not yet merged, have to be replaced with a new LOG() method.
<hr>

## Testing

 - Testing for GUI Features is done manually, by abusing the GUI Systems and trying different interactions. Feedback from the mentors helped me a lot in bringing new bugs into the notice.
 More Details can be found at respective PRs.
 - Testing of the new LOG() method introduced, is done through the already existing test-bed of OpenSCAD.

## Challenges

-  The biggest challenge for me was to jump from working on one feature to another, because they were quite different in implementation, and it took time for me to understand my tasks, before making significant progress at the start of all the three features.
- While introducing the new LOG() method for messages, most of the tests start failing due to certain differences in the expected output. So, handling those tests made me explore the entire source-code, and it was quite challenging.

**Comment by t-paul** [comment]
Thank you for all the work put into this GSoC project. With GSoC now finished, I'm closing this issue which is meant a documentation of the final state.
