### ISSUE TITLE
improve communication of 'non manifold' with users

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#343]
during discussion of issue #337 some folks have said it would be helpful if the program communicated the fact that their object was 'non manifold' more effectively with the users. 

Right now the Nef Polyhedron info dump shows "simple: no" 

but some would perhaps find it preferable to have something like this:

"Simple: No. Object is not 2-manifold."

Or even something like this:

"Simple: No. Object is not 2-manifold. Click here for more info" with a hyperlink to the wiki manual page about manifold-ness and what it means. 

addendum - unify all non-manifold messages to a single message, and make hyperlinking work from each one.
##

**Comment by njsokalski** [comment]
I think it would be extremely helpful to have some kind of indicator as to where the problem is, I have spent several weeks trying to figure out why my model will not render, and it seems almost impossible with large models.

**Comment by kintel** [comment]
Closing as this has improved a bit the last decade.
@njsokalski Please open a new ticket to request visual feedback for non-manifold issues.
