### ISSUE TITLE
GGAL Error when using BOSL gear library.  

### ISSUE THREAD

**Issue by CD1010** [openscad/openscad#3436]
I submitted this under BOSL but i think it may apply here.

I am using the latest version of OpenSCAD downloaded 9/17/2020.

Running 64 bit version on windows 10.
version 2019.05

Use the following code:

use <BOSL/involute_gears.scad>

$fn = 360;

gear(mm_per_tooth=10, number_of_teeth=64, thickness=8, hole_diameter=6);

Execute render above and rendering will show nothing. If i change to 32 teeth, it works fine.

Any guidance?

Error in console as follows:

Parsing design (AST generation)...
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
ERROR: CGAL error in CGAL_Nef_polyhedron3(): CGAL ERROR: assertion violation! Expr: e->incident_sface() != SFace_const_handle() File: /mxe/usr/x86_64-w64-mingw32.static.posix/include/CGAL/Nef_S2/SM_const_decorator.h Line: 329
Geometries in cache: 74
Geometry cache size in bytes: 415952
CGAL Polyhedrons in cache: 1
CGAL cache size in bytes: 0
Total rendering time: 0 hours, 0 minutes, 0 seconds
Rendering finished.

**Comment by kintel** [comment]
Are you able to reproduce with BOSL2?
