### ISSUE TITLE
OpenSCAD crashes while rendering division of STL with cylinder

### ISSUE THREAD

**Issue by Knochi** [openscad/openscad#3441]
Hi,

I'm trying to modify (remix) a model for metric nuts and bolts.
https://www.thingiverse.com/thing:4500713

When I try to subtract a cylinder from the imported mesh OpenSCAD crashes while rendering, preview works fine.
Rendering of imported mesh without substraction works as well.

Version Information:
OpenSCAD Version: 2020.06.14.ci5408 (git be16bd85)
System information: Windows(TM) 10.0 SP 0.0 NTW 1 MSDN 724833 4 CPUs 7.85 GB RAM

[DiffFromSTLCrash.zip](https://github.com/openscad/openscad/files/5282844/DiffFromSTLCrash.zip)

**Comment by MichaelAtOz** [comment]
The STL is bad.
Meshlab:
![Capture#3441](https://user-images.githubusercontent.com/1972961/94328512-91b7c900-fff6-11ea-993f-127887866764.JPG)
It's a mix of holes, degenerate faces and self-intersections.

**Comment by Knochi** [comment]
Ok but then I would expect an error message rather than a crash. I will try to fix up the STL using meshmixer.

**Comment by MichaelAtOz** [comment]
Possibly #2847.

**Comment by MichaelAtOz** [comment]
> And why does the unmodified mesh render fine?

If there is only one object CGAL does not get called.

**Comment by militaryCoder** [comment]
@Knochi, havve you tried to remesh this item and perform subtraction again?

**Comment by Knochi** [comment]
No.. I gave up on the idea of remixing this item. The point about the issue was robustness, so even if something is wrong with the operation the application shouldn’t crash.

Cu
David

**Comment by ChrisCoxArt** [comment]
The example given no longer crashes, but gives "ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron."

**Comment by thehans** [comment]
Fixed via #3526.
