### ISSUE TITLE
Command Line API?

### ISSUE THREAD

**Issue by edmundsj** [openscad/openscad#3455]
Is there a command-line API for this tool, or do I have to use the GUI? I would much prefer to simply invoke this from the command line.

**Comment by edmundsj** [comment]
JK, I see there is a section of the user manual dedicated to this. Closing issue.

**Comment by t-paul** [comment]
Plus new feature in snapshot versions as of yesterday :grinning: -> #3407.

**Comment by edmundsj** [comment]
Great work! This is an awesome package, by the way. I'm currently using [openpyscad](https://github.com/taxpon/openpyscad) to generate the source files in python, it would be really neat if this had a python wrapper. I suggested to the author of openpyscad that he do just that by hooking into your CLI. I think that would greatly improve usability.
