### ISSUE TITLE
Crash on rendering union of malformed polyhedrons

### ISSUE THREAD

**Issue by dottedmag** [openscad/openscad#3457]
Reproducible on 2019.05 and 2020.10.09 (git 7c2074fa5), macOS 10.14 (haven't tried other OSes).

Rendering attached file crashes OpenSCAD with SIGSEGV.

Stacktrace:
<pre>
* thread #11, name = 'QThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
    frame #0: 0x000000010d55c6f8 OpenSCAD`void CGAL::polygon_mesh_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > > >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >&, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>&, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyh
edron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > >) + 728
OpenSCAD`CGAL::polygon_mesh_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > > >:
->  0x10d55c6f8 <+728>: movq   (%rax), %rax
    0x10d55c6fb <+731>: movq   0x18(%rax), %rax
    0x10d55c6ff <+735>: movq   0x8(%rax), %rax
    0x10d55c703 <+739>: movq   %rax, -0x88(%rbp)
Target 0: (OpenSCAD) stopped.
(lldb)  bt
* thread #11, name = 'QThread', stop reason = EXC_BAD_ACCESS (code=1, address=0x0)
  * frame #0: 0x000000010d55c6f8 OpenSCAD`void CGAL::polygon_mesh_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > > >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >&, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>&, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_face<CGAL::I_Polyhedron_facet<CGAL::HalfedgeDS_face_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Plane_3<CGAL::Cartesian<CGAL::Gmpq> > > > > > > >, CGAL::internal::Polyhedron_index_map_external<CGAL::internal::In_place_list_iterator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > >, std::__1::allocator<CGAL::HalfedgeDS_in_place_list_halfedge<CGAL::I_Polyhedron_halfedge<CGAL::HalfedgeDS_halfedge_base<CGAL::HalfedgeDS_list_types<CGAL::Cartesian<CGAL::Gmpq>, CGAL::I_Polyhedron_derived_items_3<CGAL::Polyhedron_items_3>, std::__1::allocator<int> >, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true>, CGAL::Boolean_tag<true> > > > > > >) + 728
    frame #1: 0x000000010d5389f0 OpenSCAD`void CGAL::polyhedron_3_to_nef_3<CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool> >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >&, CGAL::SNC_structure<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>&) + 128
    frame #2: 0x000000010d53873c OpenSCAD`CGAL::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::SNC_indexed_items, bool>::Nef_polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >(CGAL::Polyhedron_3<CGAL::Cartesian<CGAL::Gmpq>, CGAL::Polyhedron_items_3, CGAL::HalfedgeDS_default, std::__1::allocator<int> >&) + 508
    frame #3: 0x000000010d512016 OpenSCAD`createNefPolyhedronFromPolySet(PolySet const&) + 2214
    frame #4: 0x000000010d5831e3 OpenSCAD`CGALUtils::applyUnion3D(std::__1::__list_iterator<std::__1::pair<AbstractNode const*, std::__1::shared_ptr<Geometry const> >, void*>, std::__1::__list_iterator<std::__1::pair<AbstractNode const*, std::__1::shared_ptr<Geometry const> >, void*>) + 243
    frame #5: 0x000000010d33bf4a OpenSCAD`GeometryEvaluator::applyToChildren3D(AbstractNode const&, OpenSCADOperator) + 522
    frame #6: 0x000000010d33bb2f OpenSCAD`GeometryEvaluator::applyToChildren(AbstractNode const&, OpenSCADOperator) + 495
    frame #7: 0x000000010d33e4ea OpenSCAD`GeometryEvaluator::visit(State&, AbstractNode const&) + 154
    frame #8: 0x000000010d33a550 OpenSCAD`NodeVisitor::traverse(AbstractNode const&, State const&) + 336
    frame #9: 0x000000010d33abe2 OpenSCAD`GeometryEvaluator::evaluateGeometry(AbstractNode const&, bool) + 578
    frame #10: 0x000000010d6a24b3 OpenSCAD`CGALWorker::work() + 67
    frame #11: 0x000000010f743140 QtCore`QMetaObject::activate(QObject*, int, int, void**) + 2320
    frame #12: 0x000000010f54e868 QtCore`QThread::started(QThread::QPrivateSignal) + 56
    frame #13: 0x000000010f551f46 QtCore`___lldb_unnamed_symbol298$$QtCore + 326
    frame #14: 0x00007fff67ae82eb libsystem_pthread.dylib`_pthread_body + 126
    frame #15: 0x00007fff67aeb249 libsystem_pthread.dylib`_pthread_start + 66
    frame #16: 0x00007fff67ae740d libsystem_pthread.dylib`thread_start + 13
(lldb) 
</pre>

**Comment by dottedmag** [comment]
[bug.txt](https://github.com/openscad/openscad/files/5358954/bug.txt)

**Comment by MichaelAtOz** [comment]
Probably #2847.

**Comment by t-paul** [comment]
Fixed by #3526.
