### ISSUE TITLE
Create new example(s): Module recursion (and cascading modules)

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#346]
From #116 - create a new official example or two demonstrating the new possibilities.

**Comment by kintel** [comment]
@NateTG @elalish We're relicensing all examples to CC0 (see https://github.com/openscad/openscad/pull/1144). This is the only remaining one not compatible. Would you guys mind authorizing this license change?

**Comment by NateTG** [comment]
I have no problem with it, but you'll need to get approval from him as well.

**Comment by elalish** [comment]
That’s fine with me; I didn’t even realize that had made it in.

-Emmett
