### ISSUE TITLE
[Feature requst] Running external editor from within openSCAD

### ISSUE THREAD

**Issue by pedjas** [openscad/openscad#3462]
It would be great to have option to run external editor from OpenSCAD.

Operating system can be set to run only one application on file double click. By default OpenSCAD runs on *.scad files. If one wants to use other editor he must manually start editor and load .scad file. That is cymbersome.

If there is option within OpenSCAD to run external editor, things would be much easier. User would run .scad file in OpenSCAD and then switch to external editor with simple click or keypress.

**Comment by MichaelAtOz** [comment]
You can right-click/open-with (Windows - there is similar on Linux) to open with an editor.

**Comment by pedjas** [comment]
On my computer I have option to open with but then selected application becomes default for oppening file extension.

In good old times, Windows had options to set default application sepearately for opening and editing file, but now it seems they decided to toss that functionality out.

**Comment by MichaelAtOz** [comment]
With Windows-7, right-click/open-with:
![Capture - open-with 1](https://user-images.githubusercontent.com/1972961/95932294-3750a200-0e17-11eb-8d31-0dcac748c58f.JPG)

choose-default-program:

![Capture - open-with 2](https://user-images.githubusercontent.com/1972961/95932328-4c2d3580-0e17-11eb-9715-616d41d911d4.JPG)

Un-check always-use...
Select your editor.
Then next time your editor will be on the list of right-click/open-with.

I did similar on Windows-10, it is slightly different, but same outcome.

I'm not too familiar with Linux.

**Comment by t-paul** [comment]
It seems we should leave that to the environment/OS then.
