### ISSUE TITLE
`rands()` with seed specified different to 2019.05

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3466]
```
key=373710; 
s=rands(-20,20,7,key);     // seed
echo(s=s);
```
2019.05
ECHO: s = [-7.58944, -4.83806, -12.6946, -14.347, -0.16186, 16.4219, -12.5746]

2019.11.20
ECHO: s = [-7.58944, -4.83806, -12.6946, -14.347, -0.16186, 16.4219, -12.5746]

2019.12.21
ECHO: s = [-4.83806, -14.347, 16.4219, 19.4972, 4.94835, 13.0342, -9.32073]

**Comment by t-paul** [comment]
Yes, that is due to #3144 moving to standard implementation (`std::mt19937`). That unfortunately makes seed values incompatible.
