### ISSUE TITLE
MacOS GUI help

### ISSUE THREAD

**Issue by lag4dayz** [openscad/openscad#3487]
I'm such a noob, but I am on MACOS, and I open scad, and only the yellow object screen pops up, I don't know how to add the code screen and am trying to get to the customizer, I have clicked every button but only this yellow object scale screen that I cannot even interact with the object appears, where do I click?? I am so lost.

**Comment by MichaelAtOz** [comment]
Please post a screen grab.

**Comment by mjparme** [comment]
@lag4dayz View->Hide Editor should be unchecked.

**Comment by t-paul** [comment]
Closing, no feedback.
