### ISSUE TITLE
New feature: OBJ export

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#351]
Export to the OBJ file format. OBJ is supported by at least Slic3r.
OBJ also opens for exporting objects with multiple materials. Support for this should be synced with availability of corresponding support in slicing software.

Future: Also import (apart from colors that should be easy enough for basic features)
##

**Comment by bo01ean** [comment]
+1

**Comment by GilesBathgate** [comment]
I believe the code for this is quite simple.

'''C++
void CGALExport::exportOBJ(QString filename)
{
	CGALPrimitive* pr=dynamic_cast<CGALPrimitive*>(primitive);
	if(!pr)
		return;

	CGAL::Polyhedron3* poly=pr->getPolyhedron();
	std::ofstream file(QFile::encodeName(filename));
	print_polyhedron_wavefront(file,*poly);
	file.close();
}
'''

That should work as a basic OBJ export. You might of course want to do something more exotic in your code that's entirely up to you. ;)

**Comment by kintel** [comment]
@GilesBathgate Yes, as mentioned above, that was what @donbright had prototyped. I didn't want to spend time implementing something which is partially broken, so I'd prefer tackling #910 properly.

Also, the primary benefits of OBJ export will probably be support for multiple objects or materials. Once we move forward with those features, this will be necessary, and in that case using ```print_polyhedron_wavefront``` won't be sufficient.

**Comment by GilesBathgate** [comment]
@kintel Its a difference in approach. One option would be to implement a feature with known limitations, publish those limitations and include user documentation that points the user to issue #910 . Alternatively you can hold off the feature until its implemented properly. 

The question is whether your users would be satisfied waiting or would gladly take something in the interim that they can use for the majority of cases. 

One might simply tell those users they can instead just use an 3rd party STL to OBJ conversion tool.

**Comment by MichaelAtOz** [comment]
Or leave it in the snapshots until mature, advanced users can use it from there.

**Comment by doug-moen** [comment]
@kintel wrote "Also, the primary benefits of OBJ export will probably be support for multiple objects or materials."

OBJ is a 3D graphics format, not a solid modelling format.
* An "object" is a named collection of polygons. There is no expectation that these form a 2-manifold surface. There is no concept of a solid.
* A "material" is actually a set of Phong shading parameters. "Materials" are applied to polygons. So using "materials", you can apply different shading parameters to different polygons. This is incompatible with the volumetric definition of color and material in #1608.
* Materials have the additional complication that materials must be defined in an external *.MTL file, which must be named by the *.OBJ file.

In the context of #1608, it might make sense to ignore the "material" feature of OBJ, and treat each named object as a named part.

**Comment by kintel** [comment]
@doug-moen Yes, I agree that materials in OBJ are better handled as named materials, not actual OBJ surface materials.

**Comment by jtoy** [comment]
so is this going into OpenSCAD?

**Comment by GilesBathgate** [comment]
>Its a difference in approach.
It seems I was championing the "agile approach", deliver some value early and then improve it later on. That is a very strange thing for me to do, I very much dislike half-finished code. ;)

**Comment by donbright** [comment]
The above arguments are also valid arguments against adding AMF import/export ... but it was added anyways. But I personally am still against adding half-finished OBJ export/import code. I can't even remember if regression test for 3d formats ever made it into the test suite?

**Comment by kintel** [comment]
The `experimental` feature system was introduced to allow us to merge such functionality early. Until we agree it's good enough, we just leave such features out of the release builds and require people to explicitly enable them.

**Comment by donbright** [comment]
yeah i know a lot of people like that system....  but my brain could never remember it... i just started getting confused... there is  "release" and "development" versions but also "experimental development version" and then for some branches, "experimental development branch with xyz feature" .. i could never remember which was which.

**Comment by kintel** [comment]
The development versions should always have experimental features enabled. That's what a development version is.
To avoid having to make public build of "branch with xyz feature", we're trying to fast-forward almost-finished features into master, but tagged experimental.

**Comment by mknippen** [comment]
+1

**Comment by sdasda7777** [comment]
Hi, it seems to me that when exporting to .obj, the top-level objects are implicitly unioned, negating lazy union feature. Is that the case?

**Comment by tpimh** [comment]
Should this be closed?

**Comment by t-paul** [comment]
Yep, thanks. Closed via #4542 / #4670.
