### ISSUE TITLE
Critical error in render in 2020.11.30.ci6340

### ISSUE THREAD

**Issue by nyponen** [openscad/openscad#3514]
This occurs sporadically on Windows 10. The render does not complete.
![OpenSCAD_bug](https://user-images.githubusercontent.com/17462467/101285117-67258180-3798-11eb-96ee-a84d0041678c.JPG)

**Comment by t-paul** [comment]
There's nothing that can be done with just a screen shot. Please read this [FAQ entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#How_do_I_report_bugs?) for bug reports that can be processed.
