### ISSUE TITLE
2020.12.RC2 Customizer preset dialogue

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3522]
Customizer active, click '+' button, dialogue 'Create New...', click Cancel, another dialogue pops-up.
Clicking Cancel clears it, but I had an instance when there were three.
Doesn't happen with 2020.11.30.

**Comment by t-paul** [comment]
I can't reproduce that. I suspect that might be the text-cache issue (e.g. #3119).

**Comment by MichaelAtOz** [comment]
No, not like that.
![Capture-RC3-custom-cancel](https://user-images.githubusercontent.com/1972961/103180924-f7199f80-48ee-11eb-9374-593f1f2a0163.JPG)
That '+' button, cancel brings up the dialogue again, two or three or more.
It appears to be related to multiple tabs, more tabs, more repeats.
RC3, 2020.12.12, 2020.12.14.
