### ISSUE TITLE
Segmentation fault when doing minkowski() with a circle with radius=0

### ISSUE THREAD

**Issue by quirxi** [openscad/openscad#3527]
Whenever this code is compiled/rendered it produces a segmentation fault reliably:

`
fiRad=0.0;
basePoints =[[0,0],[100,0],[0,100]];
basePaths =[];

minkowski()
{
    circle(r=fiRad);
        offset(-fiRad)
            polygon(basePoints,basePaths,18);
}
`

dmesg gives out following error:
> [43732.416499] AppRun.wrapped[26927]: segfault at 18 ip 00000000005493d8 sp 00007ffe8adb4360 error 4 in openscad[400000+726000]
>[43732.416515] Code: 00 00 41 57 41 56 41 55 41 54 55 53 48 89 fb 48 83 ec 48 48 c7 07 00 00 00 00 48 c7 47 08 00 00 00 00 48 c7 47 10 00 00 00 00 <4c> 8b 6e 18 48 8b 6e 10 64 48 8b 04 25 28 00 00 00 48 89 44 24 38

When I set fiRad=0.1 everything works as expected. 

OpenSCAD version 2020.12.08.ai6411 (git 1896c18) 
Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 GNU/Linux

**Comment by t-paul** [comment]
Fixed via #3528.
