### ISSUE TITLE
2020.12.RC2 (& older) Drag & Drop to Editor fails

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#3536]
Drag a .scad file, drop in Editor pane, doesn't load. 
Cursor shows correctly.
Drop on Title-bar, Preview, Console works.

Windows-7/64.
Fails as far back as 2019.10.15. Works on 2019.05, I have nothing installed in between these two.

**Comment by lar3ry** [comment]
Drag and drop fails for .stl and .svg as well. Worked on 2019.05

**Comment by t-paul** [comment]
Fixed, but the fix will only be effective for QScintilla >= 2.11. That should cover Windows builds, but currently does not include the AppImages.
