### ISSUE TITLE
Ctrl-insert (copy) does not work with 2020.12-RC3

### ISSUE THREAD

**Issue by tarhytti** [openscad/openscad#3558]
I'm using ctrl + insert button to copy selection but this key combination does not work in with rc3 version.

Of course, there's work-a-round by using ctrl-v but habit is hard to change...

**Comment by t-paul** [comment]
Keyboard shortcuts should become configurable at some point, there's not going to be support for that in the next release yet though. At this point only `CTRL+C` / `CTRL+V` is supported

**Comment by MichaelAtOz** [comment]
ctrl+insert produces this pop-up
![Capture-ctrl-insert](https://user-images.githubusercontent.com/1972961/103253359-ecd1d100-49d4-11eb-9fb8-7d9b6f926018.JPG)
What is it meant to do? It worked as 'Copy' in 2019.05.

**Comment by t-paul** [comment]
Insert text template (code snippet).

**Comment by MichaelAtOz** [comment]
Is that documented anywhere?

**Comment by t-paul** [comment]
I don't see it in https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/WIP so it's probably only in https://github.com/openscad/openscad/issues/3047

**Comment by nophead** [comment]
How does this work? I get a popup but I can't find any way to use it. Is it
just a prompt or I am supposed to be able to get it to complete what I
started typing?

**Comment by MichaelAtOz** [comment]
> How does this work?

I'm looking...

**Comment by nophead** [comment]
Oh, it seems to be right click to code complete. It isn't normal to right click on a context menu in Windows.

**Comment by t-paul** [comment]
Ok, can we *please* go back to the actual issue?

Any suggestions for a different keyboard short-cut to use for the templates?

**Comment by ofmetal** [comment]
> Any suggestions for a different keyboard short-cut to use for the templates?

How about just Ctrl+T ?

BTW, Ctrl+Ins is not completely gone in RC3. I've found it still works in about window :)

**Comment by t-paul** [comment]
`CTRL+T` is already spoken for although for a feature which is probably rarely used. For reference, see https://github.com/openscad/openscad/wiki/Keyboard-Shortcuts

**Comment by jordanbrown0** [comment]
And if we were to reassign Ctrl+T, it should go to New Tab (and Ctrl+N to New Window), to match browsers.

**Comment by t-paul** [comment]
IntelliJ IDEA uses `ALT+Insert` for "Generate Code". That might work?

**Comment by ofmetal** [comment]
> IntelliJ IDEA uses `ALT+Insert` for "Generate Code". That might work?

Sounds good.

**Comment by t-paul** [comment]
Windows build from #3562:
- [64-bit installer](https://6549-1049088-gh.circle-artifacts.com/0/64-bit/OpenSCAD-2020.12.29.ci6549-x86-64_change-template-shortcut-Installer.exe)
- [64-bit zip](https://6549-1049088-gh.circle-artifacts.com/0/64-bit/OpenSCAD-2020.12.29.ci6549-x86-64_change-template-shortcut.zip)

**Comment by MichaelAtOz** [comment]
In my searching it appears that many new keyboards drop the insert key. 

Not a problem for me, but I'm wondering how wide spread this is, particularly Mac.

 

Aside:

Have to be careful with Alt re menu selection, but Alt-Insert can't be a menu shortcut.

Using another modifier with Alt, can stop conflict with menu selection, e.g. Ctrl+Atl+T.

 

 

  _____
