### ISSUE TITLE
uncaught boost::filesystem exception when using relative path for -o .ast/.csg

### ISSUE THREAD

**Issue by knielsen** [openscad/openscad#3579]
This short snippet causes openscad to crash with uncaught exception:

```
  (mkdir -p z/a z/b/c && echo 'sphere(r=10);' > z/b/c/1.scad && cd z/a && ../../openscad ../b/c/1.scad -o 1.ast)
terminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::current_path: No such file or directory: "/kvm/src/openscad/openscad.git/z/b/c/../b/c"
```

Same with -o 1.csg.

I think the problem is just leftover code in do_export(), extra fs::current_path(fparent) calls when this is already done in cmdline(). I will submit a patch.

 - Kristian.

**Comment by t-paul** [comment]
Fixed via #3580.
