### ISSUE TITLE
Newline and tab ignored in echo

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#3585]
This used to work to insert a newline and tab in the GUI Console:
```
echo("Hello\n\tWorld!");
```
but looks like it got changed by https://github.com/openscad/openscad/commit/28d4a934

Previously "ECHO:" messages were specifically added using `QPlainTextEdit::appendPlainText` so that newline and tab could work, but now all console messages are added with `QPlainTextEdit::appendHtml` which ignores whitespace.

`appendHtml` is needed for Warnings etc which use the html to color the text.
But since echo strings get html escaped (so `<br>` can't be used either), there's no way to print multiple lines from one echo.

**Comment by TLC123** [comment]
Similar with:
echo( 1 , chr( 9 ) , 1 , chr( 13) , 1 );
-> ECHO: 1, " ", 1, " ", 1 

echo(str( "     1 " , chr( 9 ) , 1 , chr( 13) , 1) );
-> ECHO: " 1 1 1" 

in version 2020.12.31.ci6564 (git 7618d4d0f)
