### ISSUE TITLE
Talos Security Advisory Report (TALOS-2020-1222, TALOS-2020-1223)

### ISSUE THREAD

**Issue by CiscoTalos** [openscad/openscad#3598]
Hello, the Cisco Talos team found a security vulnerability affecting Openscad. As this is a sensitive security issue, we prefer to send this via email with PGP key, this message is to request a point of contact for handling.  Alternatively, if you can mark this issue private, we can send the details of the report and trigger input here.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. https://tools.cisco.com/security/center/resources/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue.

**Comment by t-paul** [comment]
Email sent, closing the issue here.
