### ISSUE TITLE
--hardwarnings causes warnings to terminate the command line mode but the exit code is 0

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#3616]
I expected the exit code to be 1, the same as errors when --hardwarnings is active as it promotes a warning to an error in my mind.

**Comment by Tomatower** [comment]
Is this related to #3660 / #3646?

**Comment by julianstirling** [comment]
Some more detail

If creating an STL `--hardwarnings` does create a non-zero exit code as there is no top level geometry. If creating say a PNG it exits with 0, an any script running it is unaware of the problem.

We have just his this problem on our automatic renders. We expected the script to say it had failed like it does on the automatic builds.
