### ISSUE TITLE
2021.01-RC6 - Hangs when quitting on macOS Catalina 10.15.7

### ISSUE THREAD

**Issue by riazzi** [openscad/openscad#3639]
When quitting either by the menu item or the window's close button, OpenSCAD hangs with the spinning rainbow wheel.  Activity Monitor shows the app as unresponsive but consuming 70-80% CPU.  It continues in this state indefinitely, requiring a Force Quit to end the process.  The hang occurs every time the application is run.

HW & SW details:
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro14,3
  Processor Name:	Quad-Core Intel Core i7
  Processor Speed:	2.9 GHz
  Number of Processors:	1
  Total Number of Cores:	4
  L2 Cache (per Core):	256 KB
  L3 Cache:	8 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  Boot ROM Version:	429.60.3.0.0
  SMC Version (system):	2.45f4

  System Version:	macOS 10.15.7 (19H114)
  Kernel Version:	Darwin 19.6.0

**Comment by t-paul** [comment]
Should be fixed via #3837.
