### ISSUE TITLE
Rendering bug in preview mode only - Z-buffer or blend mode?

### ISSUE THREAD

**Issue by WMays287** [openscad/openscad#3663]
I'm working on a small library for my robotics projects which adds rendering subroutines for simple metal hardware (screws, extrusions, etc.). While working on a T-nut, I noticed what I suspect to be a bug involving difference() linear_extrude() and polygon(): When looking at a preview (F5) some of the faces turn invisible, which doesn't happen with render (F6). ...Yes I know I have an outdated version of OpenSCAD, and this issue may have already been solved, but I'm still posting this just in case.
![Screenshot_2021-02-12_07-16-16](https://user-images.githubusercontent.com/60365549/107768181-12583700-6d04-11eb-9837-a1e4815b9a45.png)
![Screenshot_2021-02-12_07-16-33](https://user-images.githubusercontent.com/60365549/107768185-12f0cd80-6d04-11eb-8806-5e07092cebb5.png)

**Comment by t-paul** [comment]
Looks like you need to specify `convexity` of the polyhedron (see [faq entry](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#Why_are_some_parts_(e.g._holes)_of_the_model_not_rendered_correctly?)).

**Comment by WMays287** [comment]
You're right, the default convexity is too low for shapes like this.
