### ISSUE TITLE
positional parameter silently overrides previous named parameter

### ISSUE THREAD

**Issue by jordanbrown0** [openscad/openscad#3672]
```
module foo(a) {
    echo(a=a);
}

foo(a=1, 2);
```

results in

```
ECHO: a=2
```
It sure seems like this should be a warning, just like `foo(a=1, a=2)` is.

**Comment by thehans** [comment]
I worked on fixing this sort of thing as part of #3161 but it was out of scope for the original issue and never ended up getting merged.  The `resolveArguments` overhaul was pretty comprehensive in terms of avoiding these sort of odd overrides or warning when they occur.

**Comment by thehans** [comment]
Fixed by #3745
