### ISSUE TITLE
Two identical models - one gives WARNING: Object may not be a valid 2-manifold and may need repair! 

### ISSUE THREAD

**Issue by openscaduser** [openscad/openscad#3700]
Hi

Two identical models - one gives WARNING: Object may not be a valid 2-manifold and may need repair! 
The other shape is fine. The only difference is a translate outside a block and the same translate applied to all elements inside the block.

File examples are below

[zzz_warning_scad.txt](https://github.com/openscad/openscad/files/6067225/zzz_warning_scad.txt)
[zzz_nowarning_scad.txt](https://github.com/openscad/openscad/files/6067226/zzz_nowarning_scad.txt)

Interestingly the console gives different outputs even though they are the same. see below

OpenSCAD 2021.01
https://www.openscad.org/

Copyright (C) 2009-2021 The OpenSCAD Developers
This program is free software; you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.

 
Parsing design (AST generation)...
Saved backup file: /home/sgeorge/.local/share/OpenSCAD/backups/unsaved-backup-VFGpAVwP.scad
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
Geometries in cache: 6
Geometry cache size in bytes: 87312
CGAL Polyhedrons in cache: 5
CGAL cache size in bytes: 2961168
Total rendering time: 0:00:17.093
   Top level object is a 3D object:
   Simple:        yes
   Vertices:      600
   Halfedges:    1800
   Edges:         900
   Halffacets:    608
   Facets:        304
   Volumes:         2
Rendering finished.
 
Parsing design (AST generation)...
Saved backup file: /home/sgeorge/.local/share/OpenSCAD/backups/unsaved-backup-VFGpAVwP.scad
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
Geometries in cache: 6
Geometry cache size in bytes: 87312
CGAL Polyhedrons in cache: 6
CGAL cache size in bytes: 3904136
Total rendering time: 0:00:02.201
   Top level object is a 3D object:
   Simple:         no
   Vertices:      699
   Halfedges:    2102
   Edges:        1051
   Halffacets:    708
   Facets:        354
   Volumes:         2
WARNING: Object may not be a valid 2-manifold and may need repair! 
Rendering finished.

**Comment by rcolyer** [comment]
This is not a bug in OpenSCAD, it's a subtle requirements violation in the design.
```
 difference()
  {

  cylinder(h=6,d=12 );

  translate([0,0,4])
  cylinder(h=2,d=9);
  }
```
The heights of these two cylinders are both 6, so you are getting "z-fighting" (which you might see in preview as a flickering surface), which under render operations has undefined results and can result in geometries which are not manifold.  Applying additional transformations before the difference between two results with z-fighting will sometimes arbitrarily change whether or not it works in the desired manner, as is the expectation for an undefined result.  The correct solution to this is to always guarantee that designs have a clearly defined overlap on difference operations, where the part being removed is either entirely inside a coplanar surface, or entirely outside (overlap) to remove a piece of a surface.
