### ISSUE TITLE
Crash with some specific letters, e.g. RUNIC LETTER PERTHO PEORTH P

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#3701]
Ref: https://en.wikipedia.org/wiki/Peor%C3%B0
```
text("ᛈᚪᛋᛏᚪ", size=24, $fn=16);
```
Looks like there's no default direction as this can be written rtl and ltr so harbuzz crashes with
```
../../src/hb-shape-plan.cc:208: hb_shape_plan_t* hb_shape_plan_create2(hb_face_t*, const hb_segment_properties_t*, const hb_feature_t*, unsigned int, const int*, unsigned int, const char* const*): Assertion `props->direction != HB_DIRECTION_INVALID' failed.
```
as OpenSCAD passes HB_DIRECTION_INVALID.

Interesting side note: The [BabelStone](https://www.babelstone.co.uk/Fonts/Runic.html) font flips glyphs depending on writing direction:

![grafik](https://user-images.githubusercontent.com/1330241/109650317-5731f980-7b5d-11eb-87b3-177d83b60ab9.png)

**Comment by jordanbrown0** [comment]
Tidbit:  on Windows, use Segoe UI Historic.

Note:  The problem only occurs when `text()` tries to automatically determine the intended direction. Work around it by explicitly specifying a direction.
