### ISSUE TITLE
2021.01 not working on macos: 11.2.2

### ISSUE THREAD

**Issue by stepheneb** [openscad/openscad#3708]
I recently upgraded from the last version of macos 10.x to Big Sur 11.2.2 and OpenScad v2021.01 which had been working fine seems to be broken.

Opening examples or choosing new results in a blank pane on the left. Looks like one problem is that the top of the window is positioned above the top of the window.

![image](https://user-images.githubusercontent.com/7188/110227065-68af3480-7ec2-11eb-875e-8cb4e36fe954.png)

**Comment by stepheneb** [comment]
And this morning it appears to be working -- can't think of any changes ???

![image](https://user-images.githubusercontent.com/7188/110247798-03982500-7f3c-11eb-83e2-87bd8b6b0ea6.png)

**Comment by t-paul** [comment]
Thanks, good news. Without an active macOS developer we would have a difficult time tracking down issues specific to macOS.
