### ISSUE TITLE
Give colour triplets/quadruplets the same privileges given to x-y-z triplets

### ISSUE THREAD

**Issue by mjk-at-sag** [openscad/openscad#3722]
Support `colour.r`, `colour.g`, `colour.b`, and `colour.a` in the same way that `vector.x`, `vector.y`, and `vector.z` are supported.

I see this as a low-priority enhancement -- but well above `"aliceblue".g`!

A more useful enhancement would be `.h`, `.s`, `.l`, and `.v` with internal conversions to allow some users more comfortable input.
```openscad
c.h = 210; c.s = 79.1; c.v = 33.7;
echo(red=255*c.r, green=255*c.g, blue=255*c.b);
```
yielding
```openscad
ECHO: red = 18, green = 52, blue = 86
```

**Comment by MichaelAtOz** [comment]
```
c.h = 210; c.s = 79.1; c.v = 33.7;
echo(red=c.r, green=c.g, blue=c.b);
```

That is more than just access to elements, that (converting to/from) is equiv. to a color class.

Linking to objects discussion #3088.

**Comment by jordanbrown0** [comment]
Access to the first four elements as r, g, b, a, analogous to x, y, z, w, was added in #4010 .
