### ISSUE TITLE
Lost translation

### ISSUE THREAD

**Issue by PRouzeau** [openscad/openscad#3726]
Lost translation
Recent snapshots (Windows, 64 bits) lost most translation.
The only things which remain translated now is the panels titles (except the error-log panel, too recent stuff), and in customizer panel, the default set name, everything else stay in English (see the images) 
![Copie_ecran_01](https://user-images.githubusercontent.com/11719573/111921089-f1b59680-8a92-11eb-84d3-53c2d3df45f8.jpg)
![Copie_ecran_02](https://user-images.githubusercontent.com/11719573/111921106-0db93800-8a93-11eb-8f94-37d18ee9d874.jpg)
Below image is what it used to be. Note that I did’nt lost everything because in this old screen copy (2016), the customizer default set name was not translated, while it is now...
![Copie_ecran_03](https://user-images.githubusercontent.com/11719573/111921126-21fd3500-8a93-11eb-91c0-61330767c379.jpg)

**Comment by thehans** [comment]
I identified some problems with the translation configuration due to our switch from qmake to cmake.  I think it should be better with changes in #3787.
@PRouzeau Can you try the build artifacts from the PR to verify if it is better now?

I've only done a quick test of the win64 build through wine but it seemed to apply translations correctly.

**Comment by thehans** [comment]
The PR mentioned above has been merged now, so the most recent dev snapshots should have those changes available for testing.

**Comment by PRouzeau** [comment]
Tested the 31.05.2021 snapshot in Windows 32 bit (got troubles- with antivirus ?-  installing the 64 bit version), and translation is now back except that the default name set of customizer is yet back to english (while it was the only translated part on former versions) was 'valeurs de conception par défaut' and now '<design default>'.
![Op15b](https://user-images.githubusercontent.com/11719573/120502836-0d0e1d80-c3c3-11eb-8cf0-201a36ab3961.jpg)
![Op15](https://user-images.githubusercontent.com/11719573/120502839-0da6b400-c3c3-11eb-9945-5426139b4ce4.jpg)
