### ISSUE TITLE
MCAD library outdated

### ISSUE THREAD

**Issue by fozzedout** [openscad/openscad#3727]
I've been using the MCAD library on the latest Mac release (2021.01), but the MCAD/boxes.scad is very much out of date - it only has the code in for roundedBoxes and not roundedCube, and that file was last updated in 2019 ([master branch](https://github.com/openscad/MCAD/blob/master/boxes.scad))!

Can the latest version of the MCAD library please be included in the next release?

```
use <MCAD/boxes.scad>

// works
roundedBox(size=[10,20,30],radius=1,sidesonly=false);

// doesn't work - WARNING: Ignoring unknown module 'roundedCube' in file , line 7
roundedCube([20, 30, 40], 5, true, true);
```

**Comment by t-paul** [comment]
It's on the checklist #3640.
