### ISSUE TITLE
Key expired for ubuntu 20.04

### ISSUE THREAD

**Issue by farzonl** [openscad/openscad#3747]
Noticed a build error today:
![image](https://user-images.githubusercontent.com/1802579/115186822-5a069080-a0b0-11eb-8879-248abf58626d.png)

Seems like the Key expired yesterday:
![image](https://user-images.githubusercontent.com/1802579/115186832-5ecb4480-a0b0-11eb-9d7f-f4d34ef94604.png)

**Comment by t-paul** [comment]
Thanks, extended key at https://files.openscad.org/OBS-Repository-Key.pub - rebuild is running.
