### ISSUE TITLE
macOS: missing close cross button on tabs

### ISSUE THREAD

**Issue by gingerbeardman** [openscad/openscad#3758]
In older versions there used to be a cross to show the tab could be close.

You can still click in the white space to the left of the filename to close the tab, but there should be a cross icon/widget there.

<img width="1080" alt="Screen shot 2021-05-03 at 11 45 49" src="https://user-images.githubusercontent.com/49612/116867481-38a3b980-ac05-11eb-88b2-6b95d1aa0bf9.png">

Tested:
- 2021.01 public release
- 2021.05.02 dev snapshot

**Comment by t-paul** [comment]
Closing this one, #3775 shows it's a Qt5 issue so tracking continues there.
