### ISSUE TITLE
list more info in 'help/lib info', like the branch

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#376]
note to self

the info dumped by the test suite should be the same info dumped by the gui. the gui should have more info available, like compiler, branch, date of compilation, etc. 

its important when trying to debug stuff, to be able to verify you are running the version you think you aree running. or when testing out an experimental branch. it is easy to get confused. esp on Windows. 

a good refactor would be to consolidate that code into one place

**Comment by kintel** [comment]
This was significantly improved recently
