### ISSUE TITLE
Naming model in 3mf export

### ISSUE THREAD

**Issue by freiser77** [openscad/openscad#3763]
Hello,

I create a model in openSCAD and export it in 3mf format. When I import it in PrusaSlicer, the model is shown there as "OpenSCAD model".

Is there any way to set a name for the models in OpenSCAD?

Like
```
name("bottom") cube(10);
name("top") cube(20);
```

Greetings

**Comment by t-paul** [comment]
No, there's currently no way to give a specific name.

**Comment by freiser77** [comment]
Hello @t-paul,

why do you close the issue then?

Wouldn't it be worth a feature request?
It shouldn't be such an effort, should it?

Greetings

**Comment by t-paul** [comment]
What you posted was not a feature request but a question, so I answered. There's already feature requests that are very much covering the core topic (not the specific 3mf name though).
And yes, multiple objects are a bigger change as the current processing results in a single object.
