### ISSUE TITLE
2021-01 Release build issues (ABI mismatch?  -D_GLIBCXX_USE_CXX11_ABI=0)

### ISSUE THREAD

**Issue by TheAndr0id** [openscad/openscad#3768]
I'm not a developer, I'm a sysadmin.  I build code to deploy on systems (in this case, my own).

Trying to build the latest release (2021.01) under Linux x86 (custom deployment, no apt-get here) I ran into something I've never seen before.  I'm using an older build of the Boost system (1.65.1) which still meets requirements.  The configure worked, and after running the make I was getting the following error during linking:

```undefined reference to `boost::program_options::abst```

(This was dug out of three pages of random noise generated by the compiler)

After doing some googling, I found some postings around Boost and ABI mismatches.  Then I found this: https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

After I added    QMAKE_CXXFLAGS+="-D_GLIBCXX_USE_CXX11_ABI=0"  to the qmake call, then everything builds and I can run the new openscad.  (I haven't checked it with code, the window opens, so yay!)

I'm not going to say what I've done is good, but it works and maybe this will help someone else who runs into this issue.   Have I done something bad here?  From the above link:

> In the GCC 5.1 release libstdc++ introduced a new library ABI that includes new implementations of std::string and std::list. These changes were necessary to conform to the 2011 C++ standard which forbids Copy-On-Write strings and requires lists to keep track of their size. 

That sounds kind of bad, but sometimes there's a little "cry wolf" to justify a political/design/development decision.

The task that *I* see here is to address the requirements for OpenSCAD.  My Boost is a couple of years old, but still within the requirements listed.  From some of the reading I've done the newer releases of Boost use the new ABI which removes this issue.   (I didn't test this as updating Boost on my system would most likely introduce a whole new world of hell)

So...  Should the requirements be updated to remove this macro workaround for the Boost libraries?

**Comment by t-paul** [comment]
QMake support is now obsolete. I don't know if and how `cmake` handles this case. It sounds like this is more a topic for the local system / compiler setup, not a specific application as in all cases libraries and applications need to be compiled with compatible compiler flags that affect the ABI.

**Comment by TheAndr0id** [comment]
According to the front page build documentation:
https://github.com/openscad/openscad#compilation

> First, run qmake openscad.pro from Qt to generate a Makefile.

and

> If you had problems compiling from source, raise a new issue in the issue tracker on the github page.

So, if there's another way to do this, shouldn't the documentation be updated?

I'm just sayin'...

**Comment by t-paul** [comment]
I'm closing this as I don't see anything that can be done from OpenSCAD side. Builds on a system with special build flags will need to take care of those flags being passed to the OpenSCAD build too.
