### ISSUE TITLE
OpenSCAD closes when trying to save STL

### ISSUE THREAD

**Issue by colinhercus** [openscad/openscad#3769]
HI,

When I try to export as STL my model Openscad closes. This happens immediately I click the STL icon.
 
Using OpenSCAD-2021.01-x86_64.AppImage and OpenSCAD-2021.05.11.ai7925-2021.05.11.ai7925-x86_64.AppImage

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
Codename:	focal

I'll try and build from source to see if that helps.

Thanks, Colin

**Comment by t-paul** [comment]
Duplicate of #3523.
