### ISSUE TITLE
echo("%2");  --> error

### ISSUE THREAD

**Issue by 3Dietrich** [openscad/openscad#3771]
version 2021.01 
macOS BigSur 11.3.1

This code:
```
echo("%2");
```
leads to an error
<img width="418" alt="Bildschirmfoto 2021-05-13 um 13 05 56" src="https://user-images.githubusercontent.com/4608796/118118808-ba59cb00-b3ed-11eb-90c7-fdfb7c7bb43a.png">

and I need to restart OpenSCAD to continue working because it doesn't update anymore

**Comment by nophead** [comment]
Same on Win7 with OpenSCAD 2021.03.24.ci7656. Looks like something passes the string to be echoed to something that expects a format string first.

**Comment by redlizard** [comment]
This is fixed in master.
