### ISSUE TITLE
Customizer field disappear if value is negative

### ISSUE THREAD

**Issue by PRouzeau** [openscad/openscad#3772]
On the version 2021.05.14 (Windows, 64 bits) If a field default value is negative, the associated field disappear from the customizer tab. This occurs only for default value, you can modify a positive value to negative without trouble.
This is new and was not present in version 2021.03.21 (Windows, 64 bits)

Below code show normally  the two fields in customizer tab
<pre><code>/* [data tab] */
field1 = 1;
field2 = 1;
</code></pre>
while here, the second field disappear from customizer tab
<pre><code>/* [data tab] */
field1 = 1;
field2 = -1;
</code></pre>

**Comment by t-paul** [comment]
For clarity please also add the code snippet to reproduce.

**Comment by thehans** [comment]
I can confirm that this is reproducible on Linux Mint 20 Nightly build.

The code given is enough to create customizer tab after F5.

**Comment by redlizard** [comment]
My mistake entirely. Thanks for the report.
