### ISSUE TITLE
Retina/hi-dpi toolbar icons

### ISSUE THREAD

**Issue by gingerbeardman** [openscad/openscad#3786]
Current icons are:
- pixelated on retina/hi-dpi displays
- different styles as they were drawn at different times by different people

I'm happy to draw a new set of toolbar icons if this would be helpful.

New icons would be a unified style with a library of shapes that can be used for future toolbar icons.

They would be as vector so can work at any size, and I would contribute the original artwork and any exported versions (32px, 64px, black, white, etc) with no licence, or your chosen licence, attached.

**Comment by gingerbeardman** [comment]
Some examples from a spare few minutes

<img width="677" alt="Screen shot 2021-05-24 at 14 37 55" src="https://user-images.githubusercontent.com/49612/119355849-a3dd2a80-bc9d-11eb-8f7c-f20e792c43e9.png">

**Comment by t-paul** [comment]
We have some (most?) of the icons in some branch as OpenSCAD code. The plan was to move to SVG icons at some point which might be even better than the need for different pixel sizes.

I'll have a look where those icons are stored...

**Comment by gingerbeardman** [comment]
Moving to vector makes total sense.

I'll stop now and wait to hear from you.

**Comment by t-paul** [comment]
I've merged the script and icons from the old `svg-icons` branch. They are not actually used directly yet but were used to generate the current pixmaps.

The SCAD script is https://github.com/openscad/openscad/blob/master/resources/icons/svg-default/icons.scad

List of icons available so far:
![icons](https://user-images.githubusercontent.com/1330241/120083094-ba80e880-c0c6-11eb-8e9d-2228e03122a4.png)

**Comment by t-paul** [comment]
Added some more icons. I'll try to post a PR actually using the icons.
![1](https://user-images.githubusercontent.com/1330241/120090260-5cbdc200-c101-11eb-9a78-ffae8f7ac123.png)

Those will need some more polishing to create a bit of a border (Linux/4k display):
![grafik](https://user-images.githubusercontent.com/1330241/120090493-3436c780-c103-11eb-8e75-c05ce46bf753.png)

**Comment by gingerbeardman** [comment]
Cool.

My issue with these icons, and with the pixmaps, is that the icons seem to fight against each other due to their relative sizes. 

I think all icons should be as wide/tall as the "angled cube" with the exception of any elements that like the arrows and hourglass. This would give much more pleasing and less claustrophobic toolbars.

**Comment by t-paul** [comment]
Yes, that's what I mean with the todo item in #3795. Right now they just scale to fit based on bounding box. I think the easiest solution is to normalize to e.g. 100x100 in the SCAD and then patch the SVG to use a viewbox of maybe 140x140 to also keep some additional margin.

**Comment by gingerbeardman** [comment]
Ah, right, great!

I should have read that rather than doing this mockup.

![m](https://user-images.githubusercontent.com/49612/120218162-3dbe4d80-c231-11eb-8fb8-2a42a9f17264.png)

**Comment by t-paul** [comment]
Yes, that's much more like I would want it to look like.

**Comment by gingerbeardman** [comment]
Just a quick note that whilst SVG icons change colour in dark mode the chrome around them does not and this makes things less readable: white on silver.
