### ISSUE TITLE
Weird half visible surface

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#379]
I noticed something strange.

I presume you know the half visible surface you get when you don't do a clean difference.
e.g.
![weird 2011-12-30](https://f.cloud.github.com/assets/1972961/589665/572e7760-c9c7-11e2-91a6-b62374128175.jpg)

I usually use `s=0.01` and something like `translate([10,10,-s])` to make sure `difference()` doesn't have coincident surfaces. Similarly for `union()`. Worked for me.

So I was designing something and got the funny looking surface even though I used the above technique. Zooming in the surface would dissapear, zooming out it would solidify. I don't recall earlier versions having this problem.

The above image is from

```
// test.scad
echo(version());
s=0.01;  // smidgen for difference 
// clean difference
difference() {
cube([200,200,200]);
// -
translate([1,-s,1])
cube([198,199+s,198]);
}
// bad difference
translate([-210,0,0])
difference() {
cube([200,200,200]);
// -
translate([1,0,1])
cube([198,199,198]);
}
```

So the right cube should be OK.

I noticed it in 2013.05.28, then went back .03.09 & 2011.12.30 and it behaved the same.
I am certain I never had that issue before, is it possible, after having used the installer for .05.30, that older .exe files are using newer libraries or something. (prior to that I just had unzipped the openscad files rather than installing). This is what help lists;
![weird libraries](https://f.cloud.github.com/assets/1972961/589747/84c6e628-c9ca-11e2-842e-0742b5cfe5c0.jpg)
(or if I run the old version concurrently but after the new, will it use the new libs - I'll test this - edit - no No difference)

If I change it to `s=0.02` It looks like it used to;
![weird 2](https://f.cloud.github.com/assets/1972961/589724/cd152288-c9c9-11e2-9be1-e80a9a117d52.jpg)

Until I zoom out
![weird 3](https://f.cloud.github.com/assets/1972961/589733/17462316-c9ca-11e2-8dc9-dd017a37050b.jpg)

As I said, something weird...I used `s=0.01` for ages without this happening...

**Comment by jsdevel** [comment]
I just got bit by this as well using `difference`:

![2015-09-30-214225_789x651_scrot](https://cloud.githubusercontent.com/assets/2605980/10213031/77360d6c-67bc-11e5-96d1-74171ee80120.png)

**Comment by jsdevel** [comment]
Interestingly, this only happens in preview for me, not render.

**Comment by TakeItAndRun** [comment]
Please share your code and we can have a look.

Most likely, the holes are as long as the plate is thick. Make the holes
(the cylinders that you difference() ) a little longer.

This effect is called z-fighting ( I think).
OpenSCAD does not calculate any 3d geometry in pre-view.
It is all done with drawing 2views over a stencil-buffer.





2015-10-01 6:48 GMT+02:00 Joseph Spencer <notifications@github.com>:

**Comment by jsdevel** [comment]
Thanks for the info (`z-fighting`)!  The holes and the plate were the same depth.

**Comment by naggie** [comment]
I also get this, which is particularly bad in my case:
![image](https://cloud.githubusercontent.com/assets/208440/11994179/3e6cf08c-aa32-11e5-9356-1a6fda3d4715.png)
versus
![image](https://cloud.githubusercontent.com/assets/208440/11994182/45a478e8-aa32-11e5-9cb5-756246bc31e5.png)


It's good to know what's causing it though. I assume this won't be fixed as it's a limitation of the preview method -- unless it's wrong to have coincident surfaces?

Is it a good convention to extend the difference-volumes a bit each time? 

Interesting to know it's z-fighting.

**Comment by kintel** [comment]
It is good convention to make sure negative volumes are slightly extended.

**Comment by nh2** [comment]
> It is good convention to make sure negative volumes are slightly extended.

To me this seems like a hack/workaround to me.

The real issue seems to be that openscad leaks an implementation detail (OpenGL Z-buffering being used) into the CAD tool.

The solution should be not to draw the coincident surfaces (e.g. OpenGL triangles or quads) of a `difference` at all.

**Comment by MichaelPFrey** [comment]
> The real issue seems to be that openscad leaks an implementation detail (OpenGL Z-buffering being used) into the CAD tool.

It is not just OpenGL/OpenCSG (Preview), it also has to do with OpenCGAL (Render). Ignoring that, you get down to floating point arithmetic issues. Ignoring that, at some point you export STL file and read it in some other software that has to deal with the uncertainty/numeric representation of the points.

We are not the only CAD packages that "leaks" such details - read into ProE/Creos relatives accuracy, which makes sense for heavy machinery that is defined via tolerances, but is a pain when design plastic housing where you would like to emboss text in to the plastic.
 
> The solution should be not to draw the coincident surfaces (e.g. OpenGL triangles or quads) of a `difference` at all.

We can not simply ignore coincident surfaces, we would have to actively search those and correct them.
That is a hard problem, as we would have to guess/keep design intention while dealing with a triangle soup. (doing it earlier makes it "easier", but does not cover more complex cases, making the language more complex as for easy cases coincident surfaces get resolved, but for the really complicated cases they won't)

**Comment by nh2** [comment]
Thanks for your detailed response!

> Ignoring that, you get down to floating point arithmetic issues

> We can not simply ignore coincident surfaces, we would have to actively search those and correct them.

Would a "rational numbers" approach solve this, working with infinite-precision integers for nominator and denominator?

For example, as you say, in a floating point world, for two sidelength-_n_-cubes offset on an axis by _n_, their side surfaces may or may not touch dependin on how the floating point arithmetic works out, but in a rational world, they do exactly.

**Comment by nophead** [comment]
That is what CGAL uses but it is very very slow and uses and enormous amount of memory. And it fails whenever you have a rotation that isn't a multiple 90 degrees because sin and cos become irrational.

**Comment by thehans** [comment]
Another scripting tip that avoids this sort of issue is to do as many boolean operations in 2D as possible.  @naggie's example (and maybe @jsdevel's ?) look like there are straight through holes with straight walls, which is a perfect case for subtracting the those parts in 2D before linear extruding.

**Comment by nh2** [comment]
> Another scripting tip that avoids this sort of issue is to do as many boolean operations in 2D as possible ... extruding

Right, that is a solution, but sometimes the ergonomics may go against that. For example, if you want to model a trash bin, it may be sometimes be easier to `difference() { largerCylinder(); smallerCylinder(); }` than to `rotateExtude` an L-shaped object, or to `linearExtrude` a ring and put a circle as the bin bottom.

But I think the key thing you're saying is: _don't use difference_, only union, then the problem cannot happen.

**Comment by nophead** [comment]
No union is only reliable if they overlap. If you stack two cubes you might get a gap due to floating point inaccuracy unless the numbers are nice ones.
