### ISSUE TITLE
qt5 curl target is broken

### ISSUE THREAD

**Issue by Corallus-Caninus** [openscad/openscad#3803]
in scripts/uni-build-dependencies:

in build_qt5:
curl -O -L http://download.qt-project.org/official_releases/qt/$v/$version/single/qt-everywhere-opensource-src-$version.tar.gz

returns http 404

**Comment by Scopeuk** [comment]
It looks like we are trying to pull down QT 5.3.1 but the qt downloads system only has versions back to 5.12 available now.
see https://download.qt.io/official_releases/qt/

**Comment by Corallus-Caninus** [comment]
I am working on parallel CGAL but have found various other discrepancies thank you I hope to contribute.

**Comment by ChrisCoxArt** [comment]
Pretty sure this has been fixed already.
