### ISSUE TITLE
clean up the echo

### ISSUE THREAD

**Issue by ivoknutsel** [openscad/openscad#382]
In scripting environments, we may want to redirect and parse the echo-ed strings. It would be useful if the output of the echo function was less noisy and the formatting better controllable. 

Requiring explicit carriage return, newline would make the scripting a little harder to use for beginners so maybe a second echo function ("writeline", "output", something like that..) would be a better option.
##

**Comment by t-paul** [comment]
There might be an actual output window at some point, but there are no plans on changing echo() and/or add formatting to console output.
