### ISSUE TITLE
Wrong version of MCAD

### ISSUE THREAD

**Issue by skeptonomicon** [openscad/openscad#3821]
I am confused by this, but the windows installer for 64 bit on the openscad site installs version 2021.1, If I look at the github repo, the versions from this era have a recent MCAD version, but the installer installs a very old and buggy version of MCAD. I think this is a problem with the installer. In particular the installed version of involute_gears is several years out of date.

**Comment by t-paul** [comment]
Yes, MCAD was not updated by mistake. It's on the checklist for next release so hopefully this does not happen again. You can still install the latest MCAD code, or even the DEV version in addition.
