### ISSUE TITLE
GLSL 1.10 is not supported

### ISSUE THREAD

**Issue by izumariu** [openscad/openscad#3823]
Installed OpenSCAD via apt on Ubuntu 20.04, everything worked fine. Recently updated to 21.04 via 20.10, and the 3D window won't show anything, not even the grid, and pressing F5/F6 for preview and rendering won't change anything of that either. Running `openscad --debug all` gives me:

    GLEW Error: Unknown error
    GLView: OpenGL Shader Program Compile Error:
    0:2(10): error: GLSL 1.10 is not supported. Supported versions are: 1.00 ES, 3.00 ES, and 3.10 ES

**Comment by t-paul** [comment]
Sounds like `libqt5gui5-gles` got installed. OpenSCAD does not support this. It should work with the none `*-gles` packages installed.
