### ISSUE TITLE
Some keyboard shortcuts are freezing/crashing OpenSCAD nightly build for macOS

### ISSUE THREAD

**Issue by PLSomebody** [openscad/openscad#3835]
Checked on version 2021.07.07 (git cff035686) installed on macOS
Pressing cmd+q freezes OpenSCAD instead of quitting it.
When cmd+v (paste) is used in SFL save dialog, app ceashes.
Both shortcuts work OK on regular version of OpenSCAD.

**Comment by MichaelAtOz** [comment]
Issues #3784 & #3343 seem to cover this. Reopen if you disagree.
