### ISSUE TITLE
Exporting smooth PNG images from STL files

### ISSUE THREAD

**Issue by deji-nova** [openscad/openscad#3843]
When I render images using `openscad file.scad -o out.png`, the round surfaces are far from smooth. 
`file.scad` has the code ```import('file.stl')```

Example image:
<img src="https://user-images.githubusercontent.com/77294638/126639015-bb89e6a2-5587-4879-90fe-1320ac628074.png" width="300" height="300"/>

Is there a way to increase the smoothness of images rendered from stl files?

**Comment by Scopeuk** [comment]
Unfortunately not within open scad. the STL defines the exact geometry as a series of triangles (which you can see around the outside surface). openscad renders these without further processing.

**Comment by deji-nova** [comment]
Then would increasing the number of triangles by remeshing before exporting help?

**Comment by jordanbrown0** [comment]
Whatever tool you used to generate the STL needs to be set to use more triangles.

**Comment by deji-nova** [comment]
Thanks! Increasing the number of triangles improved the smoothness.
