### ISSUE TITLE
not responding in windows

### ISSUE THREAD

**Issue by G-Iarrusso** [openscad/openscad#3868]
Opening openscad allows me to go to the menu however opening any file will hangup and display a not responding in the top bar
Cant seem to correct this tried running as administrator.

Thanks!

**Comment by t-paul** [comment]
Which OpenSCAD version? Can you run `openscad.exe --info` from commandline / terminal, if yes, please post the output. Is the part of the window where the 3d view should show just black?

**Comment by t-paul** [comment]
Closing, no feedback.
