### ISSUE TITLE
linear_extrude with difference results in unwanted transparency

### ISSUE THREAD

**Issue by erichstuder** [openscad/openscad#3903]
Hello

I've looked up the other issues but haven't found any about this problem so far.

The following code shows a simplification of my problem.
If I do a linear_extrude first and then a difference then the extruded part becomes partly transparent in the preview (F5).
The rendering (F6) however looks fine.

I'm aware that there are most of the times workarounds, as for example in my code.
But in my case I have a library that generates a peace with linear extrude.
Later I want to cut a whole in I it with difference.
So I don't really have a workaround if I don't want to modify the library.

Is this a bug?

I'm using OpenSCAD version 2021.01 on Debian 11.

The example:
```
height = 20;

//the bad one
color("red")
	difference(){
		linear_extrude(height){
			square([70, 2]);
			rotate([0, 0, 5])
				square([70, 2]);
		}
		#cylinder(d=5, h=height+2);
	}


//the good one
color("green")
	translate([0, 10, 0])
		difference(){
			union(){
				cube([70, 2, height]);
				rotate([0, 0, 5])
					cube([70, 2, height]);
			}
			#cylinder(d=5, h=height+2);
		}
```
![preview](https://user-images.githubusercontent.com/28953680/134803173-5583eeec-3baa-47d7-be9a-330fc7985131.png)

**Comment by nophead** [comment]
You need to set the convexity parameter in linear_extrude.

**Comment by erichstuder** [comment]
This solved the problem. Thank you!

But...
1. Because the problem only showed up after I applied 'difference()', I would never have thought of this solution.
2. According to the manual I expected that I had to set a convexity of 4 for my example, but 2 seems to work fine.

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_the_2D_Subsystem
![Screenshot from 2021-09-26 14-46-19](https://user-images.githubusercontent.com/28953680/134808718-7502ba93-3118-4dff-bdbb-49024346fac5.png)

Maybe this is something for future improvement...

Many Thanks.

**Comment by nophead** [comment]
The manual example is wrong. The ray crosses two front faces so it has a convexity of 2, not 4. You can either count front or back face crossing but not both. Otherwise the minimum convexity for a closed shape would be 2 making the default convexity of 1 not make sense.

Yes if there isn't a CSG operation after the linear_extrude then convexity doesn't matter. It just produces a mesh that is drawn. If you have a difference or intersection then OpenCSG does some tricks to show the result without actually computing the new shape. To do that it has to know the convexity.

**Comment by jordanbrown0** [comment]
We should really change the default convexity to 10 or so.  I don't think anybody has shown any significant problem with 10, and it would eliminate most of these troubles.

**Comment by nophead** [comment]
I wonder why it isn't needed when you make a concave object in 3D. For example if you subtract a sphere from a cube you don't need to specify the convexity if you do another 3D operation on it but if you import an STL of the same you do. Does the 3D system keep track of convexity, in which case can the 2D substem do the same?

**Comment by kintel** [comment]
Closing as not really an issue
