### ISSUE TITLE
Icon for macOS Big Sur

### ISSUE THREAD

**Issue by MohanMaker** [openscad/openscad#3907]
macOS Big Sur introduced a new icon style (square icons instead of round icons). It would be great if OpenSCAD had a new icon to agree with this design scheme. I know some individual users have already created their own versions of a square icon here: https://macosicons.com

**Comment by TheJKM** [comment]
The only file that has to be updated is `icons/OpenSCAD.icns`, this container format is only used on macOS. This will change the icon for all versions of macOS, as Apple writes:

> IMPORTANT
> When you update your app for macOS 11, use your new app icon design to replace the icon you designed for earlier versions. You can’t include two different app icons for one app, and the macOS 11 app icon style looks fine on a Mac running Catalina or earlier.
(https://developer.apple.com/design/human-interface-guidelines/macos/icons-and-images/app-icon/)

I'm not a fan of the linked icon, I'd prefer the current icon on a white square to differ the icon from the background. In the linked version, they become blurred. An Example:

<img width="469" alt="image" src="https://user-images.githubusercontent.com/21987613/136023391-9c227fe0-dae4-4026-9710-0803dd46ebb7.png">

**Comment by TheJKM** [comment]
Now that the icon is merged, I think we can close this.

**Comment by t-paul** [comment]
Closed via #3970.
