### ISSUE TITLE
Substraction missing when using negative scale factors

### ISSUE THREAD

**Issue by o-jasper** [openscad/openscad#393]
I have had 'disappearances' in CGAL openscad before, but i have stumbled upon one that i could easily boil down.

    intersection()
    {//   cube([20,20,20],center=true);
        difference()
        {   sphere(15);
            for( s=[1,-1] ) scale(s) //It seems to be the `scale`, not the `for`.
                translate([0,0,8]) cylinder(r1=8,r2=10,h=4, $fn=8);
        }
    }

This was with one of the git versions (in master), and the latest; d6ff5e9468e48de44a68b46ecdd65b79f398e5e0

(too much text on an issue besides the point, ignore me if you wish)I donth think [this](http://www.reprap.org/wiki/Separate_page_on_the_question) is the case here, but i am also not convinced by the idea there isnt a solution. For instance you could build it by cubes with an octree, determing if stuff inside/outside/partial for each.([did so much](https://github.com/o-jasper/physical_map), but basically that's died due to bit rot; would need to be coaxed quite a bit into living again) Then you could remove all cubes that are too close to the rounding error and have partial/outside on both sides. Tbh i am not very sure about what your approach is, but do realize that an approach may be limited and if you're into code re-use, you're a bit invested(or stuck) in it. Sorry to have a possibly harsh thing to say, openscad is a very good program over-all, and it being used makes it worth being invested in it. Besides, for instance ImplicitCAD isnt quite an alternative at this point, the `.stl`s it produces are too big and for some reason dont play well with slic3r currently.

**Comment by kintel** [comment]
This was fixed a while ago during a larger refactoring

**Comment by laird** [comment]
I'm seeing mirrored objects having inverted normals. #1174 . It sounds related. If there's a version that fixed that, I'd love to use it. It's broken as of yesterday's build.
