### ISSUE TITLE
extend special variables to map 3d-printer feature size

### ISSUE THREAD

**Issue by torwag** [openscad/openscad#394]
Currently, we have 
$fa, $fs and $fn  as special variables control the number of facets used to generate an arc.
It would be good to extend those to set different values for all three dimensions (X,Y,Z) since different 3D printer technologies vary with the minimum feature size among the dimensions.
Furthermore, I would like to suggest a new variable to reflect the minimum feature size of a certain processing method. Basically it comes down to round given values to discreet values. 
E.g. giving a cube with a length of 10.15 mm whereas the minimum feature size of the 3D printer is 0.5 mm would result in 10.00 mm. For 10.45 mm it would be 10.5 mm, etc. 
I believe that this could help people to understand how much clearance they might need to take into account and how to improve there models for a certain printing process.
It has to be taken into account that the feature size in X,Y and Z direction can differ and thus, people can see within the design process that e.g., printing in Z directions enables for a higher accuracy compared to X and Y. 

I know that this is partly covered by the printing software, however, noticing problems at that point might be to late and the entire design needs a rework.

One would need to check how the current printer software deals with this inaccuracy. Do they round mathematically correct, just truncate or round up to the next possible value?

In total the output will look much more like the final object, giving people a much better understanding and the possibility to adjust the design to the printers needs.
##

**Comment by t-paul** [comment]
Discussed multiple times without much consensus. It seems to be mostly out of scope as OpenSCAD does not do CAM. Should that ever change, we can always reopen this topic.
