### ISSUE TITLE
BOSL2 cyl with rounding fails in nightly build

### ISSUE THREAD

**Issue by bob-ewart** [openscad/openscad#3945]
OpenSCAD 2021.10.17 nightly 
Kubuntu 20.04.3

include <BOSL2/std.scad>
include <BOSL2/shapes.scad>
cyl(d1=15, d2=10, h=15, rounding=2 );

This works on 2019.05 and fails on the nightly builds up to 2021.10.17 with:
WARNING: undefined operation (undefined * number) in file ../.local/share/OpenSCAD/libraries/BOSL2/shapes.scad, line 651
TRACE: called by 'if' in file ../.local/share/OpenSCAD/libraries/BOSL2/shapes.scad, line 645
TRACE: called by 'children' in file ../.local/share/OpenSCAD/libraries/BOSL2/transforms.scad, line 509
TRACE: called by 'if' in file ../.local/share/OpenSCAD/libraries/BOSL2/transforms.scad, line 508
TRACE: called by 'zrot' in file ../.local/share/OpenSCAD/libraries/BOSL2/shapes.scad, line 644
TRACE: called by 'children' in file ../.local/share/OpenSCAD/libraries/BOSL2/attachments.scad, line 929
TRACE: called by 'if' in file ../.local/share/OpenSCAD/libraries/BOSL2/attachments.scad, line 928
TRACE: called by 'if' in file ../.local/share/OpenSCAD/libraries/BOSL2/attachments.scad, line 927
TRACE: called by 'multmatrix' in file ../.local/share/OpenSCAD/libraries/BOSL2/attachments.scad, line 919
TRACE: called by 'attachable' in file ../.local/share/OpenSCAD/libraries/BOSL2/shapes.scad, line 643
TRACE: called by 'cyl' in file straight4.scad, line 3
Execution aborted

**Comment by t-paul** [comment]
`include <BOSL2/shapes.scad>` does not exist anymore, looks like that was recently changed to `include <BOSL2/shapes3d.scad>` and that works fine with the snapshot as far as I can tell.
