### ISSUE TITLE
Remove Travis CI badge as it's no longer in use?

### ISSUE THREAD

**Issue by mbrukman** [openscad/openscad#3953]
The [`README.md`](https://github.com/openscad/openscad/blame/d201a8ae134b4f7567457bbeff97237d0eec4e27/README.md#L2) includes a badge linking to Travis CI at the top:

https://github.com/openscad/openscad/blob/d201a8ae134b4f7567457bbeff97237d0eec4e27/README.md#L2

>  [![Travis (master)](https://img.shields.io/travis/openscad/openscad/master.svg?logo=travis&logoColor=black&colorA=f9d72c&style=plastic)](https://travis-ci.org/openscad/openscad/)

This badge links to https://travis-ci.org/openscad/openscad/ which says:

> This repository was migrated and is now building on travis-ci.com
>
> [Take me there!](https://travis-ci.com/openscad/openscad)

However, the link it points to (https://travis-ci.com/openscad/openscad) says:

> 404
>
> Oops, seems like you’ve came across the wrong job site builder, try again!

This seems to suggest that this project is no longer using Travis CI in any form, and the badge should be removed.

**Comment by mbrukman** [comment]
@t-paul — https://app.travis-ci.com/github/openscad/openscad/branches shows me (at the top, in red):

> We are unable to start your build at this time. You exceeded the number of users allowed for your plan. Please review your plan details and follow the steps to resolution.

The latest [branch build](https://app.travis-ci.com/github/openscad/openscad/branches) appears to be [from a year ago](https://app.travis-ci.com/github/openscad/openscad/builds/237042752), and looking at [build history](https://app.travis-ci.com/github/openscad/openscad/builds), the latest build there is from 8 months ago.

I see the `README.md` has a combination of GitHub Actions and Circle CI badges (and had for a while?), so I presume you've already migrated from Travis CI to the alternatives.

Would it makes sense to remove `.travis.yml` and the Travis CI badge to complete the cleanup?

**Comment by t-paul** [comment]
Yes, I think it's now pretty clear there's no going back. I did go through with a support ticket, but that went nowhere. They enforce credit cards for accessing the open source plan and that's not going to happen. Also it's still unclear if it would still mean begging for new credits every now an then.
So I'm not sure if there's some other options, but I don't intent to spend more time on it.
