### ISSUE TITLE
default center=true

### ISSUE THREAD

**Issue by emard** [openscad/openscad#3978]
When I design in openscad, I more often place objects
relative to their centers, rather than edges, it's because
of my way of thinking about space and coordinates.

So I made small  include file which can hopfully replace
often typed "center=true". Currently it is so small that
no bug can fit inside (I guess :)

https://github.com/emard/openscad-center

**Comment by t-paul** [comment]
Announcements are better placed on the [mailing list](https://openscad.org/community.html), [Thingiverse group](https://www.thingiverse.com/groups/openscad), [reddit](https://www.reddit.com/r/openscad/)...
