### ISSUE TITLE
Add preference option to swap left and right mouse buttons.

### ISSUE THREAD

**Issue by mwbogucki** [openscad/openscad#3981]
Many other applications that I use, usually user the left-mouse-button for translation and the right-mouse-button for rotation. 
Can a swap option (checkbox) be added to the Preferences?
Thank you.

**Comment by t-paul** [comment]
I'd prefer to see a more general way to setup assignments, similar to what we have for 3d-mouse input devices. But I guess if someone want's to have a stab at this it could be a useful short-term solution.
