### ISSUE TITLE
Rendering only 1 cpu core

### ISSUE THREAD

**Issue by djfix13** [openscad/openscad#3985]
with the latest realese the long rendering time intrigued me; I saw in the taskmanager that only one core is used... why??
![render-cpu](https://user-images.githubusercontent.com/94961589/143213551-2eccf4e3-cc5e-45d0-afbc-f4acfbe2b896.jpg)

**Comment by t-paul** [comment]
See #391.

**Comment by djfix13** [comment]
sorry for question but I read the project goes on 2013, 8 year late...notingh happen?

**Comment by jordanbrown0** [comment]
Many things have happened since 2013.  Just not that, because it's really hard.  Feel free to take a stab at it.

**Comment by jasonrhardman** [comment]
How far have people come? Has it even been pursued beyond a cursory assessment that it's too hard? I want to take a stab at it, but need to know where the giant's shoulders are so I can stand on them.

**Comment by JayRugMan** [comment]
How far have people come? Has it even been pursued beyond a cursory assessment that it's too hard? I want to take a stab at it, but need to know where the giant's shoulders are so I can stand on them.

**Comment by t-paul** [comment]
Active work in #4293.
