### ISSUE TITLE
[Solved] Torus doesnt Render with F6

### ISSUE THREAD

**Issue by Sploopiii** [openscad/openscad#4001]
rotate([90,0,0]) translate([160,240,-220]) cylinder(h = 100, r = 80, $fn = 50);
	rotate([90,0,0]) translate([160,240,-120]) cylinder(h = 40, r1 = 80, r2 = 50, $fn = 50);
	union() {
	rotate([90,0,0]) translate([160,240,-220]) rotate_extrude(convexity = 20, $fn = 100) translate([40, 0, 0]) circle(r = 40, $fn = 100) ; 
	}
	rotate([90,0,0]) translate([160,240,-260]) cylinder(h = 80, r= 40,$fn = 50);
	
	F5:
![grafik](https://user-images.githubusercontent.com/61621914/145368248-fae4bfc9-4016-43e7-acfd-5535ffcf4980.png)

        F6:
        
![grafik](https://user-images.githubusercontent.com/61621914/145368295-1778478d-2814-4000-a9a9-3d1c018b424f.png)

**Comment by t-paul** [comment]
The torus is created with a circle touching the middle at exactly a single point. This produces invalid geometry.

As simple way around that is to fill the shape in 2D already, instead of using the cylinder to fill the space:
```
rotate([90,0,0]) translate([160,240,-220]) rotate_extrude(convexity = 20, $fn = 50) {
    translate([40, 0]) circle(r = 40, $fn = 50);
    translate([0, -40]) square([40, 80]);
}
```

**Comment by Sploopiii** [comment]
Yup, this works, thank you!
