### ISSUE TITLE
64 bit nsis is flaky

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#401]
$ ./scripts/release-common.sh mingw64
Detected build-machine ARCH: 64
Mingw-cross build using ARCH=64
Detected OS: UNIX_CROSS_WIN
Checking pre-requisites...
makensis not found. please install nsis

------------

Essentially the issue is that you need a working copy of 'makensis' on the build machine. 

How do you get that? 

1. In the 32-bit mingw32 build, a 'cross-nsis' is created (i686-pc-mingw-nsis or something like that), and, surprisingly, it is usable as a 'makensis' binary on the build machine. 

2. In the 64bit mingw build, no cross-nsis is created because nsis is not really 64 bit compatible.

3. If the build machine, itself, has 'makensis' installed as a native binary, it can be used. On linux systems, this is usually in a package like 'nsis' that can be installed on the package manager. If you are not root, though, this may be a problem. 

Solutions:

option 1. create a build_nsis bash function, like what is in the dependency script builds. download and build makensis, similar to how we can download and build cmake, bison, etc. 

option 2. build the 32 bit mingw cross-build first, including cross-makensis. use this 32 bit makensis to create the 64-bit package. this will be tricky but seems possible in theory

**Comment by kintel** [comment]
This wasn't a bug, just a weakness in nsis
