### ISSUE TITLE
How to build by Qt5.15,mingw  in win10,thanks

### ISSUE THREAD

**Issue by zhichangxuexi** [openscad/openscad#4014]

**Comment by t-paul** [comment]
The process outlined in https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Microsoft_Windows should still apply. If you find problems, please report those here so we can update the documentation.

**Comment by t-paul** [comment]
Closing, no feedback. (I you come back to this topic, feel free to reopen or post a new issue)
