### ISSUE TITLE
On 2021.01 the X axis is unexpectedly offset by 0.1

### ISSUE THREAD

**Issue by Kreyren** [openscad/openscad#4017]
DISCLAIMER: Unless my math is wrong..

.. The X Axis is unexpectedly offset by +0.1 which significantly complicates a design with 1mm tolerance:

![2021-12-19_01-02](https://user-images.githubusercontent.com/11302521/146659350-1c073aaa-6c55-4828-abb4-552aff2120a5.png)

### Code:

```openscad
ancor_width = 1;
ancor_height = 10.42;
ancor_lenght = 4.2;

module ancor(x, y, z) {

    difference() {
        cube([x, y, z], center = true);
        
        // Remove top left corner
        translate([-z/10,0,x]) {#
             cube([x/2,y,x/2], center = true);
        }
        
        // Remove bottom left corner
        translate([-z/10,0,-x]) {#
             cube([x/2,y,x/2], center = true);
        }
    }
}

// Create the ancor
ancor(ancor_lenght, ancor_width, ancor_height);
```

**Comment by Kreyren** [comment]
Closing as pebcak

**Comment by jordanbrown0** [comment]
The rendering artifacts that cause the requirement to have the subtrahend of a difference operation extend outside the original object is called "Z-fighting", and is documented in a note on difference() at

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/CSG_Modelling#difference

See also the Wikipedia article at https://en.wikipedia.org/wiki/Z-fighting .

The basic problem is that when presented with a zero-thickness object, the renderer can't quite decide whether it's there or not.

And yes, it's a pain in the neck.
