### ISSUE TITLE
Change the tab indentation character from `⟶` on `|` or `»`

### ISSUE THREAD

**Issue by Kreyren** [openscad/openscad#4019]
I was told that in the tabs vs spaces war the `⟶` character is used by spaces-people who want to deter other users from using tabs as it's probably the most distracting character that can be used for the tab whitespace:

![2021-12-19_03-29](https://user-images.githubusercontent.com/11302521/146661481-fd8e34dc-8b80-4fb7-a0af-99a32a9182d5.png)

Proposing to use the more workable:
a) pipe `|`  symbol which is a favorite choice for emacs users where the whitespace can't be easily aligned in the center of the whitespace
a) Right-Pointing Double Angle Quotation Mark `»` which is favorite choise for VSCodium assuming it being aligned in the center of the indentation else it's too distracting.

.. preferably with rainbow indentation to orient in the levels of indentation.

**Comment by Kreyren** [comment]
Note: The pipe character is also more portable:

![2021-12-19_03-39](https://user-images.githubusercontent.com/11302521/146661675-64914afe-b102-4af0-8ba4-4221de4b7e57.png)

**Comment by ChrisCoxArt** [comment]
Just because your browser or IRC client can't handle extended characters and unicode....

**Comment by Kreyren** [comment]
> Just because your browser or IRC client can't handle extended characters and unicode.... -- @ChrisCoxArt (https://github.com/openscad/openscad/issues/4019#issuecomment-997319349)

It can handle it as you can see below :p but my browser randomizes fingerprint so some values are changed on random to change the behavior.

**Comment by t-paul** [comment]
As already discussed, that's a feature of QScintilla which is the editor component used by OpenSCAD.
If you would like that feature, the request needs to be made for that project, there's nothing OpenSCAD can do.

Quoting the [documentation](https://docs.huihoo.com/pyqt/QScintilla2/classQsciScintilla.html#ab83469cc9550eadcd5d4e8ca3d20d07b)
> This enum defines the different whitespace visibility modes. When whitespace is visible spaces are displayed as small centred dots and *tabs are displayed as light arrows pointing to the right*.
