### ISSUE TITLE
Large model fails in OpenCSG (F5) mode

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#403]
The following model causes a crash in csgterm.cc:191:
  assert(term->left && term->right);

..for the following model:
https://github.com/josefprusa/Prusa3/blob/master/box_frame/doc/complete-printer.scad

..when "Turn of Rendering" is set to 10K elements.

**Comment by t-paul** [comment]
Seems to be fixed. Checked with 2015.01.12.nightly (git e84f797).

**Comment by kintel** [comment]
Confirmed to be fixed
