### ISSUE TITLE
Option to clear console on each Preview/Render

### ISSUE THREAD

**Issue by woferry** [openscad/openscad#4030]
I can't personally think of any reason why I'd want to still see old console contents when starting a new Preview/Render, and for debugging it makes it really inconvenient to have to manually clear the well every time to keep from being shown previous warnings/errors and having to scroll down to find the ones I haven't fixed yet.  It would be nice if there was at least an option (if not the default) to auto-clear the console in the app preferences (as seemed to be the default in 2015.03).

Above behavior confirmed in 2021.01 release and 2021.12.27 nightly for macOS, on macOS 12.0.1.

**Comment by t-paul** [comment]
I've removed the "I have another gripe" part (still accessible via the history selector). This is not a place to throw in different whishes as that makes handling issues complicated. I'm not sure the link behavior will change, but if really needed, this has to go into a separate issue.
