### ISSUE TITLE
Highlighting  with  some characters 

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#4047]
v22.01.10
when a comment or string contain certain character the highlight is moved 

![image](https://user-images.githubusercontent.com/93376232/149586216-9b2c091e-a1bc-40eb-9ac6-9e918e5e5da0.png)

```
a="äööaa";
// comment ö
// comment
```

**Comment by jordanbrown0** [comment]
Something is counting bytes instead of characters.  ä and ö are two bytes each.

Similar to #3939.

**Comment by ChrisCoxArt** [comment]
yep, working on this now. Seems that a conversion to QString was unnecessary and counted glyphs instead of bytes, but qscintilla wants bytes.

**Comment by ChrisCoxArt** [comment]
testing the fix now.

**Comment by ChrisCoxArt** [comment]
The fix seems solid across many languages. I tried UDHR translations for samples, plus emoji, plus random glyphs.
pull request submitted, but it'll take time to pass all the checks.

**Comment by t-paul** [comment]
Fixed by #4048.
