### ISSUE TITLE
linear_extrude can't handle negative height

### ISSUE THREAD

**Issue by ivoknutsel** [openscad/openscad#405]
If i use negative heights for linear_extrude it produces large-ish positive extrusions. Easy to work around with a translate but caused some head scratching.

**Comment by spuder** [comment]
I'm unable to extrude into the negative z axis with `linear_extrude` on version `2021.01` Is there a work around?

**Comment by jordanbrown0** [comment]
Use translate() to move it down.

For instance, for an extrusion of height h that you want to be below the Z=0 plane:

```
translate([0,0,-h]) linear_extrude(height=h) ... whatever ...;
```

**Comment by jordanbrown0** [comment]
You could even wrap that into a module:
```
module lx(h) {
    assert(h != 0);
    if (h > 0) linear_extrude(height=h) children();
    else translate([0,0,-h]) linear_extrude(height=h) children();
}
```

**Comment by jordanbrown0** [comment]
[ For those reading e-mail notifications:  I made an error on the signs in the "negative" case in that previous example and have edited the comment. ]

**Comment by MichaelAtOz** [comment]
Testing...1...2...3...

 

module lx(h) {

    assert(h != 0);

    if (h > 0) linear_extrude(height=h) children();

    else translate([0,0,h]) linear_extrude(height=-h) children();

}

 

  _____

**Comment by t-paul** [comment]
```
module lx(h) {
    mirror([0, 0, h < 0 ? 1 : 0]) linear_extrude(abs(h)) children();
}
```

**Comment by dossalab** [comment]
why not make it a feature? seems cleaner than writing additional mirroring code
