### ISSUE TITLE
Viewport controls

### ISSUE THREAD

**Issue by psteiner** [openscad/openscad#4053]
Provide UI controls to set or constrain viewport parameters, for example to rotate the z-axis to a specific angle, without altering the angles of other axes. This is difficult to achieve when click-dragging in the viewport with a mouse.

Constraints could be implemented by modifier keys, e.g. holding control, alt, shift, etc. while dragging to constrain movement to a single axis, or by providing fields to input values, e.g. clicking on a viewport value transforms it into an field for keyboard input.

**Comment by UBaer21** [comment]
So besides [$vpr](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Other_Language_Features#$vpr,_$vpt,_$vpf_and_$vpd)
and customizer use?
- maybe if we move away from the fixed buttons to an interactive gizmo for viewport control - (like the view cube used by autodesk)

**Comment by psteiner** [comment]
Yes, $vpr does what I want! I didn't know about that one, thanks!
