### ISSUE TITLE
Feature Request: Elementary OS Support

### ISSUE THREAD

**Issue by Mentors4EDU** [openscad/openscad#4094]
Can you make a version of this software for people who use Elementary OS?

**Comment by t-paul** [comment]
From what I see on the Wikipedia page, Elementary OS is based on Ubuntu. Can't is use the normal Ubuntu packages?

**Comment by Mentors4EDU** [comment]
Actually, I just realized it is a redesign based off LUbuntu or lightweight Ubuntu and that should work for your PPAs. Thank you!
