### ISSUE TITLE
Dark mode plz.

### ISSUE THREAD

**Issue by jmerc77** [openscad/openscad#4130]
option for dark UI. maybe use the OS color scheme???

**Comment by t-paul** [comment]
It should use the OS theme automatically. If there's a specific issue, you'll have to give more details.

**Comment by Nikorasu** [comment]
Does anyone know a way to fix this?
I'm on Linux Mint 20, using the system Mint-Y-Dark theme, and most windows obey that fine.. However, the AppImage for OpenSCAD still uses a white theme for the window colors outside the editor/3d preview. (If I install OpenSCAD from the terminal, that obeys the theme, but that installs a version from 2019..)

![Screenshot from 2023-06-27 12-32-52](https://github.com/openscad/openscad/assets/1338231/15f0c465-ff5a-4731-a928-28e29b7e1c87)

Is there any way I can get a more recent version to work with the system dark theme?

**Comment by t-paul** [comment]
For AppImage see #4105.
