### ISSUE TITLE
brackets in comments are parsed for collapsible block

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#4144]
version 2022.02.18

- Issue

following code will collapse the union only till the comment

```
union(){
// parsed }
// inside [ will collapse the curly brace from the union
}
```

- Feature Request
collapse All/expand All  (show All / hide All) for bracket sections

**Comment by ChrisCoxArt** [comment]
It would be much better to have this broken into separate parts: 1 bug report, 1 feature request.

**Comment by MichaelPFrey** [comment]
the issue is in ScadLexer.cc - I am on it

**Comment by MichaelPFrey** [comment]
There are more related issues:
```
str1 = "Hallo { ";

cube();

str2 = "} Welt";
```
