### ISSUE TITLE
Customizer no longer handle vectors and crush them in json file

### ISSUE THREAD

**Issue by PRouzeau** [openscad/openscad#4147]
On recent snapshots customizer no longer handle vectors. Also, if you record file and data, the data set in vectors are all removed from the json file even for dataset which haven't been modified. 
2 views from my published app BentSim, the first on version 2021.01, the second from the nigthly 2022.02.13
![OpenScad_lost_vector0](https://user-images.githubusercontent.com/11719573/155824513-d1a7a956-1ef8-4cfa-876f-8118fcda77ee.jpg)

![OpenScad_lost_vector1](https://user-images.githubusercontent.com/11719573/155824573-4d5ae3f3-ac4b-4b4e-8998-a7f17e2d521d.jpg)

**Comment by ChrisCoxArt** [comment]
ok, sounds like maybe the JSON code has a problem reading and writing vectors....

**Comment by t-paul** [comment]
If you are closely integrating with the OpenSCAD application itself, the only option I see to limit those issues in the future is to engage in the development discussions. There's not going to be a guaranty to keep the GUI same or identical. Discussing changes at the time they happen could move things into a direction benefitting everyone. Trying to roll back after the fact is unlikely unless there's severe user facing bugs introduced by the change.

**Comment by t-paul** [comment]
There's never going to be any deprecation for GUI features. Those only apply to the language. Anything else it simply not possible.

Development discussions are on github and in the IRC channel.
