### ISSUE TITLE
Preview won't show an item that touches a hole(), but render works fine.

### ISSUE THREAD

**Issue by threed-factory-store** [openscad/openscad#4149]
All my measurements are integers.  I'm hoping this is an internal floating point imprecision thing.

Maybe OpenScad could truncate all floating point values at a certain number of digits after the decimal?  Other CAD programs don't seem to have the rounding issues that OpenScad has.

**Comment by t-paul** [comment]
Please add relevant details as described in the [FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#How_do_I_report_bugs?).

**Comment by t-paul** [comment]
Closing, no feedback.
