### ISSUE TITLE
Incomplete render with fast-csg-trust-corefinement and fast-csg being set

### ISSUE THREAD

**Issue by printerderby** [openscad/openscad#4150]
Hello

I just read about some cool performance improvements and had to give them a try. My current model is pretty simple, yet running with a painful $fn value.
- OpenSCAD-2021.04.13: 160sec
- OpenSCAD-2022.02.26: 80sec
- OpenSCAD-2022.02.26, "fast-csg": 40s

Amazing!

I followed your call to test "fast-csg-trust-corefinement", for even more performance. This option alone seems to have no effect. I guess it does nothing on it's own and has to be used with "fast-csg". Maybe this can be described in the settings or "fast-csg" activated implicitly. 

Combining "fast-csg-trust-corefinement" and "fast-csg", results in a worse performance (160s instead of 80s; see #4114). 
In addition, the model is incomplete. Even exporting it (and putting it on a slicer), does result in lost elements. Lines 152 to 158 from [lazy-susan-3.txt](https://github.com/openscad/openscad/files/8149317/lazy-susan-3.txt) are missing. 

Maybe I am doing something wrong, as I am pretty new to OpenSCAD. 

Some screenshots and the tested code are attached

Regards
Steffen

// no options set - everything normal: 
![openscad](https://user-images.githubusercontent.com/73718651/155897277-7cad7be8-288e-4405-99a7-5669ad3cd4ab.png)

// "fast-csg-trust-corefinement" set - looks and performs exactly like not being set at all 
![openscad-corefinement-only](https://user-images.githubusercontent.com/73718651/155897169-eed43aa0-5c04-45c4-9ddc-62bca89a022d.png)

// fast-csg - faster and the appearance changes
![openscad-fast-only](https://user-images.githubusercontent.com/73718651/155897176-9247418a-f6ae-462c-b5b2-4e2190c467aa.png)

// "fast-csg-trust-corefinement" and "fast-csg" - elements are missing, poor performance 
![openscad-fast-and-corefinement](https://user-images.githubusercontent.com/73718651/155897173-0223ca46-14b8-4f48-8959-93b662f37ad3.png)

**Comment by printerderby** [comment]
Only using "fast_csg", I played around with the customizer:
- Changing ttl_dia to 50mm results in the same loss. Even with fast_csg, only.  
- Setting "view" to "all" and the ttl_dia to values of 47, 50, 98 and 100 will result in different results. Sometimes the output is just complete blank. 

Turning off "fast_csg" and the result looks like the preview again. Maybe someone can retest this. I guess, I am doing something wrong.

**Comment by MichaelAtOz** [comment]
Why doesn't fast-csg show edges with `View/Show-edges`, first image above v's 3rd?

**Comment by MichaelAtOz** [comment]
Fast-csg (just that feature set), for this model, is using 2.8-3.7 times the memory.
This is from System Monitor/properties on Debian, OpenSCAD 2022.02.13.
Fast-csg / Memory / Virtual / Resident
```
Off /  874.4MiB / 1.4 GiB / 981.8 MiB
On / 3.3GiB / 3.9GiB / 3.4 GiB
```

**Comment by ochafik** [comment]
> Why doesn't fast-csg show edges with View/Show-edges, first image above v's 3rd?

@MichaelAtOz I didn't reimplement the viewing code to deal with the new mesh data structure. Looking into options (I might just let it try and create a Nef that can be rendered at the end).

> Fast-csg (just that feature set), for this model, is using 2.8-3.7 times the memory.

I'm very curious of whether upcoming `fast-csg-remesh` (https://github.com/openscad/openscad/pull/4117) will improve things (it should drastically drop the # of faces). Would you be able to compare the # faces in the STL output with and without fast-csg?

**Comment by printerderby** [comment]
Thanks for your feedback. $fn got reduced and any object eliminated, that is not involved in causing the error.  

```
/* [Accuracy] */
// 
$fn=12;

// this mirror-action breaks anything, as long as the subpart uses a difference
mirror([0, 0, 1])
  translate([0, 0, -15])
  {
    difference()
    {
      translate([0, 0, 0])
        cylinder(h=26.25, d=11);
      // This negative part seems important. 
      translate([0, 0, 0])
        cylinder(h=26.25, d=2.8);
    }
  }

// this is the part, getting lost
cylinder(h=13, d=75);
```

Used: OpenSCAD-2022.03.07.ai11323-x86_64.AppImage with fast-csg-trust-corefinement *and* fast-csg enabled. 

The preview and the render will differ. The negative part (the latter part in the "difference()") in combination with the "mirror()" seem to cause the issue.
The large cylinder (last line) will get lost when rendering. Interestingly, it will also remove the intersecting part of the smaller cylinder.

Regards
Steffen

![break1-preview_000](https://user-images.githubusercontent.com/73718651/157297782-a78c61e7-c227-473f-b356-ab511cc3215d.png)
![break1-render_000](https://user-images.githubusercontent.com/73718651/157297832-a6dd1e1a-6552-4156-8066-4e00123bd9d4.png)

**Comment by printerderby** [comment]
Used: OpenSCAD-2022.03.07.ai11323-x86_64.AppImage with fast-csg enabled, only.

The original model showed a similar problem, with fast-csg only. You had to use the view "all". 
Using that error as a base, there is an even simpler example. It also debunks my theory, about the negative object. Maybe it is just the "mirror()"'s amount of children.

```
$fn=12;
cylinder(25, 5, center=true);
mirror([0, 0, 1])
{
  cylinder(h=2, r=8, center=true);
  cylinder(h=6, d=12, center=true);
}
```
Again, the disappearing object also removes any parts of other, intersecting objects. 

![break2-preview_000](https://user-images.githubusercontent.com/73718651/157301498-6e87a1db-d748-470f-95ba-957bab2dfa82.png)
![break2-render](https://user-images.githubusercontent.com/73718651/157301508-007fe3a3-1ac0-4c39-96b3-cdcfdb20092b.png)

**Comment by ochafik** [comment]
@printerderby amazing, super useful, thanks a lot! Fix on its way :-) (forgot to flip the faces of surface meshes after a transform with a negative determinant, oops!)

**Comment by ochafik** [comment]
> Fast-csg (just that feature set), for this model, is using 2.8-3.7 times the memory.

@MichaelAtOz Thanks for reminding me of the memory issue! Good news: found the culprit, the workaround is to trust (when you can, which you will from tomorrow's dev snapshot) and I'll work on a fix straight away.

There are 2 causes of huge memory consumption at play here:
- Lazy numbers going beserk --> normally meant to be fixed by `fast-csg-exact` or `fast-csg-exact-callbacks`, but I never had it cover the case where we fall back to Nef operations when corefinement seems too risky (which `fast-cst-trust-corefinement` avoids, but it was triggering the disappearance). The fallback nefs are using the same lazy kernel so have the same issue with "surprising" numeric performance (and clearly, memory).
- To a much lesser degree: corefinement's known propensity to generate more triangles: fixed by `fast-csg-remesh`.

Some measurements on my local build w/ the mirroring fix (https://github.com/openscad/openscad/pull/4164):
- With only `fast-csg` it mostly falls back to Nefs, almost no numbers are made exact and RAM spikes to 3.6GB.
- With `fast-csg` + `fast-cst-trust-corefinement` it uses 408MB
- With `fast-csg` + `fast-cst-trust-corefinement`+ `fast-csg-remesh` + `fast-csg-exact-callbacks` +  it uses 270MB (each of remesh & exact-callbacks brings down the memory usage a bit)

I'll now try and add exact calls on Nef numbers to keep the non-corefinable cases in check :-)
