### ISSUE TITLE
Customizer Presets don't save

### ISSUE THREAD

**Issue by nickeeey** [openscad/openscad#4154]
Hi, my Presets on the right won't save. 
I press plus and name it, then i click on save (on the right) and save the whole scad but after opening it is missing and i don't find any File in the folder
![Bild_2022-03-03_200331](https://user-images.githubusercontent.com/22114715/156634456-3d1e6aeb-69a9-45a9-a9a2-21e4febfada7.png)

**Comment by t-paul** [comment]
Closing, no feedback.

**Comment by GitYowie** [comment]
I also have this issue. 
Version: 2021.01
OS: Windows 11
Can confirm, no special characters in preset name.
