### ISSUE TITLE
Plans for a new release?

### ISSUE THREAD

**Issue by voxpelli** [openscad/openscad#4156]
As someone not very involved with the project, but following all of the news that's going into master – like native ARM binaries for MacOS and some great speed improvement in places – when do you plan to do a new release containing one or more of these?

I know I can download nightlies, but since I'm not that involved I prefer to stay on stable releases.

I did search the issues and found https://github.com/openscad/openscad/issues/3640 + the two projects (bugfix release + next release), but couldn't really find out what's blocking a new release, if there's some specific features or whether it's lack of time or something else.

How can one help push the work on a next release forward?

**Comment by t-paul** [comment]
I issue is really for collecting a checklist, as it says "no timeline" yet.

Main blocker is #3781 which has my motivation for putting in work for a release at 0. I don't know what could work to get this moving again.
