### ISSUE TITLE
arrays in customizer won't update

### ISSUE THREAD

**Issue by juupStraathof** [openscad/openscad#4177]
when trying to update a array in the customizer when you press save preset it just overwrites what is in the textbox with the standard values that are coded into the array, if array is emtpy it just shows a empty array 
![image](https://user-images.githubusercontent.com/74771575/158411185-b77a206d-2419-40c5-a329-0cdccff45437.png)
![image](https://user-images.githubusercontent.com/74771575/158411264-ee7e59d2-69da-4cb1-a552-01e1be8e776b.png)

i don't use any custom costomizer options or textboxes the other options work just fine

**Comment by t-paul** [comment]
Sorry, but arbitrary / varying length arrays are not supported at this point.
