### ISSUE TITLE
Submit modification from clone repository https://github.com/AGZ-france/openscad

### ISSUE THREAD

**Issue by AGZ-france** [openscad/openscad#4190]
I have updated my repository with a branch named Helicoidal, and I would like to submit it in the master branch of openscad.
But I do not know how to do this.

**Comment by thehans** [comment]
Go to your repository:  https://github.com/AGZ-france/openscad/tree/Helicoidal
And there should be a link at the top to "Contribute" -> "Open Pull Request"
