### ISSUE TITLE
STL and AMF output should have a canonicalization option

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#420]
nop head has to run stl through a 'canonicalization' script that sorts the triangles. 

this should be an option available in openscad itself. 

https://github.com/nophead/Mendel90/blob/master/c14n_stl.py
##

**Comment by t-paul** [comment]
Added AMF too. As it's XML it might be useful for that too.

**Comment by thehans** [comment]
I'm looking into fixing this, but I'm a little confused about the export code.  It looks like STL export converts CGAL_Nef_polyhedron to Polyset before exporting:
https://github.com/openscad/openscad/blob/master/src/export_stl.cc#L153-L156

While AMF export does the opposite, converting Polysets to CGAL_Nef_polyhedron before exporting:
https://github.com/openscad/openscad/blob/master/src/export_amf.cc#L162-L165

I don't understand the reasoning, or if either option is particularly better than the other, but it seems like they should be changed so that both follow the same general export procedure if possible?

**Comment by kintel** [comment]
The STL approach should be significantly more robust when exporting designs that are not technically manifold. The AMF, OFF etc. exporters didn't get that facelift, so they're still using the method resulting in the least amount of code.
Getting all exporters to do the same thing sounds like the correct approach.

**Comment by GilesBathgate** [comment]
@kintel @thehans It seems like the main difference between `tessellatePolygonWithHoles` and `convert_to_Polyhedron` is that one uses a Constrained_delaunay_triangulation and the other uses just a plain Constrained_triangulation. The former is better as it produces fewer sliver triangles.

As an aside I think you could have just swapped in the delaunay one here: https://github.com/openscad/openscad/blob/master/src/CGAL_Nef3_workaround.h#L82

BTW I am looking at this approach, which is supposed to be much faster and uses delaunay  (If I can get it to work correctly)
https://github.com/GilesBathgate/cgal/commit/580486a1f9700d10d104e396312593683c605640

**Comment by kintel** [comment]
IIRC, using CGAL's delaunay triangulator only works if we're using rationals, and even then, we can only extract the resulting triangles if the design is perfectly manifold. This caused a bunch of issues, hence the introduction of a separate triangulator.
@GilesBathgate I believe you opted for keeping rationals as late in the process as possible to accommodate this, including experimenting with rational representation of STL/OBJ files?

**Comment by GilesBathgate** [comment]
>triangulator only works if we're using rationals
Ok that makes sense, and yes I did experiment with keeping Gmpq rationals for as long as possible.

What is interesting about the new (as of cgal 5.10) `CGAL::convert_nef_polyhedron_to_polygon_mesh` is that it really takes any type that implements a MutableFaceGraph concept. So you could potentially add that concept to the Polyset class and have it convert from Nef -> Polyset (at least in theory). I think it also does the conversion from Exact to Inexact kernels. Here is the implementation: https://github.com/CGAL/cgal/blob/master/BGL/include/CGAL/boost/graph/convert_nef_polyhedron_to_polygon_mesh.h#L166

The documentation is here: https://doc.cgal.org/latest/BGL/group__PkgBGL.html#ga7cf62f17d3bb060519e682ad9499c7d4

**Comment by GilesBathgate** [comment]
As an aside, I was reading the wrong code in cgalutils.cc, I thought tessellatePolygonWithHoles was using the CGAL delaunay triangulator, but that was in some commented out code: https://github.com/openscad/openscad/blob/master/src/cgalutils.cc#L425

**Comment by kintel** [comment]
Yah, moving to a more recent CGAL would open some doors, but close a bunch of Linux distro doors. Not sure how to best manage this, apart from drawing a line and not support older distros.

**Comment by GilesBathgate** [comment]
@kintel I thought you might be interested in my proposed PR for cgal. https://github.com/CGAL/cgal/pull/2614 I think its _just about_ on topic ;)
