### ISSUE TITLE
Unable to find official LICENSE file?

### ISSUE THREAD

**Issue by luzpaz** [openscad/openscad#4224]
Is this intentional ?

**Comment by Ckath** [comment]
theres other names that are often used, here its [COPYING](https://github.com/openscad/openscad/blob/master/COPYING)

**Comment by luzpaz** [comment]
Thanks, sorry for the noise

**Comment by t-paul** [comment]
What?

You mean that one? https://github.com/openscad/openscad/blob/master/COPYING

![grafik](https://user-images.githubusercontent.com/1330241/163687619-5ea531ff-d910-47d0-8127-0faa7279b501.png)

**Comment by t-paul** [comment]
See also Debian package for a more standardized format: https://sources.debian.org/src/openscad/2021.01-4/debian/copyright/
