### ISSUE TITLE
Feature request: iOS and android app

### ISSUE THREAD

**Issue by dcherrera** [openscad/openscad#4248]
I spend allot of time out and about and use openscad as my sole cad program. It would be really nice if someone would compile it for iOS at the very least and put it on the App Store so I can work on projects when I'm on lunch. It's a bit above me. Plus if someone from your team did it. It's more likely to revive updates. Thanks for at least looking at this. Thank you so much for the awesome software.

**Comment by t-paul** [comment]
Sorry, not possible. Apple Licensing rules make that impossible.

**Comment by t-paul** [comment]
You can try if the (still very experimental) Web version works... https://ochafik.com/openscad/#
