### ISSUE TITLE
Customizer slider control is too small in Windows 10.

### ISSUE THREAD

**Issue by ScottNudds** [openscad/openscad#4269]
The OpenScad customizer slider control used in both the current official release and the current build is unusable because the slider handle is only 2 or 3 pixels tall, and only extends above the central line.

In addition no tick-marks appear, no upper and lower values appear.

**Comment by t-paul** [comment]
Please add at least some more details like screen resolution (e.g. is it a 4k screen? are there any special display settings), and a screenshot..

**Comment by ScottNudds** [comment]
Window Resolution 2048x1152
Latest build of Openscad and the last release build.
Windows 10 Home 64 bit.
scale and layout 100% (default)
![Capture1](https://user-images.githubusercontent.com/106360343/170802728-e3074610-c504-4e0c-bb2a-a8f9f73add10.PNG)

**Comment by ScottNudds** [comment]
Consider this issue resolved.  Turns out it was one a Theme that was installed that was causing the issue.

Reverting back to the default theme restored the slider handles to their appropriate mode and size.
