### ISSUE TITLE
Removing material from imported STL breaks preview

### ISSUE THREAD

**Issue by hadess** [openscad/openscad#4278]
Using `openscad-2021.01-8.fc36.x86_64` and current Flathub version

In a number of my "editing" projects, I use OpenSCAD to chop off material using `difference()`, for example:
https://github.com/masible/extra-large-light-ruler-based-calipers

The preview appears with missing faces, but there are no errors in the logs. Removing the objects that remove material fixes the preview. The full on render doesn't show any artifacts

I understand that the STL files I've been using might have minor glitches, but the render can go past that and render correctly. I would happily take a slightly slower preview if that means I can preview with the colours I assigned rather than having to use the monochrome render.

Broken preview:
![Broken preview](https://user-images.githubusercontent.com/769861/172144368-ca145c95-4875-4fb9-a92b-356905aac4c6.png)

Working render of the same source:
![Working render](https://user-images.githubusercontent.com/769861/172144371-33190dfc-7565-4221-992a-b5142ddc6e64.png)

Working preview, without the removed material:
![Working preview](https://user-images.githubusercontent.com/769861/172144374-a3270ddc-8f50-4717-8140-fcf21f29a032.png)
.

**Comment by nophead** [comment]
Have you see the convexity parameter of the import statement?

**Comment by hadess** [comment]
Setting the convexity to, say, 10, solves the problem. Is there any reason why a higher convexity than the default (I imagine it's 2) isn't the default? It only changes the preview, so should be a backwards-compatible change to make.
