### ISSUE TITLE
OpenSCAD crashes compiling specific file, Windows 8.1 Beta

### ISSUE THREAD

**Issue by pbaughman** [openscad/openscad#428]
OpenSCAD crashes when compiling this: http://www.thingiverse.com/thing:18379 in CGAL, Windows 8.1 Beta 64-bit.  This happens in the latest release and the latest development snapshot (2013.06.15).  ATI drivers are running the latest version (3/28/2013).  Compilation gets all the way to 997/1000 before the crash happens.  Same place every time

From the WIndows event viewer:
Faulting application name: openscad.exe, version: 0.0.0.0, time stamp: 0x51bc7c11
Faulting module name: atio6axx.dll, version: 6.14.10.12217, time stamp: 0x5154f6b2
Exception code: 0xc0000005
Fault offset: 0x000000000016b394
Faulting process id: 0xf0c
Faulting application start time: 0x01ce75c8865892eb
Faulting application path: C:\Program Files\OpenSCAD\openscad.exe
Faulting module path: C:\WINDOWS\SYSTEM32\atio6axx.dll
Report Id: 10d02ea9-e1cc-11e2-be79-0018f3ab70b4
Faulting package full name: 
Faulting package-relative application ID: 

**_and**_

Fault bucket 113947574, type 4
Event Name: APPCRASH
Response: Not available
Cab Id: -540966854

Problem signature:
P1: openscad.exe
P2: 0.0.0.0
P3: 51bc7c11
P4: atio6axx.dll
P5: 6.14.10.12217
P6: 5154f6b2
P7: c0000005
P8: 000000000016b394
P9: 
P10: 

Attached files:
C:\Users\Peter\AppData\Local\Temp\WERE62D.tmp.WERInternalMetadata.xml
C:\Users\Peter\AppData\Local\Temp\WERF1D7.tmp.appcompat.txt
C:\Users\Peter\AppData\Local\Temp\WERF1D8.tmp.dmp

These files may be available here:
C:\Users\Peter\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_openscad.exe_e35b035f42de8df18347457957fac783244caf_a49b2d19_cab_04891607

Analysis symbol: 
Rechecking for solution: 0
Report Id: 10d02ea9-e1cc-11e2-be79-0018f3ab70b4
Report Status: 24
Hashed bucket: f2e866912dbb321f71c5a41194ecf2e2

**Comment by OZ1SEJ** [comment]
Why is this issue closed? I have the lastest AMD drivers, and my OpenSCAD crashes in this exact manner, whenever $fn is too high...

**Comment by t-paul** [comment]
The issue owner confirmed it was a driver bug and closed the issue. We really can't do anything against crashing graphics drivers.
