### ISSUE TITLE
CGAL error when using `projection(cut=true)`

### ISSUE THREAD

**Issue by frazar** [openscad/openscad#4288]
When running the following code with OpenScad 2021.01-5:

```
projection(cut=true) translate([126.5,179,-170 + 65.1]) rotate([+90,0,-90]) import("F5.stl");
```

using [this .stl file](https://github.com/openscad/openscad/files/8974955/F5.stl.gz) as input I get the following error message:

```
 CGAL error in CGALUtils::project during bigbox intersection: CGAL ERROR: assertion violation!
Expr: target(s1).vertex()==target(s2).vertex()
File: /usr/include/CGAL/Nef_3/SNC_FM_decorator.h
Line: 219
```

**Comment by UBaer21** [comment]
seems to be related to this stl (or size/resolution), i got that error also on different positions.
But 
`projection(cut=true) translate([-150,-150,-50]) import("F5.stl");`
is working fine when only the ring is cut.
![image](https://user-images.githubusercontent.com/93376232/175517144-429ac90b-bf3d-4979-bc00-e3211af2d486.png)

**Comment by UBaer21** [comment]
when cutting the stl i find several voids
```
intersection(){
  translate([126.5,179,-170 + 65.1]) rotate([+90,0,-90])  import("F5.stl",convexity=10);
  cylinder(.0001,d=1000);
}
```

![image](https://user-images.githubusercontent.com/93376232/175521616-1976cc80-69a6-4847-bef8-5e45a3efaa7e.png)

So i assume you need to repair the stl to get results.

**Comment by frazar** [comment]
Ops! Sorry for mistakenly reporting this issue, I am not particularly proficient with .stl files.

If I'm not asking too much, could you give me some general indications as to how to repair the stl?

Thank you again for you help.

**Comment by UBaer21** [comment]
[F5.tar.gz](https://github.com/openscad/openscad/files/8984535/F5.tar.gz)
 here the result (svg) and a re-meshed and reduced version.  There are some tools to repair geometry http://meshrepair.org/

**Comment by frazar** [comment]
Amazing! Worked like a charm. Thank you very much
