### ISSUE TITLE
can't get windows native build to work.. "if [ -e " [$5]

### ISSUE THREAD

**Issue by ivoknutsel** [openscad/openscad#431]
i'm trying to build openscad on windows, the dependencies all build, qmake works and generates a  makefile. nmake fails on

```
bison -d -p parser -o src/parser_yacc.cpp src\parser.y && if [ -e src/parser_yacc.hpp ]; then mv    
src/parser_yacc.hpp src/parser_yacc.h ; fi

-e was unexpected at this time.
NMAKE : fatal error U1077: 'bison' : return code '0x1'
```

This was included from bison.pri and that file seems to have been changed recently.

Any hints and tips ?
##

**Comment by kintel** [comment]
@ivoknutsel Are you still interested in Windows building? We now have a working native Windows build using the MSYS2 system, but Visual Studio is still a bit off due to the difficulty building dependencies.
Also, is this issue still valid or could we close?

**Comment by t-paul** [comment]
Can we close this and refund the bounty?

It would be nice to have a native Windows build (right now we build on MXE/Linux and MSYS2/Windows but have no native Visual Studio based build).

Maybe we can create a new ticket with some clear title + expectation and move the bounty there?

**Comment by kintel** [comment]
Closing as this has stagnated

**Comment by MichaelAtOz** [comment]
> Can we close this and refund the bounty?

Apart from possibly asking boutysource support, the only way I found is for the bounty poster to claim they fixed it.
