### ISSUE TITLE
Export color models

### ISSUE THREAD

**Issue by Rami5743** [openscad/openscad#4311]
It seems that until now, openscad does not allow to export of color models (though it does support presenting such models). 

I think this is a very important feature to add since 3d printing of color models become much cheaper now. 

Thanks a lot,
Rami

**Comment by jordanbrown0** [comment]
See #1608.

I believe that a common mechanism for multi-color slicers is to give them one STL per color.  You would then correspondingly arrange for your OpenSCAD model to have a parameter that would let you generate each color individually.  Not nearly as convenient as built-in support, but do-able.

**Comment by Rami5743** [comment]
Thank you very much.

I think that I do not really understand your answer. If my model has only one part, how can I use one stl per color? In many of my models, I have several "pieces" and each "piece" have its own color. However, the "pieces" are glued together, so they are not separate stl's. 

Thanks again,
Rami

**Comment by jordanbrown0** [comment]
You would make one STL of the red parts, one STL of the green parts, et cetera. Then you import them all into your slicer with the same origin so they are reassembled correctly, and assign the desired colors for each.

**Comment by kintel** [comment]
Fixed by #5185 - only OFF supported so far, but the feature is complete.
