### ISSUE TITLE
Feature Request: Save a Copy menu option [$25]

### ISSUE THREAD

**Issue by jbinvnt** [openscad/openscad#4314]
Add a new File menu option titled "Save a Copy." This option exists in other software such as LibreOffice, and its behavior is described [here](https://askubuntu.com/questions/398969/what-is-the-difference-between-save-as-and-save-a-copy). This would be helpful for when the user wants to save a benchmark copy or alternate version with a different name, but then keep making modifications to the original file without needing to reopen it.

Most users would likely expect to see the option placed below "Save As," which is where it is located in LibreOffice et al.

**Comment by MichaelAtOz** [comment]
I just added a US$25 bounty for  #4314, expires in 1 month, **easy beer money**. 
(testing the Boutysource interface tool, but go for it if anyone wants it)

**Comment by MichaelAtOz** [comment]
OK again, this one got the bounty treatment without me triggering anything.
That looks promising.

**Comment by MichaelAtOz** [comment]
@RayyanAnsari you should claim the bounty.

**Comment by RayyanAnsari** [comment]
@MichaelAtOz I already have claimed the bounty - I think you need to approve it.

**Comment by MichaelAtOz** [comment]
OK accepted on BS, thanks.

I recall in the past getting an email from BS asking for acceptance. 
I didn't get one this time.
@t-paul is that how you remember it working?
