### ISSUE TITLE
Feature request: faster projection cut

### ISSUE THREAD

**Issue by ochafik** [openscad/openscad#4319]
Placeholder to investigate CGAL's [PMPSlicer](https://doc.cgal.org/latest/Polygon_mesh_processing/index.html#PMPSlicer) + triangle mesh in fast-csg mode, instead of the current Nef code.

The use case I'm trying to speed up is to do 3D printer slicer operations in OpenSCAD:

```js
n=100;
for (z=[-n:n])
  translate([0, 0, z])
    linear_extrude(1)
      projection(cut=true)
        translate([0, 0, -z])
          // import("model.stl");
          sphere(n);
```

**Comment by kintel** [comment]
FYI: This is fast with manifold now, since #5076
