### ISSUE TITLE
cmd line file output error when no file present

### ISSUE THREAD

**Issue by tenaciousRas** [openscad/openscad#432]
Using the -o switch from the command line, for example:
/path/to/openscad -o path/to/foo.stl foo.scad

If path/to/foo.stl doesn't exist then OpenSCAD complains:
Can't open file "/path/to/foo.stl" for export

OpenSCAD apparently overwrites /path/to/foo.stl if it exists, otherwise it fails.  However it waits until processing foo.scad to report the error thus wasting time and resources.

It should either:  create the file if one doesn't exist; or check for existence of the export file first, before processing the SCAD.
- this is on OpenSCAD 20120822 on Mac OSX Lion
##

**Comment by t-paul** [comment]
Closed via #3387.
