### ISSUE TITLE
Right double click sometimes messes up rendering

### ISSUE THREAD

**Issue by jordanbrown0** [openscad/openscad#4332]
Start with a simple cube(10);.

F5 preview, then right double click outside the model.  It might take a few times, but usually not many.  Click and drag to pan or rotate, and observe the ... interesting ... rendering.

![image](https://user-images.githubusercontent.com/31949071/185777723-33b57ee0-658f-4360-9fa4-3b9b65aa6979.png)
![image](https://user-images.githubusercontent.com/31949071/185777827-5d4bed68-1aec-4a10-baec-e5d06321dad8.png)

It may (or may not) be relevant that Thrown Together shows it in purple.

![image](https://user-images.githubusercontent.com/31949071/185777781-0c8c00a3-0f5c-41b1-88d1-34f90c7c598f.png)

**Comment by jordanbrown0** [comment]
The problem seems to be caused by the double-click handler changing the GL context and not restoring it.  That newly selected GL context - which is the one used for normal preview - is then used by the right-click object selection magic, and damaged.

There are a number of outstanding questions about exactly why things behave the way that they do.

See the PR to follow for more details.

**Comment by thehans** [comment]
I wonder if there is a race condition between rendering the graphics frame and the `MouseSelector` modifying GL states... might need to protect each frame render with a lock.

**Comment by jordanbrown0** [comment]
InPhase and I looked at that, because MT issues were our first guess.  (Or at least my first guess.)
There's only one thread involved in the picture, as far as we could tell.  See the PR for a lot more detail.
