### ISSUE TITLE
Feature request : Extend array syntax to allow indices  to be generally accessible via '.' syntax by allowing optional names for elements

### ISSUE THREAD

**Issue by kwikius** [openscad/openscad#4351]
Firstly, it is necessary to point out that this is current practise, but is limited to certain arbitrary things

```openscad
ar = [1,2,3,4];
echo(ar.x);
echo(ar.r);
echo(ar.w);
```

The proposal is to allow this feature to be extensible by users.
```openscad
tm = [
  nominal = [
    ascent = 12.5733,
    descent = -2.9433,
  ],
  max = [
    ascent = 13.6109,
    descent = -4.2114,
  ],
  interline = 15.9709,
  font = [
    family = "Liberation Sans",
    style = "Regular",
  ],
];

ascent = tm.nominal.ascent;
```

FAQ : Does this  break anything?
No

---

FAQ: What happens if you want to add a name to an element that already has one?
EDIT: modified

A member name is first looked up as a potential user name. If not found then the builtin names are looked up.
This implies that you can override a builtin name by a user defined name at any position in the array.

```scad
ar = [0,1,2,x=5];

assert( ar.x == 5);
assert(ar[0] == 0);
```
Is this confusing? 
   That is up to you. Would you seriously write the above code? 

Won't that be slow looking up all thos names? 
   That is an implementation issue, but for example you can set a in the implementation array object that an array has user defined element names. If the array has no user defined element names then the speed differences is just a few ns to check that flag

---

FAQ: What happens if an element doesn't have a name?

Duh? .. Then you can't look it up by name!

---

FAQ: What happens if an array has 2 members with same name?
```scad
ar = [
    a = 1,
    a = 2
]
```

lookup uses find first so only the first is found. 
```scad
assert(ar.a == 1);
assert(ar[0] ==1);
assert(ar[1] ==2);
```
Openscad could issue a warning too.

---

FAQ : Does this impact the objects proposals #3087 ?

No. I think you can use same syntax. ( I would argue that with this feature, object syntax may be redundant but ...)

**Comment by UBaer21** [comment]
size1=[1,2,3]; ↦ size1.x=1
size2=[a=1,b=2,c=3,x=4] ↦ size2.x=4
module X(var)echo(var.x);
X(size2) ↦  1 or 4 ?

**Comment by kwikius** [comment]
> size1=[1,2,3]; ↦ size1.x=1 size2=[a=1,b=2,c=3,x=4] ↦ size2.x=4 module X(var)echo(var.x); X(size2) ↦ 1 or 4 ?

https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/General#Dot_notation_indexing

See the 2nd item in the  faq

**Comment by UBaer21** [comment]
so your approach would break that.  And why the 2nd .. that would be Y and you didn't linked to [FAQs](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ) 

Sorry but you are very confusing.

**Comment by UBaer21** [comment]
that https://github.com/openscad/openscad/issues/4351#issuecomment-1243663667

**Comment by kwikius** [comment]
> that [#4351 (comment)](https://github.com/openscad/openscad/issues/4351#issuecomment-1243663667)

Trying to create some executable code from what you wrote above. You mean ...?
```
size1=[1,2,3];
size1.x=1;
size2=[a=1,b=2,c=3,x=4] ;
size2.x=4 ;
module X(var)echo(var.x);
```
output ERROR: Parser error: syntax error in file , line 2
@UBaer21   Perhaps you could try your code out first before posting?

/*irrelevant*/ size1=[1,2,3];
//size1.x=1; //error
size2=[a=1,b=2,c=3,x=4] ;
//size2.x=4 ; // error
module X(var)echo(var.x);

X(size2);

// output
// ECHO: 1

**Comment by UBaer21** [comment]
did you replace "↦"  with ; and added ";" and now complain that your code doesn't work? What make you think you can change this? These are pseudo code, text and comments, or were they formatted as code? - obviously you try to misunderstand - that way  good luck with any of your requests.

also there is nothing brocken - i assume you just don't understood this
`color=[.1,.2,.3,1]; //  color.rgba`
color.brag  would be blue, red ,alpha , green
 echo↦ ECHO: [0.3, 0.1, 1, 0.2]
`color(color)cube(10);`
`color(color.brag)cube(10);`  doesn't make much sense to replace blue with alpha and alpha with green but however.. 
`color(color.brga)cube(10);`  now this shifted red with blue, green with red and blue with green
`color(color.rrra)cube(10);`  now using red for all 3 color components and alpha

**Comment by kwikius** [comment]
Its true. I think I have been wasting my time. 

Bye

**Comment by UBaer21** [comment]
that would be fine if it is also working if you assign  ar2=ar;   so  ar2.rgba=42; need to be working also else this causes inconsistency.

**Comment by kwikius** [comment]
> that would be fine if it is also working if you assign ar2=ar; so ar2.rgba=42; need to be working also else this causes inconsistency.

I'm not sure what the above pseudocode is meant to mean. Since this is a feature request about openscad, perhaps express yourself in openscad language, else don't be surprised if you get upset again when others can't understand what you mean.

Maybe you mean ?:
```openscad
ar = [z=1, x=2, b=3, rgba=42];
ar2 = ar;
```
In this proposal this implies ( straight copy of the attributes from ar to ar.2):
```openscad
assert(ar2.rgba == 42);
assert(ar2[3] == ar2.rgba);
assert(ar2[0] == 1);
assert(ar2.z == 1);
assert(ar2.x == 2);
assert(ar2.x == ar2[1]);
```
In openscad you can also do:
```openscad
module cube(size) {
   cylinder(d=size[1],h=size[1],$fn=size[2]);
}

cube([40,12,3]);
```
Try it and you won't get the result you expect,. You can always produce nonsense in any language if you wish!

**Comment by kwikius** [comment]
Here is an example showing how the element name is useful documentation, to help remember which element is a translation and which a rotation( note that the module literals require https://github.com/openscad/openscad/issues/4349 and the named element feature isn't available there)
```openscad
use <MCAD/regular_shapes.scad>
use <MCAD/boxes.scad>

extrusionInfo = [
   [position = [0,0,0], rotation = [0,0,0], extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
   }],
   [[10,10,0],[22.5,5,0], module(height) cylinder(d = 7, h = height, $fn = 30)],
   [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
   [[30,30,10],[67.5,15,0], module(height) octagon_prism(height,4)],
   [[40,40,15],[90,20,0], module(height) {
      translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
   }]
];

for(elem = extrusionInfo)
   translate(elem[0])
      rotate(elem[1]){
         height = 40;
         m = elem[2];
         m(height);
      }
```

**Comment by jordanbrown0** [comment]
Nobody disagrees that named elements are valuable; that's much of the rationale behind the objects proposal.  The question here is why it makes sense to mix names with indexes.

**Comment by kwikius** [comment]
> Nobody disagrees that named elements are valuable; that's much of the rationale behind the objects proposal. The question here is why it makes sense to mix names with indexes.

1. You are questioning an existing language feature, since the feature already exists for element access via ar.x etc.  Are you suggesting deprecating its use?

2. How would you rewrite the [above example](https://github.com/openscad/openscad/issues/4351#issuecomment-1258763047) using objects ( replacing the module literals with something appropriate,if you prefer, to get it to compile). Or are objects to be accessible via index? ( but then your original question was why it makes sense to mix names with indexes, so I presume the answer would be No?)

**Comment by jordanbrown0** [comment]
I think the existing language feature addresses a very narrow case, two specific types of vectors that have shortcuts for their elements.  It is not a general name-value-pair mechanism.  (The swizzling mechanism makes that excruciatingly clear.)

Postulating a module literal mechanism, and using my proposed syntax for objects (but the others would work equally well for this case):
```
extrusionInfo = [
   {position = [0,0,0]; rotation = [0,0,0]; extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
   };},
   {position = [10,10,0]; rotation = [22.5,5,0]; extrusion = module(height) cylinder(d = 7, h = height, $fn = 30);},
   {position = [20,20,5]; rotation = [45,10,0]; extrusion = module(height) triangle_prism(height,5);},
   {position = [30,30,10]; rotation = [67.5,15,0]; extrusion = module(height) octagon_prism(height,4);},
   {position = [40,40,15]; rotation = [90,20,0]; extrusion = module(height) {
      translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
   };}
];

for(elem = extrusionInfo)
   translate(elem.position)
      rotate(elem.rotation){
         height = 40;
         m = elem.extrusion;
         m(height);
      }
```

And of course like most name-value data structures, the order of the entries doesn't matter.
```
{
  position = [0,0,0];
  rotation = [0,0,0];
  extrusion = module(height) { 
    translate([-3.5,-3.5,0]) cube([7,7,height]);
  };
},
```
is equivalent to
```
{
  extrusion = module(height) { 
    translate([-3.5,-3.5,0]) cube([7,7,height]);
  };
  rotation = [0,0,0];
  position = [0,0,0];
},
```

**Comment by jordanbrown0** [comment]
What's missing from today:
- Object literal syntax, the syntax that would let you create one of these from an OpenSCAD program.
- Module literal syntax.
- Module references.

What's there today (in the development snapshot):
- object[expr]
- object.identifier
- for (key = object)

**Comment by jordanbrown0** [comment]
If you really wanted to access an object's members by indexes, you could do it with either of these:
```
function obj_by_index(o, i) = o[ [ for (k=o) k ][i] ];
function obj_by_index(o, i) = [ for (k=o) o[k] ][i];
```
... but you really shouldn't, because by definition it is the *names* that are important.

In case explanation is necessary: 
- The first generates a list of all of the keys in the object, then selects the i'th key and looks it up in the object.
- The second generates a list of all of the values in the object, then selects the i'th value.

Both of those work today in the development snapshot.

**Comment by kwikius** [comment]
I'll take another look at the object branch. Unfortunately the build takes me an hour or so and am currently building another branch( Will make a separate issue about that. unless there already is one?)

**Comment by kwikius** [comment]
meanwhile...
```openscad
use <MCAD/regular_shapes.scad>
use <MCAD/boxes.scad>

extrusionInfo = [
   cube = [position = [0,0,0], rotation = [0,0,0], extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
   }],
   cylinder = [[10,10,0],[22.5,5,0], module(height) cylinder(d = 7, h = height, $fn = 30)],
   triangle = [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
   octagon = [[30,30,10],[67.5,15,0], module(height) octagon_prism(height,4)],
   roundcube = [[40,40,15],[90,20,0], module(height) {
      translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
   }]
];

for(elem = extrusionInfo)
   translate(elem[0])
      rotate(elem[1]){
         height = 40;
         m = elem[2];
         m(height);
      }
```

is IMHO nice and simple  versus the o syntax!

**Comment by kwikius** [comment]
I had a go (compare to proposed [the array version](https://github.com/openscad/openscad/issues/4351#issuecomment-1259143517) )
```openscad
use <MCAD/regular_shapes.scad>
use <MCAD/boxes.scad>

extrusionInfo = {
   cube = {
     position = [0,0,0];
     rotation = [0,0,0];
     extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
     };
   };
   cylinder = {
      position = [10,10,0];
      rotation = [22.5,5,0];
      extrusion =  module(height) cylinder(d = 7, h = height, $fn = 30);
   };
   triangle = {
      position = [20,20,5];
      rotation = [45,10,0];
      extruson = module(height) triangle_prism(height,5);
   };
   octagon = {
      position = [30,30,10];
      rotation = [67.5,15,0];
      extrusion = module(height) octagon_prism(height,4);
   };
   roundcube = {
     position =[40,40,15]
     rotation = [90,20,0];
     extrusion = module(height) {
      translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
    };
   };
};

for(i = [0:len(extrusionInfo)-1]){
   elem = obj_by_index(extrusionInfo,i)
   translate(elem.position)
      rotate(elem.rotation){
         height = 40;
         elem.extrusion(height);
      }
}
```
Or maybe I'm cheating her ? Can you do better...?
HINT:Also spot the deliberate mistake!

**Comment by kwikius** [comment]
> ```
>          m = elem.extrusion;
>          m(height);
>       }
> ```
could presumable be replaced with

```
   elem.extrusion(height);
}
```

**Comment by kwikius** [comment]
so you could do it with objects , but you could do it with arrays. Neither option excludes the other!

**Comment by kwikius** [comment]
The array could provide optional names.. which can save a lot of typing and hence typoing

**Comment by MichaelAtOz** [comment]
a. 
Please note, those of use who read the Git Emails do not see your edits to the posts, only the original posts, and rarely visit the Git.
So possibly, consider your message before actually posting. 
I usually read non trivial ones about four times with different audiences in mind prior to 'Comment'.
Otherwise post a 'sorry correction...' post, or 'I just edited the previous post' post if it is actually material, rather than minor editorial.

b. You have YHO, others have their opinions. Neither has precedence. Nor do quantity or frequency of posts have such.

c. I may be reading too much into some comments, but please do not disparage other comments.

> You are questioning an existing language feature, since the feature already exists for element access via ar.x etc. Are you suggesting deprecating its use?

I would have to look up the quote, but the original author stated that  .x .y .z was not meant to be 'official', it was not documented. I actually found it in the source and asked the question; he said he thought it would be a problem, it was there to assist with test cases. So don't use it as a precedent... Too late he cried...

....
I am on the spectrum, a late discovery, it leads to introspection. 
I try to consider and reflect on other perspectives, sometimes I misread them. Such is life.

**Comment by MichaelAtOz** [comment]
BTW, with my years of involvement, I note that historically, non-trivial language changes usually take years to successfully emerge. Just say'in, expectation management 101.

**Comment by kwikius** [comment]
Thanks to @jordanbrown0  for staying bang on topic, for using examples to illustrate his points with openscad code and for not making unnecessary personal comments , and for putting up with my modifications to previous comments which I try to flag up. 

@MichaelAtOz If there is anywhere in the previous posts where I edited to change semantics  without an informative comment, point me to it, and I will try to fix it.

**Comment by kwikius** [comment]
> BTW, with my years of involvement, I note that historically, non-trivial language changes usually take years to successfully emerge. Just say'in, expectation management 101.

And your point about the feature is ...?

**Comment by jordanbrown0** [comment]
Edit trick:  Make the edit.  Make another comment describing the edit.  (Ideally enough that you don't have to go back and re-read.)  Delete the new comment.  This keeps the comment history clean, and notifies people of the change.

---

I don't know what the state of the "object literals" branch is.  I don't think anybody has worked on it in a long time.  Critically, I don't know that it's been updated since I added object support to the development snapshot.  I would look at it for ideas, but wouldn't try to work from it.

---

Yes, objects are iterable.  (They're based, at least roughly, on JavaScript objects.)

`for (k = o)` iterates through the keys of the object.  (Currently in the order that they were added, but there's a decent argument that order should be unspecified.)

There is currently no `len(o)`, though you can get it via `len([for(k=o) k])`.  Then again, since there's no indexing, it's not clear what `len(o)` would be useful for.

Object keys are currently always strings, but that's not necessarily a requirement.  If objects ever allowed, say, numbers as keys, I'd say they could be sparse, negative, or fractional, and so wouldn't behave like indexes.

---

```
extrusionInfo = [
   cube = [position = [0,0,0], rotation = [0,0,0], extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
   }],
   cylinder = [[10,10,0],[22.5,5,0], module(height) cylinder(d = 7, h = height, $fn = 30)],
   triangle = [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
   octagon = [[30,30,10],[67.5,15,0], module(height) octagon_prism(height,4)],
   roundcube = [[40,40,15],[90,20,0], module(height) {
      translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
   }]
];
```
So in this proposal can I say `extrusionInfo.cylinder.position`?

If I have
```
extrusionInfo = [
   cube = [rotation = [0,0,0], extrusion = module(height) { 
      translate([-3.5,-3.5,0]) cube([7,7,height]);
   }],
   cylinder = [position=[10,10,0],module(height) cylinder(d = 7, h = height, $fn = 30)],
   triangle = [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
];
```
what does extrusionInfo.triangle.rotation mean?  What does extrusionInfo.cylinder[0] mean?  I can come up with meanings, but they do not seem to be *useful* meanings.  (`undef` and `[10,10,0]`, respectively.)

Lookup-by-name schemes are naturally order-insensitive and sparse.  Lookup-by-index schemes are naturally order-sensitive and want you to fill in every slot.  Mixing the two can easily yield variations that aren't useful, without enabling very many additional useful variations.

You can mix them better if you get to declare a schema, like a C structure.  Then you can both know which one is "first" and which is "second", and you can access them by name.  But I don't think a structure declaration mechanism is in our future in this language.

**Comment by kwikius** [comment]
@jordanbrown0 I have got the object_literals branch to build and run. Will put up some comments about the results in https://github.com/openscad/openscad/pull/3087#issuecomment-1259710359

**Comment by jordanbrown0** [comment]
Going back and responding to a question or two that I missed.

Yes, array notation can be quite a bit terser than object notation, because which data item is which is implied by position and you don't need labels on each item.  OTOH... which item is which is implied by position, so you have to keep track of position and include all of them in the same order.

```
for(i = [0:len(extrusionInfo)-1]){
   elem = obj_by_index(extrusionInfo,i);
   translate(elem.position)
      rotate(elem.rotation){
         height = 40;
         elem.extrusion(height);
      }
}
```
That would work (give or take the lack of `len(o)`), but more natural would be to iterate through the keys:
```
for(k = extrusionInfo) {
   elem = extrusionInfo[k];
   translate(elem.position)
      rotate(elem.rotation){
         height = 40;
         elem.extrusion(height);
      }
}
```

**Comment by kwikius** [comment]
> extrusionInfo = [
>    cube = [position = [0,0,0], rotation = [0,0,0], extrusion = module(height) { 
>       translate([-3.5,-3.5,0]) cube([7,7,height]);
>    }],
>    cylinder = [[10,10,0],[22.5,5,0], module(height) cylinder(d = 7, h = height, $fn = 30)],
>    triangle = [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
>    octagon = [[30,30,10],[67.5,15,0], module(height) octagon_prism(height,4)],
>    roundcube = [[40,40,15],[90,20,0], module(height) {
>       translate([-3.5,-3.5,0]) roundedCube([7,7, height],2,false,false);
>    }]
> ];
> ```
> 
> So in this proposal can I say `extrusionInfo.cylinder.position`?

No. (undef) You would have to name an element  of the cylinder array position. ( But note how I can easily identify and discuss  the extrusionInfo.cylinder array, rather than the extrusionInfo[1] array :) )
> 
> If I have
> 
> ```
> extrusionInfo = [
>    cube = [rotation = [0,0,0], extrusion = module(height) { 
>       translate([-3.5,-3.5,0]) cube([7,7,height]);
>    }],
>    cylinder = [position=[10,10,0],module(height) cylinder(d = 7, h = height, $fn = 30)],
>    triangle = [[20,20,5],[45,10,0], module(height) triangle_prism(height,5)],
> ];
> ```
> 
> what does extrusionInfo.triangle.rotation mean? 

undef

> What does extrusionInfo.cylinder[0] mean? 

[10,10,0]

> I can come up with meanings, but they do not seem to be _useful_ meanings. (`undef` and `[10,10,0]`, respectively.)

Yep. But its is easy to add a name if you want to , but  it till can be used as an array

> Lookup-by-name schemes are naturally order-insensitive and sparse. Lookup-by-index schemes are naturally order-sensitive and want you to fill in every slot. Mixing the two can easily yield variations that aren't useful, without enabling very many additional useful variations.
