### ISSUE TITLE
how to update macports version or get the dmg version working in MacOS via command line

### ISSUE THREAD

**Issue by WolfgangFahl** [openscad/openscad#4360]
https://ports.macports.org/port/openscad/ shows Version 2015-03-03 and can't be installed due to 
```
parser.tab.c:145:10: fatal error: 'parser.tab.h' file not found
:info:build #include "parser.tab.h"
:info:build          ^~~~~~~~~~~~~~
```
in my mac OS Big Sur environment
I have installed the dmg version as a workaround but don't know how to use it from the command line to be used as part of a python library. 

How could i use OpenSCAD on my mac os with macports via command line?

**Comment by WolfgangFahl** [comment]
see also https://trac.macports.org/ticket/65881

**Comment by WolfgangFahl** [comment]
The workaround seems to be
```
/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD -v
OpenSCAD version 2021.01
```

**Comment by t-paul** [comment]
Sorry the MacPorts build is not maintained here, so the ticket you created at macports.org seems to be the best way for reaching the right people.

Yes otherwise that script should work, I'd sugest adding quotes to `"$@"`. That should make it safe against parameters with spaces in them.

**Comment by WolfgangFahl** [comment]
@t-paul  thx. I have also added a hint to https://wiki.bitplan.com/index.php/PythonScad#Installation. ViewScad now works properly with OpenSCAD which is great.
