### ISSUE TITLE
[Bug] Selected tab is completely white

### ISSUE THREAD

**Issue by lucafaggianelli** [openscad/openscad#4375]
I have multiple tabs opened and the selected one is white with no close button available (I don't if there should be one actually):

![image](https://user-images.githubusercontent.com/4471043/194276150-3f197df8-550b-489b-8b15-bcc98a8e5db8.png)

I'm running OpenSCAD v2021.01 on macOS 12.2.1

**Comment by MichaelAtOz** [comment]
Debian & Windows have a close button (on the right end of the tab), so imagine Mac should too.

**Comment by lucafaggianelli** [comment]
Mmmm interesting so the lack of the close button is a bug too :)

**Comment by t-paul** [comment]
Please check with the development snapshot, if that shows the same issue.

**Comment by lucafaggianelli** [comment]
Ah great, indeed it works fine in the dev snapshot `2022.10.17`:
![image](https://user-images.githubusercontent.com/4471043/196955122-6aebb3c5-1f72-4a10-988f-82148a8ba89e.png)

**Comment by t-paul** [comment]
Thanks, closing as fixed then.
