### ISSUE TITLE
Consider upgrading to Clipper2

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#4394]
The author of the Clipper library (sometimes known as "polyclipping"), which we use for 2D booleans and offsets, has released a major update which I think would be worth looking into.
https://github.com/AngusJohnson/Clipper2

Currently we have source files of clipper included into our own project under `src/ext/polyclipping`.   With Clipper2 being in a github repo, I think it would be simpler and cleaner to build as a git submodule instead.

I'm not sure yet how much of the interface has changed, so no idea how large or small of an effort this would be.

**Comment by thehans** [comment]
There is also a chance that the new version happens to fix some existing issues such as #4393

**Comment by nophead** [comment]
I might be wrong but I think that might be a regression. I ran into  such problems in the last year maybe and probably in the last release but the 2D system seemed to be solid going way back before then. It took me by surprise when I was just subtracting squares with coincident edges. I am sure I didn't need an overlap in the past when the coordinates are exactly coincident.
