### ISSUE TITLE
Colours are not updated until the file is saved/not when the model is rendered

### ISSUE THREAD

**Issue by AcinonXDev** [openscad/openscad#4405]
When colouring objects with `color([ r, g, b ])`, the colours don't update until the file is saved. They should update when the object is rendered.

**Comment by t-paul** [comment]
Colors are only supported for F5 (preview), not F6 (mesh-render). I assume that is what you are seeing (with `Design` -> `Automatic Reload and Preview` enabled).

**Comment by AcinonXDev** [comment]
Okay. Is there a way to get colours in mesh-render?

**Comment by t-paul** [comment]
No, that is not yet supported. Initially used STL file format would not even allow those to be exported, newer formats handle colors and at some point OpenSCAD will hopefully catch up too.
