### ISSUE TITLE
Command line option "filename" does not accept spaces in filename.

### ISSUE THREAD

**Issue by JoshMcCullough** [openscad/openscad#441]
On windows, when I run:

```
openscad.com -o "My_Output_File.stl" ... "My Input File.scad"
```

OpenSCAD seems to think that the first word of my filename is the only word in my filename because it says "can't open input file 'My'."
##

**Comment by ChrisVesters** [comment]
Is this still relevant?

**Comment by MichaelAtOz** [comment]
I just ran
```
C:\test>%osp%openscad -o "my cube10.stl" "my cube10.scad"
```
And with a _ instead of space.
With 2017.04.05, and both worked.

Closing...
