### ISSUE TITLE
STL import does not show up

### ISSUE THREAD

**Issue by ygoe** [openscad/openscad#4422]
I'm designing a case for a PCB with connectors on it. To visualise how my case fits the board, I'd like to also add a simplified PCB with the outward-facing connectors on it. I've already got some 3D models to use in KiCad so I thought I'd just throw them into my OpenSCAD case so I have the proper sizes.

This is the script I used:

```c
import("Molex MicroFit 43650-0200.stl");
```

The original file is a STEP file but OpenSCAD can't import those (as per the documentation). I read that FreeCAD could convert it but I've already uninstalled it for its huge disk space and I don't need it. So I used PrusaSlicer to convert the file. The original and the converted STL are attached.

[Molex MicroFit 43650-0200.step.zip](https://github.com/openscad/openscad/files/10079119/Molex.MicroFit.43650-0200.zip)
[Molex MicroFit 43650-0200.stl.zip](https://github.com/openscad/openscad/files/10079122/Molex.MicroFit.43650-0200.stl.zip)

The stl file is stored in the same directory as the scad file.

However, nothing appears in the preview or rendering. Here's the log output:

```txt
Parsing design (AST generation)...
Saved backup file: C:/Users/Yves/Documents/OpenSCAD/backups/test-backup-xnlgnstV.scad
Compiling design (CSG Tree generation)...
Compiling design (CSG Products generation)...
Geometries in cache: 1
Geometry cache size in bytes: 56600
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Compiling design (CSG Products normalization)...
Normalized tree has 1 elements!
Compile and preview finished.
Total rendering time: 0:00:00.012
 
Parsing design (AST generation)...
Saved backup file: C:/Users/Yves/Documents/OpenSCAD/backups/test-backup-xnlgnstV.scad
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using CGAL...
Geometries in cache: 1
Geometry cache size in bytes: 56600
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.024
   Top level object is a 3D object:
   Facets:        784
Rendering finished.
```

**Comment by t-paul** [comment]
It's just waaaay off center. Use `View` -> `View All`.
