### ISSUE TITLE
float variable treat as integer, if the decimal value is 0

### ISSUE THREAD

**Issue by sugizo** [openscad/openscad#4428]
this code will treat as integer, because the decimal value is 0, 
if the up or down is pressed on the customizer parameter it will increase or decrease by 1 (integer)
```
/*[ option ]*/
size = 1.0;
```

this code will treat as float, because the decimal value is not 0
if the up or down is pressed on the customizer parameter it will increase or decrease by 0.1 (float)
```
/*[ option ]*/
size = 1.1;
```

**suggestion**
it's nice to have the float variable stay float variable whether the decimal value is 0 or not

thanks and best regards

**Comment by UBaer21** [comment]
```
a=0;// .1
b=0;// .5
```
you find more here https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Customizer#Spinbox
