### ISSUE TITLE
lexer.lexer.cpp #include "parser_yacc.h"

### ISSUE THREAD

**Issue by ivoknutsel** [openscad/openscad#445]
lexer.lexer.cpp includes "parser_yacc.h", bison creates a parser_yacc.hpp which is then renamed to parser_yacc.h.

lexer.lexer.cpp line 625
bison.pri line 6 en 14 i believe

Can't we just include the .hpp or will this break other platforms ?

http://stackoverflow.com/questions/15265770/how-to-tell-bison-to-generate-a-parser-cpp-and-parser-h-file-instead-of-parser-c
##

**Comment by t-paul** [comment]
Looks like that was fixed long time ago via #447.
