### ISSUE TITLE
Crash during compile of qrc_common.cpp

### ISSUE THREAD

**Issue by threed-factory-store** [openscad/openscad#4544]
I'm on Ubuntu 22.10.

I cloned the repository, ran uni-get-dependencies.sh and check-dependencies.sh and everything came back OK.

Generated the makefile, ran make -j, and it crashed on qrc_common.cpp.  Took the terminal window with it.

**Comment by t-paul** [comment]
Well, don't do that (`make -j`) unless you have unlimited memory. Try `make -j2` and increase if you have enough memory.

**Comment by threed-factory-store** [comment]
> Well, don't do that (make -j)

Then would you fix this page?
https://github.com/openscad/openscad#building-openscad

**Comment by t-paul** [comment]
Thanks for the pointer. Suggesting that in the readme makes no sense.

**Comment by threed-factory-store** [comment]
Thanks, and thanks for the quick response!

**Comment by t-paul** [comment]
Readme is updated now.
