### ISSUE TITLE
Segmentation fault when generating STL file from Scad file

### ISSUE THREAD

**Issue by threed-factory-store** [openscad/openscad#4547]
When I run 
      openscad -o 
on the attached Scad file, it crashes with the following message:

1121795 Segmentation fault      (core dumped) openscad -o "${StlFile}" "${ScadFile}"

[SegFault.zip](https://github.com/openscad/openscad/files/10948647/SegFault.zip)

**Comment by craftmaster1231** [comment]
Any details about version, environment?
Everything works fine in my case.
![image](https://user-images.githubusercontent.c

Just in case you need that stl file:
[stl.zip](https://github.com/openscad/openscad/files/11409965/stl.zip)
om/32911478/236565799-71aa5cc8-a486-4336-930a-895cb89bbbcf.png)

**Comment by craftmaster1231** [comment]
> Any details about version, environment? Everything works fine in my case. ![image](https://user-images.githubusercontent.com/32911478/236566105-7acc504b-f584-4b48-886b-c11e31542a49.png)
> 
> Just in case you need that stl file: [stl.zip](https://github.com/openscad/openscad/files/11409965/stl.zip) om/32911478/236565799-71aa5cc8-a486-4336-930a-895cb89bbbcf.png)

Of course, after path updated to `use <fillets3d.scad>` .

**Comment by threed-factory-store** [comment]
Ah.  So I had two versions of OpenScad installed on Ubuntu, both from the Software Center.    I was runnning version 2021.01 which is "openscad" in the terminal.  The other version is called "openscad-nightly".  If I run that version, it generates the STL file.

Thanks for your help!
