### ISSUE TITLE
Manifold: Decimates embossed text or images

### ISSUE THREAD

**Issue by alidaf** [openscad/openscad#4579]
Full renders seem to decimate the geometry of embossed text or SVG images. The simplest test I can do is below. In this case, $fn needs to be large to introduce the artefact but in most of my other models where a similar artefact occurs, I use $fn = 12. This does not happen with raised ("debossed") text or images. With text, the artefact starts off most noticeably with the "e" at around $fn = 30 and gets progressively worse, spreading to the other letters as the value increases.
Bizarrely, temporarily commenting out the difference() to create an extruded image or text, rendering, and then reverting back to embossing, seems to fix the issue entirely, even if the text is changed!

That said, Manifold helps immensely with a lot of other models, especially vases with a lot of Bezier controlled adjustments. I can easily render with 100+ interpolation points in seconds compared to minutes for 50 data points without Manifold.

iMac Retina 5K Intel Core i7, OSX Ventura 13.2.1
OpenSCAD 2023.03.24 (git 1295101a0)

`difference()
 {
    cylinder(d = 23,
             h = 2.8,
             center = true,
             $fn = 360);
    translate([0, 1.2, 1.1])
    linear_extrude(1.0, convexity = 2)
    scale([0.26, 0.26, 1])
        import("triskelion.svg", center = true, $fn = 30);
 //        text("Hello", $fn = 30);
}`
![Manifold Test Preview](https://user-images.githubusercontent.com/14184640/227980756-87911b60-11ef-4d46-b702-a1e0d35c525b.png)
![Manifold Test Render](https://user-images.githubusercontent.com/14184640/227980739-9564a83e-8845-4a9f-852e-a379c598192c.png)
![Triskelion](https://user-images.githubusercontent.com/14184640/227980855-99a2dede-7f85-40b3-a921-a6adfd5dde81.svg)

**Comment by ochafik** [comment]
Thanks for reporting! I reckon this probably has the same root cause as https://github.com/elalish/manifold/issues/388
