### ISSUE TITLE
Text isn't centered if ttb or btt direction used

### ISSUE THREAD

**Issue by cymplecy** [openscad/openscad#4591]
and halign set to center

text("OpenSCAD",size=12,font="Liberation Mono",halign="center",valign="center",direction="ttb");

![image](https://user-images.githubusercontent.com/2357428/230703880-6d97dad3-2d0a-4026-ab3f-7c3c96e9e24a.png)

**Comment by jordanbrown0** [comment]
Which version are you using?  I believe this is fixed in the development snapshot, in PR#3684.

![image](https://user-images.githubusercontent.com/31949071/230743977-923a9015-10df-4b90-9056-8b9b1d1e92f3.png)

**Comment by jordanbrown0** [comment]
btt:

![image](https://user-images.githubusercontent.com/31949071/230744206-f0d431db-6d5c-4d59-9b3d-1f541df509a9.png)

**Comment by cymplecy** [comment]
I'm just using 2021.01 on Windows but glad to know it's been fixed in a dev version :)
