### ISSUE TITLE
Export to STL has no respond

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4600]
WIN7
OpenSCAD 2021.01
```
color("gray")
difference() {
    cylinder(1,d=60,$fn=360); 

    translate([0,0,-1])
    cylinder(3,d=32,$fn=360); 
}

color("gray")
translate([-17.5,-1,-34])
cube([35,2,35]);

color("gray")
rotate([0,0,90])
translate([-17.5,-1,-34])
cube([35,2,35]);
```

**Comment by t-paul** [comment]
Please add more details and context.

**Comment by sonichy** [comment]
Console:
`ERROR: Nothing to export! Try rendering first (press F6)`
I see render first, then can export stl !
It is better to show a dialog to tell user to render.

**Comment by jordanbrown0** [comment]
FWIW, I agree that a dialog would be appropriate here - and it shouldn't just say "you need to render first"; it should have a "Render" button.
