### ISSUE TITLE
Move improve

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4625]
Ctrl + mouse left drag move horizontal and vertical.

Or like [ FlashPrint](https://www.sz3dp.com/download-center):
Mouse left drag: move horizontal or vertical.
Mouse right drag: rotate.

**Comment by UBaer21** [comment]
Sorry but what does "move" mean?  Is this an object  translation? Is this improvement something like ` alt+scroll (or arrow)` ?

**Comment by jordanbrown0** [comment]
Or is it perhaps a request for *constrained* panning, so that once you start moving left-right it won't move up-down, and vice versa?

**Comment by sonichy** [comment]
I see,  mouse left drag rotate, mouse right drag move horizontal and vertical.
