### ISSUE TITLE
How to model cube round a face 

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4629]
![alt](https://questionimg.3d66.com//answers/question/20210906/5fd3d9239e0ef84700f8523c182e0672.jpg)

**Comment by UBaer21** [comment]
@sonichy you might check out the https://openscad.org/documentation.html and Tutorials.  Or the [Community ](https://openscad.org/community.html) We have an IRC-channel where you can ask questions. But this is not an issue that needs to be tracked in github.
You can make this form by adding a `cylinder()` to a `cube()`. Or using `hull()` or using `[minkowski](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#minkowski)`
