### ISSUE TITLE
polyhedron render disappear

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4635]
```
cube(10);

polyhedron(
 points = [[0,-3,0], [-2,-3,0], [0,-3,3], [-2,0,0], [0,0,3], [0,0,0]],
 faces = [[1,3,2], [2,3,4], [0,2,4], [4,5,0], [0,1,3], [0,3,5], [0,1,2], [3,4,5]]
);
```

**Comment by UBaer21** [comment]
no 
![image](https://github.com/openscad/openscad/assets/93376232/7df58695-c27b-4b41-955f-800aa1546330)

**Comment by UBaer21** [comment]
faces 4,5 and 7 have wrong order resulting in inverted normal
![image](https://github.com/openscad/openscad/assets/93376232/8f4d2cdc-d880-4216-b579-91643bc01698)

**Comment by sonichy** [comment]
What is the order ?

**Comment by UBaer21** [comment]
a face has two sides .. an inside (pink in F12 view)  and an outside (white) , this is the normal vector and depends if the points are cw or ccw ordered 
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Primitive_Solids#Mis-ordered_faces

**Comment by jordanbrown0** [comment]
Faces need to be specified clockwise when viewed from the outside.  Use View/Thrown Together (F12); in the default color scheme anything purple is backwards.

![image](https://github.com/openscad/openscad/assets/31949071/a5cf9efe-03ae-4cf3-9247-026788947ac2)

**Comment by sonichy** [comment]
https://files.openscad.org/documentation/manual/Primitive_Solids.html#Mis-ordered_faces
