### ISSUE TITLE
How to partly cut ?

### ISSUE THREAD

**Issue by sonichy** [openscad/openscad#4636]
Target
![alt](https://s1.ax1x.com/2023/05/12/p9yXuwR.jpg)
```
intersection(){
linear_extrude(height=130)
polygon([[0,0],[86,0],[86,2],[80,9],[6,9]]);

translate([43,10,56])
rotate([90,0,0])
cylinder(11,56,56,$fn=200);
}
```
![alt](https://s1.ax1x.com/2023/05/12/p9yX6XQ.png)

**Comment by UBaer21** [comment]
This is not an issue/bug/enhancement - please use the community for questions.
(make a union of the circle with a square and offset it for the rounding)
