### ISSUE TITLE
Can't difference custom geometry

### ISSUE THREAD

**Issue by dre506** [openscad/openscad#464]
difference()
{
	
	testBox();
	translate([0.5,0.5,0.5])
	testBox();
	
}

module testBox()
{
	union()
	{
		polyhedron(points=[[0,0,0],[1,0,0],[1,0,1],[0,0,1]],triangles=[[0,1,2],[0,2,3]]);
		polyhedron(points=[[1,0,0],[1,1,0],[1,1,1],[1,0,1]],triangles=[[0,1,2],[0,2,3]]);
		polyhedron(points=[[1,1,0],[0,1,0],[0,1,1],[1,1,1]],triangles=[[0,1,2],[0,2,3]]);
		polyhedron(points=[[0,1,0],[0,0,0],[0,0,1],[0,1,1]],triangles=[[0,1,2],[0,2,3]]);
		polyhedron(points=[[0,0,1],[1,0,1],[1,1,1],[0,1,1]],triangles=[[0,1,2],[0,2,3]]);
		polyhedron(points=[[0,0,0],[1,0,0],[1,1,0],[0,1,0]],triangles=[[2,1,0],[3,2,0]]);
	}
}

**Comment by kintel** [comment]
With [List Comprehensions](http://en.wikibooks.org/wiki/OpenSCAD_User_Manual/List_Comprehensions) and [concat()](http://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Mathematical_Functions#concat) we now have the ability to stitch together lists of coordinates and indices and pass them to polyhedron() later. That should fix the issue discussed here.
