### ISSUE TITLE
Openscad has licencing issues when run in the browser

### ISSUE THREAD

**Issue by traverseda** [openscad/openscad#466]
If there's any way we could add this special exception...

http://www.gnu.org/licenses/gpl-faq.html#WMS

> As a special exception to the GPL, any HTML file which merely makes function calls to this code, and for that purpose includes it by reference shall be deemed a separate work for copyright law purposes. In addition, the copyright holders of this code give you permission to combine this code with free software libraries that are released under the GNU LGPL. You may copy and distribute such a system following the terms of the GNU GPL for this code and the LGPL for the libraries. If you modify this code, you may extend this exception to your version of the code, but you are not obligated to do so. If you do not wish to do so, delete this exception statement from your version.

**Comment by mmiscool** [comment]
I know this is an exceptionally old thread but I was wondering if you could point me in the direction of a function working openscad wasm implementation?

**Comment by MichaelAtOz** [comment]
That is wishful thinking...
I believe the sites fronting OpenSCAD on the web use it in scripted command-line mode.

**Comment by t-paul** [comment]
@mmiscool I'm not aware of any fully running version at this point, but it was shown that it's possible to run OpenSCAD via `emscripten`. There's also a later effort mentioned in #1262.

So in summary I think it would take quite a bit of work (maybe also skipping preview mode first) but it would be awesome to see this happening.
