### ISSUE TITLE
Add doxygen style comments on module/function

### ISSUE THREAD

**Issue by vicnet** [openscad/openscad#467]
Doxygen is a tool for generating documentation from C++ sources, based on comments.
I suggest to do the same things for OpenSCAD file.
As doxygen tags are included in comments, this could be already be done yet.
But I suggest to integrate it more in OpenSCAD interface (don't know how to yet) to help/stimulate user to use it...
##

**Comment by t-paul** [comment]
I support the general idea of adding documentation but this issue has no real path forward as it's too general.

Integrating doxygen does not seem viable as it's a separate program, generating files, so control is very limited. What I'm thinking is actually supporting something like the 3 quotes documentation section (similar to what python uses) in the syntax and declaring that to be markdown text.
