### ISSUE TITLE
CSG File Format > Versioning documentation, support, and comments

### ISSUE THREAD

**Issue by yaxy** [openscad/openscad#4721]
CSG File Format > Versioning (https://github.com/openscad/openscad/wiki/CSG-File-Format#versioning) states "Version of CSG file should be defined with version tag in the begining [sic] of the file." However, a .CSG file consisting of exactly the example given yields "ERROR: Parser error: syntax error in file test.csg, line 1 Execution aborted."

Indeed, CSG files created through File > Export > Export as CSG do not start with a versioning line e.g. #openscad 1.0.

Suggest dropping Versioning section entirely. Or a Feature Request to allow comments in CSG files by ignoring any line that begins with #.

![Image3](https://github.com/openscad/openscad/assets/11161822/e0b7bd1b-e17c-4996-ac17-7a500144c0ec)
![Image2](https://github.com/openscad/openscad/assets/11161822/9c34e9e5-cd62-403e-bd78-5046276f4396)

**Comment by kintel** [comment]
That wiki page contained some old proposal which was never implemented. Have killed it now.
