### ISSUE TITLE
getting the current co-ordinates of a created object

### ISSUE THREAD

**Issue by radianttone** [openscad/openscad#4727]
WHERE I GET THE PROBLEM:
When creating a more complex model (complex for me mostly because I'm bad at math), I often use a number of translate or rotate blocks, for instance creating a thing with a function that is called inside a few translates and rotates and other functions.  So by the end, I might have moved an object, rotated it again, combined it or subtracted it with another object, mirrored the result - and called that 30 times in a ring around some other object (so the location of the original sphere in that construct is unclear).

THE SOLUTION I'D LIKE:
being able to surround a given item with something that would return [x,y,z] and possibly the combined rotation that is affecting that object. either to the context of the scope that called it or the entire 3D space that is being modeled.

or really as a more comprehensive thing being able to return information from functions, like:

SpecialVariableDeclaration bob = runSomeStuff( thingsISentYou );

where the return is an object with characteristics definable in the function accessible like:
bob.ThingIReturned1 bob.ThingIReturned2 bob.ThingIReturned3 

so I can send them to other things 
otherFunction( bob.ThingIReturned1 , someOtherThing );

preferably where that variable can be references in an array that is iterate-able somehow 

ALTERNATIVES I'VE CONSIDERED
Currently I'm using a set of workarounds like matching points with a separate function that allows me to specify the angle from a point or a cartesian coordinate, and then match it up using those numbers later when I rewrite additional code, and then matching the rotation within that derived space with another point (and creating a 3d model of a compass at the location so i can measure the angle from that location). and creating triangles there to check my guesses.  If the information can't be returned within the scripting language, then at least a right-click option that turns on flyover tooltips that show that or other categories of information on the model 
![openscnewgeoscrn](https://github.com/openscad/openscad/assets/117468480/824237c7-9feb-4f2d-a601-9c324ce82b8b)

---------------
So simple version:  a built-in function like:

returnThePosition( ParticularThingIwantToKnow ) { 
       shape(); 
       }

complicated version:
Object oriented variables

by the way, don't get me wrong I love the actual program and I'm a big fan of it. This problem doesn't make it unusable, it's just multiplying the amount of time I have to spend doing it.

**Comment by t-paul** [comment]
See #4478 and associated discussion.
