### ISSUE TITLE
cylinder center parameter not work as expected

### ISSUE THREAD

**Issue by Dachtire** [openscad/openscad#4740]
**Describe the bug**
cylinder center parameter not work as expected. `cylinder(true);` should be same as `cylinder(center = true);`, but now is equal to `cylinder(center = false);`

**To Reproduce**
1. Use the code below

**Code reproducing the issue**
```
cylinder(true);
```

**Environment and Version info (please complete the following information):**
 - OS: Ubuntu 22.04
 - System: Intel PC 64-bit
 - OpenSCAD Version: 2023.09.09.nightly (git dcaf25f)

**Comment by thehans** [comment]
When in doubt, its always best to be explicit with parameter names.
