### ISSUE TITLE
Manifold 1st and 2nd F6 Render return different Geometry types

### ISSUE THREAD

**Issue by thehans** [openscad/openscad#4753]
**Describe the bug**
This is a follow-up to issue #4685. where a 2nd render with manifold enabled was triggering an assertion.  The assertion has been removed, but behavior remains where it seems to return different Geometry types between the 1st and 2nd render.  This is apparent by the differing render statistics displayed upon F6.

I suspect the cause is related to caching in some way, but haven't dug in to determine specifics.

**To Reproduce**
1. Enable Preferences->Features->Manifold
2. Use the following design (but pretty much any design should do):
```
union() {
  cube();
  sphere();
}
```
3. Hit F6. Then hit F6 again.
4. Review Console output (only 2nd render says `Top level object is a 3D object (manifold)` indicating a `ManifoldGeometry`, not sure what type is returned on the 1st render):
```
Parsing design (AST generation)...
Saved backup file: /home/hans/.local/share/OpenSCAD/backups/unsaved-backup-YaYgPcrb.scad
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using Manifold...
Geometries in cache: 3
Geometry cache size in bytes: 2560
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.022
Top level object is a 3D object:
   Facets:         44
Rendering finished.
 
Parsing design (AST generation)...
Saved backup file: /home/hans/.local/share/OpenSCAD/backups/unsaved-backup-YaYgPcrb.scad
Compiling design (CSG Tree generation)...
Rendering Polygon Mesh using Manifold...
Geometries in cache: 3
Geometry cache size in bytes: 2560
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.016
   Top level object is a 3D object (manifold):
   Status:     NoError
   Genus:      0
   Vertices:       24
   Facets:         44
   BBox.min:   -0.809016, -0.951056, -0.866025
   BBox.max:   1.000000, 1.000000, 1.000000
Rendering finished.
```
 
**Expected behavior**
Consistent Render Statistics across renders

**Environment and Version info (please complete the following information):**
 - OS: Linux Mint 21.2
 - System: amd64
 - OpenSCAD Version 2023.09.22 nightly

**Comment by pca006132** [comment]
It seems that polyset is returned in the first render. Perhaps something in the non-cached code path will convert manifold into a polyset, and does not perform such conversion in the cached code path? I wonder if this is also related to #4732, where the first render will fail and the second will succeed.
