### ISSUE TITLE
Testunit on include KO

### ISSUE THREAD

**Issue by vicnet** [openscad/openscad#477]
I just recompile openscad, taken from git and pass some tests.
'opencsgtest_include-tests' test is KO because  a cube is missing.

If I render this test in openSCAD manually, it is ok (cgal or openscg).
If I use command line with -o xxx.png, it is KO (render option or not).

This cube is included from a file whose name contains a space.
Don't know if there is a link...

I was thinking about a timing problem put add a sleep(2) after generating and before saving don't change anything.

**Comment by kintel** [comment]
Sounds like this was a GL driver issue and was resolved using SW rendering.
