### ISSUE TITLE
Non-gui usage broken, GLEW Error: Unknown error, Can't create OffscreenView

### ISSUE THREAD

**Issue by rcolyer** [openscad/openscad#4777]
**Describe the bug**
On xubuntu 22.04 (anywhere else?) only 23% of tests pass, and all command line image generation appears to be broken with the error:
```
Compiling design (CSG Products normalization)...
Normalized CSG tree has 8 elements
GLEW Error: Unknown error
Can't create OffscreenView: Unable to initialize Glew.
```

**To Reproduce**
1. Run tests, get 23% pass
2. Or, run "openscad -o foo.png foo.scad" for any foo.scad ("cube(1);" will suffice)

**Expected behavior**
Image output

**Environment and Version info (please complete the following information):**
 - OS: Xubuntu 22.04.3 LTS
 - System: AMD Ryzen 7 4800H with Radeon Graphics
 - OpenSCAD Version 2023-10-10 build, whereas 2023-09-17 build before GLX/Offscreen work was fine.

**Comment by rcolyer** [comment]
@kintel Per request, building with "-DUSE_BUILTIN_OPENCSG=ON" results in tests passing and restores normal command line functionality.

**Comment by pca006132** [comment]
I encountered this error as well when using the system OpenCSG library and GLEW. If I manually change the CMakeLists.txt to use GLAD, it works.

I use nixos with intel graphics, so this should be a general issue.

**Comment by kintel** [comment]
Can reproduce on Ubuntu/nVidia as well. Will Fix.
