### ISSUE TITLE
Coredump with File|Quit but not Main Window Close

### ISSUE THREAD

**Issue by neildarlow** [openscad/openscad#4799]
**Describe the bug**
When quitting OpenSCAD using File|Quit a coredump results. However, using the Main Window Close icon (top-right) doesn't result in a coredump. Two distinctly different behaviours.

**To Reproduce**
1. Start OpenSCAD and select New
2. Click on 'Main Window Close icon'
3. OpenSCAD closes and note no coredump in /var/lib/systemd/coredump
4. Start OpenSCAD and select New
5. Click in 'File|Quit Menu item'
6. OpenSCAD closes and note a coredump in /var/lib/systemd/coredump

**Expected behavior**
File|Quit should behave like Main Window Close and not generate coredump.

**Code reproducing the issue**
If applicable, add trimmed down, self-contained code demonstrating the issue.

**Screenshots**

**Environment and Version info (please complete the following information):**
 - OS: fedora Workstation 38 Cinnamon Edition
 - System: Intel Core i5 desktop with NVidia graphics running Nouveau driver
 - OpenSCAD Version: 2021.01 flatpak from flathub.org
Also:
 - OS: openSUSE Aeon GNOME 45
 - System: Intel Core i5 laptop with Intel iRIS Xe graphics
 - OpenSCAD Version: 2021.01 flatpak from flathub.org
 
**Library & Graphics card information**
If applicable, add the content of the Help->Library Info window, or the output of running the `openscad --info` command.

**Additional context**

**Comment by sebeaumont** [comment]
Interestingly exhibits exactly the same behaviour on Mac OS Ventura on a M1 (arm64) build from MacPorts.

**Comment by thehans** [comment]
This is fixed in the current source tree (since #3846).  You can run a recent build downloaded from the "developement snapshots" section here:
https://openscad.org/downloads.html#snapshots
