### ISSUE TITLE
Windows 2023.11.08 crash on salt pig lid model with manifold enabled

### ISSUE THREAD

**Issue by owebeeone** [openscad/openscad#4815]
**Describe the bug**
Attempting to render the model linked below crashes or wedges Openscad v Windows 2023.11.08

https://drive.google.com/file/d/1qmgVoY0NuFzueMCYkebTCH9kjReEhAtO/view?usp=sharing

**To Reproduce**
1. Load the model linked
2. Render

**Expected behavior**
Create a model

**Code reproducing the issue**
(https://drive.google.com/file/d/1qmgVoY0NuFzueMCYkebTCH9kjReEhAtO/view?usp=sharing)

**Environment and Version info (please complete the following information):**
 - OS: Windows 11
 - System Model	ROG Strix G513RM_G513RM
 - Installed Physical Memory (RAM)	32.0 GB
 - OpenSCAD Version [2023.11.08 ] installed exe installer

**Library & Graphics card information**
OpenSCAD Version: 2023.11.08 (git e7abd10a9)
System information: Microsoft Windows 11 (10.0.22621) x86_64 16 CPUs 31.26 GB RAM
User Agent: OpenSCAD/2023.11.08 (git e7abd10a9) (Microsoft Windows 11 (10.0.22621) x86_64)
Compiler: GCC "11.3.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_81
Eigen version: 3.4.0
CGAL version, kernels: 5.5, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.5.0
Qt version: 5.15.10
QScintilla version: 2.11.2
InputDrivers: 
GLib version: 2.70.2
lodepng version: 20210627
libzip version: 1.5.2
fontconfig version: 2.14.2
freetype version: 2.13.1
harfbuzz version: 7.3.0
cairo version: 1.16.0
lib3mf version: 1.8.1
Features: fast-csg, fast-csg-safer, fast-csg-debug, manifold*, roof, input-driver-dbus, lazy-union*, vertex-object-renderers, vertex-object-renderers-indexing, vertex-object-renderers-direct, vertex-object-renderers-prealloc, textmetrics, import-function, predictible-output
Application Path: C:/Program Files/OpenscadDev
Documents Path: C:\Users\gianni\Documents
User Documents Path: C:\Users\gianni\Documents
Resource Path: C:/Program Files/OpenscadDev
User Library Path: C:/Users/gianni/Documents/OpenSCAD/libraries
User Config Path: C:\Users\gianni\AppData\Local/OpenSCAD
Backup Path: C:/Users/gianni/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
C:/Users/gianni/Documents/OpenSCAD/libraries
C:/Program Files/OpenscadDev\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
C:/WINDOWS/fonts
C:/Users/gianni/AppData/Local/Microsoft/Windows/Fonts
C:/Users/gianni/.local/share/fonts
C:/usr/local/share/fonts
C:/usr/share/fonts
C:/usr/X11/lib/X11/fonts
C:/System/Library/Fonts
C:/Library/Fonts
C:/Users/gianni/Library/Fonts
GLEW version: 2.1.0
OpenGL Version: 4.6.0 Compatibility Profile Context 22.20.28.09.221101
GL Renderer: AMD Radeon(TM) Graphics
GL Vendor: ATI Technologies Inc.
RGBA(8888), depth(32), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8888), depth(32), stencil(8)

GL Extensions:
GL_AMD_blend_minmax_factor
GL_AMD_bus_addressable_memory
GL_AMD_depth_clamp_separate
GL_AMD_gpu_shader_half_float
GL_AMD_gpu_shader_int16
GL_AMD_gpu_shader_int64
GL_AMD_pinned_memory
GL_AMD_sample_positions
GL_AMD_shader_trinary_minmax
GL_ARB_ES2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compute_shader
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_query_buffer_object
GL_ARB_robustness
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_stencil_export
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shadow
GL_ARB_shadow_ambient
GL_ARB_sparse_buffer
GL_ARB_sparse_texture
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_filter_minmax
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_multisample
GL_ARB_texture_multisample_no_array
GL_ARB_texture_non_power_of_two
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_meminfo
GL_ATI_separate_stencil
GL_ATI_shader_texture_lod
GL_ATI_texture_env_combine3
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_clip_cull_distance
GL_EXT_color_buffer_half_float
GL_EXT_compiled_vertex_array
GL_EXT_copy_buffer
GL_EXT_copy_image
GL_EXT_debug_label
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_buffers_indexed
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_point_size
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_gpu_shader5
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_multi_draw_arrays
GL_EXT_nonuniform_qualifier
GL_EXT_packed_depth_stencil
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_provoking_vertex
GL_EXT_render_snorm
GL_EXT_sRGB_write_control
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shader_io_blocks
GL_EXT_shadow_funcs
GL_EXT_stencil_wrap
GL_EXT_tessellation_point_size
GL_EXT_tessellation_shader
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_border_clamp
GL_EXT_texture_buffer
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_bptc
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_format_BGRA8888
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_object
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_RG8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_texture_snorm
GL_EXT_texture_storage
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_NV_blend_square
GL_NV_copy_image
GL_NV_primitive_restart
GL_NV_shader_atomic_int64
GL_OES_EGL_image
GL_OES_draw_texture
GL_OVR_multiview
GL_OVR_multiview2
GL_OVR_multiview_multisampled_render_to_texture
GL_S3_s3tc
WGL_EXT_swap_control

**Comment by owebeeone** [comment]
This is a low res version of the model above, it also crashes - https://drive.google.com/file/d/1RRS6CzdnHLmmJMYyWSKS25_chYqjrkWP/view?usp=drive_link

**Comment by gsohler** [comment]
it does not crash on my
OpenSCAD <https://www.openscad.org/> version 2023.10.22 (git )
in windows


but it appears  that there are some volumes missing ?
the volume is  very thin on the right hand side and probably no printer can
easily resolve that.


https://imgur.com/a/W3SGsWB

**Comment by owebeeone** [comment]
It definitly prints. https://makerworld.com/en/models/18828#profileId-17591

**Comment by pca006132** [comment]
is it related to #4814?

**Comment by owebeeone** [comment]
Another data point. I decided to roll back openscad to snapshot version 2023.10.27 and it renders properly and very fast.
OpenSCAD Version: 2023.10.27 (git ab5dd9338) - I turned on manifold and lazy-union exactly as before 11.08.

**Comment by kintel** [comment]
I added the low-res version as a test case, and for some reason, it doesn't crash: https://github.com/openscad/openscad/pull/4819

@owebeeone Could you try reproducing on the cmd-line?
`openscad.com issue4815.scad --enable=manifold --render -o out.png`

issue4815.scad is https://github.com/openscad/openscad/blob/1ff854259dcd524723bffec272d61395734e6ad5/tests/data/scad/3D/issues/issue4815.scad

**Comment by owebeeone** [comment]
@kintel I have reproduced the error wirh 11.08 with the command line you suggest. openscad terminates with -o out,png without producing a png file. Sometimes it will segv. When I try to render stl (out,stl) it will sometimes hang.

This is the output with various command lines:
- works 
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad -o out.png

Compiling design (CSG Products normalization)...
Normalized CSG tree has 35 elements
Geometries in cache: 18
Geometry cache size in bytes: 141656
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.133

Added --render
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --render -o out.png

Geometries in cache: 64
Geometry cache size in bytes: 888944
CGAL Polyhedrons in cache: 12
CGAL cache size in bytes: 8549560
Total rendering time: 0:00:03.187
Top level object is a 3D object:
   Simple:     yes
   Vertices:     1304
   Halfedges:    5214
   Edges:        2607
   Halffacets:   2586
   Facets:       1293
   Volumes:         2

Failures:
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --enable=manifold  --render -o out.png

 Got a Dr watson - segv reading 0x18

- repeat
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --enable=manifold  --render -o out.png

Segmentation fault  (...cygwin segv...)

- repeat 2
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --enable=manifold  --render -o out.png

- just hangs there, wedged, doesnt exit

- try to render STL
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --enable=manifold  --render -o out.stl

- Also just hangs
- repeat - segv reading 0x18
- repeat - exits without output and a status of 127
$ echo $?
127
- repeat - just hangs again
These are the 4 error modes after further repeated attempts in random order. segv 0x18, cygwin segv, exit status 127 and wedge,

Just in case, this is the sha256sum of issue4815,scad since I copied it from anchorcad_HingedLid_example2_example.scad
e2038911ec498b43f87b8526d7164400cf2dc9235f0553d1523f437280bb61e6 *issue4815.scad

OpenSCAD version 2023.10.27 on the other hand works just fine:
$ cmd /c 'C:\\Program Files\\OpenSCADDev\\openscad.exe' issue4815.scad --enable=manifold  --render -o out.stl

Geometries in cache: 76
Geometry cache size in bytes: 888944
CGAL Polyhedrons in cache: 0
CGAL cache size in bytes: 0
Total rendering time: 0:00:00.998
Top level object is a 3D object:
   Facets:       2420

**Comment by kintel** [comment]
@owebeeone Please give this build a spin: https://app.circleci.com/pipelines/github/openscad/openscad/4212/workflows/56748a42-6ca7-47b9-9372-66ba2a4d17ec/jobs/16991/artifacts

**Comment by pca006132** [comment]
Hi, have you been able to make manifold work on simpler models? I feel like this is a build issue rather than bug with certain model.

**Comment by owebeeone** [comment]
Tried it on OpenSCAD version 2023.11.15, appears to work fine now.

**Comment by owebeeone** [comment]
Tried Version 2023, 11, 15, 18, 23, 34, the salt pig lid model works fine. Running against all other anchorscad models too. Will report any issues.

**Comment by pca006132** [comment]
by 2023.11.15, do you mean the build in #4830?

**Comment by owebeeone** [comment]
@pca006132 Yes, the one on #4830

**Comment by t-paul** [comment]
Added latest oneTBB to MXE, build fixed via #4847. Builds will upload in the next couple of hours.
