### ISSUE TITLE
building manifold: bound between 18446744022169944064 and 18446744073709551592 exceeds maximum object size 9223372036854775807

### ISSUE THREAD

**Issue by zaitcev** [openscad/openscad#4818]
**Describe the bug**

Running make ends with an error:

/home/zaitcev/prog/openscad/openscad-work/submodules/manifold/src/third_party/thrust/thrust/system/detail/sequential/trivial_copy.h:47:17: error: ‘void* memmove(void*, const void*, size_t)’ specified bound between 18446744022169944064 and 18446744073709551592 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
   47 |     std::memmove(result, first, n * sizeof(T));
      |     ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

See attached build log.

**To Reproduce**
1. Follow all the steps to build in README.md
2. make 2>&1 | tee ../build.out

**Expected behavior**
`make` completed

**Code reproducing the issue**
see attached

**Environment and Version info (please complete the following information):**
 - OS: Linux, Fedora 38
 - System: x86_64
 - OpenSCAD Version: git clone 

**Library & Graphics card information**
n/a

**Comment by t-paul** [comment]
Please use latest commit from master. This is fixed in Manifold via #4728.
