### ISSUE TITLE
documentation lacking for offset()

### ISSUE THREAD

**Issue by purple512** [openscad/openscad#4823]
**Describe the bug**
One of the example files that you ship with OpenSCAD (GEB.scad) contains expressions like `offset(0.3)`.

I'm trying to comprehend the [documentation for `offset()`](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#offset) and it talks about `r` and `delta` modes, but every example in the documentation uses a named parameter! Nothing tells me which mode is used in `offset(0.3)`. I'm guessing `r` because it was mentioned first? But who knows.

Why is this so unnecessarily obfuscated? Why can it not say "r. double. The default type if not specified."? Or something along those lines?

Also, this documentation is confusing because it makes it look at first glance like the function takes three parameters, but there's really only two.

![image](https://github.com/openscad/openscad/assets/79816784/9ba3921b-a831-4b66-9ecc-2dda7cc74cc5)

It would be much more clear at a glance if you included the function signature from the cheat sheet: `offset(r|delta,chamfer)`.

**Comment by jordanbrown0** [comment]
Somewhat unfortunately, the documentation on wikibooks is actually more accurate.  If you want to use positional parameters, they are `r`, `delta`, and `chamfer`, in that order - and if you supply a valid number for `r`, `delta` is ignored.

If you want delta mode, the best strategy is to set delta as a named parameter `offset(delta=10) ...`, and then if you want chamfer mode set that as a named parameter too.  The implementation currently allows you to pass a non-number for `r` and it will be ignored, `offset(undef, 3, true)`, but I would not recommend it - that seems like the kind of pattern that might yield a warning in the future.

We should probably change the cheat sheet to `offset(r, delta, chamfer)` and clarify in wikibooks that if you want delta mode you should use named parameters.

**Comment by amatulic** [comment]
I have fixed the documentation at https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Transformations#offset to address the issues raised in this ticket. If that is satisfactory, this issue may be closed.

I submitted a related issue #4973 regarding the tooltip that pops up for offset().

**Comment by jordanbrown0** [comment]
Thanks for the cleanup.  Works for me.
