### ISSUE TITLE
Issue running a difference and a for loop

### ISSUE THREAD

**Issue by baslisks** [openscad/openscad#484]
when I run my for loop inside my difference I get an error that says.

//Assertion failed!

//programs:\Program Files\OpenScad\openscad.exe
//file: ../src/csgterm.cc, line 191

//expression term -.left && term -> right

__________________________________________________________________________

difference()
{
union(){
hull(){
	translate([0,0,30])cylinder(r = 55, h = 7, $fn = 40);
	translate([-75/2,0,0])rotate([0,90,0])cylinder(r = 23.75/2, h = 75);
}
hull(){
translate([0,0,0])cube([50,20.75,7], center = true);
translate([-75/2,-35,-3.5])cube([15,70,7]);
}
hull(){
translate([0,0,0])cube([50,20.75,7], center = true);
translate([22.5,-35,-3.5])cube([15,70,7]);
}
}
hull(){
	translate([0,0,30])cylinder(r = 53, h = 7, $fn = 20);
	translate([-68.58/2,-12.7/2,10])cube([68.58,12.7,1]);
}
translate([-65,0,0])rotate([0,90,0])cylinder(r = 20.75/2, h = 130);
translate([30,27,-5])cylinder(r = 2.75,h = 10);
translate([30,-27,-5])cylinder(r = 2.75,h = 10);
translate([-30,27,-5])cylinder(r = 2.75,h = 10);
translate([-30,-27,-5])cylinder(r = 2.75,h = 10);
translate([-75,-75,-150])cube([150,150,150]);
for ( i = [0:.5:720]){
	rotate([0,0,i])translate([106/2,0,(i*.0139)+30])cube([1.5,1,1]);
}
}

this is the bit of code I am dumping into it.

**Comment by t-paul** [comment]
Seems to be fixed. Checked with 2015.01.12.nightly (git e84f797).

**Comment by kintel** [comment]
Confirmed to be fixed
