### ISSUE TITLE
Is the `docker-build.sh` script in this repo used anymore?

### ISSUE THREAD

**Issue by DeflateAwning** [openscad/openscad#4843]
Is the `/scripts/docker-build.sh` file in this repo still used? Seems like it might be redundant with the existance of the entire [openscad/docker-openscad](https://github.com/openscad/docker-openscad) repo? Its existance left me quite confused trying to follow out-of-date build documentation.

If it is indeed out-of-date and unused in favor of the regular docker repo, we should delete that file to save anyone else the hassle.

Maybe @t-paul would be a good person to check, as they seem to be involved in the CI setup.

**Comment by t-paul** [comment]
Thanks for the pointer. Yes, that's obsolete, Ubuntu 16.04 and use of `qmake` is not going to work with the recent OpenSCAD source code.
