### ISSUE TITLE
can spline curves be imported to OpenSCAD

### ISSUE THREAD

**Issue by WinlCheng** [openscad/openscad#4860]
spline curves is a way to describe the curve.
OpenSCAD seems not to be able to make a accurate curve, this may cause some problems and reduce model quality. And more $fn cause obvious low speed of model produce.
is it possible to introduce it, or other way to describe the curve?

**Comment by pca006132** [comment]
No, OpenSCAD works with mesh and is unable to deal with curves precisely. High $fn (~100) is now feasible with manifold enabled.
If you want better precision than that, you should probably look into brep kernels, e.g. OpenCASCADE.

**Comment by jordanbrown0** [comment]
Hint:  Use `$fn` *only* to produce regular polygons.  Do *not* use it to control model quality.  Use `$fa` and `$fs` to control model quality.  If you use `$fn` to make your large circles good, it will make your small circles unnecessarily complex.

**Comment by pca006132** [comment]
closing as there is no plan in introducing brep.
