### ISSUE TITLE
(1) STL Export Bug for a .STL successfully rendered

### ISSUE THREAD

**Issue by SoMuchHope** [openscad/openscad#487]
Openscad version: 2013.06
OS: Windows 7

Hello,

Thanks to all of the coders for their beautiful and very useful job. I would not be able to keep up in my work without openscad.

Issue:

I have a export STL issue with a .STL. This STL can be imported. It can be rendered. But it cannot be exported.

I get the following error message:

"This application has requested the Runtime to terminate it in a unusual way.
Please contact the application's support team for more information"

then openscad crashes.

![puppetsuccessulfyrendered](https://f.cloud.github.com/assets/5527418/1201001/6e32c3ae-252e-11e3-8b83-2713fa769d8c.png)
![errorpuppetstl](https://f.cloud.github.com/assets/5527418/1201002/713581e0-252e-11e3-815a-ea9441fe7aae.png)

I will give you other input about Import/ export STL files,

the source STL to check is there (file more than 5mb):
http://www.thingiverse.com/thing:25466

Nb of faces (if it matters): 35 543

Regards,

John

**Comment by kintel** [comment]
This should now be fixed.
