### ISSUE TITLE
What does the name consist of?

### ISSUE THREAD

**Issue by Develeon64** [openscad/openscad#4896]
Open is very clear, what it stands for. CAD also...

But I ever wondered, what the S stands for?
**Open _Script_-CAD** maybe? Or something like this?

What was the initial idea for the name oft this masterpiece of software?

**Comment by UBaer21** [comment]
**S**olid

**Comment by nophead** [comment]
I thought it was Open Source CAD.

**Comment by UBaer21** [comment]
@nophead  assumed from  https://openscad.org/

> OpenSCAD
> The Programmers Solid 3D CAD Modeller

**Comment by t-paul** [comment]
Added to [FAQ](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#What_is_the_meaning_of_the_S_in_OpenSCAD?) now.
