### ISSUE TITLE
little bug with french version on version 2023.12.11 (git 3d094bf87)

### ISSUE THREAD

**Issue by terpene33** [openscad/openscad#4897]
**Describe the bug**
in the interface there are some command in French Language but other in turckish language
Yeni dosia
Yeni penserede Aç  and other command.

**To Reproduce**
1. Go to '.fichiers..'

**Environment and Version info (please complete the following information):**
 - OS: [macOS 12 ventura, ]
 - System: [ Intel PC 64-bit]
 - OpenSCAD Version [2023.12-11.] 

** Can I help You ???  For traduction ?

**Comment by terpene33** [comment]
Perhaps do to an old MacOS version ? macOS 13.6.1 (22G313)  not 14 Mojave

**Comment by kintel** [comment]
On my macOS 13 laptop I don't see the Turkish strings. However, the strings you mention are not French either, they're English. Do you happen to have Turkish as a configured language in System Settings -> Language & Region?

I also notice that the strings in question look a bit odd in the translation files:
https://github.com/openscad/openscad/blob/master/locale/fr.po#L477

They have a `#, fuzzy` comment, which may confuse the lookup.

**Comment by terpene33** [comment]
Yes ! it's right : there is turkish in configured langage  !
I don't use this !!!
So now there some item in English language (it's well for me and I have Add English language) or in french )
Thanks You ! You are right ! Can you write on git this issue is solved ?

My appologies for my poor English language !

Best regards ! ( my SMTP  don't work with your IP adresse ?? !?)

**Comment by thehans** [comment]
> Can you write on git this issue is solved ?

Closing per request
