### ISSUE TITLE
Animate window has too many play/pause buttons

### ISSUE THREAD

**Issue by jordanbrown0** [openscad/openscad#4899]
The Animate window has three closely-related buttons:
* Centered just below the parameters, a play/pause button.  It's a play icon while not playing, and a pause icon while playing.
* Left-center of the button bar, a play button.  It's inactive while playing.
* Right-center of the button bar, a pause button.  

Really, only the first is necessary - but if one really prefers two buttons, the first is unnecessary.  Having all three leads one to wonder what they do differently, especially when the pause icon is small and looks more like a stop icon.  (Ref the "Also" below.)

I would put a single play/pause button in the center of the button bar.

Also:  the icons, especially the button-bar "pause" icon, turn into somewhat undistinguished blobs when the Animate window is small.  They could usually be considerably bigger while still fitting inside their buttons.  Alternatively, making them less bold (as is done in the single play/pause button) would help.

Also also:  It seems a bit weird to have the "Dump Pictures" checkbox between the two sets of buttons; it belongs above the buttons.

![image](https://github.com/openscad/openscad/assets/31949071/0a16f1d8-a980-4ec1-910c-b8733f7f03d0)

![image](https://github.com/openscad/openscad/assets/31949071/77ea340c-c519-4fe9-b7b0-8d898e277fd7)

 - OS: Windows 10
 - System: PC 64-bit
 - OpenSCAD 2023.12.09 developer snapshot

**Comment by t-paul** [comment]
How about:

[Screencast from 2024-04-26 21-53-27.webm](https://github.com/openscad/openscad/assets/1330241/22fe51b7-2650-4375-8aa6-c6a4b5dc3ce8)
