### ISSUE TITLE
Linux: Incorrect app id matching for .desktop icon in Wayland

### ISSUE THREAD

**Issue by darkblaze69** [openscad/openscad#4910]
**Describe the bug**
Incorrect app id matching for .desktop icon in Wayland, so missing icon in wayland session. 
.desktop file should contain correct StartupWMClass= or correct .desktop filename.

**To Reproduce**
* To see the bug it should run in native wayland mode (not xwayland)
* Run Wayland session, e.g. in GNOME
* have environment var set `QT_QPA_PLATFORM="wayland;xcb"`
* run openscad
* in GNOME Overview it's generic icon for openscad
* in GNOME looking glass the app is untracked, and the wmclass is org.openscad.openscad

**Expected behavior**
app icon should be shown in Overview.

**Environment and Version info (please complete the following information):**
- OS: Arch Linux
- DE: GNOME, Wayland session, `QT_QPA_PLATFORM="wayland;xcb"` to run in native wayland (not xwayland)
 - OpenSCAD Version 2021.01-10 from Arch pacman default repo

**Screenshots**
Original package, app id not match, generic icon:
![Screenshot from 2023-12-31 22-38-56](https://github.com/openscad/openscad/assets/6976920/e7ca470f-8b90-4f8b-b2dd-2c00dbd8b411)

Looking glass:
![Screenshot from 2023-12-31 22-21-53](https://github.com/openscad/openscad/assets/6976920/b26c3215-4eaa-4d3a-8d4e-9fe18ff4e853)

After .desktop renaming it is shown correctly:
![Screenshot from 2023-12-31 22-40-32](https://github.com/openscad/openscad/assets/6976920/d9f2e806-842b-4837-8ab3-14677327d4fa)

![Screenshot from 2023-12-31 22-41-53](https://github.com/openscad/openscad/assets/6976920/4cbdedca-b478-4e5d-81ad-4078e945304e)

Also without renaming, but adding correct `StartupWMClass=org.openscad.openscad` to desktop file:
![Screenshot from 2023-12-31 22-43-30](https://github.com/openscad/openscad/assets/6976920/0f7c1021-1be5-4a47-9af4-b24beee99019)

**Comment by t-paul** [comment]
fixed via #4862
