### ISSUE TITLE
Code completion for modules in included files

### ISSUE THREAD

**Issue by hatalmasalma** [openscad/openscad#4912]
For me it seems like code autocompletion doesn't use module or function names from include() or use() files, only from the currently edited file.

I hope it would be easy to implement.

**Comment by kberkut** [comment]
How did you enable auto-completion of the code?

**Comment by hatalmasalma** [comment]
Seems like autocompletion is extremely basic, and only completes names from the currently edited file by pressing Ctrl+Space (if I remember correctly)

Since then I moved on from OpenScad because the rendering times became unbearable even in my simple projects.

**Comment by pca006132** [comment]
@hatalmasalma you can give the development snapshot a try, just enable the `manifold` experimental feature and the rendering time should improve by a lot.
