### ISSUE TITLE
Editor reverts to light theme on every start

### ISSUE THREAD

**Issue by korpx** [openscad/openscad#4920]
Editor reverts to light theme on every start

1. Start OpenSCAD
2. Click on 'Edit'-menu, 'Preferences', 'Editor'
3. Change 'Color syntax highlighting:' to 'For Dark Background'
4. Exit OpenSCAD
5. Start OpenSCAD
6. 'Color syntax highlighting:' has reverted to 'For Light Background'

Expected behavior;
'Color syntax highlighting:' stays permamently set.

Screenshots;
![image](https://github.com/openscad/openscad/assets/1850308/75fb92a1-906b-4cab-a77b-d15fb8b19e4c)

OpenSCAD Version: 2024.01.03 (git b1160fa43)
System information: Microsoft Windows 10 (10.0.19045) x86_64 4 CPUs 15.88 GB RAM
User Agent: OpenSCAD/2024.01.03 (git b1160fa43) (Microsoft Windows 10 (10.0.19045) x86_64)

**Comment by korpx** [comment]
Even if I import this before start the setting is reverted;

Windows Registry Editor Version 5.00

[HKEY_CURRENT_USER\SOFTWARE\OpenSCAD\OpenSCAD\editor]
"syntaxhighlight"="For Dark Background"

**Comment by SongZihui-sudo** [comment]
You can try editing in vscode, it works fine

**Comment by korpx** [comment]
The internal editor work fine too but this is a cosmetic bug introduced recently.

**Comment by kberkut** [comment]
On linux, the theme setting is also reset. The version is similar.

**Comment by Nikorasu** [comment]
Yup, this happens to every dev build I've tried after OpenSCAD-2023.12.28.ai17902-x86_64.AppImage, that was the last one that still kept it's Editor background setting.

**Comment by majekw** [comment]
Same here.
Os: Linux Slackware 15.0.
It works ok on OpenSCAD-2023.11.14.ai16996-x86_64.AppImage
Color settings is lost on startup on OpenSCAD-2024.02.11.ai18430-x86_64.AppImage

**Comment by korpx** [comment]
Still happens with 2024.02.22 (Windows 10 22H2)

**Comment by t-paul** [comment]
Fixed via #5026.
