### ISSUE TITLE
Manifold doesn't support Minkowskis convexity

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#4934]
Version 2024.01.03

code:
```
difference(){
  minkowski(convexity=5){
    difference(){
      cylinder(10,d=15);
      cylinder(30,d=14,center=true);
    }
    sphere(.5);
  }
  cube(100);
}
```
results in 
![image](https://github.com/openscad/openscad/assets/93376232/4b7c4c29-892d-4884-b2eb-511db9d6347f)

**Comment by jordanbrown0** [comment]
It it's helpful, I think the convexity of a Minkowski sum is likely limited to the sum of the convexities of the individual operands, so it may be possible to do something reasonable by default.

**Comment by pca006132** [comment]
I think the implementation forgot to propagate the convexity parameters. I wonder if we have the same issue with fast-csg as well.
