### ISSUE TITLE
How do I deal with "distutils" being deprecated (?) with macos build?

### ISSUE THREAD

**Issue by Jimw338** [openscad/openscad#4947]
I'm trying to compile from source on Apple Silicon osx, and failing when it runs into "distutils".  Suggestions for how to get around this all use things that osx doesn't have (apt-get, pip, etc).  Any ideas?

**Comment by t-paul** [comment]
As you are not saying what exactly you are compiling, I'm assuming it's the release version and DEV has that fixed via
https://github.com/openscad/openscad/commit/cca602ed16c76d2b10286349308a67ed75e3773e

**Comment by kintel** [comment]
Closing as fixed by https://github.com/openscad/openscad/commit/cca602ed16c76d2b10286349308a67ed75e3773e. Please reopen with more information if you experience the same on current master.
