### ISSUE TITLE
Port to iPadOS / iOS

### ISSUE THREAD

**Issue by dwt** [openscad/openscad#4952]
**Is your feature request related to a problem? Please describe.**
I would like to preview and work on OpenSCAD files on the go. Working with a keyboard can actually be quite comfortable on iPadOS and iOS, thus I would like to try it for an ultra light computing device.

**Describe the solution you'd like**
An OpenSCAD renderer, that either includes its own text editor, or uses directory or file sharing, to use the text editor of another application would be ideal. Especially if an external editor is used, I would hope that the port could be relatively simple.

**Describe alternatives you've considered**
I've tried installing it in ish, an x86 emulator that runs Linux, but was not able to get that environment stable. Using it in a-shell could be nice, but is probably too niche to bundle it there.

**Additional context**
None

**Comment by t-paul** [comment]
This is impossible with current AppStore rules. It remains to be seen if the latest actions in EU have a chance of changing that.

**Comment by Scopeuk** [comment]
an alternative may be one of the webasm ports, I believe safari should support running these implementations. one example is https://ochafik.com/openscad2

**Comment by dwt** [comment]
Oh sad, I was under the impression that those problems have long been resolved. Ah damn. That leaves distribution through tools like the [alt store](https://altstore.io), which is way less popular, but free of restrictions.

**Comment by t-paul** [comment]
I have not heard about any issues being resolved, but maybe I missed that. I'll have another look. It's probably still a big project limited by Apple restricting development to Apple hardware, so I'm out. So the web version seems to have a much higher chance of becoming a viable option.

**Comment by kintel** [comment]
Closing as infeasible. A web version is likely the best alternative for mobile usage.

**Comment by jordanbrown0** [comment]
https://www.fsf.org/blogs/licensing/more-about-the-app-store-gpl-enforcement
seems like an authoritative statement of why GPL-licensed software can't be distributed through the Apple app store.

**Comment by jesseditson** [comment]
Hey! I'm an iOS developer, and I'm curious if anyone has tried building this to a local device. I don't need an App Store version, and due to lack of Apple Silicon support on the current release I build OpenSCAD from source anyway. I'll give it a try, but curious if there's any prior art I should be aware of. I have not tried building a Qt project on iOS before.

**Comment by t-paul** [comment]
The dev snapshot has full support for Apple Silicon. I can't comment on the Qt topic.

**Comment by kintel** [comment]
Qt might be a challenge, but we also require desktop OpenGL which isn't available on iOS. The OpenGL issue will eventually be resolved, but not quite yet..

**Comment by eduo** [comment]
> Helpful, thank you!

Hello! Did you ever get further on this?

I'm in the same boat. The App Store is a red herring since openscad for Mac isn't in the Mac App Store either. Many who would use openscad wouldn't have a problem compiling locally and/or sideloading.

I know I wouldn't. Qt would be less of a problem than OpenGL if porting, though.

**Comment by jesseditson** [comment]
I ended up making the VSCode plugin support inline previews (https://github.com/Leathong/openscad-support-vscode/pull/36) and VSCode Server to run a remote session on my iPad, which unblocked for the project I was working on - I still think this would be worth pursuing, if only for offline editing.
