### ISSUE TITLE
OpenCSG difference does not work if you view from inside the subtrahend object.

### ISSUE THREAD

**Issue by nophead** [openscad/openscad#496]
If you subtract a large cube from something it only works if the viewpoint is outside the cube. E.g.

```
difference() {
    cube(20, center = true);
    cube(1000, 1000, 1000);
}
```

It seems like the large cube gets culled because the front of it is in front of the clip plane but the back is still relevant to the difference.
##

**Comment by kintel** [comment]
This does behave as expected; don't think there is much actionable here
