### ISSUE TITLE
crash when trying to export stl

### ISSUE THREAD

**Issue by DraconPern** [openscad/openscad#4981]
**Describe the bug**
Program exits and windows disappears.

**To Reproduce**
1. Install [OpenSCAD](https://www.openscad.org/) version 2024.02.04 (git f3de51827)
2. Open the files here https://www.printables.com/model/757297-gridfinity-rugged-storage-box-parametric-and-custo/files
3. Change Part to 'Bottom'
4. F6 to render
5. F7 to export stl
6. Program disappears. No warning, no error pop up. Main window just poofs.

**Expected behavior**
Not crash

**Code reproducing the issue**
cube(10); works.  
fast-csg, fast-csg-safer, manifold are turned on

**Screenshots**

**Environment and Version info (please complete the following information):**
 - OS: Windows 10
 - System: Intel PC 64-bit
 - OpenSCAD Version 2024.02.04 (git f3de51827)

**Library & Graphics card information**
OpenSCAD Version: 2024.02.04 (git f3de51827)
System information: Microsoft Windows 10 (10.0.19045) x86_64 20 CPUs 63.82 GB RAM
User Agent: OpenSCAD/2024.02.04 (git f3de51827) (Microsoft Windows 10 (10.0.19045) x86_64)
Compiler: GCC "13.2.0" 64bit
MinGW build: MingW64
Debug build: No
Boost version: 1_81
Eigen version: 3.4.0
CGAL version, kernels: 5.5, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.5.0
Qt version: 5.15.11
QScintilla version: 2.11.2
InputDrivers: 
GLib version: 2.70.2
lodepng version: 20210627
libzip version: 1.5.2
fontconfig version: 2.14.2
freetype version: 2.13.2
harfbuzz version: 7.3.0
cairo version: 1.16.0
lib3mf version: 1.8.1
Features: fast-csg*, fast-csg-safer*, fast-csg-debug, manifold, roof, input-driver-dbus, lazy-union, vertex-object-renderers, vertex-object-renderers-indexing, textmetrics, import-function, predictible-output
Application Path: C:/Program Files/Openscad
Documents Path: C:\Users\DraconPern\Documents
User Documents Path: C:\Users\DraconPern\Documents
Resource Path: C:/Program Files/Openscad
User Library Path: C:/Users/DraconPern/Documents/OpenSCAD/libraries
User Config Path: C:\Users\DraconPern\AppData\Local/OpenSCAD
Backup Path: C:/Users/DraconPern/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
C:/Users/DraconPern/Documents/OpenSCAD/libraries
C:/Program Files/Openscad\libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
C:/WINDOWS/fonts
C:/Users/DraconPern/AppData/Local/Microsoft/Windows/Fonts
C:/Users/DraconPern/.local/share/fonts
C:/usr/local/share/fonts
C:/usr/share/fonts
C:/usr/X11/lib/X11/fonts
C:/System/Library/Fonts
C:/Library/Fonts
C:/Users/DraconPern/Library/Fonts
GLEW version: 2.1.0
OpenGL Version: 4.6.0 NVIDIA 536.23
GL Renderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
GL Vendor: NVIDIA Corporation
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(8888), depth(24), stencil(8)

GL Extensions:
GL_AMD_multi_draw_indirect
GL_AMD_seamless_cubemap_per_texture
GL_AMD_vertex_shader_layer
GL_AMD_vertex_shader_viewport_index
GL_ARB_ES2_compatibility
GL_ARB_ES3_1_compatibility
GL_ARB_ES3_2_compatibility
GL_ARB_ES3_compatibility
GL_ARB_arrays_of_arrays
GL_ARB_base_instance
GL_ARB_bindless_texture
GL_ARB_blend_func_extended
GL_ARB_buffer_storage
GL_ARB_clear_buffer_object
GL_ARB_clear_texture
GL_ARB_clip_control
GL_ARB_color_buffer_float
GL_ARB_compatibility
GL_ARB_compressed_texture_pixel_storage
GL_ARB_compute_shader
GL_ARB_compute_variable_group_size
GL_ARB_conditional_render_inverted
GL_ARB_conservative_depth
GL_ARB_copy_buffer
GL_ARB_copy_image
GL_ARB_cull_distance
GL_ARB_debug_output
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_derivative_control
GL_ARB_direct_state_access
GL_ARB_draw_buffers
GL_ARB_draw_buffers_blend
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_indirect
GL_ARB_draw_instanced
GL_ARB_enhanced_layouts
GL_ARB_explicit_attrib_location
GL_ARB_explicit_uniform_location
GL_ARB_fragment_coord_conventions
GL_ARB_fragment_layer_viewport
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_fragment_shader_interlock
GL_ARB_framebuffer_no_attachments
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_geometry_shader4
GL_ARB_get_program_binary
GL_ARB_get_texture_sub_image
GL_ARB_gl_spirv
GL_ARB_gpu_shader5
GL_ARB_gpu_shader_fp64
GL_ARB_gpu_shader_int64
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_indirect_parameters
GL_ARB_instanced_arrays
GL_ARB_internalformat_query
GL_ARB_internalformat_query2
GL_ARB_invalidate_subdata
GL_ARB_map_buffer_alignment
GL_ARB_map_buffer_range
GL_ARB_multi_bind
GL_ARB_multi_draw_indirect
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_occlusion_query2
GL_ARB_parallel_shader_compile
GL_ARB_pipeline_statistics_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_polygon_offset_clamp
GL_ARB_post_depth_coverage
GL_ARB_program_interface_query
GL_ARB_provoking_vertex
GL_ARB_query_buffer_object
GL_ARB_robust_buffer_access_behavior
GL_ARB_robustness
GL_ARB_sample_locations
GL_ARB_sample_shading
GL_ARB_sampler_objects
GL_ARB_seamless_cube_map
GL_ARB_seamless_cubemap_per_texture
GL_ARB_separate_shader_objects
GL_ARB_shader_atomic_counter_ops
GL_ARB_shader_atomic_counters
GL_ARB_shader_ballot
GL_ARB_shader_bit_encoding
GL_ARB_shader_clock
GL_ARB_shader_draw_parameters
GL_ARB_shader_group_vote
GL_ARB_shader_image_load_store
GL_ARB_shader_image_size
GL_ARB_shader_objects
GL_ARB_shader_precision
GL_ARB_shader_storage_buffer_object
GL_ARB_shader_subroutine
GL_ARB_shader_texture_image_samples
GL_ARB_shader_texture_lod
GL_ARB_shader_viewport_layer_array
GL_ARB_shading_language_100
GL_ARB_shading_language_420pack
GL_ARB_shading_language_include
GL_ARB_shading_language_packing
GL_ARB_shadow
GL_ARB_sparse_buffer
GL_ARB_sparse_texture
GL_ARB_sparse_texture2
GL_ARB_sparse_texture_clamp
GL_ARB_spirv_extensions
GL_ARB_stencil_texturing
GL_ARB_sync
GL_ARB_tessellation_shader
GL_ARB_texture_barrier
GL_ARB_texture_border_clamp
GL_ARB_texture_buffer_object
GL_ARB_texture_buffer_object_rgb32
GL_ARB_texture_buffer_range
GL_ARB_texture_compression
GL_ARB_texture_compression_bptc
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_cube_map_array
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_filter_anisotropic
GL_ARB_texture_filter_minmax
GL_ARB_texture_float
GL_ARB_texture_gather
GL_ARB_texture_mirror_clamp_to_edge
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_multisample
GL_ARB_texture_non_power_of_two
GL_ARB_texture_query_levels
GL_ARB_texture_query_lod
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_texture_rgb10_a2ui
GL_ARB_texture_stencil8
GL_ARB_texture_storage
GL_ARB_texture_storage_multisample
GL_ARB_texture_swizzle
GL_ARB_texture_view
GL_ARB_timer_query
GL_ARB_transform_feedback2
GL_ARB_transform_feedback3
GL_ARB_transform_feedback_instanced
GL_ARB_transform_feedback_overflow_query
GL_ARB_transpose_matrix
GL_ARB_uniform_buffer_object
GL_ARB_vertex_array_bgra
GL_ARB_vertex_array_object
GL_ARB_vertex_attrib_64bit
GL_ARB_vertex_attrib_binding
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_vertex_type_10f_11f_11f_rev
GL_ARB_vertex_type_2_10_10_10_rev
GL_ARB_viewport_array
GL_ARB_window_pos
GL_ATI_draw_buffers
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXTX_framebuffer_mixed_formats
GL_EXT_Cg_shader
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_compiled_vertex_array
GL_EXT_depth_bounds_test
GL_EXT_direct_state_access
GL_EXT_draw_buffers2
GL_EXT_draw_instanced
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_multisample_blit_scaled
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_import_sync_object
GL_EXT_memory_object
GL_EXT_memory_object_win32
GL_EXT_multi_draw_arrays
GL_EXT_multiview_texture_multisample
GL_EXT_multiview_timer_query
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_packed_pixels
GL_EXT_pixel_buffer_object
GL_EXT_point_parameters
GL_EXT_polygon_offset_clamp
GL_EXT_post_depth_coverage
GL_EXT_provoking_vertex
GL_EXT_raster_multisample
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_semaphore
GL_EXT_semaphore_win32
GL_EXT_separate_shader_objects
GL_EXT_separate_specular_color
GL_EXT_shader_image_load_formatted
GL_EXT_shader_image_load_store
GL_EXT_shader_integer_mix
GL_EXT_shadow_funcs
GL_EXT_sparse_texture2
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture3D
GL_EXT_texture_array
GL_EXT_texture_buffer_object
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_latc
GL_EXT_texture_compression_rgtc
GL_EXT_texture_compression_s3tc
GL_EXT_texture_cube_map
GL_EXT_texture_edge_clamp
GL_EXT_texture_env_add
GL_EXT_texture_env_combine
GL_EXT_texture_env_dot3
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_filter_minmax
GL_EXT_texture_integer
GL_EXT_texture_lod
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_object
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_R8
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shadow_lod
GL_EXT_texture_shared_exponent
GL_EXT_texture_storage
GL_EXT_texture_swizzle
GL_EXT_timer_query
GL_EXT_transform_feedback2
GL_EXT_vertex_array
GL_EXT_vertex_array_bgra
GL_EXT_vertex_attrib_64bit
GL_EXT_win32_keyed_mutex
GL_EXT_window_rectangles
GL_IBM_rasterpos_clip
GL_IBM_texture_mirrored_repeat
GL_KHR_blend_equation_advanced
GL_KHR_blend_equation_advanced_coherent
GL_KHR_context_flush_control
GL_KHR_debug
GL_KHR_no_error
GL_KHR_parallel_shader_compile
GL_KHR_robust_buffer_access_behavior
GL_KHR_robustness
GL_KHR_shader_subgroup
GL_KTX_buffer_region
GL_NVX_blend_equation_advanced_multi_draw_buffers
GL_NVX_conditional_render
GL_NVX_gpu_memory_info
GL_NVX_gpu_multicast2
GL_NVX_linked_gpu_multicast
GL_NVX_multigpu_info
GL_NVX_nvenc_interop
GL_NVX_progress_fence
GL_NV_ES1_1_compatibility
GL_NV_ES3_1_compatibility
GL_NV_alpha_to_coverage_dither_control
GL_NV_bindless_multi_draw_indirect
GL_NV_bindless_multi_draw_indirect_count
GL_NV_bindless_texture
GL_NV_blend_equation_advanced
GL_NV_blend_equation_advanced_coherent
GL_NV_blend_minmax_factor
GL_NV_blend_square
GL_NV_clip_space_w_scaling
GL_NV_command_list
GL_NV_compute_program5
GL_NV_compute_shader_derivatives
GL_NV_conditional_render
GL_NV_conservative_raster
GL_NV_conservative_raster_dilate
GL_NV_conservative_raster_pre_snap
GL_NV_conservative_raster_pre_snap_triangles
GL_NV_conservative_raster_underestimation
GL_NV_copy_depth_to_color
GL_NV_copy_image
GL_NV_depth_buffer_float
GL_NV_depth_clamp
GL_NV_draw_texture
GL_NV_draw_vulkan_image
GL_NV_explicit_multisample
GL_NV_feature_query
GL_NV_fence
GL_NV_fill_rectangle
GL_NV_float_buffer
GL_NV_fog_distance
GL_NV_fragment_coverage_to_color
GL_NV_fragment_program
GL_NV_fragment_program2
GL_NV_fragment_program_option
GL_NV_fragment_shader_barycentric
GL_NV_fragment_shader_interlock
GL_NV_framebuffer_mixed_samples
GL_NV_framebuffer_multisample_coverage
GL_NV_geometry_shader4
GL_NV_geometry_shader_passthrough
GL_NV_gpu_multicast
GL_NV_gpu_program4
GL_NV_gpu_program4_1
GL_NV_gpu_program5
GL_NV_gpu_program5_mem_extended
GL_NV_gpu_program_fp64
GL_NV_gpu_shader5
GL_NV_half_float
GL_NV_internalformat_sample_query
GL_NV_light_max_exponent
GL_NV_memory_attachment
GL_NV_memory_object_sparse
GL_NV_mesh_shader
GL_NV_multisample_coverage
GL_NV_multisample_filter_hint
GL_NV_occlusion_query
GL_NV_packed_depth_stencil
GL_NV_parameter_buffer_object
GL_NV_parameter_buffer_object2
GL_NV_path_rendering
GL_NV_path_rendering_shared_edge
GL_NV_pixel_data_range
GL_NV_point_sprite
GL_NV_primitive_restart
GL_NV_primitive_shading_rate
GL_NV_query_resource
GL_NV_query_resource_tag
GL_NV_register_combiners
GL_NV_register_combiners2
GL_NV_representative_fragment_test
GL_NV_sample_locations
GL_NV_sample_mask_override_coverage
GL_NV_scissor_exclusive
GL_NV_shader_atomic_counters
GL_NV_shader_atomic_float
GL_NV_shader_atomic_float64
GL_NV_shader_atomic_fp16_vector
GL_NV_shader_atomic_int64
GL_NV_shader_buffer_load
GL_NV_shader_storage_buffer_object
GL_NV_shader_subgroup_partitioned
GL_NV_shader_texture_footprint
GL_NV_shader_thread_group
GL_NV_shader_thread_shuffle
GL_NV_shading_rate_image
GL_NV_stereo_view_rendering
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_NV_texture_compression_vtc
GL_NV_texture_dirty_tile_map
GL_NV_texture_env_combine4
GL_NV_texture_multisample
GL_NV_texture_rectangle
GL_NV_texture_rectangle_compressed
GL_NV_texture_shader
GL_NV_texture_shader2
GL_NV_texture_shader3
GL_NV_timeline_semaphore
GL_NV_transform_feedback
GL_NV_transform_feedback2
GL_NV_uniform_buffer_std430_layout
GL_NV_uniform_buffer_unified_memory
GL_NV_vertex_array_range
GL_NV_vertex_array_range2
GL_NV_vertex_attrib_integer_64bit
GL_NV_vertex_buffer_unified_memory
GL_NV_vertex_program
GL_NV_vertex_program1_1
GL_NV_vertex_program2
GL_NV_vertex_program2_option
GL_NV_vertex_program3
GL_NV_viewport_array2
GL_NV_viewport_swizzle
GL_OVR_multiview
GL_OVR_multiview2
GL_S3_s3tc
GL_SGIS_generate_mipmap
GL_SGIS_texture_lod
GL_SGIX_depth_texture
GL_SGIX_shadow
GL_SUN_slice_accum
GL_WIN_swap_hint
WGL_EXT_swap_control

**Additional context**

**Comment by DraconPern** [comment]
I did a clean install to make sure there wasn't any left over from previous install.  Couldn't find how to reset user setting so I don't know if that affects anything.

**Comment by kintel** [comment]
Could try try disabling all the fast-csg options and enable just `manifold` instead?
fast-csg and manifold are mutually exclusive, but we don't currently have a good way of surfacing that in the GUI.

**Comment by MWStonton** [comment]
Can't add to detail (other than also on macOS, 14.3, M2) having seen the same thing once in the last couple of days with recent dev. snapshot. Didn't record details as it was fine after restarting OpenSCAD. Was probably switching between rendering methods as I use manifold for speed while iterating design but often have to use older rendering methods before exporting as stl for many designs to prevent my slicer (for 3D print) finding errors.

**Comment by pca006132** [comment]
what is the error in your slicer when the design is rendered with manifold?

**Comment by MWStonton** [comment]
@pca006132 Not sure at the moment - just says there's an error with options to correct, close or ignore. Not obvious to me (haven't spotted visually if I ignore) what it is at the moment - when I get a spare moment I'll have a play with the design and try to find out which sections cause the issue and then see if it is obvious if ignored in the slicer. (Slicer is Flashforge FlashPrint). The design uses offset, lots of text, difference and intersections.

**Comment by pca006132** [comment]
Sure, you can open an issue when you find a reproducible example. I think it is a manifoldness issue.

**Comment by MWStonton** [comment]
I was thinking the same (had it in my mind (thought I remembered a message along the lines of  "design (rendered using manifold) is not manifold" which made me smile - maybe an older version of the slicer did say more. I assumed manifold was still a work in progress and so just worked around it for now. If I can spend a little time this evening and at least narrow down which part of the design is the issue and it may help with development, then I'll post it as a new issue

**Comment by pca006132** [comment]
@MWStonton Do note that this is usually issue on openscad side, e.g. some primitives did not guarantee manifoldness. There were some changes recently regarding that, so it may fix the issue and you will not be able to reproduce it with recent versions :)

**Comment by MWStonton** [comment]
@pca006132 I had reduced the code down to what created the issue for me and it was a difference where the original and part to be removed should be identical on one face (which was a cylinder and removing text which was shaped using intersection to the same thing on the outer face). I tried it this morning with the same version of OpenSCAD and same code and it doesn't fail (though the original "full" code it came from does).
This is an image of the text after render showing a sliver of material left over through the vertical of the "T". I assume the error might relate to that?
![Manifold_slicer_issue](https://github.com/openscad/openscad/assets/151874781/b00af8dd-ab37-43e5-b2ec-c13f1dd1c536)
I have done similar things with added proud text where I overlap with the cylinder a little and I believe if I make the text to remove slightly bigger than the cylinder for the cut in, it works o.k. I did try a radius bigger by 0.001 and it seemed to fix things but 0.000001 didn't fix it.

**Comment by pca006132** [comment]
It is for both input and output, STL does not preserve manifoldness. Yeah you should use 3mf when possible. For now, openscad does not preserve manifoldness when using 3mf as *input*, but it should not matter in your case.

**Comment by gsohler** [comment]
pca006132,

can you quickly explain:

why is manifoldness lost when using stl ? (is it two cubes touching at one
corner only and its not clear which solid the corner belongs to ) ?

why is 3mf better than stl in this respect ?

Thank you for answering curious questions :)

**Comment by pca006132** [comment]
@gsohler 

> is it two cubes touching at one corner only and its not clear which solid the corner belongs to

Yes, this is an example. We care about how the vertices are connected, and collapsing vertices when the position of them are the same will lose this topology information, thus losing manifoldness.

> why is 3mf better than stl in this respect ?

STL only store triangles as coordinate triples, so you cannot distinguish two vertices if they have the same coordinate. However, 3MF stores vertex position and connection information separately, so the topology information is not lost.

**Comment by grufkork** [comment]
Can confirm having the same issue, using Manifold. OBJ export works as expected, STL crashes, producing malformed file. [2024.02.11]

**Comment by MWStonton** [comment]
re: stl export error
I've tried a couple of files just exporting and re-exporting and seen no error (overwriting the same stl file, or creating a new one) BUT if I edit the design scad file  (I use an external editor), let OpenSCAD pick up the changes and re-preview and then manually render and re-export then the crash is quite common. I believe it happens whether the stl file is a new one or overwritten.

**Comment by gsohler** [comment]
Yes , two cubes touching in one coordinate is really a very
interesting scenario. You can think of two separate objects.
But at the same time, you could also vision one object with a micro
connection formed from 6 faces which form a ring and are perpendicular to
each other.

If you read that in double-cube stl and look at the special coordinate, you
will find, that it's used by 6 faces.
Running the faces-around-corner algorithm, you will easily find out, that
there are 2 chains, thus two objects . Easy task to duplicate the vertex
and share evenly between the objects.
This could easily done  in the end of import_stl without big time expense.
After that I don't see this disadvantage over 3mf anymore.

**Comment by pca006132** [comment]
Yes it can be done, but it is not as simple and you can write a paper about it (Cutting and stitching: converting sets of polygons to manifold surfaces), and the implementation is not trivial as well, we are currently using CGAL's implementation and porting it takes a lot of time. Another issue is that slicers don't implement this, so you will get warnings in slicers.

Regarding disadvantage over 3mf, the only task for stl is to represent a single 3D object, and it cannot do it without the help of some mesh fixing algorithm, so I cannot see the advantage of stl, apart from the weird popularity...

**Comment by gsohler** [comment]
I understand your argument that it takes a lot of time to port
CGALS's implementation.  CGAL has the same score in Versatility and
Obfuscation.
But i am wondering why you need an any cutting and sticking of faces when
doing vertex separation of  a manifold stl input ?(this means that no faces
would intersect others nor there any points below surface)(apart from
inside negative volumes)
When you first create a edge mapping database(which face index is opposite
of an edge (specified by 2 vertices),
then it's just an O(N) task to find out if two or more vertices share the
same coordinate. I have done that before.

Even though nobody here appears to like STL I can think of quite some
reasons for its weird popularity
* its an very old format
* very established, everybody knows it
* its very simple, can easily be read and written

Not as easy to create 3mf. it is zipped and contains (few) different files
which need to be in sync to each other.
And many people put several objects into one STL when they share a design
with many parts readily placed for printing.
Even though the STL spec does not specify that STL can contain several
objects, its easily doable, practical, works well
and probably many people will cry if this got forbidden 🤣

**Comment by pca006132** [comment]
It is one thing that you can find out the vertex that requires duplication, figuring out how to split the vertex into two (which face got which) is another issue. This is the reason why we need to find a cut. If you think it is a simple thing to do, you are welcome to submit a PR to manifold for that...

And I am not here to argue about why STL is a bad format nor I want to make it obsolete in openscad, I just want to point out that if users get manifoldness issue when importing stl into a slicer, they can just use 3mf. Whether or not writing stl/3mf by hand is easy is not of my concern.

I think we should not continue this thread here, free to open another thread to discuss about manifoldness issues. I think we are distracting the discussion here.

**Comment by nophead** [comment]
STL works fine for my uses and the slicer I use doesn't accept any more recent formats. It can't represent anything with self intersections but I don't count those as real object that can be printed. The main problem is OpenSCAD snaps vertices to a grid and that can cause self intersection and break STL export even if the solid has no self intersections and could be represented in S TL. The only time STL format cause a problem is if the vertices are separated by less that the resolution of a float but that is many orders  magnitude less that the OpenSCAD grid.

**Comment by gsohler** [comment]
I believe the reason why openscad snaps vertices to a grid is to find out
quickly, if two imported coordinates are meant to be the same.
But there are better approaches.
We could code a map function like:

space[3d-coordinate ] = information

when the underlying data is stored as a binary tree(actually octant ) its
pretty easy to quickly find out, how many/much information is stores at a
coordinate+search sphere-radius
I got code for that, when interested.

**Comment by jordanbrown0** [comment]
> The only time STL format cause a problem is if the vertices are separated by less that the resolution of a float but that is many orders magnitude less that the OpenSCAD grid.

Not "many".  The OpenSCAD grid is around 10^-6 or 10^-7 (I have seen somebody say it's at 2^-20).  A single-precision float, as used in STL, is only good for about 7 digits.  The OpenSCAD grid appears to be absolute, while the ~7 digits of 32-bit floating point are relative to the size of the value.  If you're working with values around 100, the grid might well be smaller than the resolution of a float.

OpenSCAD arithmetic is 64-bit float, but STL is 32-bit float.

---

Grid snap is not just about imports; it's visible even with normal primitives.  I am told that without it vertices that are supposed to be identical drift apart and cause problems.  That shouldn't apply to "simple" cases where two vertices start the same and are transformed the same, but it might be an issue for cases where two vertices are derived through different paths and mathematically *should* be the same.

**Comment by jordanbrown0** [comment]
> Yeah so I guess this is a known issue :)

Remember that the original complaint is that the application crashed, poof, gone, not merely artifacts or a CGAL error.  That's a different class of problem.

**Comment by pca006132** [comment]
@jordanbrown0 yeah I am replying to the issue @MWStonton mentioned, not to the original post. And I suggest not to clutter this thread more...

**Comment by kintel** [comment]
Thanks @pca006132 for spotting a (in retrospect) painfully obvious bug!
