### ISSUE TITLE
Some preferences are reset when program starts

### ISSUE THREAD

**Issue by StarkRG** [openscad/openscad#4992]
**Describe the bug**
Though the settings are, indeed, saved to the config file, the editor's "color syntax highlighting" option is set to "For Light Background" the next time the app is loaded (and the config file is updated to match). The window state is also reset. I haven't come across any other settings that are reset (font size, for example, is correctly loaded) 

**To Reproduce**
1. Start program and open Preferences
3. Set "Color syntax highlighting" in "Editor" tab to something other than "For Light Background"
4. Close preferences and program (optionally check config file to make sure the change has been saved)
6. Start program again and note that the editor's colors have reverted to "For Light Background"

**Expected behavior**
Previously saved preferences should be loaded and honored

**Environment and Version info (please complete the following information):**
 - OS: Pop!_OS 22.04 LTS (based on Ubuntu 22.04)
 - System: Intel PC 64-bit
 - [OpenSCAD](https://www.openscad.org/) version 2024.02.11.ai18430 (git dd2da9e29) appimage from openscad.org

**Comment by MS3FGX** [comment]
I can confirm the same issue using the 2024.02.26 development snapshot AppImage on Linux. Not only does the editor color scheme revert to "For Light Background", but if you check the config file before and after starting OpenSCAD, you can see that the "syntaxhighlight" option appears to be overwritten on startup.

![scad_bg](https://github.com/openscad/openscad/assets/1843361/b147d94b-987a-4a6a-a0c8-c53688ef1607)
