### ISSUE TITLE
assigned values aren't accessible by child()

### ISSUE THREAD

**Issue by brad** [openscad/openscad#50]
I wrote about this to the mailing list, but noone replied. Maybe it will get more attention here.

I tried doing something like this:

module test() {
&nbsp;&nbsp;&nbsp;&nbsp;assign(variable=1) child();
}

test() cube(variable);

and found that OpenSCAD complained about not knowing what variable is.
Shouldn't variable be known to the child? Otherwise the assign really isn't doing anything.
##

**Comment by kintel** [comment]
Closing as expected behavior; variables are lexically scoped. For dynamically scoped variables, use `$variable`
