### ISSUE TITLE
echo("%0") critical error

### ISSUE THREAD

**Issue by Elektrostraka** [openscad/openscad#5039]
Critical error at command:
echo("%0");
when preview.
Error description: A critical error was caught. The application may have become unstable:boost::bad_format_string: format-string is ill-formed.

Should not fall to critical error.
OpenSCAD version: 2021.01
OS Windows 10
 - OpenSCAD Version [e.g. 2021.01, 2023.04.16] and where it was installed from

**Comment by jordanbrown0** [comment]
Fixed in 2ca8d5e6edc10b05ced3f6c060238bd32a626817.  (Was a typical error of using the thing to be printed as the format string, rather than having a fixed format string that printed that value.)
