### ISSUE TITLE
Générer du code avec ChatGPT

### ISSUE THREAD

**Issue by vincent-olmos** [openscad/openscad#5044]
Il semble que ChatGPT soit peu fiable pour la génération de code OpenSCAD !
Copilot ne semble pas faire mieux.

**Comment by kintel** [comment]
Please use English for OpenSCAD discussions. This sounds like you're trying to report a weakness in ChatGPT, perhaps open an issue with OpenAI?

**Comment by vincent-olmos** [comment]
I'm French and it seems that ChatGPT is unreliable for OpenSCAD code generation!
Copilot doesn't seem to do any better.

**Comment by jordanbrown0** [comment]
Yes, it is basically unusable.  It tends to put together mostly-legal programs that don't really have much to do with the shape requested.  But the OpenSCAD development team doesn't have any way to affect that picture.  I don't think even OpenAI can directly affect it.  My understanding of the technology is that nobody specifically taught it to write OpenSCAD programs; it learned on its own by reading web pages.

**Comment by vincent-olmos** [comment]
OpenAI est sensé apprendre tout seul !

**Comment by jordanbrown0** [comment]
> OpenAI is supposed to learn on its own!

Yep.  Not much we can do about it, other than write OpenSCAD programs and post them on the web for it to see.
