### ISSUE TITLE
Highlight negative regions when rendering using Manifold

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#5047]
When using the (default) CGAL Nef polyhedron backend, F6 rendering results in "negative surfaces" (cutouts) being rendering in a different color. We should implement the same for the Manifold backend.

Example for a difference between a sphere and a cube:
<img width="452" alt="Screenshot 2024-03-16 at 19 43 01" src="https://github.com/openscad/openscad/assets/186094/a310e39a-1ab9-4ec5-99cf-b61b549c4429">

A similar feature is demoed on https://manifoldcad.org/#Tetrahedron%20Puzzle

A related opportunity with Manifold is to also support preserving `color()` in F6 rendering. A prototype has shown that this is doable in OpenSCAD. Keep that in mind when solving this ticket by making the rendering backend flexible enough to handle multiple colors.

**Comment by gsohler** [comment]
kintel, see this one

https://github.com/gsohler/openscad/blob/color/src/geometry/manifold/ManifoldGeometry.cc#L114-L117
triangle points runIndex[0-1] -> yellow
triangle points runIndex[2-3] -> green

**Comment by gsohler** [comment]
BTW my code is wrong
for(int i=0;i<mesh.runIndex.size()-1;i++) {

should be:

for(int i=0;i<mesh.runIndex.size();i+=2) {

**Comment by kintel** [comment]
Fixed by #5185
