### ISSUE TITLE
Quiet mode for command line

### ISSUE THREAD

**Issue by benhowes** [openscad/openscad#505]
I'm using openscad with makefiles from the command line a fair bit and it would certainly be handy to be able to turn off everything other than errors with a -q, or put them on stdout so I can pipe them to /dev/null or something.

I searched through the issues and didn't find this as one, sorry if there is.

Thanks!
##

**Comment by ChrisVesters** [comment]
Is this still revelant?

**Comment by benhowes** [comment]
It looks like #1343 closes this.
