### ISSUE TITLE
Poor transparency calculation for previewing extruded hollow shapes with holes cut into them

### ISSUE THREAD

**Issue by MethylBromide** [openscad/openscad#5060]
**Describe the bug**
When an extruded 2D shape with internal holes is perforated via the "difference" function, large portions of the remaining surface vanish from preview.

**To Reproduce**
1. Create a new SCAD file.
2. Paste in the below code and execute. The script creates two objects -- one is an extruded flat shape with an interior hole, and the other is the same shape with slots cut into it via the difference function.
3. Move the perspective around to see the issue. Depending on angle of view, large portions of the surface become transparent.

**Expected behavior**
This is a simple enough shape I would expect the preview and the rendered version to look nearly identical.

**Code reproducing the issue**
`/* [Hidden] */
$fa = 1;
$fs = 0.4;
for (slots=[false, true])
    translate([slots?40:0,0,0])
    difference() {
        linear_extrude(height=18) {
            difference() {
                offset(r=4) polygon([[15,0], [0,15], [-15,0], [0,-15]]);
                offset(r=3) polygon([[15,0], [0,15], [-15,0], [0,-15]]);
        }   }
        if (slots) {
            translate([0,0,-1]) cylinder(17, r=9);
            for(z=[1:3:13])
                translate([12,0,z]) cube([12,12,1], center=true);
        }
    }
`

**Screenshots**
![Screenshot_161](https://github.com/openscad/openscad/assets/12117008/04720059-a248-49d0-801c-f93cd9fa2fd7)
![Screenshot_162](https://github.com/openscad/openscad/assets/12117008/faac5dc5-b5e3-45ab-9efe-c5f99d5de42b)

**Environment and Version info (please complete the following information):**
 - OS: Windows 11.
 - System: Intel PC 64-bit
 - OpenSCAD Version: 2024.03.22 (git 968835698) from OpenSCAD website.

**Additional context**
This is severely impacting my ability to create complex models to post on Thingiverse for use with the Customizer, because huge swaths of my model turn into gaping holes in the preview. People can't see what they're getting.

**Comment by UBaer21** [comment]
`linear_extrude(height=18, convexity=5) `
Add the convexity parameter for correct preview display.

**Comment by t-paul** [comment]
See also https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/FAQ#preview-convexity
