### ISSUE TITLE
Linear_extrude with 3d vector as height yields inapropriate result

### ISSUE THREAD

**Issue by gsohler** [openscad/openscad#5079]
**Describe the bug**
height parameter of linear_extrude incorrecly used

**To Reproduce**

Use this code:

linear_extrude(height=[0,0,10]) square(1);

It always extrudes 100 for all vector values

**Expected behavior**
Either output an error or create oblique prism 

**Code reproducing the issue**

linear_extrude(height=[0,0,10]) square(1);

**Environment and Version info (please complete the following information):**
Windows version 2023.12.28 (git bdb7b78ac) and probably many others

**Library & Graphics card information**
If applicable, add the content of the Help->Library Info window, or the output of running the `openscad --info` command.

**Additional context**

I am happy that anybody with scad parsing experience addresses the bug

**Comment by kintel** [comment]
This is because there is no type checking. If the argument isn't a number, it will fall back to the default: https://github.com/openscad/openscad/blob/dfa7855cfa83958008c50ebf5a3a701e64ff22b9/src/core/LinearExtrudeNode.cc#L92

I expect this to be the case for a lot of built-in modules.

**Comment by gsohler** [comment]
interpreting the vector correctly could  open many possibilities ....

https://imgur.com/a/bJKjPAd

**Comment by jordanbrown0** [comment]
Looks to me like an error that isn't being detected and reported.
