### ISSUE TITLE
Character "degrees" not rendering

### ISSUE THREAD

**Issue by daackm** [openscad/openscad#5130]
Is there a way to get a degree symbol to display in a text function?  I have tried creating a string of chr(186) and printing that , but it gives something like a square.  Thanks

**Comment by MethylBromide** [comment]
I believe you are getting the right character code, but using a font (maybe the default font?) that doesn't contain an image for that character.

**Comment by t-paul** [comment]
Yes, try with this: `text(str("23", chr(186)), font = "Liberation Sans:style=Regular");`

<img src="https://github.com/openscad/openscad/assets/1330241/2d4f01cd-b772-4c45-abb6-7fe2092c5b82" width="600">

What Operating System are you using?

**Comment by daackm** [comment]
Thanks for the help.  I got it to work.  
 
I use OpenSCAD to design structures for model railroads.  I build front end programs which collect the design parameters for walls, roofing, windows and so forth, but was stuck on how to place text on a tool for designing a circus tent (visit http://daackm.github.io to see what I do).
 
I appreciate the information you shared with me.
 
Dave Ackmann

**Comment by daackm** [comment]
Thanks for the help.  I got it to work.  
 
I use OpenSCAD to design structures for model railroads.  I build front end programs which collect the design parameters for walls, roofing, windows and so forth, but was stuck on how to place text on a tool for designing a circus tent (visit http://daackm.github.io to see what I do).
 
I appreciate the information you shared with me.
 
Dave Ackmann

**Comment by t-paul** [comment]
Once the remaining issues are solved, #5114 will provide a way to filter for fonts having specific glyphs.
