### ISSUE TITLE
ERROR: The given mesh is not closed!

### ISSUE THREAD

**Issue by quiet-ranger** [openscad/openscad#5146]
**Describe the bug**
I get this error with a very simple polyhedron with 5 faces only and I am not sure how to fix it.

**To Reproduce**
1. Create a new file with the following contents:
```
module sample() {
    polyhedron(
        points=[
          [0,0,0],[0,4,0],[4,0,0],[0,0,10],[0,4,10],[4,0,10]
        ],
        faces=[[0,1,2],[3,4,5],[1,4,5,2],[0,1,4,3],[0,3,5,2]
      ]
    );
}

sample();
```
2. Save the file
2. Press F6 to Render
3. From menu select Design / Check Validity

**Expected behavior**
A more informative error of what exactly is wrong with the model

**Code reproducing the issue**
N/A

**Screenshots**
N/A

**Environment and Version info (please complete the following information):**
 - OS: Linux Mint 21.3
 - System: PC 64-bit
 - OpenSCAD Version 2021.01 installed via  `flatpak install openscad`

**Library & Graphics card information**
N/A

**Additional context**
N/A

**Comment by UBaer21** [comment]
try `faces=[ [0,2,1],[3,4,5],[2,5,4,1],[0,1,4,3],[0,3,5,2] ]`
With F12 you can see faces with wrong normal
