### ISSUE TITLE
textmetrics does not work from command line

### ISSUE THREAD

**Issue by ostat** [openscad/openscad#5150]
**Describe the bug**
the **Textmetics** function works when the UI is open but when executed from the command line it returns undefined.

**To Reproduce**
1. create a script that uses the **textmetrics** function
```js
textvalue = "sample text!!!!";
font = "Liberation:style=Bold";
fontSize = 6.5;
ver = version();
matrics = textmetrics(text=textvalue,size=fontSize,font=font);
echo(matrics=matrics, version=ver);

linear_extrude(5)
text(
  str(textvalue, " size='", matrics.size, "' version=", ver),
  size=fontSize,
  font=font);
```
3. Click render in the UI and see that the size is returned as expected.
![image](https://github.com/openscad/openscad/assets/2128234/0f537891-2898-4fca-99f4-38f95b52796d)
4. Create a script (in my example powershell) to run the above openscad script via the command line.
```ps
$script:ScadExePath = 'C:\Program Files\OpenSCAD\openscad.exe'
$script:SourceFolder = (Get-Item $MyInvocation.MyCommand.Source).Directory.FullName
$script:ScadScriptPath = Join-Path $SourceFolder 'test_text_length.scad'
$script:target = Join-Path $SourceFolder 'test_text_length.stl'

$args = ""
$args += "-o `"$($script:target)`""
$args += " $($script:ScadScriptPath)"

write-host $args

$executionTime = $args | Measure-Command { 
    write-host 'starting'
    $output = ''
    Start-Process $script:ScadExePath -ArgumentList $_ -wait | Tee-Object -Variable output
    Write-Host "done`r`n$($output)"
}
```
6. See that the text size is not rendered.
![image](https://github.com/openscad/openscad/assets/2128234/07b72595-784e-42e8-bd7f-f8530b371511)

**Expected behavior**
I expected to be able to get the text metrics while executing the script via the command line

**Environment and Version info (please complete the following information):**
 - OS: Windows 11
 - System: Intel PC 64-bit
 - OpenSCAD Version 2023.05.20 installed from official site

**Comment by t-paul** [comment]
It's flagged experimental, you need to `--enable textmetrics`.

**Comment by ostat** [comment]
> It's flagged experimental, you need to `--enable textmetrics`.

Thanks that worked.

```ps
$script:ScadExePath = 'C:\Program Files\OpenSCAD\openscad.exe'
$script:SourceFolder = (Get-Item $MyInvocation.MyCommand.Source).Directory.FullName
$script:ScadScriptPath = Join-Path $SourceFolder 'test_text_length.scad'
$script:target = Join-Path $SourceFolder 'test_text_length.stl'

$args = ""
$args += "-o `"$($script:target)`""
$args += " --enable textmetrics"
$args += " $($script:ScadScriptPath)"

write-host $args

$executionTime = $args | Measure-Command { 
    write-host 'starting'
    $output = ''
    Start-Process $script:ScadExePath -ArgumentList $_ -wait | Tee-Object -Variable output
    Write-Host "done`r`n$($output)"
}
```

![image](https://github.com/openscad/openscad/assets/2128234/8c730b1b-ee5f-43f9-8979-3401c7329197)

**Comment by jordanbrown0** [comment]
We should really un-experimental-ize it.
