### ISSUE TITLE
Rotate by 90° is not accurate

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#517]
Maybe it is caused by bad approximation of pi? But rotating the object by 90 degrees does not rotate the object exactly by 90 degrees.

See this (Note: updated example 2018-12-07)
``` c
difference() {
  cube(10,true);
    
  rotate([0,90,0]) 
      cube(10,true);
}
```

I know that pressing F5 would generate what I call Schrodinger's walls, but pressing F6 should render empty scene. Instead, this is produced:
<img width="512" alt="screen shot 2018-12-07 at 2 33 54 pm" src="https://user-images.githubusercontent.com/186094/49668772-28d01d00-fa2d-11e8-88d3-ef6bd9cd6061.png">

The following code will produce no output, as expected:

``` c
difference() {
  cube(10,true);
  cube(10,true);
}
```
##

**Comment by kintel** [comment]
This was fixed a good while ago, by making certain angles behave perfectly

**Comment by nophead** [comment]
How was this fixed? The code here: https://github.com/openscad/openscad/blob/2dc786bd5998c7e555c403d54d503e39e86abfef/src/transform.cc#L111 still looks inaccurate but the example above does seem to work now, so I am confused.

The user mode trig functions are now accurate but I can't see where they are used in openscad.

**Comment by kintel** [comment]
I remember there being lots of discussions and some work done, and the examples accompanying this ticket now works.

If someone can reproduce this with a newer OpenSCAD, feel free to reopen.

**Comment by kintel** [comment]
Thanks for the updated test - I've updated the description with the new example.

**Comment by nophead** [comment]
This is my latest user mode version, updated to take both an angle and a vector:
```
module rotate(a, v) 
{
    if(v == undef) {
        av = len(a) == undef ? [0, 0, a] : a;
        cx = cos(av[0]);
        cy = cos(av[1]);
        cz = cos(av[2]);
        sx = sin(av[0]);
        sy = sin(av[1]);
        sz = sin(av[2]);
        multmatrix([
          [ cy * cz, cz * sx * sy - cx * sz, cx * cz * sy + sx * sz, 0],
          [ cy * sz, cx * cz + sx * sy * sz,-cz * sx + cx * sy * sz, 0],
          [-sy,      cy * sx,                cx * cy,                0],
          [ 0,       0,                      0,                      1]
        ]) children();
    }
    else { // formula from wikipedia transposed.
        s = sin(a);
        c = cos(a);
        C = 1 - c;
        m = sqr(v.x) + sqr(v.y) + sqr(v.z); // m used instead of norm to avoid irrational roots as much as possible
        u = v / sqrt(m);
        multmatrix([
          [ C * v.x * v.x / m + c,       C * u.y * u.x     + u.z * s, C * u.z * u.x     - u.y * s, 0],
          [ C * u.x * u.y     - u.z * s, C * v.y * v.y / m + c,       C * u.z * u.y     + u.x * s, 0],
          [ C * u.x * u.z     + u.y * s, C * u.y * u.z     - u.x * s, C * v.z * v.z / m + c,       0],
          [ 0,                        0,                           0,                              1]
        ]) children();
    }
}
```
I had some fun getting rotating around a diagonal of a cube by multiples of 120 accurate because of sqrt(3) in the norm.

If people think it looks correct I could have a go at integrating into OpenSCAD in place of the Eigen calls.

**Comment by kintel** [comment]
Hard to say if it's correct, but it should easy to write a bunch of tests, and e.g. compare that all values are within some epsilon of the Eigen equivalent.

**Comment by GilesBathgate** [comment]
I think the issue with Eigen is that its using floats (doubles?) so there is always going to be some roundoff error, so unless you use a Quotient based number system (such as gmpq) you are not going to get a perfect rotation. Furthermore sin/cos/tan are irrational functions so can't even represent the results of them using quotients. I believe my suggestion of clamping special cases to specific constants (such as 90°) is a bit of a hack, but if its applied it should be applied consistently.

**Comment by nophead** [comment]
Yes the trig functions exported to the user have hacks for all the common angles, they just aren't used inside OpenSCAD itself. Anywhere degrees are converted to radians should use the trig functions that take degrees instead. Radians cannot express any angle accurately on a computer because PI is transcendental.

**Comment by hroncok** [comment]
FWIW I don't see this behavior any more with OpenSCAD 2019.05 with CGAL 5.0.2.

**Comment by GilesBathgate** [comment]
@hroncok 
>This was fixed a good while ago, by making certain angles behave perfectly

Or are you saying that the fix has regressed, and you are now seeing the original issue again?

**Comment by hroncok** [comment]
I am saying this can be closed.
