### ISSUE TITLE
STL Export : what is wrong with this mesh rabbit?

### ISSUE THREAD

**Issue by SoMuchHope** [openscad/openscad#520]
Openscad version: 2013.06
OS: Windows 7

Hello !

another issue with STL render. 

I get the view on the mesh (display), but impossible to export it.

I get the following error message:
![issuerabbit](https://f.cloud.github.com/assets/5527418/1424692/9de4ea22-4023-11e3-888b-50166721cb56.png)

The mesh was done in Zbrush then fixed on Netfab cloud repair website. I do not understand what is wrong with that mesh :/

The mesh is there:

http://www.thingiverse.com/thing:173205

Thank you in advance to tell me what is wrong and if there is a method, how I could check the mesh (because netfab was OK),

Kind Regards,

John

**Comment by kintel** [comment]
The posted example has disappeared from Thingiverse - could you reupload if this is still an issue?

**Comment by kintel** [comment]
Closing as testdata isn't available
