### ISSUE TITLE
Color rendering: color() without arguments renders black with Manifold

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#5216]
This minimal example renders a black cube in render mode (both CGAL and Manifold), but a cube with default color in preview mode.
```
color() cube();
```

See also https://github.com/openscad/openscad/blob/master/tests/data/scad/3D/features/color-tests.scad

**Comment by UBaer21** [comment]
I assume replacing "undef" with black ([0,0,0]) is also the reason why  color(alpha=.5)color("blue"); works only in render but not in preview.  As alpha can be set without defining a color but can't overwrite existing alphas without defining also a color. Would be nice if that would be possible too.

**Comment by kintel** [comment]
@UBaer21 I think specifying a partial color was never intended, so if it works anywhere that's a coincidence :)
..but it's an interesting feature request. It's different from this issue though.
