### ISSUE TITLE
 Openscad-nightly 2024-07-19 does not draw picture anymore.

### ISSUE THREAD

**Issue by timonoko** [openscad/openscad#5236]
Openscad-nightly 2024-07-19 does not draw picture anymore.

Maybe because I have 2012-era graphics card.  [GeForce GTX 760] 

---
Confirmed. Works fine on newer machine.

**Comment by timonoko** [comment]
In Ubuntu 18.03 and Snap. So old machine with old operating system.  Not an issue Imho.

**Comment by t-paul** [comment]
Hmm, ok, that's a bit surprising. The "newer" version of OpenGL we need is still ancient. But it could be some incompatibility with the older drivers.

**Comment by kintel** [comment]
The only thing I can think of is that our VBO renderer inadvertently requires something that nVidia doesn't provide, or triggers a bug in the driver. If you build OpenSCAD yourself, you can test this by building with `cmake -DUSE_LEGACY_RENDERERS=ON`. Beware: This is not very well tested.
