### ISSUE TITLE
Eliminate zero-thickness artifacts from boolean operations on coplanar surfaces

### ISSUE THREAD

**Issue by unexpectedness** [openscad/openscad#5241]
When performing boolean operations, particularly difference(), on objects with coplanar surfaces, OpenSCAD produces zero-thickness artifacts. These artifacts appear as pseudo-surfaces in the rendered model, which can cause issues in further modeling steps or when preparing the model for 3D printing (and it's just ugly).

Reproducible Example:

```openscad
difference() {
    cube([10, 10, 10], center = true);
    cylinder(h = 10, r = 3, center = true);
}
```

<img width="409" alt="image" src="https://github.com/user-attachments/assets/eb36eb77-fdce-4c22-8d51-ea7f9a569ede">

In this example, the cube and cylinder have the same height (10 units) and are both centered. This causes their top and bottom surfaces to be coplanar, resulting in zero-thickness artifacts where the cylinder intersects the cube.

#### Expected Behavior:

The difference operation should cleanly remove the cylinder volume from the cube without leaving any residual surfaces or artifacts.

#### Actual Behavior:

Zero-thickness surfaces appear where the cube and cylinder intersect, visible as lines or faint surfaces in the rendered model.

#### Potential Solutions:

- Implement a tolerance threshold for detecting and removing coplanar surfaces during boolean operations.
- Add an option to automatically adjust one of the objects slightly to prevent perfect alignment (e.g., make the cylinder slightly taller than the cube).
Provide a post-processing step to clean up these artifacts.

Any insights or suggestions on how to address this issue would be greatly appreciated.

**Comment by kintel** [comment]
For 2D objects, we already scale negative objects by 10% to avoid such artifacts. It might be possible to do something similar for 3D objects, but it's not trivial to understand in which axes such as scaling should happen.

https://github.com/openscad/openscad/blob/master/src/glview/preview/OpenCSGRenderer.cc#L300

**Comment by unexpectedness** [comment]
I hope you will forgive me for the fact that I am using an AI (Claude from Anthropic, who helped with this issue's title), but here is what he has to say about this topic:

*After reviewing the OpenCSGRenderer.cc file and considering the problem at hand, I can suggest a few strategies to address the issue of zero-thickness artifacts in 3D:*

1. *Epsilon-based adjustment:*
   *Instead of scaling, we could slightly offset the subtractive objects in the normal direction of their surfaces. This would work for both 2D and 3D objects.*

   ```cpp
   const double epsilon = 1e-5; // Small value to offset surfaces
   
   // Inside the subtraction loop
   if (csgobj.leaf->polyset) {
     // ... existing code ...
     
     Transform3d tmp = csgobj.leaf->matrix;
     if (csgobj.leaf->polyset->getDimension() == 3) {
       // For 3D objects, calculate surface normals and offset slightly
       PolySet* ps = csgobj.leaf->polyset;
       for (auto& polygon : ps->polygons) {
         Vector3d normal = polygon.normal();
         for (auto& vertex : polygon.vertices) {
           vertex += normal * epsilon;
         }
       }
     } else if (csgobj.leaf->polyset->getDimension() == 2) {
       // Keep existing 2D scaling
       tmp *= Eigen::Scaling(1.0, 1.0, 1.1);
     }
     
     // ... rest of the existing code ...
   }
   ```

2. *Detect and remove coplanar faces:*
   *Implement a pre-processing step to detect and remove faces that are coplanar with the subtractive object's surface.*

   ```cpp
   void removeCoplanarFaces(PolySet* mainObject, const PolySet* subtractiveObject) {
     const double epsilon = 1e-6; // Tolerance for coplanarity
     
     for (auto& mainPolygon : mainObject->polygons) {
       Vector3d mainNormal = mainPolygon.normal();
       
       for (const auto& subPolygon : subtractiveObject->polygons) {
         Vector3d subNormal = subPolygon.normal();
         
         if (mainNormal.dot(subNormal) > 1 - epsilon) {
           // Normals are parallel, check if polygons are coplanar
           if (std::abs(mainPolygon.vertices[0].dot(mainNormal) - subPolygon.vertices[0].dot(subNormal)) < epsilon) {
             // Polygons are coplanar, mark for removal
             mainPolygon.shouldRemove = true;
             break;
           }
         }
       }
     }
     
     // Remove marked polygons
     mainObject->polygons.erase(
       std::remove_if(mainObject->polygons.begin(), mainObject->polygons.end(),
                      [](const Polygon& p) { return p.shouldRemove; }),
       mainObject->polygons.end());
   }
   ```

3. *Implement a post-processing cleanup:*
   *After performing the boolean operations, add a step to identify and remove any resulting faces with zero or near-zero thickness.*

   ```cpp
   void removeZeroThicknessFaces(PolySet* object) {
     const double epsilon = 1e-6; // Tolerance for thickness
     
     for (auto it = object->polygons.begin(); it != object->polygons.end(); ) {
       bool hasAdjacentFace = false;
       
       for (auto other = object->polygons.begin(); other != object->polygons.end(); ++other) {
         if (it != other) {
           Vector3d normal1 = it->normal();
           Vector3d normal2 = other->normal();
           
           if (normal1.dot(normal2) < -1 + epsilon) {
             // Normals are opposite, check if faces are very close
             if (std::abs((it->vertices[0] - other->vertices[0]).dot(normal1)) < epsilon) {
               hasAdjacentFace = true;
               break;
             }
           }
         }
       }
       
       if (hasAdjacentFace) {
         it = object->polygons.erase(it);
       } else {
         ++it;
       }
     }
   }
   ```

*These strategies can be combined or used individually depending on the specific requirements and performance considerations of your project. The epsilon-based adjustment (strategy 1) is probably the easiest to implement and least computationally expensive, while strategies 2 and 3 offer more precise control but may be more computationally intensive.*

Here is what i have to say about this:

I've just upgraded openscad (development version) and was looking for what had changed (I'm thrilled by manifold). And then I checked whether zero-thickness artifacts were still here, because this is something a little annoying and seems like an easy fix.

That being said, OpenScad source code and domain in general is totally foreign to me, but maybe I could attempt something.

Here are some comments on the 3 suggestions made by Claude:

1. Wouldn't normal orientation pose problem ? 

2. Quadratic complexity. Botched surgery. We shouldn't remove the face from the "main" polygon. Instead we should offset the polygon in the direction of the normale. Same problem as with point 1.

3. Quadratic complexity too. Seems better than point 2.

I'm afraid removing zero-thickness artifacts may incur a high computational cost. However, this could be dealt with by only applying this processing step to objects with a low polygon count or only to polygons that are big enough. In the latter case, this would require using a sorting algo on polygons having all edges > some value, in other words O(3*N*Log(N)).

Thoughts ?

**Comment by t-paul** [comment]
Is any of that code actually tested? If not, I will mark it as off-topic.

**Comment by unexpectedness** [comment]
It's not.

**Comment by t-paul** [comment]
Discussion based on potentially buggy, misleading and/or plainly wrong code is a waste of time. If you want to use it as base for the discussion, that's fine, but then please extract the core idea / algorithm it (hopefully) presents and lets discuss based on that.

So far nobody has come up with a general idea that always works as scaling in 3d starts to get hugely difficult in terms of understanding overlaps with other parts of a design. It might be reasonably possible to handle convex objects, but if the object has holes it gets difficult fast.

That said, a solution would be nice. But it has to cover pretty much 100% of all cases without additional manual guidance. Otherwise it would not a huge win over the simple manual solution.
