### ISSUE TITLE
The D (distance) and A (angle) commands are inactive

### ISSUE THREAD

**Issue by PierreDeQuebec** [openscad/openscad#5257]
I installed the nighty version with snap under Kubuntu 24.04. The commands to measure distance and angle are grayed out. Is there a reason for this? I also checked on the appimage version: same observation.

**Comment by t-paul** [comment]
Measurement currently only works with Render (F6) and Manifold enabled (Preferences->Features->Manifold).

**Comment by PierreDeQuebec** [comment]
Thanks for the quick response. This is an incredibly useful feature.
