### ISSUE TITLE
GPU Support

### ISSUE THREAD

**Issue by Pizzanomicon** [openscad/openscad#5258]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when previewing/rendering a drawing.  I feel like this could be a much faster process.

**Describe the solution you'd like**
Utilizing a GPU, perhaps specifically CUDA, could drastically speed up processes in this software by orders of magnitude.

**Comment by pca006132** [comment]
Did you try the latest snapshot with manifold enabled?

And GPU acceleration is not that simple.

**Comment by t-paul** [comment]
For some additional context Manifold had CUDA support and @pca006132 knows that very well including performance measurements. CUDA did not provide any reasonable benefit for the specific work load OpenSCAD generates. Also there's not enough dev resources for considering such a platform limited (Nvidia controlled) solution.
Manifold already brings speed improvement by (usually) multiple orders of magnitude including multithreading support. If you want to give that a try, use a dev snapshot and enable Manifold (Preferences -> Features -> Manifold).
