### ISSUE TITLE
Variable assignment inside difference or similar block: Decent error message

### ISSUE THREAD

**Issue by hroncok** [openscad/openscad#526]
When I run this code:

```c
difference() {
  c = 5;
  cube(c);
  cube(c/2);
}
```

OpenSCAD says:

````
Parser error in line 2: syntax error

ERROR: Compilation failed!
````

In this simple example it is quite obvious, that I try to assign variable in differece() block, and that doesn't work. However, if the example is much more complex, it's sometimes hard to spot the problem. It would be nice, if the error is more explaing. 

Something like:

````
Parser error in line 2: variable assignment in forbidden content (difference)

ERROR: Compilation failed!

````

**Comment by kintel** [comment]
This feature is now implemented
