### ISSUE TITLE
[CAM Workbench] Sub-objects not hidden when Job hidden in "Model" outliner

### ISSUE THREAD

**Issue by alexfacciorusso** [openscad/openscad#5264]
**Describe the bug**

When hiding a Job created with the CAM Workbench, its sub-objects remain shown.

**To Reproduce**

1. Create a body and an additive box as an example (any body would work)
2. Create a Job in the CAM workbench
3. Add an operation (e.g. Face) and make sure the path for that operation is visible
4. Select the Job in the "Model" outliner
5. Press Spacebar or right-click > Toggle Visibility

Any operation and base model are **not** hidden. It seems only the stock and the origin is hidden

**Expected behavior**
Everything regarding that Job should be hidden

**Code reproducing the issue**
N/A

**Screenshots**

https://github.com/user-attachments/assets/669197ad-5cc5-4883-97d3-fe0e359aa2ac

**Sample project**

[hide_job_example.zip](https://github.com/user-attachments/files/16713717/hide_job_example.zip)

**Environment and Version info (please complete the following information):**

OS: Windows 11 build 22635
Word size of FreeCAD: 64-bit
Version: 0.22.0dev.38495 (Git)
Build type: Release
Branch: main
Hash: 131956e201dc5033de69ed09c28db332feb081c1
Python 3.11.9, Qt 5.15.13, Coin 4.0.2, Vtk 9.2.6, OCC 7.7.2
Locale: English/United Kingdom (en_GB)
Installed mods: 
  * 3DfindIT 1.2.0

**Comment by UBaer21** [comment]
Can you reproduce the issue with openSCAD? Because if not you may need to address this with FreeCAD

**Comment by alexfacciorusso** [comment]
I am so sorry (lol), I have filed this bug in the wrong project 🤦🏻 Forgive me and I'll close this, shame on me 🤣
