### ISSUE TITLE
Build script does not support Linux Mint Virginia

### ISSUE THREAD

**Issue by atossell91** [openscad/openscad#5265]
**Description of the error**
Attempting to build OpenSCAD on Linux Mint Virginia gives an error, stating that the OS is not recognized.

**To Reproduce**
Attempt to build OpenSCAD with a clean, Linux Mint Virginia install

**Expected behavior**
The build script should run using the same, or similar, settings to the previous versions of Linux Mint

**Environment and Version info (please complete the following information):**
 - OS: Linux Mint 21.3 Virginia

**Additional context**
I added this

    elif [ "`grep -i linux.mint.[2][1] /etc/issue`" ]; then
      get_ubuntu_16_deps

To the uni-get-dependencies.sh file and it seemed to work. I'm not sure if there's a better way though.

**Comment by t-paul** [comment]
Closed via #5193.
