### ISSUE TITLE
CLI input on windows does not accept space charachters.

### ISSUE THREAD

**Issue by jjcohen** [openscad/openscad#5275]
**Describe the bug**
Space charachters are not accepted in the cli arguments when launching from windows powershell.

**To Reproduce**
1. Enter a space in an input string on an openscad model input while executing from the windows cli.

**Expected behavior**
Space charachters should be accepted from the Windows cli.

**Code reproducing the issue**
This command works : `openscad.com -D 'input_message=\"Test\u0020test\"' model.scad`
This does not work : `openscad.com -D 'input_message=\"Test test\"' model.scad`

My model is also using `Cascadia Mono:style=SemiBold` as it's font choice.

**Screenshots**
Here is the error I get with my model (which works fine with the unicode space substitution):
![image](https://github.com/user-attachments/assets/af729600-7beb-4dda-b57d-d389147705d9)

**Environment and Version info (please complete the following information):**
 - OS: Windows 11
 - System: AMD 64 bit
 - OpenSCAD Version:  2021.01 from the openscad.org website

**Library & Graphics card information**
N/A

**Additional context**
N/A

Thanks to all the contributors, really loving openscad so far!

**Comment by tylamb1** [comment]
I have the same issue. Same environment as jjcohen.

**Comment by jordanbrown0** [comment]
Command line parsing on Windows is ... tricky.

For the Command Prompt processor, this incantation works:
```
"\Program Files\OpenSCAD"\openscad -D "x=\"hello world\"" -o echo.stl echo.scad
```

I haven't found an incantation that works for PowerShell.

**Comment by t-paul** [comment]
Not an OpenSCAD issue.

See also https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_OpenSCAD_in_a_command_line_environment

**Comment by ostat** [comment]
> Command line parsing on Windows is ... tricky.
> 
> For the Command Prompt processor, this incantation works:
> 
> ```
> "\Program Files\OpenSCAD"\openscad -D "x=\"hello world\"" -o echo.stl echo.scad
> ```
> 
> I haven't found an incantation that works for PowerShell.

in powershell you can use
` "\Program Files\OpenSCAD"\openscad -D "x=""hello\u0020world""" -o echo.stl echo.scad`

to generate the args you can use this 
```
" -D `"x=`"`"$($thetext.Replace(' ','\u0020'))`"`"`""
```
