### ISSUE TITLE
Manifold "zebra" triangulation issue is back.

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#5294]
Using manifold's triangulator, triangulation sometimes fails. This was addressed earlier in https://github.com/elalish/manifold/issues/831, but seems to not fix all issues. See image below.

Design:
```
$fn=64;
text(text="R",font="naturePro",size=5);
```

Minimal cmd-line:
```
openscad zebra.scad -o out.png --enable=manifold
```

Cmd-line to reproduce image output:
```
openscad zebra.scad -o out.png --render --imgsize 1024,1024 --camera=0,0,100,0,0,0 --viewall --autocenter --projection=ortho  --enable=manifold
```
![out](https://github.com/user-attachments/assets/207c8625-1a5d-4473-9d5d-dedef47ee3db)

**Comment by pca006132** [comment]
Weirdly, when using `-DUSE_MANIFOLD_TRIANGULATOR`, I don't get your output:

![image](https://github.com/user-attachments/assets/fde78be1-a857-49a5-a02e-5694f60027fd)

**Comment by kintel** [comment]
After merging #5282, this works again!
It's odd, as I can swear I tested against that PR a week ago, but it works now, so let's move on :)
