### ISSUE TITLE
Interest in having a script that runs clang-tidy and caches results ?

### ISSUE THREAD

**Issue by hzeller** [openscad/openscad#5300]
For various other projects I have written and refined some [script](https://github.com/hzeller/dev-tools/blob/main/run-clang-tidy-cached.cc)  (well, really a self-contained C++ program), that runs `clang-tidy` and caches all the results content-addressed out-of-tree, so that re-runs only have to look at changed files or headers. It provides a combined view of all the findings (which look like compiler-outputs, so it is easy to `cat OpenSCAD_clang-tidy.out` to step through all the findings in an editor), as well as a summary.

I know there is already a `CLANG_TIDY` config in CMake, so this might feel redundant and not interesting ... but I usually find the output of cmake harder to deal with and certainly requires more diligence in making sure the results are not lost or have to all be re-generated (and `clang-tidy` is slooow).

Dropping that script into `scripts/`, changing the configuration struct to the following could make this a useful tool:

```c++
static constexpr ConfigValues kConfig = {
  .start_dir = "src/",
  .file_exclude_re = "src/ext/",
  .revisit_brokenfiles_if_build_config_newer = false,
};
```

It uses all cores to run in parallel, but does not do Unity-builds, so it runs a bit longer as it visits each file. But since it caches the results, only changed files will be considered on re-runs. The cache is outside tree (`~/.cache/clang-tidy/` by default), it will also remember results from unchanged files between different check-outs.

Anyway, didn't want to directly send a PR, wanted to check if this is that would be interesting. If not, feel free to close.

This is how the summary output looks like for OpenSCAD:
```
491 files of interest.
Details: OpenSCAD_clang-tidy.out
Summary: OpenSCAD_clang-tidy.summary
---- Summary ----
 3985 [misc-include-cleaner]
 1153 [misc-const-correctness]
  178 [misc-use-anonymous-namespace]
   81 [clang-diagnostic-error]
   60 [modernize-use-emplace]
   42 [misc-unused-parameters]
   37 [performance-enum-size]
   31 [performance-avoid-endl]
   28 [clang-analyzer-optin.core.EnumCastOutOfRange]
   26 [bugprone-switch-missing-default-case]
   14 [modernize-use-override]
   12 [modernize-macro-to-enum]
   11 [modernize-use-auto]
   10 [performance-unnecessary-value-param]
    9 [misc-header-include-cycle]
    9 [modernize-type-traits]
    8 [bugprone-integer-division]
    7 [bugprone-assignment-in-if-condition]
    7 [clang-analyzer-deadcode.DeadStores]
    7 [modernize-redundant-void-arg]
    7 [modernize-use-equals-default]
    6 [modernize-make-shared]
    5 [bugprone-branch-clone]
    5 [bugprone-empty-catch]
    5 [bugprone-multi-level-implicit-pointer-conversion]
    5 [bugprone-reserved-identifier]
    5 [bugprone-unused-local-non-trivial-variable]
    4 [bugprone-macro-parentheses]
    4 [misc-confusable-identifiers]
    4 [modernize-use-nullptr]
    4 [performance-for-range-copy]
    3 [modernize-return-braced-init-list]
    2 [modernize-loop-convert]
    2 [modernize-use-using]
    1 [bugprone-implicit-widening-of-multiplication-result]
    1 [modernize-use-bool-literals]
    1 [modernize-use-default-member-init]
    1 [performance-type-promotion-in-math-fn]
    1 [performance-unnecessary-copy-initialization]
```

**Comment by t-paul** [comment]
I have not tried it yet, but the description sounds like it could replace the existing option while providing a number of benefits. So it has my vote for integration.
