### ISSUE TITLE
Header includes: would be neat if relative to project-root

### ISSUE THREAD

**Issue by hzeller** [openscad/openscad#5311]
Right  now, all locally used project includes are included as local files, e.g.

```c++
#include "linalg.h"
#include "CSGNode.h"
#include "GeometryEvaluator.h"
```

Which makes it harder for someone new to the code base to see where things are and 'connect the dots'.

It would be good if this was relative to the project root to provide context at one glance; also reccommended by [styleguides](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes)

```c++
#include "geometry/linalg.h"
#include "core/CsgOpNode.h"
#include "geometry/GeometryEvaluator.h"
```

If this sounds good, I have a script that can convert that.

**Comment by kintel** [comment]
Agreed. I think this is just an artifact from back when we had a flat source tree.

**Comment by kintel** [comment]
The only exception I can think of are includes isolated to sublibraries like the svg library, and perhaps .cc files assuming that the corresponding .h file can be included without a path.

**Comment by hzeller** [comment]
I think for consistency, even the corresponding header to a `foo/bar/baz.cc` should include `foo/bar/baz.h` for consistency.

It should be the very first include in the file, but clang-format can take care of that once we can enable the header sorting.
