### ISSUE TITLE
Colour removed after render.

### ISSUE THREAD

**Issue by BK524** [openscad/openscad#5330]
Opening this as a separate issue as recommended by @t-paul 
Looking to take advantage of the new colour render capability to export spacecraft .scad models into (preferably) .obj or .off format. Used the newest developmental snapshot. 
I have created this basic example with one part coloured and the rest left uncoloured, this works fine in preview mode (see first image)
<img width="722" alt="image" src="https://github.com/user-attachments/assets/400113d2-786d-4dc2-b30e-86f156456fbe">
But when rendered this colour disappears (see second image):
<img width="637" alt="image" src="https://github.com/user-attachments/assets/ede15bb6-9c14-4ec8-9cad-2481803d154b">

The code is as follows:
distance=0.71/2+1.21/2;
color("red") { rotate([ 0, 90, 0 ])
cylinder(d1=0.71, d2=0.71, h=3.2, center=true, $fn = 8);
}
translate([0,-distance+0.001,0])
rotate([0,0,90])
cube([1.21,3.2,0.01],center=true);
translate([0,distance-0.001,0])
rotate([0,0,90])
cube([1.21,3.2,0.01],center=true);

Added the .off file exported here: [OFF file ex.docx](https://github.com/user-attachments/files/17151835/OFF.file.ex.docx)
Any ideas what is wrong?
Cheers

**Comment by UBaer21** [comment]
Manifold is activated?  (preferences ↦ features ↦ manifold)

**Comment by t-paul** [comment]
Yes, I was looking for a dedicated color switch but there's none. But "manifold" needs to be enabled for this to work. Sorry I missed that when closing the other issue. I tried locally and it works, but I have "manifold" enabled already.

**Comment by BK524** [comment]
@UBaer21 @t-paul I hadn't clicked to activate manifold (silly me!)
I think it's working now.
Thanks for your help :)
