### ISSUE TITLE
Inconsistent color in render operation

### ISSUE THREAD

**Issue by MethylBromide** [openscad/openscad#5351]
**Describe the bug**
A recent regression causes **render** to fail to retain the object's color when there are more than one object.

**To Reproduce**
1. Enter the script given below.
2. Press F5. Observe the pink cube.
3. Press F6 to render the object. The cube is still pink.
4. In Customizer, select option "one pink one green". This creates a pink cube and a green one.
5. Press F6 to render the object. The cubes turn "default" color (yellow in my case).
6. In Customizer, select option "two pink". This creates two pink cubes.
7. Press F6 to render the object. The cubes turn "default" color (yellow in my case).

**Expected behavior**
Objects should not change color when they are rendered. I have screenshots showing this was working correctly, fairly recently. This is a regression introduced in the last week or so.

**Code reproducing the issue**
```
option = 0; // [0:a pink cube,1:one pink one green,2:two pink]
color("pink") cube(4);
if (option > 0) {
	color(option == 1 ? "lightgreen" : "pink")
	translate([6,0,0]) cube(4);
}
```

**Screenshots**

**Environment and Version info (please complete the following information):**
 - OS: Windows 11
 - System: Intel PC 64-bit
 - OpenSCAD Version 2024.10.02 (git e972ed84e)
 - problem also observed in 0930 Windows build.

**Comment by kintel** [comment]
You need to enable manifold (Preferences->Advanced->3D rendering->Backend) to get color support when rendering.
In CGAL mode, colors are not supported, but from time to time, colors do sneak in; that's a bug.
