### ISSUE TITLE
FAST-CSG is no longer fast starting with version 20240929

### ISSUE THREAD

**Issue by coder2999** [openscad/openscad#5358]
When I press F6, it outputs multiple lines of the same text:
[fast-csg] Performing safer but slower nef operation instead of corefinement because operands share some vertices.

It takes more time to complete the task compared to the old version.

How can I solve this problem?

**Comment by coder2999** [comment]
I found that disable "fast-cfg-safer" can solve this problem.

**Comment by coder2999** [comment]
I tested it in another project, I found that even if I disabled "fast-csg-safer", it still takes more time to complete the task compared to the old version.

**Comment by t-paul** [comment]
fast-csg is obsolete, please use Manifold instead, see https://lists.openscad.org/empathy/thread/D6KV3ZLXHLBHSITSQ5GPUZUKHURU4ABE
