### ISSUE TITLE
"The given mesh is not closed" rendering error when `rotate_extrude(rotate_extrude)` rotates a shape with a point on the rotation axis with even `$fn`

### ISSUE THREAD

**Issue by lgarron** [openscad/openscad#5376]
**Describe the bug**

OpenSCAD prints the following error when `rotate_extrude` rotates a shape with a point on the rotation axis with even `$fn`

```
ERROR: The given mesh is not closed! Unable to convert to CGAL_Nef_Polyhedron.
```

**To Reproduce**

Use OpenSCAD to render on the following scene:

```
rotate_extrude(convexity = 10) translate([ 1, 0, 0 ]) circle(r = 1, $fn = 8);
translate([ 2, 0, 0 ]) cube([ 2, 2, 2 ], center = true);
```

This includes:

- A low-poly torus generated from a circle tangent to the origin, i.e. a torus with a hole that has contracted to size 0. Note that `$fn` is set to an even value of 8.
- Any other bogus object in the scene, which doesn't even have to overlap.

Previewing this scene works perfectly fine:

![clipboard](https://github.com/user-attachments/assets/4948841f-0ecc-4ee2-85c1-7c5df0be322a)

But rendering it results in the error above and removes the torus from the scene:

![clipboard](https://github.com/user-attachments/assets/42dcefd5-669d-4d1b-b7cb-7f2a91dfaced)

The problem seems to go away with an odd value of `$fn` (including the apparent default value of 7), suggesting this has something to do with what happens when extruded shape is made up of slices that each end up exactly 180° from another slice (i.e. in the same plane but presumably with opposite orientation).

**Expected behavior**

Neither previewing nor rendering the scene causes an error, and all the objects are rendered.

**Code reproducing the issue**
See above.

**Screenshots**
See above.

**Environment and Version info (please complete the following information):**
 - OS: macOS 15.0.1
 - System: MacBook Pro
 - OpenSCAD Version: 2021.01 (latest [from Homebrew](https://github.com/Homebrew/homebrew-cask/blob/60cb5e6dc01db4b11cc87c52357a4011c5a0ad6e/Casks/o/openscad.rb))

**Library & Graphics card information**
N/A

**Additional context**

This comes from a real-world example using https://github.com/chrisspen/openscad-extra/blob/115040b2cb8e033fc62c6f2f207f7e8cc4f1d1bb/src/torus.scad to model a real-world object that happened to have dimensions producing this edge cases.

I'd like to consider myself fairly experienced with OpenSCAD, but it actually took me several hours to track down the issue and another hour to create a minimal repro.

If this isn't fixable, it would have been tremendously helpful to have debugging info that pointed to code that caused it, or perhaps a warning from `rotate_extrude(…)`.

**Comment by pca006132** [comment]
rotate extrude and linear extrude are known to produce non-manifold results... we should fix this at some point similar to manifold's extrude algorithms (adapt it to fit openscad).

**Comment by kintel** [comment]
This was fixed for the Manifold backend back in April or so. If you use a recent development snapshot instead of 2021.01 and select Manifold from Preferences->Advanced

**Comment by lgarron** [comment]
> This was fixed for the Manifold backend back in April or so. If you use a recent development snapshot instead of 2021.01 and select Manifold from Preferences->Advanced

Woah! Not only does this resolve the issue for me, it also reduces rendering time from 9 minutes to 1 second when I crank up `$fn` for the project that was running into this! 😳

I'm not sure what to make of this output, but it doesn't seem to have affected the accuracy of the result:
```
   Top level object is a 3D object (manifold):
   Status:     NoError
   Genus:      -14
   Vertices:    57205
   Facets:     114350
```

**Comment by kintel** [comment]
That output is perfectly fine. Manifold has some special interpretation of negative genus, it probably means you've got multiple objects. @pca006132 may be able to comment on that (and whether we should avoid printing it if it's potentially confusing)

**Comment by pca006132** [comment]
Yeah it is due to having multiple objects. Maybe we should not display the information as it may scare users.

**Comment by v3rtx** [comment]
@kintel huge thanks for the dev snapshot tip! Works like a charm, also the whole UI is much better than stable 2021 version. Just curious, taking into account all the goodness that has been added since 2021 why there wasn't a stable release?

**Comment by rowlesmr** [comment]
I'm running into a bunch of these errors when using BOSTL and the planetary gear generator, as well as a bunch of other things I'm doing which use rotate_extrude. 

I may have to dive into trying to build my own verions for Windows...

**Comment by kintel** [comment]
> [@kintel](https://github.com/kintel) huge thanks for the dev snapshot tip! Works like a charm, also the whole UI is much better than stable 2021 version. Just curious, taking into account all the goodness that has been added since 2021 why there wasn't a stable release?

It may be better, but not everything is stable enough: https://github.com/orgs/openscad/projects/2

**Comment by kintel** [comment]
@rowlesmr Please discuss on the mailing list, or open a new issue if you have a specific problem with OpenSCAD itself. But chat with the BOSL folks first :)
