### ISSUE TITLE
visibly module names

### ISSUE THREAD

**Issue by yahbluez** [openscad/openscad#5403]
It would be useful if a module may have access to his name:

$this_name

and to his calling parent

$parent_name

That would at least by helpful while debugging scripts and i guess that it is not that hard to implement.

**Comment by t-paul** [comment]
That already exists:
```

module z() {
	echo("in z[0]: ", parent_module(0));
	echo("in z[1]: ", parent_module(1));
}

module x() {
	echo("in x: ", parent_module(0));
	z();
}

x();

// ECHO: "in x: ", "x"
// ECHO: "in z[0]: ", "z"
// ECHO: "in z[1]: ", "x"
```

**Comment by yahbluez** [comment]
Thank you very much! I did not found that.
