### ISSUE TITLE
No preview/render without saving.

### ISSUE THREAD

**Issue by UBaer21** [openscad/openscad#5405]
**Describe the bug**
unsaved file fail on AST generation

**To Reproduce**
new↦ render/preview
```
Parsing design (AST generation)...
ERROR: Parser error: file access denied
ERROR: Compilation failed! (no top level object found)
```
 

**Expected behavior**
no error

**Code reproducing the issue**
none  

**Screenshots**
![image](https://github.com/user-attachments/assets/ede5cbb3-4456-46b4-9fcd-07a864bb2136)

**Environment and Version info (please complete the following information):**
 - OS:  Windows 10
 - OpenSCAD Version 2024.10.31

**Comment by thehans** [comment]
Can confirm on linux mint 22 also.

**Comment by jordanbrown0** [comment]
Not on 2024.10.28 on Windows 11.

**Comment by thehans** [comment]
Right, this is due to changes from #5399 which was merged on Oct 31, and involved migrating from `boost::filesystem` to `std::filesystem`.  
Looking into a fix now.

**Comment by thehans** [comment]
Demo of differences for reference https://godbolt.org/z/Tz7bWPvv7
