### ISSUE TITLE
Add AI LLM Chat window.

### ISSUE THREAD

**Issue by 0xStuart** [openscad/openscad#5408]
I have successfully created numerous OpenSCAD models using LLM's such as ChatGPT and Llama.  Copy & Pasting everything is very tedious, especially when your making manual adjustments, and you have to copy it over to the other side.

1. Add a chat window.
2. Add a setting to input your LLM Api.
3. Add a user configurable prompt to start off the chat. e,g "You are a OpenSCAD bot that creates objects"

**Comment by kintel** [comment]
The main challenge, IMO, is that LLM APIs evolve much faster than OpenSCAD itself, so to offer such a service, we'd effectively need to deploy our own bridge API, or allow people to inject logic into OpenSCAD through a plugin or smth.

All of that is doable, but it's a fair amount of work and we'd need someone to take ownership over design, implementation and testing of such a feature. ..or find a more suitable integration point.

**Comment by nophead** [comment]
I have never been able to get ChatGPT or Gemini to create anything useful in OpenSCAD. I can't see how LLMs can understand spacial relationships. For example when asked to make a 3D model of a dog they have the right components like legs and a head but they are never in the right place.  @0xStuart what sort of models have you managed to create and do you have an example prompt?

**Comment by 0xStuart** [comment]
All i'm suggesting is a chat window, and not full integration.  The API is just a json message, which in this case would be the model code, and anything the user had typed in the chat window.  Then update the code, on the reply.

@nophead I do a lot of 3D printing, but not so much CAD work, and I had not heard of OpenSCAD before.  A client of mine asked for an adaptor to connect two pipes together, with different angles. I asked ChatGPT for advice on what software I should use, and to my amazement, it returned code for the model itself in OpenSCAD.  With some back and forth, I got what I wanted.

This is another project I just completed without writing any code:
![image](https://github.com/user-attachments/assets/2da06457-17cf-4f77-a90b-8a6adc19852f)

**Comment by kintel** [comment]
The devil is in the details. What looks like a simple integration is actually an API integration with a 3rd party API, which comes with both terms and conditions of usage, as well as license key management on behalf of users, plus the API may change, be gone, or be replaced by other APIs months from now. For software designed to be stable over a timeframe of years, we need to be able to react much more swiftly to changes in API landscape. The actual complexity of this can only be estimated by someone trying to make it happen though.

**Comment by nophead** [comment]
This is the best dog I got ChatGPT to produce.

![image](https://github.com/user-attachments/assets/a63ecd91-36e5-4e65-b3ad-7e5f045dc188)

I think this is what it had in mind.

![image](https://github.com/user-attachments/assets/dff08f76-8589-4e66-b2bd-54860b4497c7)

I changed the differences to unions, added some rotations and changed some of the translations to put things in more appropriate places. The cylinders are all the original sizes it generated apart from the neck, which I made longer.

**Comment by kintel** [comment]
I think the best approach to teach LLMs OpenSCAD today it likely to amass a large collection of OpenSCAD designs and set up some fine-tuning for the models. I'm not familiar with to what degree various LLM vendors allow hosting of such fine tuning, or if that's more of a feature available only to commercial customers. For self-hosted OSS models, that could be more achievable though. This is a good time to own the rights to utilizing big human-created model repositories..

**Comment by 0xStuart** [comment]
> The devil is in the details. What looks like a simple integration is actually an API integration with a 3rd party API, which comes with both terms and conditions of usage, as well as license key management on behalf of users, plus the API may change, be gone, or be replaced by other APIs months from now. For software designed to be stable over a timeframe of years, we need to be able to react much more swiftly to changes in API landscape. The actual complexity of this can only be estimated by someone trying to make it happen though.

I was a software engineer for 30 years, so I know exactly where your coming from.  Honestly, it's much simpler than you think.  Of all the LLM providers out there, they all support the same API (OpenAI's).  Groq is free at the moment.

Anyway, I just put the suggestion out there.  It would save a lot of copy & pasting.

**Comment by UBaer21** [comment]
@0xStuart If you get the AI to write the input to a *.scad file it would be quite easy as it would just act as an external editor - also you could use the command line to run the code. 
I think wanting openSCAD to interface with some API is the wrong approach if all you need is the API to write the output to any text file.  OpenSCAD will check for changes of files and automatically recompile if a file change occurs. To use this feature enable "Design->Automatic Reload and Preview"
https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Using_an_external_Editor_with_OpenSCAD

**Comment by hzeller** [comment]
I think there is no need for a specialized feature like this as OpenSCAD nicely integrates with external editors.

Open a file with openscad, don't use the internal editor but edit your file with whatever external editor you prefer that does the automated script generations you need. On saving the file, it will automatically be picked up by OpenSCAD and re-rendered.

So integration point: the file that lives on disk.

Keeping OpenSCAD focused on model generation and not try to chase features that editors have a more native incentive to track is probably good.

**Comment by 0xStuart** [comment]
@UBaer21 @hzeller good advice, thanks.

Cursor or some other AI editor might work well.  I'll try that for the next project.

**Comment by opicron** [comment]
> I have never been able to get ChatGPT or Gemini to create anything useful in OpenSCAD. I can't see how LLMs can understand spacial relationships. For example when asked to make a 3D model of a dog they have the right components like legs and a head but they are never in the right place. [@0xStuart](https://github.com/0xStuart) what sort of models have you managed to create and do you have an example prompt?

With some explanation and prompting on Claude Fable, I got this:

<img width="593" height="219" alt="Image" src="https://github.com/user-attachments/assets/c90f678c-c3bf-40c8-b346-f0e0386ba99b" />

Not a single line of code needed to be written. As https://modelrift.com/ explains, LLMs are exceptionally good in producing valid code for OpenSCAD. https://modelrift.com/blog/why-openscad#llms-generate-better-openscad

I think OpenSCAD should embrace this and not let others piggyback the open source community by offering such services.
