### ISSUE TITLE
Unable to open Openscad since MacOS 15.1 24B83

### ISSUE THREAD

**Issue by waazdakka** [openscad/openscad#5411]
**Describe the bug**
MacOS have pushed an update yesterday (15.1 24B83) and since then I'm not able to launch the application.
I obtain a double error (the window opens twice everytime) which is different from the classic "unverified developper" issue we can easily solve. 

I trie to force with ctrl click, disable again the application controle (sudo spctl --master-disable) but I still get an error.
I even tried the 2024.11.04 but i get multiple errors...

I guess this MacOS version has introduced new applications verification mecanisms :(

**To Reproduce**
1. Try to open Openscad itself or opening a scad file, from the launchpad, the finder, anywhere...
2. Obtain the error (twice)
3. (troll: install linux)

**Screenshots**
<img width="317" alt="image" src="https://github.com/user-attachments/assets/8ef58604-f094-4289-b823-85db6af2c6ac">
<img width="583" alt="image" src="https://github.com/user-attachments/assets/9543b524-6c4a-4857-ae8d-a5addc209b04">

**Environment and Version info (please complete the following information):**
 - OS: MacOS 15.1 24B83
 - System: Mac Intel 16' i9
 - OpenSCAD Version : 2021.01 AND 2024.11.04, tried from dmg, brew install...

**Comment by t-paul** [comment]
See discussion and progress in #880. Closing as duplicate.
