### ISSUE TITLE
Trying to run newly installed OpenScad results in The application “Finder” does not have permission to open “(null).”

### ISSUE THREAD

**Issue by jmauerhan** [openscad/openscad#5426]
**Describe the bug**
Trying to install OpenScad for the first time on my Mac, Apple M1 Pro, OS 15.1

**To Reproduce**
1. Installed Rosetta 2 as suggested on the brew page
2. Installed OpenScad (via website or brew)
3. Attempt to open OpenScad
4. error is shown: The application “Finder” does not have permission to open “(null).”

**Expected behavior**
The app will open

**Code reproducing the issue**
If applicable, add trimmed down, self-contained code demonstrating the issue.

**Screenshots**

**Environment and Version info (please complete the following information):**
 - OS: Mac OS 15.1
 - System: Apple M1 Pro
 - OpenSCAD Version 2021.01, installed via brew and regular download from the website

**Library & Graphics card information**
If applicable, add the content of the Help->Library Info window, or the output of running the `openscad --info` command.

**Additional context**
I tried installing `openscad@snapshot` via brew and that appears to at least open and run.

**Comment by ElhemEnohpi** [comment]
You can also just use this command:

`codesign --deep -f -s - /Applications/OpenSCAD.app`

That should prevent the "...does not have permission to open “(null).”" problem. After that, it will say that it can't check it for malware, and you have to go to System Settings, Privacy & Security, and click "Open Anyway".
