### ISSUE TITLE
which version to use?

### ISSUE THREAD

**Issue by henning** [openscad/openscad#5435]
I wonder which version is recommended to use...

I see the latest official release is from 2021 but the code seems to be in constant development, so I guess the master branch will probably be much further developed, old bugs fixed etc.

Is the master branch usually stable enough for most things or should i better start with the release to get confident with the application first?

I dont mind building if from source and am fine  if the development version has one or another roughness  - that might be outweighted by better features and old bugs fixed.  

But if it's very hard to build and expected to crash every 5min i'd rather go for the older release

**Comment by jordanbrown0** [comment]
Many people are happily using the development snapshots, and their rendering is far faster.

For questions like this the mailing list or IRC are probably better.

**Comment by t-paul** [comment]
Snapshot builds at https://openscad.org/downloads.html#snapshots
