### ISSUE TITLE
Running OpenSCAD from a symlink yields bad behavoir for homebrew install on macOS

### ISSUE THREAD

**Issue by lgarron** [openscad/openscad#5438]
(Moved from https://github.com/openscad/openscad/issues/5320#issuecomment-2481830338)

**Describe the bug**
OpenSCAD app crashes while previewing

**To Reproduce**

```
brew install openscad@snapshot # Currently installs version 2024.11.10 on macOS

cd /tmp && git clone https:///github.com/lgarron/cube-box/ && cd cube-box
git switch --detach d123b39c4e88c763ebd9c33070f3e98af3f05af4
npm install # or: bun install

# yay 😄
openscad --enable lazy-union --backend Manifold -o ./cube-box-v0.1.3.scad.3mf ./cube-box-v0.1.3.scad

# crashy crashy bad times when the app is set to Manifold
openscad ./cube-box-v0.1.3.scad
```

There are a whole bunch of warnings that are always output when running `openscad` this way:

```
Could not initialize localization (application path is '/opt/homebrew/bin').
qt.qpa.fonts: Populating font family aliases took 146 ms. Replace uses of missing font family "DejaVu Sans" with one that exists to avoid this cost.
Error reading examples.json: examples.json: cannot open file
WARNING: GLView: unknown colorscheme Tomorrow Night
ERROR: Cannot open shader source file: 'MouseSelector.vert'
ERROR: Cannot open shader source file: 'MouseSelector.frag'
/Users/distiller/project/src/gui/MouseSelector.cc: OpenGL Program Linker Error:
ERROR: Compiled vertex shader was corrupt.
ERROR: Compiled fragment shader was corrupt.


/Users/distiller/project/src/gui/MouseSelector.cc: OpenGL symbol retrieval went wrong, id is -1

FALLBACK (log once): Fallback to SW vertex for line stipple
FALLBACK (log once): Fallback to SW vertex processing, m_disable_code: 2000
FALLBACK (log once): Fallback to SW vertex processing in drawCore, m_disable_code: 2000
2024-11-19 04:39:32.822 openscad[72440:2746090] +[IMKClient subclass]: chose IMKClient_Modern
2024-11-19 04:39:32.822 openscad[72440:2746090] +[IMKInputSession subclass]: chose IMKInputSession_Moder
```

When it crashes, only the following additional line is shown:

```
fish: Job 1, 'openscad ./cube-box-v0.1.3.scad' terminated by signal SIGSEGV (Address boundary error)
```

**Expected behavior**
No crash

**Code reproducing the issue**
See above

**Screenshots**
See above

**Environment and Version info (please complete the following information):**
 - OS: macOsS15.1
 - System: MacBook Pro
 - OpenSCAD Version: see above

**Library & Graphics card information**

```
╭─── /Users/lgarron ─────────────────────────────────────────────────
├─ lgarron@Germain
│ openscad --info | 📋
┴
Could not initialize localization (application path is '/opt/homebrew/bin').
QObject::startTimer: Timers can only be used with threads started with QThread
Fontconfig error: Cannot load default config file: No such file: (null)
OpenSCAD Version: 2024.11.10 (git 6f5932feb)
System information: macOS 15.1.0 arm64 MacBookPro18,2 10 CPUs 64.00 GB RAM
User Agent: OpenSCAD/2024.11.10 (git 6f5932feb) (macOS 15.1.0 arm64 MacBookPro18,2)
Compiler: Clang "15.0.0 (clang-1500.3.9.4)"
MinGW build: No
Debug build: No
Boost version: 1_81
Eigen version: 3.4.0
CGAL version, kernels: 6.0, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.6.0
Qt version: 5.15.13
QScintilla version: 2.13.3
InputDrivers:
GLib version: 2.81.0
lodepng version: 20230410
libzip version: 1.9.2
fontconfig version: 2.14.1
freetype version: 2.12.1
harfbuzz version: 6.0.0
cairo version: 1.18.0
lib3mf version: 2.3.1
Features: roof, input-driver-dbus, lazy-union, vertex-object-renderers-indexing, textmetrics, import-function, predictible-output
Application Path: /opt/homebrew/bin
Documents Path: /Users/lgarron/Documents
User Documents Path: /Users/lgarron/Documents
Resource Path: /opt/homebrew/bin
User Library Path: /Users/lgarron/Documents/OpenSCAD/libraries
User Config Path: /Users/lgarron/Library/Application Support/OpenSCAD
Backup Path: /Users/lgarron/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
  /Users/lgarron/Documents/OpenSCAD/libraries
  /Users/lgarron

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
  /System/Library/Fonts
  /Library/Fonts
  /Users/lgarron/Library/Fonts
  /System/Library/Assets/com_apple_MobileAsset_Font3
  /System/Library/Assets/com_apple_MobileAsset_Font4
  /Users/lgarron/.data/fonts
  /usr/local/share/fonts
  /usr/share/fonts
  /System/Library/Fonts/Supplemental


GL context creator: CGL (new)
PNG generator: Core Foundation

GLAD version: 2.0.4
OpenGL Version: 2.1 Metal - 89.3
GL Renderer: Apple M1 Max
GL Vendor: Apple
RGBA(8888), depth(24), stencil(8)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

┬
╰─── ⏱️ 0.175s ──────────────────────────────────────────────────────
```

**Additional context**

There's probably a more concise repro, I'm sorry I don't have one handy.

**Comment by pca006132** [comment]
Can you try if it fails with the latest snapshot? We updated manifold version recently.

https://openscad.org/downloads.html#snapshots

**Comment by kintel** [comment]
You cannot run OpenSCAD in cmd-line mode directly from a symlink in a bin/ folder. This looks like a bug in homebrew's installer.

Try /Applications/OpenSCAD/Contents/MacOS/OpenSCAD

**Comment by lgarron** [comment]
> You cannot run OpenSCAD in cmd-line mode directly from a symlink in a bin/ folder. This looks like a bug in homebrew's installer.

Homebrew is one of the recommended install methods at the top of https://openscad.org/downloads.html , so that sounds worth fixing. Are the issues with this spelled out somewhere? Would it be sufficient to implement a wrapper script that invokes `/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD` and passes on all parameters?

> Can you try if it fails with the latest snapshot? We updated manifold version recently.

Same crash, but `/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD ./cube-box-v0.1.3.scad` works fine.

Sounds like that particular crash for the repro was a red herring. That said, the `openscad@snapshot` app crashes for me like a dozen times a day during normal use, and I'm gonna try to run it from the non-symlinked path to see if I can get a repro for my actual issue.

**Comment by t-paul** [comment]
> Homebrew is one of the recommended install methods at the top of https://openscad.org/downloads.html , so that sounds worth fixing. Are the issues with this spelled out somewhere?

Good questions, but wrong place. Homebrew builds/packages a not maintained here, I think https://github.com/Homebrew/homebrew-cask/issues might be the right place for Homebrew specific issues.

It might be a side effect of https://github.com/openscad/openscad/pull/5395, but still needs help/investigation on Homebrew side.

**Comment by kintel** [comment]
As a start, I'll investigate the symlink issue outside of the scope of Homebrew, to make sure we have a good story for that.

**Comment by kintel** [comment]
I belive my fix above will work; at least it works for manually created symlinks.

**Comment by lgarron** [comment]
Glad to hear it!

For what it's worth, crashes are still happening to me but without the red herring repro they're too rare and I have yet to get one with any useful logs.
