### ISSUE TITLE
Setting for icon color

### ISSUE THREAD

**Issue by hackwin** [openscad/openscad#5453]
**Is your feature request related to a problem? Please describe.**
The black icon for OpenSCAD is hard to spot on my Windows task bar compared to the yellow icon.

**Describe the solution you'd like**
Put a setting into the program to allow the icon to be yellow or black.

**Describe alternatives you've considered**

**Additional context**
![TwE3rVDpvu](https://github.com/user-attachments/assets/4f2df3b1-af36-48d9-acbe-a0fceb657c37)

**Comment by kintel** [comment]
FYI: The blue icon means you're using a nightly build. Official releases will have the yellow icon.

**Comment by kintel** [comment]
Btw., your screenshot shows a blue logo. We don't have any plans to change the logo, but if someone are artistically inclined and willing to design a set of logos suitable for release vs. nightly, I'm not opposed to modernizing them. It's a fair bit of work though, as logos are used in a number of places. Until then, I'm closing this as not planned.
