### ISSUE TITLE
Export of STL-Files does not work anymore on macOS 15.1.1 since version 2024-12-01

### ISSUE THREAD

**Issue by dhyananbho** [openscad/openscad#5466]
**Describe the error**
Since version 2024-12-01 git 1ad142a44 it is not possible to export STL-files anymore. The STL-Button in the top bar of the editor does not react anymore, the menu „export STL“ does not work anymore, no matter if the code was rendered before or not, no reaction at all.

This is really a serious bug, which should be solved asap.

**To reproduce the error**
1. start OpenSCAD and open a `.scad` file
2. click „render“
3. click „export STL“
–> no reaction at all.

**Environment and version information**
 - macOS Sequoia 15.1.1
 - MacBook Pro 16’ (2021) with Apple M1 Max, 64GB
 - OpenSCAD version 2024-12-01 (git 1ad142a44)

**Comment by gsohler** [comment]
works in my place without issue in Linux...

**Comment by kintel** [comment]
Fixed by #5465
