### ISSUE TITLE
Have to force quit on mac

### ISSUE THREAD

**Issue by onealexharms** [openscad/openscad#5492]
**Describe the bug**
For quite a while, I have not been able to quit OpenSCAD without force quitting. I get a beachball that never seems to stop. (Oh, also an error window pops up on starting OpenSCAD, but it's empty. No message.)

**To Reproduce**
1. Cmd Q or Quit from the menu
2. observe spinning beach ball

**Expected behavior**
OpenSCAD should quit.

**Code reproducing the issue**
n/a

**Screenshots**
n/a

**Environment and Version info (please complete the following information):**
 - OS: MacOS Sequoia 15.11 (*but also previous version*)
 - System: 2.3GHz Intel Core i9, Radeon Pro 5500M 8GB, Intel UHD Graphics 630 1536MB, 64GB 2667 MHz DDR4
 - OpenSCAD Version  2021.01 from the website.

**Library & Graphics card information (Paste of lib & build info)** 
OpenSCAD Version: 2021.01
System information: Mac OS X Version 15.1.1 (Build 24B91) MacBookPro16,1 8 CPUs 64.00 GB RAM 
User Agent: OpenSCAD/2021.01 (Mac OS X Version 15.1.1 (Build 24B91) MacBookPro16,1)
Compiler: Clang "12.0.0 (clang-1200.0.32.28)" 64bit
MinGW build: No
Debug build: No
Boost version: 1_74
Eigen version: 3.3.7
CGAL version, kernels: 4.14.3, Cartesian<Gmpq>, Extended_cartesian<Gmpq>, Epeck
OpenCSG version: OpenCSG 1.4.2
Qt version: 5.9.9
QScintilla version: 2.11.6
InputDrivers: 
GLib version: 2.56.3
lodepng version: 20180910
libzip version: 1.5.1
fontconfig version: 2.13.1
freetype version: 2.9.1
harfbuzz version: 2.3.1
cairo version: 1.16.0
lib3mf version: 1.8.1
Application Path: /Applications/OpenSCAD-2021.01.app/Contents/MacOS
Documents Path: /Users/alex/Documents
User Documents Path: /Users/alex/Documents
Resource Path: /Applications/OpenSCAD-2021.01.app/Contents/Resources
User Library Path: /Users/alex/Documents/OpenSCAD/libraries
User Config Path: /Users/alex/Library/Application Support/OpenSCAD
Backup Path: /Users/alex/Documents/OpenSCAD/backups
OPENSCADPATH: <not set>
OpenSCAD library path:
/Users/alex/Documents/OpenSCAD/libraries
/Applications/OpenSCAD-2021.01.app/Contents/Resources/libraries

OPENSCAD_FONT_PATH: <not set>
OpenSCAD font path:
/usr/share/fonts
/Users/alex/.local/share/fonts
/Users/alex/.fonts
/usr/X11/lib/X11/fonts
/System/Library/Fonts
/Library/Fonts
/Users/alex/Library/Fonts
/System/Library/Fonts/Supplemental
GLEW version: 2.1.0
OpenGL Version: 2.1 ATI-6.1.13
GL Renderer: AMD Radeon Pro 5500M OpenGL Engine
GL Vendor: ATI Technologies Inc.
RGBA(8888), depth(0), stencil(0)
GL_ARB_framebuffer_object: yes
GL_EXT_framebuffer_object: yes
GL_EXT_packed_depth_stencil: yes

Qt graphics widget: QOpenGLWidget
QSurfaceFormat: RGBA(888-1), depth(-1), stencil(-1)

GL Extensions:
GL_APPLE_aux_depth_stencil
GL_APPLE_client_storage
GL_APPLE_element_array
GL_APPLE_fence
GL_APPLE_float_pixels
GL_APPLE_flush_buffer_range
GL_APPLE_flush_render
GL_APPLE_object_purgeable
GL_APPLE_packed_pixels
GL_APPLE_pixel_buffer
GL_APPLE_rgb_422
GL_APPLE_row_bytes
GL_APPLE_specular_vector
GL_APPLE_texture_range
GL_APPLE_transform_hint
GL_APPLE_vertex_array_object
GL_APPLE_vertex_array_range
GL_APPLE_vertex_point_size
GL_APPLE_vertex_program_evaluators
GL_APPLE_ycbcr_422
GL_ARB_color_buffer_float
GL_ARB_depth_buffer_float
GL_ARB_depth_clamp
GL_ARB_depth_texture
GL_ARB_draw_buffers
GL_ARB_draw_elements_base_vertex
GL_ARB_draw_instanced
GL_ARB_fragment_program
GL_ARB_fragment_program_shadow
GL_ARB_fragment_shader
GL_ARB_framebuffer_object
GL_ARB_framebuffer_sRGB
GL_ARB_half_float_pixel
GL_ARB_half_float_vertex
GL_ARB_imaging
GL_ARB_instanced_arrays
GL_ARB_multisample
GL_ARB_multitexture
GL_ARB_occlusion_query
GL_ARB_pixel_buffer_object
GL_ARB_point_parameters
GL_ARB_point_sprite
GL_ARB_provoking_vertex
GL_ARB_seamless_cube_map
GL_ARB_shader_objects
GL_ARB_shader_texture_lod
GL_ARB_shading_language_100
GL_ARB_shadow
GL_ARB_shadow_ambient
GL_ARB_sync
GL_ARB_texture_border_clamp
GL_ARB_texture_compression
GL_ARB_texture_compression_rgtc
GL_ARB_texture_cube_map
GL_ARB_texture_env_add
GL_ARB_texture_env_combine
GL_ARB_texture_env_crossbar
GL_ARB_texture_env_dot3
GL_ARB_texture_float
GL_ARB_texture_mirrored_repeat
GL_ARB_texture_non_power_of_two
GL_ARB_texture_rectangle
GL_ARB_texture_rg
GL_ARB_transpose_matrix
GL_ARB_vertex_array_bgra
GL_ARB_vertex_blend
GL_ARB_vertex_buffer_object
GL_ARB_vertex_program
GL_ARB_vertex_shader
GL_ARB_window_pos
GL_ATI_blend_equation_separate
GL_ATI_blend_weighted_minmax
GL_ATI_separate_stencil
GL_ATI_texture_compression_3dc
GL_ATI_texture_env_combine3
GL_ATI_texture_float
GL_ATI_texture_mirror_once
GL_EXT_abgr
GL_EXT_bgra
GL_EXT_bindable_uniform
GL_EXT_blend_color
GL_EXT_blend_equation_separate
GL_EXT_blend_func_separate
GL_EXT_blend_minmax
GL_EXT_blend_subtract
GL_EXT_clip_volume_hint
GL_EXT_debug_label
GL_EXT_debug_marker
GL_EXT_depth_bounds_test
GL_EXT_draw_buffers2
GL_EXT_draw_range_elements
GL_EXT_fog_coord
GL_EXT_framebuffer_blit
GL_EXT_framebuffer_multisample
GL_EXT_framebuffer_object
GL_EXT_framebuffer_sRGB
GL_EXT_geometry_shader4
GL_EXT_gpu_program_parameters
GL_EXT_gpu_shader4
GL_EXT_multi_draw_arrays
GL_EXT_packed_depth_stencil
GL_EXT_packed_float
GL_EXT_provoking_vertex
GL_EXT_rescale_normal
GL_EXT_secondary_color
GL_EXT_separate_specular_color
GL_EXT_shadow_funcs
GL_EXT_stencil_two_side
GL_EXT_stencil_wrap
GL_EXT_texture_array
GL_EXT_texture_compression_dxt1
GL_EXT_texture_compression_s3tc
GL_EXT_texture_env_add
GL_EXT_texture_filter_anisotropic
GL_EXT_texture_integer
GL_EXT_texture_lod_bias
GL_EXT_texture_mirror_clamp
GL_EXT_texture_rectangle
GL_EXT_texture_sRGB
GL_EXT_texture_sRGB_decode
GL_EXT_texture_shared_exponent
GL_EXT_timer_query
GL_EXT_transform_feedback
GL_EXT_vertex_array_bgra
GL_IBM_rasterpos_clip
GL_NV_blend_square
GL_NV_conditional_render
GL_NV_depth_clamp
GL_NV_fog_distance
GL_NV_light_max_exponent
GL_NV_texgen_reflection
GL_NV_texture_barrier
GL_SGIS_generate_mipmap
GL_SGIS_texture_edge_clamp
GL_SGIS_texture_lod
GL_SGI_color_matrix

**Additional context**
Let me know if you want me to send you Apple's wall of text that appears when you force quit.

**Comment by kintel** [comment]
Could you try the latest development snapshot as well?

**Comment by kintel** [comment]
Closing due to lack of feedback; assuming it is fixed in the development snapshot.
