### ISSUE TITLE
Port to Apple silicon?

### ISSUE THREAD

**Issue by ebarrere** [openscad/openscad#5500]
**Is your feature request related to a problem? Please describe.**
Are there plans to port to Apple silicon so Rosetta will not be required?

**Comment by kintel** [comment]
We've had an Apple Silicon version for years, but only available using snapshot builds as we're not backporting this work to the 2021.01 release: https://openscad.org/downloads.html#snapshots

**Comment by ebarrere** [comment]
I see, thanks. I didn’t check the snapshots pageOn Dec 17, 2024, at 9:09 PM, Marius Kintel ***@***.***> wrote:﻿
We've had an Apple Silicon version for years, but only available using snapshot builds as we're not backporting this work to the 2021.01 release: https://openscad.org/downloads.html#snapshots
