### ISSUE TITLE
unable to install on mac osx 14.1.1 

### ISSUE THREAD

**Issue by DaniWin1** [openscad/openscad#5535]
Error when clicking to open dmg: 
“OpenSCAD-2021.01” cannot be opened because the developer cannot be verified.

**To Reproduce**
1. Download file
2. Click on 'dmg file"
3. receive error
4. search solution, find none. 

**Expected behavior**
openscad to install and be usable.

**Comment by kintel** [comment]
This is fixed in recent development snapshots: https://openscad.org/downloads.html
