### ISSUE TITLE
relative import paths in included files are relative to including file

### ISSUE THREAD

**Issue by kborer** [openscad/openscad#569]
bash> find
.
./scad
./scad/included_file.scad
./including_file.scad
./stl
./stl/cube.stl
bash> cat including_file.scad
include < scad/included_file.scad>
bash> cat scad/included_file.scad
import("../stl/cube.stl");

Given the preceding file structure, the expected result is that both including_file.scad and included_file.scad will compile correctly. Actual behavior is that included_file.scad compiles correctly, but including_file.scad fails to find the cube.stl file. 

This is because the import path in included_file.scad is relative to included_path.scad. When included_file.scad is compiled by itself, the path correctly  leads to cube.stl. When including_file.scad is compiled, the import path is relative to including_file.scad, so cube.stl is not found.
##

**Comment by t-paul** [comment]
Fixed via #3745.
