### ISSUE TITLE
automatic polyhedron orientation repair

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#590]
Admesh currently cannot do this 100% reliably.

This algorithm will work over the Rational field of numbers on a relatively 2-manifold-ish polyhedron() input with relatively simply math.

 convert all input to rationals.
 create point-in-tetrahedron test
 find tetrahedron ear using point-in-tetrahedron test
 use that point as point inside polyhedron
 orient faces in ear properly to generated 'inside' point
 allow those faces to 'cascade' orientation to rest of polyhedron
  (every face touching a vertex should have the same orientation.
   start with tetrahedron ear vertexes, and branch out from there 
   until all faces have been visited)
##

**Comment by kintel** [comment]
This has been implemented when using the Manifold backend
