### ISSUE TITLE
Crash when rendering (F6)

### ISSUE THREAD

**Issue by SteveGF** [openscad/openscad#597]
When working on the MakerBot lesson 1 tutorial for creating a button, I hit a crash when I hit F6 with the below code.  Removing both the $fn settings avoided the crash.  I'm a rookie, so feel free to educate me!  :)

Thanks,
Steve

$fn=64;
difference(){
    cylinder(h = 5, r = 20);
    translate(v=[7, 0, -1])
    cylinder(h = 7, r = 4);
    translate(v=[-7, 0, -1])
    cylinder(h = 7, r = 4);
    translate(v=[0, 7, -1])
    cylinder(h = 7, r = 4);
    translate(v=[0, -7, -1])
    cylinder(h = 7, r = 4);
    translate(v=[0, 0, 32])
    sphere(r=30,$fn=100);
}
##

**Comment by kintel** [comment]
Is this still reproducible using a recent development snapshot?

**Comment by kintel** [comment]
Closing as assumed fixed
