### ISSUE TITLE
Building OpenSCAD on ODROID-XU (armhf) produces a bounch of errors

### ISSUE THREAD

**Issue by roosemberth** [openscad/openscad#602]
Hi!, I've been trying to compile from source, as It's not avaliable from ubuntu sources...

I followed the instructions on http://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Linux/UNIX

So, Here's my log: http://goo.gl/p2ZFXy

Thanks for your time! 

Best Regards!
Roosemberth Palacios

**Comment by theja2289** [comment]
Hello,
I was just wondering if there is some documentation on how to get openscad working on odroid-xu now that you guys figured out the solution. I tried to follow the posts but I couldn't find the NULLGL branch, could you guys let me know if it still exists or there are new changes to this problem.

Thanks

**Comment by roosemberth** [comment]
@theja2289 It's not a branck, it's a [cmake target] (https://github.com/openscad/openscad/blob/master/tests/CMakeLists.txt#L89-L97) see [@donbright 's instructions] (https://github.com/openscad/openscad/issues/602#issuecomment-33756074) on how to compile this way
