### ISSUE TITLE
Allow command line to take a .scad file from stdin. [$5]

### ISSUE THREAD

**Issue by BenFrantzDale** [openscad/openscad#615]
Instead of 

```
$ echo "cube([1,2,3])" > /tmp/foo.scad
$ openscad -o foo.stl /tmp/foo.scad
```

it would be nice to be able to do

```
$ echo "cube([1,2,3])" | openscad -o foo.stl
```

See also: #616.
##

**Comment by ArchimedesPi** [comment]
````
$ echo "cube([1,2,3])" | openscad -o foo.stl -
````
is a more standard syntax.

**Comment by MichaelAtOz** [comment]
> is a more standard syntax.

For *nix

**Comment by runsun** [comment]
Using a blank.scad file which is blank, OpenSCAD is already capable of doing such a thing:

>>> openscad blank.scad -D "cube([2,3,4]);" -o dump.png

**Comment by littleyoda** [comment]
No need for a empty file. /dev/null works.
`openscad /dev/null -D "cube([2,3,4]);" -o dump.png`

**Comment by t-paul** [comment]
Thanks @aconz2, change is merged, bounty can be claimed.

**Comment by funrollloops** [comment]
You can also use `/dev/stdin` on Linux:
```bash
echo "cube(10);" | openscad /dev/stdin -o cube.png
```
