### ISSUE TITLE
Allow command line to write stl to stdout. [$5]

### ISSUE THREAD

**Issue by BenFrantzDale** [openscad/openscad#616]
Instead of 

```
$ openscad -o foo.stl /tmp/foo.scad
$ mySTLProcessor < foo.stl
```

it would be nice to be able to do

```
$ openscad -o stl:- /tmp/foo.scad | mySTLProcessor
```

FWIW: `tar` uses `-t` for "write to stdout"; `gzip` uses `-c`, `--stdout`, or `--to-stdout` interchangeably. ImageMagic's `convert` uses "extension colon dash": e.g., `jpeg:-`.

See also: #615.
##

**Comment by t-paul** [comment]
Thanks @aconz2, change is merged, bounty can be claimed.

**Comment by aconz2** [comment]
thanks @t-paul for taking this across the finish line

**Comment by aconz2** [comment]
@t-paul I believe the bounty can only be claimed after this issue is closed

**Comment by t-paul** [comment]
Oops, sorry, I just check the merge notice here assuming it would auto close.
