### ISSUE TITLE
add local axis indicator functionality

### ISSUE THREAD

**Issue by SquirrelCZE** [openscad/openscad#642]
well, as many of you know, it's sometimes hard to realize what is my actual "zero position" and "zero orientation", especially when we are talking about place that is under combination of 6 rotate/translate... so I thought, what if we could add cross(); functionality? 

```
module cross(){

rotate([-90,0,0]) color("green"){
    cylinder(d=1,h=10);
    translate([0,0,10]) cylinder(r1=1.5,r2=0,h=6);
}
rotate([0,0,0]) color("blue"){
    cylinder(d=1,h=10);
    translate([0,0,10]) cylinder(r1=1.5,r2=0,h=6);
}
rotate([0,90,0]) color("red"){
    cylinder(d=1,h=10);
    translate([0,0,10]) cylinder(r1=1.5,r2=0,h=6);
}

}


cross();

translate([0,0,20]) rotate([45,0,0]) {

    cross();

    translate([0,0,30]) rotate([0, -45, 0]) {
        cross();
    }

}
```

this simple example  shows simple cross and also how to use it... I think it could work?

![cross](https://f.cloud.github.com/assets/5853442/2127114/5d15103c-926a-11e3-8546-2414ee906f6c.png)
##

**Comment by kintel** [comment]
Closing as a user space solution exist
