### ISSUE TITLE
Please upgrade Ubuntu repository.  +libcal9

### ISSUE THREAD

**Issue by AndKe** [openscad/openscad#645]
The last Ubuntu version in repository is Raring, that's 13.04 , we are now on Soucy (13.10), and in two months we'll have next..

Yes, I did try to install from the raring repository, but if fails because of unsatisfiable dependency libcal9

**Comment by jbohren** [comment]
@t-paul The `openscad` PPA is now broken. It's been updated with the 2015.03 release, but that release isn't building: https://launchpad.net/~openscad/+archive/ubuntu/releases/+packages

```
Missing build dependencies: libharfbuzz-dev
```

It'd be great to have a newer version available for binary installation.

**Comment by t-paul** [comment]
I'll try to ping the maintainer.

**Comment by hyperair** [comment]
I gave up on 12.04. Too many things need to be backported in order to get it working.

**Comment by kintel** [comment]
Is the correct solution to leave the 2014.03 release for 12.04, or is that already how it works?
Btw., 2015.03 does work on travis, which runs on 12.04 (see https://github.com/openscad/openscad/blob/master/.travis.yml)

**Comment by t-paul** [comment]
Oh, this is about 12.04? Maybe we should clarify the supported combinations on the download page.

**Comment by jbohren** [comment]
@kintel
> Is the correct solution to leave the 2014.03 release for 12.04, or is that already how it works?

I think that'd be better than the alternative which is 2013.something.

@hyperair 
> I gave up on 12.04. Too many things need to be backported in order to get it working.

I understand that. I ended up just building it from source, which wasn't too bad.

@t-paul 
> Oh, this is about 12.04? Maybe we should clarify the supported combinations on the download page.

Yeah, and it might be worth a simple note that the latest version can be built from source on 12.04 with minimal effort. [These instructions](http://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Building_on_Linux/UNIX) worked pretty well.

**Comment by hyperair** [comment]
On Mon, Mar 23, 2015 at 12:18:26PM -0700, Marius Kintel wrote:
> Is the correct solution to leave the 2014.03 release for 12.04, or is that already how it works?

That's already how it works. Users won't see unbuilt binary packages because
they don't exist. They can download the sources and attempt to build it
themselves however.

> Btw., 2015.03 does work on travis, which runs on 12.04 (see https://github.com/openscad/openscad/blob/master/.travis.yml)

Hmm. Got build logs somewhere? I'd like to know where you get your dependencies
from.

At the very least, harfbuzz doesn't exist in 12.04's archive, and my feeble
attempts to backport it have led me on a never-ending chain of dependencies to
backport. I noticed 12.10 had harfbuzz. Maybe I ought to just backport the
version from 12.10 instead.

-- 
Kind regards,
Loong Jin

**Comment by t-paul** [comment]
One of the recent build logs: https://travis-ci.org/openscad/openscad/builds/55537783
I thought harfbuzz comes from @chrysn's old repo, but looking at the build log I think it's from https://launchpad.net/~mapnik/+archive/ubuntu/nightly-trunk

**Comment by kintel** [comment]
@hyperair yes, it's mapnik. The travis file should logically add the PPA's in order.

**Comment by hyperair** [comment]
On Mon, Mar 23, 2015 at 02:47:18PM -0700, Marius Kintel wrote:
> @hyperair yes, it's mapnik. The travis file should logically add the PPA's in order.

Yeah I just saw it. I'll try copying that package over.

-- 
Kind regards,
Loong Jin
