### ISSUE TITLE
Open STL on generation

### ISSUE THREAD

**Issue by laird** [openscad/openscad#648]
I'd like to have a feature added to have an option for OpenSCAD to tell the OS to open the STL files after they are generated.

My workflow is to edit in an editor, have OpenSCAD auto-refresh the file when saved, then compile and render an STL, switch to the slicer and manually open the new STL.

If the STL automatically opened when it was generated, that would eliminate a manual step. Not everyone would want this, so it should be a program setting.

It's not necessary to configure OpenSCAD to launch the STL file into a particular app, because these days OSs have facilities to do that mapping,  So to keep OpenSCAD simpler, best to leave it to the OS.
##

**Comment by kintel** [comment]
Closing, not something that really belongs in OpenSCAD
