### ISSUE TITLE
OpenCSG renders with errors on Macbook Air [$5]

### ISSUE THREAD

**Issue by iamwilhelm** [openscad/openscad#65]
When I put in the test case:

intersection() {
  sphere(30);
  cube(30);
}

It's suppose to show 1/8th of a sphere. However, the display is completely blank and empty. This only happens with intersection and difference. For union, they both show up correctly.

I'm running mac os X 10.7.2. Lion. Are there libraries I need to install or check before I install openSCAD? I suspect I may be missing a library. But if not, then it's a bug with openSCAD.

I will try to compile it from source and see if I have the same issue.
##

**Comment by kintel** [comment]
Can anyone still reproduce this issue?

**Comment by kintel** [comment]
Closing as likely to be an ancient driver issue, possibly solved by OpenCSG-1.4.2 and new drivers.
