### ISSUE TITLE
QSettings should use INI files on Windows(TM) instead of the Windows Registry

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#670]
If we move QSettings from the Windows Registry into a simple .ini file inside the OpenSCAD per-user directory, this would make it very simple for the windows folks to customize settings if they wanted to. It would be a text file, much like the .config/OpenSCAD.conf situation that we have on Linux. 

The immediate benefit here is for the easy user-customization of colors for the 3d window and for syntax highlighting. It is not as "good" as a fancy GUI interface for color-picking, but it is a good start towards that and is relatively simple to implement. It is an important part of UI to allow users to customize certain things for their environment and situation, such as Colorblind users who may have different perceptions of red/green and whatnot. 

---

The problem wil be migrating Registry entries to the .ini file so that people settings wont change after upgrade of OpenSCAD. 

This is a bit tricky but its not rocket science. We can set a rule to prefer .ini file to registry. 

Then on startup if the .ini file is missing (as it will be for all upgrades) we can load the registry entries, then immediately save them to a .ini file. (We have to verify that the .ini file wrote properly, of course, by loading it and doing a quick sanity check).

On subsequent runs the per-user .ini file will have all the settings saved. 
##

**Comment by Zaiborg** [comment]
if this issue is still open, there is the option to add some lines of code to the updater (if there is any) and read all the registry entries, clear them and write them into the said ini file

**Comment by thehans** [comment]
I think ideally we should have a non-Qt dependent alternative to reading settings(for all platforms, not just Windows) so that headless build can read settings without linking to Qt.  I know most of the settings are GUI specific, but there are a couple like cache size that shouldn't be tied to GUI.

**Comment by MichaelAtOz** [comment]
Ideally a mechanism to allow versioning of preferences. 
It doesn't happen often but there was once a problem where a snapshot preference caused (minor PITA) difficulties to the installed Release version. Even just Snapshot v's Release would be a safe practice.

**Comment by t-paul** [comment]
An alternative way of saving might be a nice option. It's probably not very easy to move everything out as there are a couple of cases where Qt stores some kind of internal data representation (QGamepad, Window positions, ...?) so we have to find a way to tunnel that though to a different backend.
