### ISSUE TITLE
Optimization parameter for union() to assume that all children are non-intersecting

### ISSUE THREAD

**Issue by AustinSpafford** [openscad/openscad#688]
Quite often when using OpenSCAD for printing, I create a module for creating a tightly packed "plate" of parts. While this works extremely well (esp. packing odd shapes), sometimes the CGAL step takes an enormous amount of time. For example, there's a part I'm looking at right now that took a few seconds to CGAL-render a single copy, but it's been over an hour to CGAL-render a plate of 24 (and still going). While it would be an option to use another package (Blender?) to perform the plating, I cannot understate just how useful it has been to do the math in OpenSCAD (especially for highly parametric parts).

To work around this problem, I would like there to be some sort of optimization flag I could set to effectively say "assume that all children are non-intersecting", either passed to union() to wrap up the output of my plating modules or as some sort of global flag (akin to global $fn) that affects the (to my knowledge) root's implicit union. If the parts are indeed intersecting and bad geometry is generated, then presumably the slicer would catch the problem (though at least visual inspection would have caught the intersection).

In any case, thank you for the excellent tool!

 -Austin

P.S. If alternatively it would be inexpensive to have union() always perform a first-pass set of intersection checks between children during CGAL rendering, then that would be superb as it would mean that output would still always be correct, and that situations such as a module generating plating would silently perform enormously faster.
##

**Comment by t-paul** [comment]
As #350 is moving again with #3138 merged to snapshot, I think we can close this one.
