### ISSUE TITLE
Code preprocessor support

### ISSUE THREAD

**Issue by flo-l** [openscad/openscad#715]
The openscad language is perfectly ok for creating most objects. But sometimes one hits the limit with more complex projects/ideas. The use of software that lets users write their code in a more expressive language like [Ruby](https://github.com/cjbissonnette/RubyScad) or [Python](https://github.com/SolidCode/SolidPython) and then compiles it to the openscad language is a solution to that.

However, these code preprocessors have a major drawback: Every time the user changes the script they have to run the code preprocessor by hand, reload the file and finally compile it with openscad to see the results. This is not very efficient and annoys people.

To integrate these awesome tools better a `run script before compile/render` function would really help. [Slic3r](http://slic3r.org/) has a [similar option](http://manual.slic3r.org/PostProcessingScripts.html) for example (actually it's not a pre-, but a postprocessor hook).

This feature would make it possible to write eg. RubyScad code directly into the openscad editor and use the whole program as if it was openscad code. Pure awesomeness.

**Comment by eddieparker** [comment]
Pardon my ignorance, but how does using an external editor solve this?  Do you just hook up your external editor to generate openscad somehow?  If so, what are you using, I'm curious?

I use vim myself as an external editor, and wouldn't mind the benefit of a code preprocessor.

**Comment by flo-l** [comment]
If you follow the link it says:

*OpenScad is able to check for changes of files and automatically recompile if a file change occurs. To use this feature enable "Design->Automatic Reload and Compile"*

This means that I can use any script to generate a .scad file and openscad reloads it instantly. This way I can (and do) use my own preprocessing toolchain but still have it integrated nicely into openscad ;)

**Comment by laird** [comment]
This works very well with Solid Python, for example. You turn on Automatic
Reload, and close the editor and console, and it's almost like OpenSCAD is
a window out of Solid Python. :-)

Sent from my iPad

On Feb 23, 2015, at 2:58 PM, flo-l <notifications@github.com> wrote:

If you follow the link it says:

*OpenScad is able to check for changes of files and automatically recompile
if a file change occurs. To use this feature enable "Design->Automatic
Reload and Compile"*

This means that I can use any script to generate a .scad file and openscad
reloads it instantly. This way I can (and do) use my own preprocessing
toolchain but still have it integrated nicely into openscad ;)

--
Reply to this email directly or view it on GitHub
<https://github.com/openscad/openscad/issues/715#issuecomment-75619168>.
