### ISSUE TITLE
Discussion: interpreter/diagnostic improvements

### ISSUE THREAD

**Issue by tim-caper** [openscad/openscad#727]
It is unfortunate that OpenSCAD may ignore misspellings and it looks like really good idea to add as much diagnostic messages as possible.

1) It seems relatively easy to add to variable data a flag if it was used, then set it to true every time the variable used in computation and print diagnostics about unused variables at the end. I am not sure though if this is really good idea: this approach may result in false alarms if some variable used in conditional context and its was not used due to condition (but may be used in some other case). Static analysis, on the other hand may be too complex or just impossible.

2) It looks like a good idea to add diagnostic messages in expr.cc/func.cc, i.e. before returning undefined value print something like 'ERROR: operator [] applied to neither range nor vector' or 'ERROR: operator + applied to neither scalar nor vector' as appropriate. Is this idea really that good? :-)

3) I put to https://github.com/tim-caper/openscad/compare/lowlevelp changes intended to reduce stack usage and accelerate calculations. Do they fit into OpenSCAD coding style? Do they worth pull request?
##

**Comment by MichaelPFrey** [comment]
I suggest closing this issue.

1.  Nice idea, but it would generate a lot of data even from a simple scad file
2. To my understanding, a lot of work as been done in this direction recently. If not, that can be a separate issue with specific examples.
3. merged in 2014

**Comment by t-paul** [comment]
Agreed, the optimization seems to be merged via #773 - if there's interrest in the other topics we should separate them into their own issues.
