### ISSUE TITLE
Windows test suite failures

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#744]
As per [forum](http://forum.openscad.org/Snapshot-file-date-v-s-web-description-tp7596p7626.html) logs of failing Windows test suite. (will follow shortly - I need the issue #)

**Comment by kintel** [comment]
@MichaelAtOz Perhaps we should close all Windows test failure issues and start a new one once we can get the tests to build and run?

**Comment by MichaelAtOz** [comment]
Sound reasonable
