### ISSUE TITLE
How to determine cause of crash when rendering complicated mountain STL import

### ISSUE THREAD

**Issue by JCrew7384** [openscad/openscad#765]
I am importing an STL file that contains a mountain range. From there I place it on a cube, and add some text to the side of the cube. Nothing complicated. It compiles fine, but on Render, after about 20 minutes, it crashes. Have tried on multiple systems, Mac and PC. On PC I get a C++ runtime error. On Mac just becomes unresponsive.

How do I investigate this? Is it possible my mountain range import is "too" complicated? Without that import everything works fine.
##

**Comment by kintel** [comment]
This should perform a lot better now, when enabling the Manifold feature. Closing this as we have a good path forward for larger models like this.
