### ISSUE TITLE
Function arguments are evaluated twice

### ISSUE THREAD

**Issue by t-paul** [openscad/openscad#767]
The fix for #738 only prevents the horrible complexity explosion when using min()/max() in a recursive context. But almost all functions (see `func.cc`) still evaluate the first argument twice (using `evalctx->getArgValue()`).
This can still cause performance problems when the argument is a complex function call.
##

**Comment by Ch3ck** [comment]
I'll  love to work on this if  it's not been fixed already :+1:

**Comment by t-paul** [comment]
There was some refactoring in the evaluation stuff, so the remaining places might be fixed in the meantime.

**Comment by Ch3ck** [comment]
alright, any pointers  as to which files I should   look  into? @t-paul

**Comment by Ch3ck** [comment]
builtin_lookup() looks Ok. Don't see any double evaluation of args. Will make AbstractFunction::evaluate to virtual method.

**Comment by ChrisVesters** [comment]
Is this still relevant? @t-paul you were looking into this?

**Comment by redlizard** [comment]
I can confirm that this is fixed in master.
