### ISSUE TITLE
2014.05.18 Flush caches appears not to

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#811]
Background. After a bit of modeling, a few versions of the same thing, MDI so using the same cache for the various File/Opens of each version (external editor with auto reload & compile). (having to close the existing window when a new version opened).

Get a Warning from Windows to close programs due to low memory.

OpenSCAD process was as 1.3GB.
Did a flush caches, memory didn't change.
As I had last done a F6 and was viewing it (view/surface) I did a F5 (hence view/preview), to hopefully release cache used by F6 (??).
Did flush cache, memory didn't change.
Could swap between view/surface view/preview and see an image, not my recollection of how that worked before. You could only see the relevant one for the last F5/6.

This is compounded due to larger memory use as I noted on the forum, it doesn't take long for the memory to get over 1GB. And the model I was doing wasn't _that_ complicated.
##

**Comment by thehans** [comment]
Implementation details of memory handling are up to the OS.  
As far as I understand, even after C++ has deallocated some objects etc, the OS won't necessarily show that reduced usage.  
So it likely keeps the pages allocated in case they are needed again by the same process.  Only when some other process needs the memory and no other free memory is available then it will do the bookkeeping and to take some of openscad's unused bits.

Testing the ubuntu 20.04 nightly with the [gist](https://gist.github.com/MichaelAtOz/383d930d1b3ef18e5f77) from 810, 
if there was a leak before, it seems to be much better now (doing F6 renders with flush in between each):
```
1st 582 MB
2nd 587 MB
3rd 589 MB
4th 593 MB
5th 593 MB
```

**Comment by jordanbrown0** [comment]
Having an application deallocate memory basically never releases it back to the OS.

Unused memory - actually, all application memory - is available to be paged out when there's a need for more.

On Linux, the two most interesting numbers are VSZ and RSS.  VSZ, the virtual memory size, is the total size of the process.  RSS, the Resident Set Size, is the amount of memory the process is more or less actively using - or at least the amount that it *has* used and hasn't gotten paged out.

**Comment by MichaelAtOz** [comment]
On Windows released memory is returned to the kernel. See figures below.

This does appear fixed, but there is still something fishy.
OpenSCAD 2021.01
![Capture-sheet-chart-cache](https://user-images.githubusercontent.com/1972961/121764787-da65e100-cb89-11eb-9f51-7116ae2b6096.JPG)
Op=FC is flush cache.
Working Set & Commit Size are from task manager.
The rest are from OpenSCAD console, ie:
```
Geometries in cache: 23
Geometry cache size in bytes: 1189768
CGAL Polyhedrons in cache: 40
CGAL cache size in bytes: 210569632
```
The dotted lines are linear trendlines. Memory is going up. Probably a small leak.
In between line 7 & 8, I did F6 x 10 (ie cached F6) there was no change in the figures, 
then a FLUSH CACHE, unfortunately I forgot to get WS & CS...
I'll raise a issue to request the Cache Flush logs cache stats too, that will make it easier to see.
This issue can stay closed.

**Comment by jordanbrown0** [comment]
I don't know enough about Windows memory management to really know, but I don't think it's that simple.

If you use a tool like [VMMap](https://docs.microsoft.com/en-us/sysinternals/downloads/vmmap) it also shows a total that doesn't seem to go down, and a heap size that doesn't seem to go down.

But maybe that's only measuring the addresses allocated to those purposes, and the actual pages are observed to be unused and freed.

**Comment by MichaelAtOz** [comment]
I DO know Windows memory management.

 

VM of a process and memory handled by the Kernel are different beasts.

I don't use VMMap but just had a look.

'Size' is the Virtual memory addresses allocated, assigned may be better, not in a C style allocated (note Free = 8TB).

'Committed' is VM actually used, ie written (whether in memory or swapped).

'Total WS' is the set of committed pages resident in physical memory.

 

The same .scad F6 & FC as I previously used show,

 

Post-F6-pre-FC Heap 

Size: 1,292,048K Committed: 1,285,520K Total WS: 1,264,352K

Post-FC

Size: 1,258,204K Committed:   619,504K Total WS:   556,744K

 

When memory is deallocated that physical page is handed back to the Kernel, it is no longer committed.

The Kernel sticks it on a list, a background process zeros the page and sticks it on a 'free' list.

Once on the 'free' list it can be handed to another process.

 

The post-F6 Committed and Total WS are creeping up with cycles of F6 & FC, probably a leak.

 

The other interesting thing is that there is a large chunk of something that is not free'd by FC.

 

This is the cycle



 

A. post last Flush, B. F6 starts, C. F6 finished, D. Flush, E. post Flush.

That drop at B gets ~to the size of a freshly run .exe.

It could be screen buffers, but I would not have thought they would be 100's of MB's.

 

In my previous post the Geometry # and CGAL # figures seem odd.

 

 

  _____

**Comment by MichaelAtOz** [comment]
Well, that email lost formatting and an image...

I'll post it via the forum later.

 

  _____

**Comment by MichaelAtOz** [comment]
(reposted with formats and image)

I DO know Windows memory management.

VM of a process and memory handled by the Kernel are different beasts.
I don't use VMMap but just had a look.
'Size' is the Virtual memory addresses ~~allocated~~, assigned may be better, not in a C style allocated (note Free = 8TB).
'Committed' is VM actually used, ie written (whether in memory or swapped).
'Total WS' is the set of committed pages resident in physical memory.

The same .scad F6 & FC as I previously used VMMap shows,

```
Post-F6-pre-FC Heap 
Size: 1,292,048K Committed: 1,285,520K Total WS: 1,264,352K
Post-FC
Size: 1,258,204K Committed:   619,504K Total WS:   556,744K

Also note that a fresh OpenSCAD with the .scad loaded (prior to any F5/F6) the Heap is
Size:    43,588K Committed:    32,124K Total WS:    31,588K
```

When memory is deallocated that physical page is handed back to the Kernel, it is no longer committed.
The Kernel sticks it on a list, a background process zeros the page and sticks it on a 'free' list.
Once on the 'free' list it can be handed to another process.

The post-F6 Committed and Total WS are creeping up with cycles of F6 & FC, probably a leak.

The other interesting thing is that there is a large chunk of something that is not free'd by FC.

This is the cycle
![OPENSCAD MEMORY](https://user-images.githubusercontent.com/1972961/121791230-fb324300-cc2a-11eb-8522-762f812db1a5.png)

 
A. post last Flush, B. F6 starts, C. F6 finished, D. Flush, E. post Flush.
That drop at B gets ~to the size of a freshly run .exe.

It could be screen buffers, but I would not have thought they would be 100's of MB's.

In my previous post the Geometry # and CGAL # figures seem odd.

**Comment by nophead** [comment]
If you just delete C++ objects on the heap doesn't it just leave small holes in the allocation, not aligned with pages, so nothing is released to the OS? I.e. you would need to move all the C++ objects to compress the heap and give back the  free memory and that would need handles instead of pointers, etc.

**Comment by MichaelAtOz** [comment]
No.

 

  _____

**Comment by nophead** [comment]
Care to explain how deleting C++ objects on the heap returns free memory to the OS then? I have been retired 10 years but it certainly didn't when I was a programmer. Blocks that aren't touched eventually get paged out if another process needs the RAM, so no longer use physical memory, but are still part of the virtual memory space.

Unless you use custom allocators heap objects aren't block aligned and can be fragmented.

**Comment by MichaelAtOz** [comment]
"After a memory block has been freed, _heapmin <https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/heapmin?view=msvc-160>  minimizes the amount of free memory on the heap by coalescing the unused regions and releasing them back to the operating system. Freed memory that is not released to the operating system is restored to the free pool and is available for allocation again."

 

  _____

**Comment by MichaelAtOz** [comment]
@jordanbrown0 emailed
> OK, but... does anything ever call it?  I don't see it called from the OpenSCAD sources.
> (But I hadn't seen a function like that before.  It's interesting.)

My quote above is from [free() reference](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/free?view=msvc-160). free() calls _heapmin().

Class constructors/destructors end up calling malloc() & free() under the covers of new/delete.

The other thing you need to realise is the heap (& everything) is virtual, the memory manager knows the status of pages mapped to the heap, so if there is a hole in the heap from free(), if any pages in that hole are completely in the hole they can be unmapped and returned to the OS. Hence you don't need to manually maintain the heap. 
To the process, it still sees 8TB of virtual memory, it doesn't know or care, whether there are physical pages underneath.
(this is all in 64 bit context)

**Comment by jordanbrown0** [comment]
It's at least a bit unusual for a free() to do system calls, because they are so very expensive, and swap space is cheap.

But maybe this one does.

**Comment by MichaelAtOz** [comment]
It is entirely implementation dependent, but I understand the runtime has a bit of smarts, it will not necessarily do heapmin() for every free(). There are layers, with turtles all the way down.
