### ISSUE TITLE
List comprehension and let() issues [$25]

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#814]
Remaining TODOs after merging #792 to master:

- [x] wikibooks documentation
- [x] cheat sheet
- [ ] add one or more examples demoing this

**Comment by alhirzel** [comment]
What needs to be done to satisfy the bounty?

**Comment by kintel** [comment]
@alhirzel The bounty is for one or more good examples demoing list comprehension. ..for inclusion in the File->Examples menu

**Comment by kintel** [comment]
Note: The example needs to be released under CC0 (http://creativecommons.org/publicdomain/zero/1.0/)

**Comment by MichaelAtOz** [comment]
@kintel The bounty is outstanding, unclaimed, but this is closed, is the example still outstanding? The task in OP is ticked?

**Comment by kintel** [comment]
I guess I ended up fixing it myself :)
