### ISSUE TITLE
Hadamard product

### ISSUE THREAD

**Issue by adius** [openscad/openscad#821]
It would be cool to support the hadamard product natively!

**Comment by pekka-28** [comment]
In version 2019.05 this no longer works. The [User manual](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Mathematical_Functions#len) documents the len() function as not defined for scalar arguments. The guard predicate must be modified to detect the termination of the recusion.

The code:
`function hadamard(a,b) = !is_list(a) ? a*b : [ for(i = [0:len(a)-1]) hadamard(a[i],b[i]) ];
`
appears to work correctly by more correctly detecting the type or the first argument, and not the length.
