### ISSUE TITLE
Transparent color on object with a 'difference' is Purple instead of Green

### ISSUE THREAD

**Issue by archie305** [openscad/openscad#857]
```
size=20;

  module obj(T)
  {
    color([0,1,0,T]) {
      difference() {
        cube(size=size,center=true);
        translate([size/2,0,0]) cube(size=size/4,center=true);
  translate([0,-size/2,0]) cube(size=size/4,center=true);
      }
    }
  }

  for (i=[1:5])
    translate([(i-3)*(size+10),0,0]) obj(i/5);
```

with 'Force Goldfeather' enabled displays on Compile - F5 in OpenSCAD 2014.03 (2013.06) for Windows as: 
![capture1](https://cloud.githubusercontent.com/assets/3846531/3434028/8eb82816-0085-11e4-8f42-ef884a3f53e4.PNG)
with 'Force Goldfeather' disabled (or as below with 'Thrown Together' selected) it displays as expected:
![capture2](https://cloud.githubusercontent.com/assets/3846531/3434077/063a84c4-0086-11e4-9410-49e37a354f11.PNG)
##

**Comment by kintel** [comment]
Do you still experience this. Looks suspiciously like a OpenGL driver bug.

**Comment by MichaelAtOz** [comment]
Force Goldfeather 
![purple goldfinger](https://cloud.githubusercontent.com/assets/1972961/5867238/865cad94-a2ed-11e4-9edb-e07ab9fd04ac.JPG)

**Comment by thehans** [comment]
This is an OpenCSG issue.

I experienced this bug when I was using OpenCSG 1.3.2.  
It went away since I upgraded to OpenCSG 1.4.0.

**Comment by thehans** [comment]
No response from OP after 7yrs, closing.
