### ISSUE TITLE
2d rendering has strange artefacts

### ISSUE THREAD

**Issue by donbright** [openscad/openscad#858]
the existing 2d tests hid this because they were on an angle. 

the new 2d tests in the @test3dexport branch show some issues as they are 'top down render'.

The first image was generated by TEST_GENERATE=1 ctest on ubuntu 14 on an amd64 machine.

![a](https://cloud.githubusercontent.com/assets/896858/3439123/1efefb78-00dd-11e4-8118-1790f89c51b0.png)

The second image was generated on an IBM POWER7 (PPC64) machine

![b](https://cloud.githubusercontent.com/assets/896858/3439126/3ad6030a-00dd-11e4-8556-2ff9918a7ac7.png)

both show some puzzling artefacts. not sure what is going on but it doesnt seem right.
##

**Comment by t-paul** [comment]
I have not seen this for a long time and can't reproduce the effect, so maybe we blame that on old Mesa/Gallium?

Current driver is
```
GLEW version: 2.0.0
OpenGL Version: 3.0 Mesa 18.1.9
GL Renderer: Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) 
GL Vendor: Intel Open Source Technology Center
```
