### ISSUE TITLE
2014.06.30 distance= not updated in Orthogonal, & size change, & drag issue

### ISSUE THREAD

**Issue by MichaelAtOz** [openscad/openscad#863]
When in Orthogonal mode, the object zooms, distance= doesn't change.

I'm assuming the following is related.

When changing between Orthogonal & Perspective, the object changes size significantly. Compared to 2014.04.

Also the drag/translate is less related to the mouse movement. Compared to 2014.03 for a similar mouse move, 06.30 only moves the object 25% the distance.

**Comment by t-paul** [comment]
Should be fixed by  #1134 and #1135.
