### ISSUE TITLE
AMF export issues

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#909]
The current AMF export forces a creation of a Nef polyhedron even though that's unnecessary (https://github.com/openscad/openscad/blob/master/src/export.cc#L292).
- [ ] Implement direct export of PolySet
- [ ] Enable conversion from Nef polyhedron to PolySet (see #337)
##

**Comment by doug-moen** [comment]
I gather that the problem with creating a Nef polyhedron is that we get an error message if the mesh is not 2-manifold. Issue #910 says "The current OFF export requires us to create a CGAL Polyhedron. This causes some corner cases to fail exporting to OFF which works for STL ", and #1621 says that AMF export is less reliable.

I am wondering if these corner cases that fail are the same as the corner cases which are not permitted by the AMF standard. If so, then maybe it isn't a bad thing if we refuse to create an invalid AMF file. Here's what the standard says:

6.6 Restrictions on Geometry—All geometry shall comply with the following restrictions:

1. Every triangle shall have exactly three different vertices.
2. Triangles may not intersect or overlap except at their common edges or common vertices.
3. Volumes shall enclose a closed space with nonzero volume.
4. Volumes may not overlap.
5. Every vertex shall be referenced by at least three triangles.
6. Every pair of vertices shall be referenced by zero or two triangles per volume.
7. No two vertices can have identical coordinates.
8. The outward direction of triangles that share an edge in the same volume must be consistent.

#1621, first comment, gives a model that fails at AMF export, but this model has self-intersection (restriction 2 above).

**Comment by nophead** [comment]
Those rules should be applied to STLs as well as AMF because although STL
does not have those rules it should do. They don't look hard to code either
so could be applied to polyset.

**Comment by kintel** [comment]
AMF does indeed have a strict non-manifold requirement, so it would make sense to respect those.
STL, otoh, doesn't, so such checks should be optional.
I'm believe that e.g. 3MF specifically allows such vertex or edge self-intersections, so what we should allow really depends on the downstream processes.

As mentioned in #1621, performing these checks ourselves is probably a better solution rather than relying on partially available functionality in CGAL.

**Comment by kintel** [comment]
Closing as AMF export is deprecated
