### ISSUE TITLE
Scintilla editor issues

### ISSUE THREAD

**Issue by kintel** [openscad/openscad#915]
This is a followup issue collecting misc. scintilla issues which are not serious enough to hold back a merge to master.

**Color scheme**
- [x] Brace matching highlight colors needs to be matched for each color scheme
- [x] Cursor is almost invisible in the Monokai scheme

**Editor**
- [x] Improve tab/indentation behavior (see #905)
- [ ] Add "Convert tabs to spaces" (which should treat tab width equal to configured indentation width)
- [x] Line wrapping symbols are a bit visually disturbing (fixed by only showing end of line wrap symbol)
- [x] Make word wrapping optional?
- [ ] It's hard to see what code will be folded. If we could highlight the folded region, it might be more intuitive.
- [ ] Tune error display; save screen real-estate by sharing the line number area + tight-adjust line numbers (now they always have some spacing on the right side of the numbers).
- [x] Scale line number column to match font size
- [x] Use the same font size (or smaller) for line numbers as for text. Currently it's bigger
- [x] auto-scroll to error line after compilation error
- [x] Key bindings: On Mac, unbound Cmd-keys produce printable characters (e.g. Cmd-f).
- [ ] Key bindings: Go through in detail on all platforms and adjust remaining details. Also update https://github.com/openscad/openscad/wiki/Keyboard-Shortcuts

**Preferences**
- [x] (Auto-)Indentation width
- [x] Line wrapping

**Documentation**
- [ ] Summarize the new features somewhere
##

**Comment by MichaelAtOz** [comment]
- [ ] Whitespace highlighting for darker backgrounds

I doubt this is intentional. Color syntax highlighting doesn't do whitespace, see:
![whitespace](https://cloud.githubusercontent.com/assets/1972961/5747904/ce31d478-9c8f-11e4-9842-89a9362aa9d1.JPG)
same for:
For Dark Background
Monokai
Solarised (light)
Solarised (dark)
Tommorow - less noticable
Tomorrow Night

**Comment by t-paul** [comment]
Ahh, good catch... found the cause. That only happens after setting highlighting to OFF and back to some other setting.

**Comment by kintel** [comment]
Closing this as Scintilla has been stable for a long time. Let's open new issues per problem going forward.
