### ISSUE TITLE
Stability issues in Windows 8.1 using OpenSCAD version 2014.03

### ISSUE THREAD

**Issue by sjwebb15** [openscad/openscad#942]
Hi all.  I am new to OpenSCAD, but I have been having issues getting the figure below to render on a Windows 8.1 machine. I have left some stuff commented below, because I would like to get the full model to work, but what is below will not render.  Changing Step to 5 will cause the figure to render.  I have tried this on both 64-bit and 32-bit versions.   I finally tried to render the full model (including the hull() and second triangle statement) on my Windows 7 laptop with the 32 bit version of OpenSCAD and that worked, though it took a long time.

// Mobius solid with triangular cross-section (thanks to [kitwallace on Thingiverse](http://www.thingiverse.com/thing:239158) for the mobius strip basis of this code)

module roundedTriangle2d(thick,delta,res)
{
zNeg = thick/(4_cos(30));
zPos = thick_sin(60)-zNeg;

hull()
{
translate([-thick/2,-zNeg,0])
circle(delta/2,$fn=res);

translate([thick/2,-zNeg,0])
circle(delta/2,$fn=res);

translate([0,zPos,0])
circle(delta/2,$fn=res);
}
}

module roundedTriangle3d(thick,delta,res)
{
rotate([90,0,0])
linear_extrude(delta, center=true)
roundedTriangle2d(thick,delta,res);
}

//Radius of strip
Radius = 18.89;
//Width of Strip
Width = 4;
//Thickness of strip
Thickness=2;
//Half twists 0 is a collar, 1 is the mobius strip, 2 = fulll twist
Halftwist=1;
Thirdtwist=2;
//Start Angle - important if Halftwist = 0
Start=90;
//Step size in degrees
Step = 3;

module mobius_strip(radius,width,thickness,step, halftwist,start) {
  for (i = [0:step:360-step])
    //hull() {
       rotate([0,0,i])
          translate([radius,0,0])
             rotate([0,start+i \* halftwist / 3, 0]) 
            roundedTriangle3d(width,.5,5);

```
   /*rotate([0,0,i+step])
      translate([radius,0,0])
         rotate([0,start+(i+step)* halftwist / 3 , 0]) 
        roundedTriangle3d(width,.5,20);*/
   //}
```

}

mobius_strip(Radius, Width, Thickness, Step, Thirdtwist,Start);
##

**Comment by t-paul** [comment]
Closing, old issue with no further reports.
