### ISSUE TITLE
Improper rendering: Linux + X11 + nouveau

### ISSUE THREAD

**Issue by steelman** [openscad/openscad#967]
Recently I switched from proprietary nVidia driver to the free nouveau on my Linux desktop.
Now at some angles (which appear to be somewhat deterministic as I move around) some elements are painted white. Sometimes they are axes and crosshairs, sometimes solids (see the screenshot).

![openscad-nouveau](https://cloud.githubusercontent.com/assets/77683/4479408/013797d6-498e-11e4-85df-1ffb51c0b010.png)
##

**Comment by t-paul** [comment]
Closing, old issue with no further reports, so that was likely a driver problem.
