### ISSUE TITLE
trigonometric math functions not accurate

### ISSUE THREAD

**Issue by indazoo** [openscad/openscad#977]
Hi
I created some threaded bolts with this library
https://github.com/hyperair/MCAD/blob/master/fasteners/threads.scad
This library has some bugs which I try to contribute right now, so it is not the best sample, it just happened to be the one with which I had the issue. The trigonometric "bug" will occur for other OpenScad code also.

A threaded bolt has a flat surface on top (every screw ends, obviously). Now, the library created the flat end with calculations involing tan/sin functions. The arithmetic functions produce non zero values for some special angles (sample: sin(180) = 1.22461e-016).
You can say, this is a small deviation from zero, but then I wanted to add a solid to the screw end and got "simple = no" after compiling. Yes, I can make it overlapping, I know.
For me I wrote a workaround which resulted in a "simple=yes" without overlapping (see below).

I like accuracy and would be happy if that can be fixed.

function accurateCos(x) = 
(x%30)!=0?cos(x): (x<360?simpleCos(x):simpleCos(x-floor(x/360)*360));
function simpleCos(x) =
x==0 ? 1 :
x==60 ? 0.5 :
x==90 ? 0 :
x==120 ? -0.5 :
x==180 ? -1 :
x==240 ? -0.5 :
x==270 ? 0 :
x==300 ? 0.5 :
x==360 ? 1 : cos(x);
// TEST

for (angle = [0:1:361]) 
{
    if((cos(angle)-accurateCos(angle)) != 0)  
        echo(angle," ", cos(angle)-accurateCos(angle));
}

function accurateSin(x) = 
(x%30)!=0?sin(x): (x<360?simpleSin(x):simpleSin(x-floor(x/360)*360));
function simpleSin(x) =
x==0 ? 0 :
x==30 ? 0.5 :
x==90 ? 1 :
x==150 ? 0.5 :
x==180 ? 0 :
x==210 ? -0.5 :
x==270 ? -1 :
x==330 ? -0.5 :
x==360 ? 0 : sin(x);
//TEST

for (angle = [0:1:361]) 
{
    if((sin(angle)-accurateSin(angle)) != 0)  
        echo(angle," ", sin(angle)-accurateSin(angle));
}

function accurateTan(x) = 
(x%45)!=0?tan(x): (x<360?simpleTan(x):simpleTan(x-floor(x/360)*360));
function simpleTan(x) =
(x==360==0 ? 0 :
(x==315==0 ? -1 :
(x==225==0 ? 1 :
(x==180==0 ? 0 :
(x==135==0 ? -1: tan(x))))));
// TEST

for (angle = [0:1:361]) 
{
    if((tan(angle)-accurateTan(angle)) != 0)
    echo(angle," ", tan(angle)-accurateTan(angle));
}
##

**Comment by thehans** [comment]
@indazoo Special trigonometric angles are handled appropriately as of PR #2215, merged on Dec 23, 2017  

If you run any build(dev snapshot) created after that merge then you should see the correct behavior.
