### ISSUE TITLE
Export (flat cuts) as SVG

### ISSUE THREAD

**Issue by nichtich** [openscad/openscad#98]
OpenSCAD is designed for 3D modeling but you can also use it for some 2D modeling - the only barrier is you cannot export your models to SVG (or another vector file format). The only way is to export DXF and then convert to SVG, but there is no open source tool for this purpose (you can do to some degree with LX-viewer). 2D SVG export may also be useful to export cuts through your 3D-model.

**Comment by tcurdt** [comment]
Hm. Until https://github.com/openscad/openscad/pull/171/files is merged this isn't really "fixed", is it?

**Comment by kintel** [comment]
#171 implements a different feature than originally requested here.

**Comment by tcurdt** [comment]
@kintel I was hoping to export "flat cuts" as svg and

    export("cut.svg") projection() myobject();

looks pretty much what I am after.

Isn't that what #171 and this here is both about?

**Comment by t-paul** [comment]
Adding procedural style `export()` is likely to cause lots of trouble. I think a better fit to the OpenSCAD language being a model description would be to have some kind of annotations to define "This is a separate top level object" and have the logic in the export code. A bit like CSS/Style markup in HTML which then is handled in a specific way by the render engine (e.g. absolute positioned div blocks).

This depends on #350 though which makes it possible to skip the top level union.

**Comment by tcurdt** [comment]
@t-paul I don't see it as procedural style and I am not sure why this would cause trouble  (frankly speaking I see this `export()` more as an annotation of a subtree) but I guess you would know better.

If I could export multiple subtrees (or rather their projection) as svg I am happy.
No matter where the export code lives :)
It sounded like this issue is about that.

Thanks for the pointer to #350. Interesting.

**Comment by kintel** [comment]
@tcurdt I read the original issue as being able to export SVG, in addition to the existing DXF support:
```
 projection() myobject();
```
File->Export->Export as SVG..
