### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by Salandora** [openscad/openscad#981]
Hello,

today I wanted to compile openscad from source on my Ubuntu 14.04 machine, I used the uni-get-dep script to get alle the dependencies, after that I tried to compile everything and here were 2 problems first I missed the qmake command so I needed to install the qt4-qmake package next, after that the qmake command worked fine.
Next step was to do the make command after a short while it stopped and said it is missing the qscintilla headers, after a bit of googling i found out that i had to install libqscintilla2-dev.

So the missing deps are:
- qt4-qmake
- libqscintilla2-dev

for debian

Greetings
Salandora

**Comment by Bill-3d** [comment]
I started using opsnscad with a binary distro - I use Mint 14.3 - but the only available one
was 2014.03 which doesn't support the 'text' object. I downloaded the packaged source
for 2015.03 and started install following the guide on README.md. When I tried running
scripts/uni-get-dependencies it complained that it couldn't find 'get_debian_7_deps' which
at first I assumed to be a typo, and edited the script to run 'get_debian_deps'. This
pulled in a load of dependencies. Running 'check_dependencies' implied that everything
listed was up to date or better.

I then tried running qmake. For some reason my system seemed to wnat to run the qt4 version
but only qt5 was installed. After fiddling with things I eventually got qmake (qt5) to run but
then it complains about scintilla not being found:

Project MESSAGE: If you're building a development binary, consider adding CONFIG+=experimental
/home/bill/CAD/openscad-2015.03-2/scintilla.pri:13: Cannot find feature qscintilla2
Project MESSAGE: Using local copy of qscintilla2.prf instead.
Project MESSAGE: Using qt5scintilla2 as library name

Any ideas?

**Comment by Bill-3d** [comment]
I now realise that the above is not strictly an error but a warning. I managed to locate a copy
of qscintilla2.prf in the installed package and copied it into the openscad folder, but I still got
the above messages. It then dawned on me that qmake only makes the Makefiles, so I went
on, with fingers crossed, and ran make. This ran for a while then terminated with:

In file included from src/QGLView.cc:28:0:
src/QGLView.h:9:21: fatal error: QGLWidget: No such file or directory
 #include <QGLWidget>
                     ^
compilation terminated.
make: *** [objects/QGLView.o] Error 1

Where does QGLWidget come from?

Thanks
Bill

**Comment by Bill-3d** [comment]
Answering my own questions again - it seems that the Mint package manager (mintinstall) has a
blind spot and can't locate libqt5opengl5-dev which seems to be the logical place to look.
Trying good old-fashioned mathods (apt-get install libqt5opengl5-dev) worked no problem,
and the compilation is off an running again....

**Comment by Bill-3d** [comment]
Finally compiled and working. Does this mean that libqt5opengl5-dev should be in the get-dependencies and check-dependencies scripts?

Bill

**Comment by kintel** [comment]
We’re trying to retire QGLWidget. The latest code uses QOpenGLWidget which doesn't require that extra package.
